/*
 * Auto-generated by tools/orig/object_def_packets.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists as a retail-backed per-object packet for exploratory split work.
 *
 * Object def: 0x0468 IceHole
 * Output path: src/main/unknown/objects/obj_0468_icehole.c
 * Retail placements: 6
 * Root romlists: 1
 * Object-def size: 0xC0
 * Root placement widths: 9w x6
 * DLL ID: 0x0273
 * Class ID: 0x0030
 * Suggested outer boundary: shared DLL family
 * Reference class name: various0030
 * Reference DLL name: FirePipe
 * Remap aliases: 0x06F9
 *
 * Related packet paths:
 * - class: src/main/unknown/classes/class_0030_various0030.c
 * - family: src/main/unknown/dll_0273_firepipe.c
 *
 * Width samples:
 * - 9w (0x24 bytes): wallcity.romlist.zlb
 *
 * Inline object-def evidence:
 * - inline fields: pModelList, hitboxes, aButtonInteraction
 * - model IDs: 0x00000362
 * - help texts: 0xFFFF 0xFFFF 0xFFFF 0xFFFF
 *
 * Same-class objects (404 defs / 2358 placements):
 * - 0x04F9 LargeCrate: placements=329, dll=0x0105, widths=9w x329
 * - 0x0068 baddieInter: placements=175, dll=0x00DE, widths=9w x175
 * - 0x0318 VFP_lavapoo: placements=107, dll=0x0226, widths=9w x107
 * - 0x0466 FireHole: placements=101, dll=0x0273, widths=9w x101
 * - 0x03B9 WM_WallTorc: placements=96, dll=0x0206, widths=9w x96
 * - 0x0515 fuelCell: placements=77, dll=0x0123, widths=9w x77
 * - 0x04F7 SmallBasket: placements=74, dll=0x0104, widths=9w x74
 * - 0x0590 CraterFlame: placements=68, dll=0x01E7, widths=9w x68
 * - 0x0530 ARWGoldRing: placements=50, dll=0x02A0, widths=9w x50
 * - 0x04F8 LargeBasket: placements=44, dll=0x0105, widths=9w x44
 * - 0x0401 MMSH_WaterS: placements=41, dll=0x018E, widths=9w x41
 * - 0x0507 SpiritDoorS: placements=38, dll=0x0157, widths=9w x38
 * - ... 392 more class siblings omitted
 *
 * Same-DLL objects (8 defs / 161 placements):
 * - 0x0466 FireHole: placements=101, class=0x0030, widths=9w x101
 * - 0x0464 FirePipe: placements=34, class=0x0030, widths=9w x34
 * - 0x046A SteamHoleFi: placements=16, class=0x0030, widths=9w x16
 * - 0x0468 IceHole: placements=6, class=0x0030, widths=9w x6
 * - 0x0469 SteamHoleNo: placements=3, class=0x0030, widths=9w x3
 * - 0x0467 FlameMuzzle: placements=1, class=0x0030, widths=9w x1
 * - 0x0086 BossDrakorF: placements=0, class=0x0030, widths=none
 * - 0x046B SteamHoleDe: placements=0, class=0x0030, widths=none
 *
 * EN descriptor slot map:
 * - descriptor=0x8032AC90 gFirePipeObjDescriptor (slots=10, mask=0001101111)
 * - slot 03: 0x802202B8 firepipe_init ref=init
 * - slot 04: 0x80220288 firepipe_update ref=update
 * - slot 06: 0x802201E0 firepipe_render ref=render
 * - slot 07: 0x80220164 firepipe_free ref=free
 * - slot 08: 0x8022015C firepipe_func08 stub=const 1
 * - slot 09: 0x80220130 firepipe_getExtraSize stub=const 68 ref=getExtraSize (stub)
 */

#if 0
/*
 * Retail-backed packet constants. Promote only after EN code inspection.
 */
enum obj_0468_IceHole_packet_info {
    ICEHOLE_DEF_ID = 0x0468,
    ICEHOLE_DLL_ID = 0x0273,
    ICEHOLE_CLASS_ID = 0x0030,
    ICEHOLE_OBJECT_DEF_BYTES = 0xC0,
    ICEHOLE_PLACEMENT_BYTES_MIN = 0x24,
    ICEHOLE_PLACEMENT_BYTES_MAX = 0x24,
};
#endif
