/*
 * Auto-generated by tools/orig/object_def_packets.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists as a retail-backed per-object packet for exploratory split work.
 *
 * Object def: 0x0333 VFP_Block1
 * Output path: src/main/unknown/objects/obj_0333_vfp_block1.c
 * Retail placements: 3
 * Root romlists: 1
 * Object-def size: 0xA0
 * Root placement widths: 9w x3
 * DLL ID: 0x021E
 * Class ID: 0x0030
 * Suggested outer boundary: tight DLL family
 * Reference class name: various0030
 * Reference DLL name: VFP_Block1
 * Remap aliases: 0x03B9
 *
 * Related packet paths:
 * - class: src/main/unknown/classes/class_0030_various0030.c
 * - family: src/main/unknown/dll_021E_vfp_block1.c
 *
 * Width samples:
 * - 9w (0x24 bytes): temple.romlist.zlb
 *
 * Inline object-def evidence:
 * - inline fields: pModelList
 * - model IDs: 0x00000467
 * - help texts: 0xFFFF 0xFFFF 0xFFFF 0xFFFF
 *
 * Same-class objects (404 defs / 2358 placements):
 * - 0x04F9 LargeCrate: placements=329, dll=0x0105, widths=9w x329
 * - 0x0068 baddieInter: placements=175, dll=0x00DE, widths=9w x175
 * - 0x0318 VFP_lavapoo: placements=107, dll=0x0226, widths=9w x107
 * - 0x0466 FireHole: placements=101, dll=0x0273, widths=9w x101
 * - 0x03B9 WM_WallTorc: placements=96, dll=0x0206, widths=9w x96
 * - 0x0515 fuelCell: placements=77, dll=0x0123, widths=9w x77
 * - 0x04F7 SmallBasket: placements=74, dll=0x0104, widths=9w x74
 * - 0x0590 CraterFlame: placements=68, dll=0x01E7, widths=9w x68
 * - 0x0530 ARWGoldRing: placements=50, dll=0x02A0, widths=9w x50
 * - 0x04F8 LargeBasket: placements=44, dll=0x0105, widths=9w x44
 * - 0x0401 MMSH_WaterS: placements=41, dll=0x018E, widths=9w x41
 * - 0x0507 SpiritDoorS: placements=38, dll=0x0157, widths=9w x38
 * - ... 392 more class siblings omitted
 *
 * Same-DLL objects (1 defs / 3 placements):
 * - 0x0333 VFP_Block1: placements=3, class=0x0030, widths=9w x3
 *
 * EN descriptor slot map:
 * - descriptor=0x80329050 gVFP_Block1ObjDescriptor (slots=10, mask=1101111111)
 * - slot 00: 0x801FBAC4 vfpblock1_initialise stub=blr ref=initialise (stub)
 * - slot 01: 0x801FBAC0 vfpblock1_release stub=blr ref=release (stub)
 * - slot 03: 0x801FBA8C vfpblock1_init ref=init
 * - slot 04: 0x801FB9F4 vfpblock1_update ref=update
 * - slot 05: 0x801FB9F0 vfpblock1_hitDetect stub=blr ref=hitDetect (stub)
 * - slot 06: 0x801FB9EC vfpblock1_render stub=blr ref=render (stub)
 * - slot 07: 0x801FB9BC vfpblock1_free ref=free
 * - slot 08: 0x801FB9B4 vfpblock1_func08 stub=const 0
 * - slot 09: 0x801FB9AC vfpblock1_getExtraSize stub=const 2 ref=getExtraSize (stub)
 */

#if 0
/*
 * Retail-backed packet constants. Promote only after EN code inspection.
 */
enum obj_0333_VFP_Block1_packet_info {
    VFP_BLOCK1_DEF_ID = 0x0333,
    VFP_BLOCK1_DLL_ID = 0x021E,
    VFP_BLOCK1_CLASS_ID = 0x0030,
    VFP_BLOCK1_OBJECT_DEF_BYTES = 0xA0,
    VFP_BLOCK1_PLACEMENT_BYTES_MIN = 0x24,
    VFP_BLOCK1_PLACEMENT_BYTES_MAX = 0x24,
};
#endif
