/*
 * Auto-generated by tools/orig/object_def_packets.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists as a retail-backed per-object packet for exploratory split work.
 *
 * Object def: 0x03BB WM_Wallpowe
 * Output path: src/main/unknown/objects/obj_03BB_wm_wallpowe.c
 * Retail placements: 1
 * Root romlists: 1
 * Object-def size: 0xA0
 * Root placement widths: 9w x1
 * DLL ID: 0x0208
 * Class ID: 0x0030
 * Suggested outer boundary: tight DLL family
 * Reference class name: various0030
 * Reference DLL name: WM_Wallpower
 * Remap aliases: 0x017A
 *
 * Related packet paths:
 * - class: src/main/unknown/classes/class_0030_various0030.c
 * - family: src/main/unknown/dll_0208_wm_wallpower.c
 *
 * Width samples:
 * - 9w (0x24 bytes): warlock.romlist.zlb
 *
 * Inline object-def evidence:
 * - inline fields: pModelList
 * - model IDs: 0x0000045F
 * - help texts: 0xFFFF 0xFFFF 0xFFFF 0xFFFF
 *
 * Same-class objects (404 defs / 2358 placements):
 * - 0x04F9 LargeCrate: placements=329, dll=0x0105, widths=9w x329
 * - 0x0068 baddieInter: placements=175, dll=0x00DE, widths=9w x175
 * - 0x0318 VFP_lavapoo: placements=107, dll=0x0226, widths=9w x107
 * - 0x0466 FireHole: placements=101, dll=0x0273, widths=9w x101
 * - 0x03B9 WM_WallTorc: placements=96, dll=0x0206, widths=9w x96
 * - 0x0515 fuelCell: placements=77, dll=0x0123, widths=9w x77
 * - 0x04F7 SmallBasket: placements=74, dll=0x0104, widths=9w x74
 * - 0x0590 CraterFlame: placements=68, dll=0x01E7, widths=9w x68
 * - 0x0530 ARWGoldRing: placements=50, dll=0x02A0, widths=9w x50
 * - 0x04F8 LargeBasket: placements=44, dll=0x0105, widths=9w x44
 * - 0x0401 MMSH_WaterS: placements=41, dll=0x018E, widths=9w x41
 * - 0x0507 SpiritDoorS: placements=38, dll=0x0157, widths=9w x38
 * - ... 392 more class siblings omitted
 *
 * Same-DLL objects (1 defs / 1 placements):
 * - 0x03BB WM_Wallpowe: placements=1, class=0x0030, widths=9w x1
 */

#if 0
/*
 * Retail-backed packet constants. Promote only after EN code inspection.
 */
enum obj_03BB_WM_Wallpowe_packet_info {
    WM_WALLPOWE_DEF_ID = 0x03BB,
    WM_WALLPOWE_DLL_ID = 0x0208,
    WM_WALLPOWE_CLASS_ID = 0x0030,
    WM_WALLPOWE_OBJECT_DEF_BYTES = 0xA0,
    WM_WALLPOWE_PLACEMENT_BYTES_MIN = 0x24,
    WM_WALLPOWE_PLACEMENT_BYTES_MAX = 0x24,
};
#endif
