/*
 * Auto-generated by tools/orig/object_def_packets.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists as a retail-backed per-object packet for exploratory split work.
 *
 * Object def: 0x03C2 SPShop
 * Output path: src/main/unknown/objects/obj_03C2_spshop.c
 * Retail placements: 1
 * Root romlists: 1
 * Object-def size: 0xC0
 * Root placement widths: 6w x1
 * DLL ID: 0x0285
 * Class ID: 0x006E
 * Suggested outer boundary: singleton object boundary
 * Reference class name: SPShop
 * Reference DLL name: Shop
 * Remap aliases: 0x045C
 *
 * Related packet paths:
 * - class: src/main/unknown/classes/class_006E_spshop.c
 * - family: src/main/unknown/dll_0285_shop.c
 *
 * Width samples:
 * - 6w (0x18 bytes): swapstore.romlist.zlb
 *
 * Inline object-def evidence:
 * - inline fields: pModelList, pSeq, hitboxes
 * - model IDs: 0x00000467
 * - sequence IDs: 0x00C4 0x00C8 0x00CB 0x042B
 * - help texts: 0xFFFF 0xFFFF 0xFFFF 0xFFFF
 *
 * Same-class objects (1 defs / 1 placements):
 * - 0x03C2 SPShop: placements=1, dll=0x0285, widths=6w x1
 *
 * Same-DLL objects (1 defs / 1 placements):
 * - 0x03C2 SPShop: placements=1, class=0x006E, widths=6w x1
 *
 * EN descriptor slot map:
 * - descriptor=0x803282A0 gShopObjDescriptor (slots=24, mask=110111111111111111111111)
 * - slot 00: 0x801E66D8 shop_initialise stub=blr ref=initialise (stub)
 * - slot 01: 0x801E66D4 shop_release stub=blr ref=release (stub)
 * - slot 03: 0x801E6634 shop_init ref=init
 * - slot 04: 0x801E64C0 shop_update ref=update
 * - slot 05: 0x801E64BC shop_hitDetect stub=blr ref=hitDetect (stub)
 * - slot 06: 0x801E648C shop_render ref=render
 * - slot 07: 0x801E6434 shop_free ref=free
 * - slot 08: 0x801E642C shop_func08 stub=const 0
 * - slot 09: 0x801E6424 shop_getExtraSize stub=const 5 ref=getExtraSize (stub)
 * - slot 10: 0x801E6414 shop_setScale ref=setScale
 * - slot 11: 0x801E63C0 shop_func0B
 */

#if 0
/*
 * Retail-backed packet constants. Promote only after EN code inspection.
 */
enum obj_03C2_SPShop_packet_info {
    SPSHOP_DEF_ID = 0x03C2,
    SPSHOP_DLL_ID = 0x0285,
    SPSHOP_CLASS_ID = 0x006E,
    SPSHOP_OBJECT_DEF_BYTES = 0xC0,
    SPSHOP_PLACEMENT_BYTES_MIN = 0x18,
    SPSHOP_PLACEMENT_BYTES_MAX = 0x18,
};
#endif
