/*
 * Auto-generated by tools/orig/object_def_packets.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists as a retail-backed per-object packet for exploratory split work.
 *
 * Object def: 0x0319 VFP_flamepo
 * Output path: src/main/unknown/objects/obj_0319_vfp_flamepo.c
 * Retail placements: 8
 * Root romlists: 3
 * Object-def size: 0xC0
 * Root placement widths: 9w x8
 * DLL ID: 0x0225
 * Class ID: 0x0030
 * Suggested outer boundary: tight DLL family
 * Reference class name: various0030
 * Reference DLL name: VFP_flamepoint
 * Remap aliases: 0x0551
 *
 * Related packet paths:
 * - class: src/main/unknown/classes/class_0030_various0030.c
 * - family: src/main/unknown/dll_0225_vfp_flamepoint.c
 *
 * Width samples:
 * - 9w (0x24 bytes): kraztest.romlist.zlb, snowmines.romlist.zlb, temple.romlist.zlb
 *
 * Inline object-def evidence:
 * - inline fields: pModelList, hitboxes, aButtonInteraction
 * - model IDs: 0x0000045F
 * - help texts: 0xFFFF 0xFFFF 0xFFFF 0xFFFF
 *
 * Same-class objects (404 defs / 2358 placements):
 * - 0x04F9 LargeCrate: placements=329, dll=0x0105, widths=9w x329
 * - 0x0068 baddieInter: placements=175, dll=0x00DE, widths=9w x175
 * - 0x0318 VFP_lavapoo: placements=107, dll=0x0226, widths=9w x107
 * - 0x0466 FireHole: placements=101, dll=0x0273, widths=9w x101
 * - 0x03B9 WM_WallTorc: placements=96, dll=0x0206, widths=9w x96
 * - 0x0515 fuelCell: placements=77, dll=0x0123, widths=9w x77
 * - 0x04F7 SmallBasket: placements=74, dll=0x0104, widths=9w x74
 * - 0x0590 CraterFlame: placements=68, dll=0x01E7, widths=9w x68
 * - 0x0530 ARWGoldRing: placements=50, dll=0x02A0, widths=9w x50
 * - 0x04F8 LargeBasket: placements=44, dll=0x0105, widths=9w x44
 * - 0x0401 MMSH_WaterS: placements=41, dll=0x018E, widths=9w x41
 * - 0x0507 SpiritDoorS: placements=38, dll=0x0157, widths=9w x38
 * - ... 392 more class siblings omitted
 *
 * Same-DLL objects (1 defs / 8 placements):
 * - 0x0319 VFP_flamepo: placements=8, class=0x0030, widths=9w x8
 *
 * Reference-only DLL hints:
 * - things Tricky needs to use flame on
 *
 * EN descriptor slot map:
 * - descriptor=0x803291D8 gVFP_flamepointObjDescriptor (slots=10, mask=0001100001)
 * - slot 03: 0x801FD66C vfpflamepoint_init ref=init
 * - slot 04: 0x801FD4EC vfpflamepoint_update ref=update
 * - slot 09: 0x801FD4E4 vfpflamepoint_getExtraSize stub=const 8 ref=getExtraSize (stub)
 */

#if 0
/*
 * Retail-backed packet constants. Promote only after EN code inspection.
 */
enum obj_0319_VFP_flamepo_packet_info {
    VFP_FLAMEPO_DEF_ID = 0x0319,
    VFP_FLAMEPO_DLL_ID = 0x0225,
    VFP_FLAMEPO_CLASS_ID = 0x0030,
    VFP_FLAMEPO_OBJECT_DEF_BYTES = 0xC0,
    VFP_FLAMEPO_PLACEMENT_BYTES_MIN = 0x24,
    VFP_FLAMEPO_PLACEMENT_BYTES_MAX = 0x24,
};
#endif
