/*
 * Auto-generated by tools/orig/object_def_packets.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists as a retail-backed per-object packet for exploratory split work.
 *
 * Object def: 0x04C4 TrickyWarp
 * Output path: src/main/unknown/objects/obj_04C4_trickywarp.c
 * Retail placements: 2139
 * Root romlists: 19
 * Object-def size: 0xA0
 * Root placement widths: 8w x2139
 * DLL ID: 0x0100
 * Class ID: 0x0061
 * Suggested outer boundary: tight DLL family
 * Reference class name: various0061
 * Reference DLL name: TrickyWarp
 * Remap aliases: 0x031C
 *
 * Related packet paths:
 * - class: src/main/unknown/classes/class_0061_various0061.c
 * - family: src/main/unknown/dll_0100_trickywarp.c
 *
 * Width samples:
 * - 8w (0x20 bytes): capeclaw.romlist.zlb, dfptop.romlist.zlb, dragrock.romlist.zlb, hollow.romlist.zlb
 *
 * Inline object-def evidence:
 * - inline fields: pModelList
 * - model IDs: 0x000002D9
 * - help texts: 0xFFFF 0xFFFF 0xFFFF 0xFFFF
 *
 * Same-class objects (213 defs / 2907 placements):
 * - 0x04C4 TrickyWarp: placements=2139, dll=0x0100, widths=8w x2139
 * - 0x007F DRDebrisGir: placements=65, dll=0x011A, widths=8w x65
 * - 0x058D SnowLog: placements=65, dll=0x011A, widths=8w x65
 * - 0x0082 DRDebrisPip: placements=63, dll=0x011A, widths=8w x63
 * - 0x0592 CobwebCeili: placements=54, dll=0x011A, widths=8w x54
 * - 0x0587 SnowBoulder: placements=40, dll=0x02B0, widths=8w x40
 * - 0x0593 CobwebEdge: placements=32, dll=0x011A, widths=8w x32
 * - 0x056B AlienTreePa: placements=26, dll=0x011A, widths=8w x26
 * - 0x00A1 CFLightWall: placements=25, dll=0x012E, widths=8w x25
 * - 0x0081 DRDebrisPip: placements=24, dll=0x011A, widths=8w x24
 * - 0x057D BoulderOne: placements=24, dll=0x02B0, widths=8w x24
 * - 0x0591 CobwebCorne: placements=24, dll=0x011A, widths=8w x24
 * - ... 201 more class siblings omitted
 *
 * Same-DLL objects (1 defs / 2139 placements):
 * - 0x04C4 TrickyWarp: placements=2139, class=0x0061, widths=8w x2139
 *
 * EN descriptor slot map:
 * - descriptor=0x803215A0 gTrickyWarpObjDescriptor (slots=10, mask=0001100101)
 * - slot 03: 0x80180218 trickywarp_init ref=init
 * - slot 04: 0x8017FF48 trickywarp_update ref=update
 * - slot 07: 0x8017FF0C trickywarp_free ref=free
 * - slot 09: 0x8017FF40 trickywarp_getExtraSize stub=const 100 ref=getExtraSize (stub)
 */

#if 0
/*
 * Retail-backed packet constants. Promote only after EN code inspection.
 */
enum obj_04C4_TrickyWarp_packet_info {
    TRICKYWARP_DEF_ID = 0x04C4,
    TRICKYWARP_DLL_ID = 0x0100,
    TRICKYWARP_CLASS_ID = 0x0061,
    TRICKYWARP_OBJECT_DEF_BYTES = 0xA0,
    TRICKYWARP_PLACEMENT_BYTES_MIN = 0x20,
    TRICKYWARP_PLACEMENT_BYTES_MAX = 0x20,
};
#endif
