/*
 * Auto-generated by tools/orig/object_def_packets.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists as a retail-backed per-object packet for exploratory split work.
 *
 * Object def: 0x01F1 CCriverflow
 * Output path: src/main/unknown/objects/obj_01F1_ccriverflow.c
 * Retail placements: 127
 * Root romlists: 9
 * Object-def size: 0xA0
 * Root placement widths: 8w x127
 * DLL ID: 0x0174
 * Class ID: 0x0035
 * Suggested outer boundary: singleton object boundary
 * Reference class name: CCriverflow
 * Reference DLL name: CCriverflow
 * Remap aliases: 0x007B
 *
 * Related packet paths:
 * - class: src/main/unknown/classes/class_0035_ccriverflow.c
 * - family: src/main/unknown/dll_0174_ccriverflow.c
 *
 * Width samples:
 * - 8w (0x20 bytes): capeclaw.romlist.zlb, dfptop.romlist.zlb, fortress.romlist.zlb, linkc.romlist.zlb
 *
 * Inline object-def evidence:
 * - inline fields: pModelList
 * - model IDs: 0x0000045F
 * - help texts: 0xFFFF 0xFFFF 0xFFFF 0xFFFF
 *
 * Same-class objects (1 defs / 127 placements):
 * - 0x01F1 CCriverflow: placements=127, dll=0x0174, widths=8w x127
 *
 * Same-DLL objects (1 defs / 127 placements):
 * - 0x01F1 CCriverflow: placements=127, class=0x0035, widths=8w x127
 *
 * EN descriptor slot map:
 * - descriptor=0x80325DC8 gCCriverflowObjDescriptor (slots=10, mask=0001101101)
 * - slot 03: 0x801C0B34 ccriverflow_init ref=init
 * - slot 04: 0x801C0AA0 ccriverflow_update ref=update
 * - slot 06: 0x801C0A9C ccriverflow_render stub=blr ref=render (stub)
 * - slot 07: 0x801C0A68 ccriverflow_free ref=free
 * - slot 09: 0x801C0A60 ccriverflow_getExtraSize stub=const 1 ref=getExtraSize (stub)
 */

#if 0
/*
 * Retail-backed packet constants. Promote only after EN code inspection.
 */
enum obj_01F1_CCriverflow_packet_info {
    CCRIVERFLOW_DEF_ID = 0x01F1,
    CCRIVERFLOW_DLL_ID = 0x0174,
    CCRIVERFLOW_CLASS_ID = 0x0035,
    CCRIVERFLOW_OBJECT_DEF_BYTES = 0xA0,
    CCRIVERFLOW_PLACEMENT_BYTES_MIN = 0x20,
    CCRIVERFLOW_PLACEMENT_BYTES_MAX = 0x20,
};
#endif
