/*
 * Auto-generated by tools/orig/object_def_packets.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists as a retail-backed per-object packet for exploratory split work.
 *
 * Object def: 0x04AE texscroll
 * Output path: src/main/unknown/objects/obj_04AE_texscroll.c
 * Retail placements: 5
 * Root romlists: 3
 * Object-def size: 0xA0
 * Root placement widths: 9w x5
 * DLL ID: 0x0135
 * Class ID: 0x0021
 * Suggested outer boundary: tight class packet
 * Reference class name: texscroll
 * Reference DLL name: texscroll
 * Remap aliases: 0x000F
 *
 * Related packet paths:
 * - class: src/main/unknown/classes/class_0021_texscroll.c
 * - family: src/main/unknown/dll_0135_texscroll.c
 *
 * Width samples:
 * - 9w (0x24 bytes): cloudrace.romlist.zlb, swapstore.romlist.zlb, wminsert.romlist.zlb
 *
 * Inline object-def evidence:
 * - inline fields: pModelList
 * - model IDs: 0x0000046B
 * - help texts: 0xFFFF 0xFFFF 0xFFFF 0xFFFF
 *
 * Same-class objects (2 defs / 226 placements):
 * - 0x04AF texscroll2: placements=221, dll=0x0134, widths=9w x221
 * - 0x04AE texscroll: placements=5, dll=0x0135, widths=9w x5
 *
 * Same-DLL objects (1 defs / 5 placements):
 * - 0x04AE texscroll: placements=5, class=0x0021, widths=9w x5
 *
 * EN descriptor slot map:
 * - descriptor=0x80322140 gTexscrollObjDescriptor (slots=10, mask=1101111111)
 * - slot 00: 0x80192390 texscroll_initialise stub=blr ref=initialise (stub)
 * - slot 01: 0x8019238C texscroll_release stub=blr ref=release (stub)
 * - slot 03: 0x80192330 texscroll_init ref=init
 * - slot 04: 0x8019232C texscroll_update stub=blr ref=update (stub)
 * - slot 05: 0x80192328 texscroll_hitDetect stub=blr ref=hitDetect (stub)
 * - slot 06: 0x801922F8 texscroll_render ref=render
 * - slot 07: 0x801922F4 texscroll_free stub=blr ref=free (stub)
 * - slot 08: 0x801922EC texscroll_func08 stub=const 0
 * - slot 09: 0x801922E4 texscroll_getExtraSize stub=const 28 ref=getExtraSize (stub)
 */

#if 0
/*
 * Retail-backed packet constants. Promote only after EN code inspection.
 */
enum obj_04AE_texscroll_packet_info {
    TEXSCROLL_DEF_ID = 0x04AE,
    TEXSCROLL_DLL_ID = 0x0135,
    TEXSCROLL_CLASS_ID = 0x0021,
    TEXSCROLL_OBJECT_DEF_BYTES = 0xA0,
    TEXSCROLL_PLACEMENT_BYTES_MIN = 0x24,
    TEXSCROLL_PLACEMENT_BYTES_MAX = 0x24,
};
#endif
