/*
 * Auto-generated by tools/orig/object_def_packets.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists as a retail-backed per-object packet for exploratory split work.
 *
 * Object def: 0x015F DIMplacehol
 * Output path: src/main/unknown/objects/obj_015F_dimplacehol.c
 * Retail placements: 2
 * Root romlists: 1
 * Object-def size: 0xA0
 * Root placement widths: 9w x2
 * DLL ID: 0xFFFF
 * Class ID: 0x0030
 * Suggested outer boundary: shared DLL family
 * Reference class name: various0030
 * Remap aliases: 0x06F8
 *
 * Related packet paths:
 * - class: src/main/unknown/classes/class_0030_various0030.c
 *
 * Width samples:
 * - 9w (0x24 bytes): snowmines.romlist.zlb
 *
 * Inline object-def evidence:
 * - inline fields: pModelList
 * - model IDs: 0x0000045F
 * - help texts: 0xFFFF 0xFFFF 0xFFFF 0xFFFF
 *
 * Same-class objects (404 defs / 2358 placements):
 * - 0x04F9 LargeCrate: placements=329, dll=0x0105, widths=9w x329
 * - 0x0068 baddieInter: placements=175, dll=0x00DE, widths=9w x175
 * - 0x0318 VFP_lavapoo: placements=107, dll=0x0226, widths=9w x107
 * - 0x0466 FireHole: placements=101, dll=0x0273, widths=9w x101
 * - 0x03B9 WM_WallTorc: placements=96, dll=0x0206, widths=9w x96
 * - 0x0515 fuelCell: placements=77, dll=0x0123, widths=9w x77
 * - 0x04F7 SmallBasket: placements=74, dll=0x0104, widths=9w x74
 * - 0x0590 CraterFlame: placements=68, dll=0x01E7, widths=9w x68
 * - 0x0530 ARWGoldRing: placements=50, dll=0x02A0, widths=9w x50
 * - 0x04F8 LargeBasket: placements=44, dll=0x0105, widths=9w x44
 * - 0x0401 MMSH_WaterS: placements=41, dll=0x018E, widths=9w x41
 * - 0x0507 SpiritDoorS: placements=38, dll=0x0157, widths=9w x38
 * - ... 392 more class siblings omitted
 *
 * Same-DLL objects (63 defs / 2 placements):
 * - 0x015F DIMplacehol: placements=2, class=0x0030, widths=9w x2
 * - 0x0000 DummyObject: placements=0, class=0x0000, widths=none
 * - 0x0002 Sabre: placements=0, class=0x0001, widths=none
 * - 0x0003 Krystal: placements=0, class=0x0001, widths=none
 * - 0x0005 TrickyBadge: placements=0, class=0x0061, widths=none
 * - 0x0006 TrickyBadge: placements=0, class=0x0061, widths=none
 * - 0x0008 ModelsWithT: placements=0, class=0x0061, widths=none
 * - 0x000B TrickyExcla: placements=0, class=0x0061, widths=none
 * - 0x000C TrickyQuest: placements=0, class=0x0061, widths=none
 * - 0x000D TrickyFood: placements=0, class=0x0061, widths=none
 * - 0x0011 BackPack: placements=0, class=0x0061, widths=none
 * - 0x0012 groundquake: placements=0, class=0x0030, widths=none
 * - ... 51 more DLL siblings omitted
 */

#if 0
/*
 * Retail-backed packet constants. Promote only after EN code inspection.
 */
enum obj_015F_DIMplacehol_packet_info {
    DIMPLACEHOL_DEF_ID = 0x015F,
    DIMPLACEHOL_DLL_ID = 0xFFFF,
    DIMPLACEHOL_CLASS_ID = 0x0030,
    DIMPLACEHOL_OBJECT_DEF_BYTES = 0xA0,
    DIMPLACEHOL_PLACEMENT_BYTES_MIN = 0x24,
    DIMPLACEHOL_PLACEMENT_BYTES_MAX = 0x24,
};
#endif
