/*
 * Auto-generated by tools/orig/object_def_packets.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists as a retail-backed per-object packet for exploratory split work.
 *
 * Object def: 0x0197 DIM2PrisonM
 * Output path: src/main/unknown/objects/obj_0197_dim2prisonm.c
 * Retail placements: 2
 * Root romlists: 1
 * Object-def size: 0x120
 * Root placement widths: 9w x2
 * DLL ID: 0x01D9
 * Class ID: 0x0030
 * Suggested outer boundary: tight DLL family
 * Reference class name: various0030
 * Reference DLL name: DIM2PrisonMammoth
 * Remap aliases: 0x018A
 *
 * Related packet paths:
 * - class: src/main/unknown/classes/class_0030_various0030.c
 * - family: src/main/unknown/dll_01D9_dim2prisonmammoth.c
 *
 * Width samples:
 * - 9w (0x24 bytes): snowmines2.romlist.zlb
 *
 * Inline object-def evidence:
 * - inline fields: pModelList, pSeq, hitboxes, aButtonInteraction
 * - model IDs: 0x000003AA
 * - sequence IDs: 0x05C8
 * - help texts: 0x010D 0xFFFF 0xFFFF 0xFFFF
 *
 * Same-class objects (404 defs / 2358 placements):
 * - 0x04F9 LargeCrate: placements=329, dll=0x0105, widths=9w x329
 * - 0x0068 baddieInter: placements=175, dll=0x00DE, widths=9w x175
 * - 0x0318 VFP_lavapoo: placements=107, dll=0x0226, widths=9w x107
 * - 0x0466 FireHole: placements=101, dll=0x0273, widths=9w x101
 * - 0x03B9 WM_WallTorc: placements=96, dll=0x0206, widths=9w x96
 * - 0x0515 fuelCell: placements=77, dll=0x0123, widths=9w x77
 * - 0x04F7 SmallBasket: placements=74, dll=0x0104, widths=9w x74
 * - 0x0590 CraterFlame: placements=68, dll=0x01E7, widths=9w x68
 * - 0x0530 ARWGoldRing: placements=50, dll=0x02A0, widths=9w x50
 * - 0x04F8 LargeBasket: placements=44, dll=0x0105, widths=9w x44
 * - 0x0401 MMSH_WaterS: placements=41, dll=0x018E, widths=9w x41
 * - 0x0507 SpiritDoorS: placements=38, dll=0x0157, widths=9w x38
 * - ... 392 more class siblings omitted
 *
 * Same-DLL objects (1 defs / 2 placements):
 * - 0x0197 DIM2PrisonM: placements=2, class=0x0030, widths=9w x2
 *
 * EN descriptor slot map:
 * - descriptor=0x803351BC gDIM2PrisonMammothObjDescriptor (slots=10, mask=1101111111)
 * - slot 00: 0x802BC740 dim2prisonmammoth_initialise ref=initialise
 * - slot 01: 0x802BC73C dim2prisonmammoth_release stub=blr ref=release (stub)
 * - slot 03: 0x802BC67C dim2prisonmammoth_init ref=init
 * - slot 04: 0x802BC4F8 dim2prisonmammoth_update ref=update
 * - slot 05: 0x802BC4F4 dim2prisonmammoth_hitDetect stub=blr ref=hitDetect (stub)
 * - slot 06: 0x802BC4C4 dim2prisonmammoth_render ref=render
 * - slot 07: 0x802BC4C0 dim2prisonmammoth_free stub=blr ref=free (stub)
 * - slot 08: 0x802BC4B8 dim2prisonmammoth_func08 stub=const 0
 * - slot 09: 0x802BC4B0 dim2prisonmammoth_getExtraSize stub=const 1540 ref=getExtraSize (stub)
 */

#if 0
/*
 * Retail-backed packet constants. Promote only after EN code inspection.
 */
enum obj_0197_DIM2PrisonM_packet_info {
    DIM2PRISONM_DEF_ID = 0x0197,
    DIM2PRISONM_DLL_ID = 0x01D9,
    DIM2PRISONM_CLASS_ID = 0x0030,
    DIM2PRISONM_OBJECT_DEF_BYTES = 0x120,
    DIM2PRISONM_PLACEMENT_BYTES_MIN = 0x24,
    DIM2PRISONM_PLACEMENT_BYTES_MAX = 0x24,
};
#endif
