/*
 * Auto-generated by tools/orig/object_def_packets.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists as a retail-backed per-object packet for exploratory split work.
 *
 * Object def: 0x0024 SkeetlaWall
 * Output path: src/main/unknown/objects/obj_0024_skeetlawall.c
 * Retail placements: 0
 * Root romlists: 0
 * Object-def size: 0xA0
 * Root placement widths: none
 * DLL ID: 0x00D4
 * Class ID: 0x0072
 * Suggested outer boundary: singleton object boundary
 * Reference class name: SkeetlaWall
 * Reference DLL name: SkeetlaWall
 * Remap aliases: 0x04AD
 *
 * Related packet paths:
 * - class: src/main/unknown/classes/class_0072_skeetlawall.c
 * - family: src/main/unknown/dll_00D4_skeetlawall.c
 *
 * Width samples:
 * - none
 *
 * Inline object-def evidence:
 * - inline fields: pModelList
 * - model IDs: 0x00000461
 * - help texts: 0xFFFF 0xFFFF 0xFFFF 0xFFFF
 *
 * Same-class objects (1 defs / 0 placements):
 * - 0x0024 SkeetlaWall: placements=0, dll=0x00D4, widths=none
 *
 * Same-DLL objects (1 defs / 0 placements):
 * - 0x0024 SkeetlaWall: placements=0, class=0x0072, widths=none
 *
 * EN descriptor slot map:
 * - descriptor=0x803203B8 gSkeetlaWallObjDescriptor (slots=11, mask=11011111111)
 * - slot 00: 0x80167760 skeetlawall_initialise stub=blr ref=initialise (stub)
 * - slot 01: 0x8016775C skeetlawall_release stub=blr ref=release (stub)
 * - slot 03: 0x8016771C skeetlawall_init ref=init
 * - slot 04: 0x80167718 skeetlawall_update stub=blr ref=update (stub)
 * - slot 05: 0x80167714 skeetlawall_hitDetect stub=blr ref=hitDetect (stub)
 * - slot 06: 0x801676D4 skeetlawall_render ref=render
 * - slot 07: 0x801676D0 skeetlawall_free stub=blr ref=free (stub)
 * - slot 08: 0x801676C8 skeetlawall_func08 stub=const 0
 * - slot 09: 0x801676C0 skeetlawall_getExtraSize stub=const 7 ref=getExtraSize (stub)
 * - slot 10: 0x801675E0 skeetlawall_setScale ref=setScale
 */

#if 0
/*
 * Retail-backed packet constants. Promote only after EN code inspection.
 */
enum obj_0024_SkeetlaWall_packet_info {
    SKEETLAWALL_DEF_ID = 0x0024,
    SKEETLAWALL_DLL_ID = 0x00D4,
    SKEETLAWALL_CLASS_ID = 0x0072,
    SKEETLAWALL_OBJECT_DEF_BYTES = 0xA0,
};
#endif
