/*
 * Auto-generated by tools/orig/object_def_packets.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists as a retail-backed per-object packet for exploratory split work.
 *
 * Object def: 0x03DF SPMapVFP
 * Output path: src/main/unknown/objects/obj_03DF_spmapvfp.c
 * Retail placements: 1
 * Root romlists: 1
 * Object-def size: 0xE0
 * Root placement widths: 7w x1
 * DLL ID: 0x0284
 * Class ID: 0x0070
 * Suggested outer boundary: shared DLL family
 * Reference class name: ShopItem
 * Reference DLL name: ShopItem
 * Remap aliases: 0x0878
 *
 * Related packet paths:
 * - class: src/main/unknown/classes/class_0070_shopitem.c
 * - family: src/main/unknown/dll_0284_shopitem.c
 *
 * Width samples:
 * - 7w (0x1c bytes): swapstore.romlist.zlb
 *
 * Inline object-def evidence:
 * - inline fields: pModelList, pSeq, hitboxes, aButtonInteraction
 * - model IDs: 0x00000439
 * - sequence IDs: 0x00C3 0x0118
 * - help texts: 0xFFFF 0xFFFF 0xFFFF 0xFFFF
 *
 * Same-class objects (30 defs / 26 placements):
 * - 0x03C4 SPFruitSmal: placements=1, dll=0x0284, widths=7w x1
 * - 0x03C5 SPEggSmall: placements=1, dll=0x0284, widths=7w x1
 * - 0x03C6 SPFruitLarg: placements=1, dll=0x0284, widths=7w x1
 * - 0x03C7 SPEggLarge: placements=1, dll=0x0284, widths=7w x1
 * - 0x03C8 SPBombSpore: placements=1, dll=0x0284, widths=7w x1
 * - 0x03CA SPLantern: placements=1, dll=0x0284, widths=7w x1
 * - 0x03CB SPBlueArtef: placements=1, dll=0x0284, widths=7w x1
 * - 0x03CC SPBlueMushr: placements=1, dll=0x0284, widths=7w x1
 * - 0x03CD SPSwapGift: placements=1, dll=0x0284, widths=7w x1
 * - 0x03CF SPBinocular: placements=1, dll=0x0284, widths=7w x1
 * - 0x03D0 SPFireFly: placements=1, dll=0x0284, widths=7w x1
 * - 0x03D1 SPFuelCell: placements=1, dll=0x0284, widths=7w x1
 * - ... 18 more class siblings omitted
 *
 * Same-DLL objects (30 defs / 26 placements):
 * - 0x03C4 SPFruitSmal: placements=1, class=0x0070, widths=7w x1
 * - 0x03C5 SPEggSmall: placements=1, class=0x0070, widths=7w x1
 * - 0x03C6 SPFruitLarg: placements=1, class=0x0070, widths=7w x1
 * - 0x03C7 SPEggLarge: placements=1, class=0x0070, widths=7w x1
 * - 0x03C8 SPBombSpore: placements=1, class=0x0070, widths=7w x1
 * - 0x03CA SPLantern: placements=1, class=0x0070, widths=7w x1
 * - 0x03CB SPBlueArtef: placements=1, class=0x0070, widths=7w x1
 * - 0x03CC SPBlueMushr: placements=1, class=0x0070, widths=7w x1
 * - 0x03CD SPSwapGift: placements=1, class=0x0070, widths=7w x1
 * - 0x03CF SPBinocular: placements=1, class=0x0070, widths=7w x1
 * - 0x03D0 SPFireFly: placements=1, class=0x0070, widths=7w x1
 * - 0x03D1 SPFuelCell: placements=1, class=0x0070, widths=7w x1
 * - ... 18 more DLL siblings omitted
 *
 * EN descriptor slot map:
 * - descriptor=0x803283E0 gShopItemObjDescriptor (slots=10, mask=1101111111)
 * - slot 00: 0x801E8EA0 shopitem_initialise stub=blr ref=initialise (stub)
 * - slot 01: 0x801E8E9C shopitem_release stub=blr ref=release (stub)
 * - slot 03: 0x801E8D7C shopitem_init ref=init
 * - slot 04: 0x801E8968 shopitem_update ref=update
 * - slot 05: 0x801E8964 shopitem_hitDetect stub=blr ref=hitDetect (stub)
 * - slot 06: 0x801E8910 shopitem_render ref=render
 * - slot 07: 0x801E88B8 shopitem_free ref=free
 * - slot 08: 0x801E88B0 shopitem_func08 stub=const 0
 * - slot 09: 0x801E88A8 shopitem_getExtraSize stub=const 236 ref=getExtraSize (stub)
 */

#if 0
/*
 * Retail-backed packet constants. Promote only after EN code inspection.
 */
enum obj_03DF_SPMapVFP_packet_info {
    SPMAPVFP_DEF_ID = 0x03DF,
    SPMAPVFP_DLL_ID = 0x0284,
    SPMAPVFP_CLASS_ID = 0x0070,
    SPMAPVFP_OBJECT_DEF_BYTES = 0xE0,
    SPMAPVFP_PLACEMENT_BYTES_MIN = 0x1C,
    SPMAPVFP_PLACEMENT_BYTES_MAX = 0x1C,
};
#endif
