/*
 * Auto-generated by tools/orig/object_def_packets.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists as a retail-backed per-object packet for exploratory split work.
 *
 * Object def: 0x008A KT_Rex
 * Output path: src/main/unknown/objects/obj_008A_kt_rex.c
 * Retail placements: 1
 * Root romlists: 1
 * Object-def size: 0x260
 * Root placement widths: 23w x1
 * DLL ID: 0x0250
 * Class ID: 0x006D
 * Suggested outer boundary: singleton object boundary
 * Reference class name: KT_Rex
 * Reference DLL name: KT_Rex
 * Remap aliases: 0x03D9
 *
 * Related packet paths:
 * - class: src/main/unknown/classes/class_006D_kt_rex.c
 * - family: src/main/unknown/dll_0250_kt_rex.c
 *
 * Width samples:
 * - 23w (0x5c bytes): trexboss.romlist.zlb
 *
 * Inline object-def evidence:
 * - inline fields: pModelList, pEvent, pHits, hitboxes, aButtonInteraction
 * - model IDs: 0x0000006D 0x0000006E
 * - help texts: 0x0122 0xFFFF 0xFFFF 0xFFFF
 *
 * Same-class objects (1 defs / 1 placements):
 * - 0x008A KT_Rex: placements=1, dll=0x0250, widths=23w x1
 *
 * Same-DLL objects (1 defs / 1 placements):
 * - 0x008A KT_Rex: placements=1, class=0x006D, widths=23w x1
 *
 * EN descriptor slot map:
 * - descriptor=0x8032A58C gKtRexObjDescriptor (slots=12, mask=110111111111)
 * - slot 00: 0x8021590C ktrex_initialise ref=initialise
 * - slot 01: 0x80215908 ktrex_release stub=blr ref=release (stub)
 * - slot 03: 0x80215538 ktrex_init ref=init
 * - slot 04: 0x80215254 ktrex_update ref=update
 * - slot 05: 0x802151EC ktrex_hitDetect ref=hitDetect
 * - slot 06: 0x80214F20 ktrex_render ref=render
 * - slot 07: 0x80214E34 ktrex_free ref=free
 * - slot 08: 0x80214E2C ktrex_func08 stub=const 73
 * - slot 09: 0x80214E24 ktrex_getExtraSize stub=const 1444 ref=getExtraSize (stub)
 * - slot 10: 0x80214E14 ktrex_setScale ref=setScale
 * - slot 11: 0x80214E10 ktrex_func0B stub=blr
 */

#if 0
/*
 * Retail-backed packet constants. Promote only after EN code inspection.
 */
enum obj_008A_KT_Rex_packet_info {
    KT_REX_DEF_ID = 0x008A,
    KT_REX_DLL_ID = 0x0250,
    KT_REX_CLASS_ID = 0x006D,
    KT_REX_OBJECT_DEF_BYTES = 0x260,
    KT_REX_PLACEMENT_BYTES_MIN = 0x5C,
    KT_REX_PLACEMENT_BYTES_MAX = 0x5C,
};
#endif
