/*
 * Auto-generated by tools/orig/object_def_packets.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists as a retail-backed per-object packet for exploratory split work.
 *
 * Object def: 0x0445 DR_Seqobj
 * Output path: src/main/unknown/objects/obj_0445_dr_seqobj.c
 * Retail placements: 8
 * Root romlists: 1
 * Object-def size: 0xE0
 * Root placement widths: 10w x8
 * DLL ID: 0x0112
 * Class ID: 0x0055
 * Suggested outer boundary: shared DLL family
 * Reference class name: SeqObject
 * Reference DLL name: SeqObject
 * Remap aliases: 0x03B6
 *
 * Related packet paths:
 * - class: src/main/unknown/classes/class_0055_seqobject.c
 * - family: src/main/unknown/dll_0112_seqobject.c
 *
 * Width samples:
 * - 10w (0x28 bytes): dragrock.romlist.zlb
 *
 * Inline object-def evidence:
 * - inline fields: pModelList, pSeq, hitboxes
 * - model IDs: 0x00000466
 * - sequence IDs: 0x02BF 0x059C 0x02C1 0x02C2 0x02C3 0x0310 0x009F 0x02CC 0x0337 0x0338 0x0339 0x033A 0x034B 0x009F 0x0395 0x035A 0x009F 0x009F 0x009F 0x04AA 0x04AB 0x04AC 0x04C1 0x04DD 0x04F0 0x04F1
 * - help texts: 0xFFFF 0xFFFF 0xFFFF 0xFFFF
 *
 * Same-class objects (44 defs / 295 placements):
 * - 0x0162 DIMSeqObjec: placements=34, dll=0x0112, widths=10w x34
 * - 0x00F2 CFseqobject: placements=28, dll=0x0112, widths=10w x28
 * - 0x00F4 CAMERAseqob: placements=24, dll=0x0112, widths=10w x24
 * - 0x02D1 SC_sequence: placements=20, dll=0x0112, widths=10w x20
 * - 0x01B9 IMSeqObject: placements=17, dll=0x0112, widths=10w x17
 * - 0x04A6 CF_BobbingC: placements=17, dll=0x0112, widths=10w x17
 * - 0x011D WCSeqObject: placements=16, dll=0x0112, widths=10w x16
 * - 0x025D MMP_seqobje: placements=15, dll=0x0112, widths=10w x15
 * - 0x0185 DIM2SeqObje: placements=12, dll=0x0112, widths=10w x12
 * - 0x00F3 CFRaceSeqob: placements=11, dll=0x0112, widths=10w x11
 * - 0x0446 FireHoleCon: placements=11, dll=0x0112, widths=10w x11
 * - 0x0549 ARWSeqObjec: placements=10, dll=0x0112, widths=10w x10
 * - ... 32 more class siblings omitted
 *
 * Same-DLL objects (43 defs / 293 placements):
 * - 0x0162 DIMSeqObjec: placements=34, class=0x0055, widths=10w x34
 * - 0x00F2 CFseqobject: placements=28, class=0x0055, widths=10w x28
 * - 0x00F4 CAMERAseqob: placements=24, class=0x0055, widths=10w x24
 * - 0x02D1 SC_sequence: placements=20, class=0x0055, widths=10w x20
 * - 0x01B9 IMSeqObject: placements=17, class=0x0055, widths=10w x17
 * - 0x04A6 CF_BobbingC: placements=17, class=0x0055, widths=10w x17
 * - 0x011D WCSeqObject: placements=16, class=0x0055, widths=10w x16
 * - 0x025D MMP_seqobje: placements=15, class=0x0055, widths=10w x15
 * - 0x0185 DIM2SeqObje: placements=12, class=0x0055, widths=10w x12
 * - 0x00F3 CFRaceSeqob: placements=11, class=0x0055, widths=10w x11
 * - 0x0446 FireHoleCon: placements=11, class=0x0055, widths=10w x11
 * - 0x0549 ARWSeqObjec: placements=10, class=0x0055, widths=10w x10
 * - ... 31 more DLL siblings omitted
 *
 * Reference-only DLL hints:
 * - objparams size: 0x24
 *
 * EN descriptor slot map:
 * - descriptor=0x80321168 gSeqObjectObjDescriptor (slots=10, mask=0001101111)
 * - slot 03: 0x8017C6AC seqobject_init ref=init
 * - slot 04: 0x8017C45C seqobject_update ref=update
 * - slot 06: 0x8017C42C seqobject_render ref=render
 * - slot 07: 0x8017C408 seqobject_free ref=free
 * - slot 08: 0x8017C400 seqobject_func08 stub=const 0
 * - slot 09: 0x8017C3F8 seqobject_getExtraSize stub=const 3 ref=getExtraSize (stub)
 */

#if 0
/*
 * Retail-backed packet constants. Promote only after EN code inspection.
 */
enum obj_0445_DR_Seqobj_packet_info {
    DR_SEQOBJ_DEF_ID = 0x0445,
    DR_SEQOBJ_DLL_ID = 0x0112,
    DR_SEQOBJ_CLASS_ID = 0x0055,
    DR_SEQOBJ_OBJECT_DEF_BYTES = 0xE0,
    DR_SEQOBJ_PLACEMENT_BYTES_MIN = 0x28,
    DR_SEQOBJ_PLACEMENT_BYTES_MAX = 0x28,
};
#endif
