/*
 * Auto-generated by tools/orig/object_def_packets.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists as a retail-backed per-object packet for exploratory split work.
 *
 * Object def: 0x0320 VFP_PodiumP
 * Output path: src/main/unknown/objects/obj_0320_vfp_podiump.c
 * Retail placements: 10
 * Root romlists: 2
 * Object-def size: 0xE0
 * Root placement widths: 10w x10
 * DLL ID: 0x0111
 * Class ID: 0x0054
 * Suggested outer boundary: shared DLL family
 * Reference class name: Lock
 * Reference DLL name: Lock
 * Remap aliases: 0x0540
 *
 * Related packet paths:
 * - class: src/main/unknown/classes/class_0054_lock.c
 * - family: src/main/unknown/dll_0111_lock.c
 *
 * Width samples:
 * - 10w (0x28 bytes): dfptop.romlist.zlb, temple.romlist.zlb
 *
 * Inline object-def evidence:
 * - inline fields: pModelList, pSeq, hitboxes, aButtonInteraction
 * - model IDs: 0x00000467
 * - sequence IDs: 0x0581 0x0582 0x05C9
 * - help texts: 0x011A 0xFFFF 0xFFFF 0xFFFF
 *
 * Same-class objects (24 defs / 41 placements):
 * - 0x0320 VFP_PodiumP: placements=10, dll=0x0111, widths=10w x10
 * - 0x04AC Landed_Arwi: placements=5, dll=0x011B, widths=10w x5
 * - 0x0132 WCInvUseObj: placements=4, dll=0x0293, widths=10w x4
 * - 0x0179 DIMUseObjec: placements=4, dll=0x0111, widths=10w x4
 * - 0x00D2 CFSunTemple: placements=3, dll=0x0293, widths=10w x3
 * - 0x019F DIM2CellKey: placements=3, dll=0x0111, widths=10w x3
 * - 0x02E8 SC_blockpla: placements=3, dll=0x0111, widths=10w x3
 * - 0x014F DIMLever: placements=2, dll=0x0111, widths=10w x2
 * - 0x04AD Landed_Arwi: placements=2, dll=0x011B, widths=10w x2
 * - 0x00B4 CFPowerLock: placements=1, dll=0x0111, widths=10w x1
 * - 0x015C DIMSnowHorn: placements=1, dll=0x0111, widths=10w x1
 * - 0x017A DIMUseObjec: placements=1, dll=0x0111, widths=10w x1
 * - ... 12 more class siblings omitted
 *
 * Same-DLL objects (18 defs / 27 placements):
 * - 0x0320 VFP_PodiumP: placements=10, class=0x0054, widths=10w x10
 * - 0x0179 DIMUseObjec: placements=4, class=0x0054, widths=10w x4
 * - 0x019F DIM2CellKey: placements=3, class=0x0054, widths=10w x3
 * - 0x02E8 SC_blockpla: placements=3, class=0x0054, widths=10w x3
 * - 0x014F DIMLever: placements=2, class=0x0054, widths=10w x2
 * - 0x00B4 CFPowerLock: placements=1, class=0x0054, widths=10w x1
 * - 0x015C DIMSnowHorn: placements=1, class=0x0054, widths=10w x1
 * - 0x017A DIMUseObjec: placements=1, class=0x0054, widths=10w x1
 * - 0x0261 MMP_padlock: placements=1, class=0x0054, widths=10w x1
 * - 0x037D WM_padlock: placements=1, class=0x0054, widths=10w x1
 * - 0x00C6 CFDoubleSwi: placements=0, class=0x0054, widths=none
 * - 0x011C WCTeethBowl: placements=0, class=0x0054, widths=none
 * - ... 6 more DLL siblings omitted
 *
 * Reference-only DLL hints:
 * - Any object that consumes an item to "open" it - padlocks, bridge cogs, LightFoot Village stone block spots, etc
 *
 * EN descriptor slot map:
 * - descriptor=0x80321130 gDoorLockObjDescriptor (slots=10, mask=0001101101)
 * - slot 03: 0x8017C178 doorlock_init ref=DoorLock_init
 * - slot 04: 0x8017BE28 doorlock_update ref=DoorLock_update
 * - slot 06: 0x8017BDD8 doorlock_render ref=DoorLock_render
 * - slot 07: 0x8017BDB4 doorlock_free ref=DoorLock_free
 * - slot 09: 0x8017BDAC doorlock_getExtraSize stub=const 1 ref=DoorLock_getExtraSize (stub)
 */

#if 0
/*
 * Retail-backed packet constants. Promote only after EN code inspection.
 */
enum obj_0320_VFP_PodiumP_packet_info {
    VFP_PODIUMP_DEF_ID = 0x0320,
    VFP_PODIUMP_DLL_ID = 0x0111,
    VFP_PODIUMP_CLASS_ID = 0x0054,
    VFP_PODIUMP_OBJECT_DEF_BYTES = 0xE0,
    VFP_PODIUMP_PLACEMENT_BYTES_MIN = 0x28,
    VFP_PODIUMP_PLACEMENT_BYTES_MAX = 0x28,
};
#endif
