/*
 * Auto-generated by tools/orig/object_def_packets.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists as a retail-backed per-object packet for exploratory split work.
 *
 * Object def: 0x033E VFP_ObjCrea
 * Output path: src/main/unknown/objects/obj_033E_vfp_objcrea.c
 * Retail placements: 13
 * Root romlists: 4
 * Object-def size: 0xA0
 * Root placement widths: 9w x13
 * DLL ID: 0x0217
 * Class ID: 0x0037
 * Suggested outer boundary: tight DLL family
 * Reference class name: ObjCreator
 * Reference DLL name: VFP_ObjCreator
 * Remap aliases: 0x02C3
 *
 * Related packet paths:
 * - class: src/main/unknown/classes/class_0037_objcreator.c
 * - family: src/main/unknown/dll_0217_vfp_objcreator.c
 *
 * Width samples:
 * - 9w (0x24 bytes): dragrock.romlist.zlb, linkf.romlist.zlb, snowmines.romlist.zlb, temple.romlist.zlb
 *
 * Inline object-def evidence:
 * - inline fields: pModelList
 * - model IDs: 0x00000469
 * - help texts: 0xFFFF 0xFFFF 0xFFFF 0xFFFF
 *
 * Same-class objects (8 defs / 41 placements):
 * - 0x0450 DR_Creator: placements=14, dll=0x0265, widths=9w x14
 * - 0x033E VFP_ObjCrea: placements=13, dll=0x0217, widths=9w x13
 * - 0x0375 DFP_ObjCrea: placements=8, dll=0x022A, widths=9w x8
 * - 0x0414 GPSH_ObjCre: placements=6, dll=0x0193, widths=9w x6
 * - 0x00B1 CF_ObjCreat: placements=0, dll=0x0152, widths=none
 * - 0x03A0 WM_ObjCreat: placements=0, dll=0x01F9, widths=none
 * - 0x03F6 DFSH_ObjCre: placements=0, dll=0x0179, widths=none
 * - 0x040C ECSH_Creato: placements=0, dll=0x0191, widths=none
 *
 * Same-DLL objects (1 defs / 13 placements):
 * - 0x033E VFP_ObjCrea: placements=13, class=0x0037, widths=9w x13
 *
 * EN descriptor slot map:
 * - descriptor=0x80328EC8 gVFP_ObjCreatorObjDescriptor (slots=10, mask=1101111111)
 * - slot 00: 0x801FA224 vfpobjcreator_initialise stub=blr ref=initialise (stub)
 * - slot 01: 0x801FA220 vfpobjcreator_release stub=blr ref=release (stub)
 * - slot 03: 0x801FA1C8 vfpobjcreator_init ref=init
 * - slot 04: 0x801F9D9C vfpobjcreator_update ref=update
 * - slot 05: 0x801F9D98 vfpobjcreator_hitDetect stub=blr ref=hitDetect (stub)
 * - slot 06: 0x801F9D8C vfpobjcreator_render ref=render
 * - slot 07: 0x801F9D88 vfpobjcreator_free stub=blr ref=free (stub)
 * - slot 08: 0x801F9D80 vfpobjcreator_func08 stub=const 0
 * - slot 09: 0x801F9D78 vfpobjcreator_getExtraSize stub=const 10 ref=getExtraSize (stub)
 */

#if 0
/*
 * Retail-backed packet constants. Promote only after EN code inspection.
 */
enum obj_033E_VFP_ObjCrea_packet_info {
    VFP_OBJCREA_DEF_ID = 0x033E,
    VFP_OBJCREA_DLL_ID = 0x0217,
    VFP_OBJCREA_CLASS_ID = 0x0037,
    VFP_OBJCREA_OBJECT_DEF_BYTES = 0xA0,
    VFP_OBJCREA_PLACEMENT_BYTES_MIN = 0x24,
    VFP_OBJCREA_PLACEMENT_BYTES_MAX = 0x24,
};
#endif
