/*
 * Auto-generated by tools/orig/object_def_packets.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists as a retail-backed per-object packet for exploratory split work.
 *
 * Object def: 0x040B ECSH_Pressu
 * Output path: src/main/unknown/objects/obj_040B_ecsh_pressu.c
 * Retail placements: 6
 * Root romlists: 3
 * Object-def size: 0xA0
 * Root placement widths: 8w x6
 * DLL ID: 0x01FE
 * Class ID: 0x0033
 * Suggested outer boundary: tight DLL family
 * Reference class name: PressureSwitch
 * Reference DLL name: PressureSwitch
 * Remap aliases: 0x066F
 *
 * Related packet paths:
 * - class: src/main/unknown/classes/class_0033_pressureswitch.c
 * - family: src/main/unknown/dll_01FE_pressureswitch.c
 *
 * Width samples:
 * - 8w (0x20 bytes): ecshrine.romlist.zlb, gpshrine.romlist.zlb, mmshrine.romlist.zlb
 *
 * Inline object-def evidence:
 * - inline fields: pModelList
 * - model IDs: 0x00000240
 * - help texts: 0xFFFF 0xFFFF 0xFFFF 0xFFFF
 *
 * Same-class objects (5 defs / 11 placements):
 * - 0x040B ECSH_Pressu: placements=6, dll=0x01FE, widths=8w x6
 * - 0x00A2 CFPressureS: placements=2, dll=0x01FE, widths=8w x2
 * - 0x03A4 WM_Pressure: placements=2, dll=0x01FE, widths=8w x2
 * - 0x0365 DFP_PuzzleP: placements=1, dll=0x01FE, widths=8w x1
 * - 0x00E7 CFPuzzleSwi: placements=0, dll=0xFFFF, widths=none
 *
 * Same-DLL objects (4 defs / 11 placements):
 * - 0x040B ECSH_Pressu: placements=6, class=0x0033, widths=8w x6
 * - 0x00A2 CFPressureS: placements=2, class=0x0033, widths=8w x2
 * - 0x03A4 WM_Pressure: placements=2, class=0x0033, widths=8w x2
 * - 0x0365 DFP_PuzzleP: placements=1, class=0x0033, widths=8w x1
 *
 * EN descriptor slot map:
 * - descriptor=0x803287F0 gPressureSwitchObjDescriptor (slots=10, mask=1101111111)
 * - slot 00: 0x801F1BC4 pressureswitch_initialise stub=blr ref=initialise (stub)
 * - slot 01: 0x801F1BC0 pressureswitch_release stub=blr ref=release (stub)
 * - slot 03: 0x801F1ABC pressureswitch_init ref=init
 * - slot 04: 0x801F166C pressureswitch_update ref=update
 * - slot 05: 0x801F1668 pressureswitch_hitDetect stub=blr ref=hitDetect (stub)
 * - slot 06: 0x801F1638 pressureswitch_render ref=render
 * - slot 07: 0x801F1634 pressureswitch_free stub=blr ref=free (stub)
 * - slot 08: 0x801F162C pressureswitch_func08 stub=const 0
 * - slot 09: 0x801F1624 pressureswitch_getExtraSize stub=const 8 ref=getExtraSize (stub)
 */

#if 0
/*
 * Retail-backed packet constants. Promote only after EN code inspection.
 */
enum obj_040B_ECSH_Pressu_packet_info {
    ECSH_PRESSU_DEF_ID = 0x040B,
    ECSH_PRESSU_DLL_ID = 0x01FE,
    ECSH_PRESSU_CLASS_ID = 0x0033,
    ECSH_PRESSU_OBJECT_DEF_BYTES = 0xA0,
    ECSH_PRESSU_PLACEMENT_BYTES_MIN = 0x20,
    ECSH_PRESSU_PLACEMENT_BYTES_MAX = 0x20,
};
#endif
