/*
 * Auto-generated by tools/orig/object_def_packets.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists as a retail-backed per-object packet for exploratory split work.
 *
 * Object def: 0x04BC HitAnimator
 * Output path: src/main/unknown/objects/obj_04BC_hitanimator.c
 * Retail placements: 303
 * Root romlists: 29
 * Object-def size: 0xA0
 * Root placement widths: 8w x303
 * DLL ID: 0x0139
 * Class ID: 0x004B
 * Suggested outer boundary: singleton object boundary
 * Reference class name: HitAnimator
 * Reference DLL name: HitAnimator
 * Remap aliases: 0x024F
 *
 * Related packet paths:
 * - class: src/main/unknown/classes/class_004B_hitanimator.c
 * - family: src/main/unknown/dll_0139_hitanimator.c
 *
 * Width samples:
 * - 8w (0x20 bytes): capeclaw.romlist.zlb, clouddungeon.romlist.zlb, dbshrine.romlist.zlb, dfptop.romlist.zlb
 *
 * Inline object-def evidence:
 * - inline fields: pModelList
 * - model IDs: 0x00000478
 * - help texts: 0xFFFF 0xFFFF 0xFFFF 0xFFFF
 *
 * Same-class objects (1 defs / 303 placements):
 * - 0x04BC HitAnimator: placements=303, dll=0x0139, widths=8w x303
 *
 * Same-DLL objects (1 defs / 303 placements):
 * - 0x04BC HitAnimator: placements=303, class=0x004B, widths=8w x303
 *
 * EN descriptor slot map:
 * - descriptor=0x80322240 gHitAnimatorObjDescriptor (slots=10, mask=0001100001)
 * - slot 03: 0x8019410C hitanimator_init ref=init
 * - slot 04: 0x80193F30 hitanimator_update ref=update
 * - slot 09: 0x80193F28 hitanimator_getExtraSize stub=const 4 ref=getExtraSize (stub)
 */

#if 0
/*
 * Retail-backed packet constants. Promote only after EN code inspection.
 */
enum obj_04BC_HitAnimator_packet_info {
    HITANIMATOR_DEF_ID = 0x04BC,
    HITANIMATOR_DLL_ID = 0x0139,
    HITANIMATOR_CLASS_ID = 0x004B,
    HITANIMATOR_OBJECT_DEF_BYTES = 0xA0,
    HITANIMATOR_PLACEMENT_BYTES_MIN = 0x20,
    HITANIMATOR_PLACEMENT_BYTES_MAX = 0x20,
};
#endif
