#ifndef MAIN_DLL_DIM_DLL_01D1_DIMTRUTHHORNICE_H_
#define MAIN_DLL_DIM_DLL_01D1_DIMTRUTHHORNICE_H_

#include "types.h"

int fn_801B6D40(int* obj, int damage);

#endif /* MAIN_DLL_DIM_DLL_01D1_DIMTRUTHHORNICE_H_ */
