#ifndef MAIN_SFA_SHARED_DECLS_H_
#define MAIN_SFA_SHARED_DECLS_H_

#include "types.h"
#include "main/game_object.h"

BOOL AttractMovie_DrawTextureCallback(int unused, u32* modelPtr, u32 renderOpIdx);
asm BOOL OSRestoreInterrupts(register BOOL level);
bool ObjTrigger_UpdateIdBlockFlag(int obj);
double SeekTwiceBeforeRead();
double __fabs(double);
double __frsqrte(double x);
f32 Camera_DistanceToCurrentViewPosition(f32 x, f32 y, f32 z);
f32 Camera_GetFarPlane(void);
f32 Camera_GetFovY(void);
f32 Camera_GetNearPlane(void);
f32 __kernel_cos(f32, f32);
f32 __kernel_sin(f32);
f32 interpolate(f32 a, f32 t, f32 exp);
f32 powf(f32 x, f32 y);
f32* Camera_GetInverseViewRotationMatrix(void);
float __fabsf(float);
float fastCastS16ToFloat(s16* p);
float fastFloorf(float x);
float mathCosf(float x);
float mathSinf(float x);
float powfBitEstimate(float x, float y);
int AudioStream_Play(int id, void (*preparedCallback)(void));
int Camera_IsViewYOffsetEnabled(void);
int DVDRead(void* fileInfo, void* buf, int size, int offset);
int GXFlush_(u8 visible, int unused);
int OSDisableInterrupts(void);
int ObjHits_PollPriorityHitWithCooldown();
int Obj_IsObjectAlive(int obj);
int RomCurve_projectPointToAdjacentWindow();
int cMenuGetSelectedItem(void);
int curves_distFn15();
int dbstealerworm_stateHandlerA02();
int dbstealerworm_stateHandlerA04();
int dbstealerworm_stateHandlerA0A();
int dbstealerworm_stateHandlerA0D();
int dbstealerworm_stateHandlerA0E();
int dbstealerworm_stateHandlerB05();
int dbstealerworm_stateHandlerB06();
int dll_19_func1B(int p);
int gameBitDecrement(int bit);
int gameBitIncrement(int bit);
int gameTextGetCharset(void);
int getCurGameText(void);
int getCurMapLayer(void);
int getCurUiDll(void);
int getHudHiddenFrameCount(void);
int getLastRenderedFrame(void);
int getPatchGroup(f32* pos, int patchGroup);
int getSaveGameLoadStatus(void);
int getTableFileEntry(int fileId, int index, int* out);
int getUiDllFn_80014930(void);
int isGameTimerDisabled(void);
int kaldachompspit_getExtraSize(void);
int kaldachompspit_getObjectTypeId(void);
int loadAndDecompressDataFile(int id, void* buf, int blockOff, int len, int a, int b, int c);
int loadMapAndParent(int mapId);
int lockLevel(s32 val, int idx);
int mapGetDirIdx(int idx);
int mapUnload(int mapId, int flags);
int mmSetFreeDelay(int v);
int objFn_802962b4(int obj);
int objGetFlagsE5_2(int obj);
int objPosToMapBlockIdx(f32 x, f32 y, f32 z);
int playerHasKrazoaSpirit();
int rand(void);
int randFn_80080100(int n);
int synthFXStart(u32 fxId, u8 volume, u8 pan, u8 studio, u32 studioAux);
int testAndSet_onlyUseHeap3(int v);
int trickyFoodFn_8014460c(int obj, int state);
int unlockLevel(s32 val, int idx, int flag);
s16 renderModeSetOrGet(int mode);
u32 OSGetTick(void);
u32 ObjPath_GetPointModelMtx();
u32 RomCurve_getAdjacentWindow();
u32 buttonGetDisabled(int port);
u32 countLeadingZeros();
u32 getButtonsHeld(int port);
u32 getScreenResolution(void);
u32 hwGetVirtualSampleID(int slot);
u32 mapLoadDataFile(int mapId, int fileId);
u32 objAudioFn_8006ef38();
u8 AudioStream_IsPreparing(void);
u8 ObjHitReact_Update();
u8 isHeavyFogEnabled(void);
u8 isOvercast(void);
void AudioStream_CancelPrepared(void);
void AudioStream_StartPrepared(void);
void AudioStream_StopCurrent(void);
void CameraShake_SetAllMagnitudes(f32 magnitude);
void CameraShake_Start(f32 magnitude, f32 duration, f32 falloff);
void Camera_ApplyFullViewport(void);
void Camera_DisableViewYOffset(void);
void Camera_EnableViewYOffset(void);
void Camera_ProjectWorldPointWithOffset(f32 x, f32 y, f32 z, f32 offset, f32* outX, f32* outY, f32* outZ);
void Camera_ProjectWorldSphere( f32 x, f32 y, f32 z, f32 radius, f32* outX, f32* outY, f32* outZ, f32* outRadiusX, f32* outRadiusY, f32* outRadiusZ);
void Camera_RebuildProjectionMatrix(void);
void Camera_SetAspectRatio(f32 aspectRatio);
void Camera_SetCurrentViewIndex(int index);
void Camera_SetCurrentViewPosition(f32 x, f32 y, f32 z);
void Camera_SetCurrentViewRotation(int pitch, int yaw, int roll);
void Camera_SetFovY(f32 fovY);
void Camera_UpdateProjection(int a, int b);
void Camera_UpdateViewMatrices(void);
void DIM2icicle_updateHitResponse(int obj, int playerObj);
void GXClearVtxDesc(void);
void GXInvalidateTexAll(void);
void GXResetWriteGatherPipe(void);
void GXSetCurrentMtx(u32 id);
void GXSetNumChans(u8 nChans);
void GXSetNumIndStages(u8 nIndStages);
void GXSetNumTevStages(u8 nStages);
void GXSetNumTexGens(u8 nTexGens);
void GXSetViewport(f32 left, f32 top, f32 wd, f32 ht, f32 nearz, f32 farz);
void GXSetZMode();
void MWTRACE(int boxId);
void OSReport(const char* msg, ...);
void Obj_GetWorldPosition(int obj, f32* x, f32* y, f32* z);
void VIFlush(void);
void VISetNextFrameBuffer(void* fb);
void __init_user(void);
void _gxSetFogParams(void);
void angleToVec2(int angle, f32* cosOut, f32* sinOut);
void audioStopByMask(int mask);
void buttonDisable(int port, u32 mask);
void checkReset(void);
void collectible_applyPickup(int obj);
void cutsceneFadeInOut(int a);
void dbegg_setupFromDef(int obj, int* state);
void debugPrintf(char* fmt, ...);
void defragMemory(int mode);
void dll_F7_init(int* obj, int* params);
void dll_F7_update(int* obj);
void doRumble(f32 duration);
void dvdCheckError(void);
void envFxActFn_800887f8(u8 value);
void gameTextAppendStr(char* str, int arg2);
void gameTextFn_80016810(int a, int b, int c);
void gameTextLoadDir(int dirId);
void gameTextLoadTaskText(int taskId);
void gameTextRun(void);
void gameTextSetCharset(int charset, int flags);
void gameTextShow(int a);
void gameTimerInit(s8 flags, int minutes);
void gameTimerStop(void);
void gcbaddieshield_update(int* obj);
void geomDrawFn_800796f0(void);
void getReflectionTexture2(int* out);
void gxBlendFn_800789ac(void);
void gxBlendFn_80078b4c(void);
void gxTexColorFn_80079254(void);
void gxTextureFn_800794e0(void);
void hudFn_8011f38c(u8 x);
void hwStart(u32 voice, u8 studio);
void initRotationMtx(f32* mtx, f32 xScale, f32 yScale, f32 zScale);
void inpResetMidiCtrl(u8 a, u8 b, u32 mode);
void inpSetMidiCtrl(u8 ctrl, u8 channel, u8 set, u8 value);
void inpSetMidiCtrl14(u8 ctrl, u8 channel, u8 set, u16 value);
void loadModelAndAnimTabs(void);
void loadUiDll(int index);
void mapInitFn_8006fccc(void);
void mmFreeTick(int arg);
void modelTextureFn_80089970(int slot);
void mtx44_mult(f32* a, f32* b, f32* out);
void mtxRotateByVec3s(f32* mtx, void* transform);
void normalize(f32 * x, f32 * y, f32 * z);
void objAudioFn_80039270(int obj, void* p, int id);
void objGetColor(int slot, u8* red, u8* green, u8* blue);
void objShadowFn_80062498(int* obj, int p2, int p3, u8 frames);
void objfx_spawnHitEmitterAtPos(f32* pos, u8 a, u8 b, u8 c, u8 d);
void padClearAnalogInputX(int port);
void padClearAnalogInputY(int port);
void padFn_80014b18(int value);
void padUpdate(void);
void playerTailFn_80026b3c(int* p1, int p2, int p3, void* p4);
void postRenderSetAlphaBlendState(void);
void saveGame_save();
void setAButtonIcon(int x);
void setBButtonIcon(int icon);
void setDrawCloudsAndLights(int v);
void setDrawLights(int v);
void setIsOvercast(int v);
void setJoypadDisabled(void);
void setLoadedFileFlags_blocks1(void);
void setMatrixFromObjectTransposed(void* obj, f32* out);
void setSubtitlesEnabled(u8 enabled);
void setTimeStop(int v);
void setWidescreen(u8 enabled);
void shield_update(int* obj);
void skyFn_80088c94(int flags, int mode);
void skyFn_800894a8(int flags, f32 x, f32 y, f32 z);
void skyFn_80089710(int flags, u8 enabled, int startComplete);
void skySetOverrideLightColor(u8 red, u8 green, u8 blue);
void skySetOverrideLightColorEnabled(u8 enabled);
void skySetOverrideLightDirection(f32 x, f32 y, f32 z, f32 intensity);
void skySetOverrideLightDirectionEnabled(u8 enabled);
void sndConvertMs(u32 * p);
void srand(int seed);
void stopRumble2(void);
void streamFn_8000a380(int a, int b, int c);
void textBlendSetupFn_80078a7c(void);
void textRenderChar(int x0, int y0, int x1, int y1, f32 u0, f32 v0, f32 u1, f32 v1);
void textRenderSetupFn_800795e8(void);
void textRenderSetupFn_80079804(void);
void textureSetupFn_800799c0(void);
void timeOfDayFn_80055000(void);
void timerSetToCountUp(void);
void titleScreenPositionElements(f32 a, f32 b);
void titleScreenShowCopyright(u8 arg);
void titleScreenTextDrawFunc(void);
void tumbleweed_updateRollingMotion(int obj, int aux);
void updateConstrainedChaseVelocity(int obj, f32 x, f32 y, f32 z, f32 scale);
void vecRotateYXZ(int, int);
void waitNextFrame(void);
void warpToMap(int idx, s8 transType);
void* gameTextGetBox(int box);
void* getTablesBinEntry(int i);
void* saveGameGetEnvState(void);
void* textureAlloc(u16 w, u16 h, int fmt, u8 mip, u8 maxLod, u8 b8, u8 b9, u8 b10, u8 b11);

#endif
