#ifndef MAIN_SFA_EXTERN_DECLS_H_
#define MAIN_SFA_EXTERN_DECLS_H_

#include "types.h"

void* RomList_GetLoadedPages(void);
int AppleOnTree_getExtraSize(void);
void AppleOnTree_setScale(void);
void cMenuRotateFn_80124d80(void);
void clearCurSeqNo(void);
void whirlpool_updateWhileFrozen(void);
void cutSceneFn_8011dd30(void);
void cutsceneExit(void);
void doNothing_afterRenderObject(void);
void doNothing_beforeRenderObject(void);
void drawViewFinderHud(void);
void fn_8001FE90(void);
void fn_8004D6D8(void);
void fn_80050F2C(void);
u8 fn_8012DDA4(void);
u16 fn_80130124(void);
void fn_80133934(void);
void debugPrintReset(void);
void debugPrintInit(void);
void errDisplayInstallHandlers(void);
void errDisplayThreadMain(void);
s32 getCurMapType(void);
void init(void);
u32 isRomListLoading(void);
int isWidescreen(void);
void linkDrawFn_801302c0(void);
void linkDrawFn_80130484(void);
u32 loadTableFiles(void);
void mapSetupPlayer(void);
u32 rand(void);
void reportAllocFail(void);
void resetYbutton(void);
int return0_8002A5B8();
void salHandleAuxProcessing(void);
void setLinkIsRotated(void);
void setLinkNotRotated(void);
int spellstone_idleCallback(void);
int SPScarab_getExtraSize(void);
int SPScarab_getObjectTypeId(void);
void SPScarab_hitDetect(void);
void SPScarab_render(void);
void streamCb_80080384(void);
void timeListFn_8012df14(void);
int TitleScreen_getExtraSize(void);
void TitleScreen_hitDetect(void);
void updateReflectionTextures(void);
void viewFn_80129c74(void);

#endif
