/*
 * Auto-generated by tools/orig/object_family_packets.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists as a makeshift source-file boundary for object/DLL recovery work.
 *
 * DLL ID: 0x01E8
 * Suggested family name: SB_Galleon
 * Output path: src/main/unknown/dll_01E8_sb_galleon.c
 * Retail placements: 1
 * Retail object defs: 1
 * Retail object record sizes: 0xE0
 * Retail root placement widths: 9w
 * EN descriptor: 0x80327BE0 gSB_GalleonObjDescriptor
 * EN descriptor shape: slots=15 mask=110111111111111
 *
 * Retail object defs:
 * - 0x02F5 SB_Galleon: class=0x0030, placements=1, romlists=1, objsize=0xE0, widths=9w x1, aliases=0x008E
 *
 * EN slot map with reference-only names by slot index:
 * - slot 00: 0x801E256C SB_Galleon_initialise stub=blr ref=initialise (stub)
 * - slot 01: 0x801E2568 SB_Galleon_release stub=blr ref=release (stub)
 * - slot 03: 0x801E23E4 SB_Galleon_init ref=init
 * - slot 04: 0x801E21AC SB_Galleon_update ref=update
 * - slot 05: 0x801E20F4 SB_Galleon_hitDetect ref=hitDetect
 * - slot 06: 0x801E1FDC SB_Galleon_render ref=render
 * - slot 07: 0x801E1F18 SB_Galleon_free ref=free
 * - slot 08: 0x801E1F10 SB_Galleon_func08 stub=const 0
 * - slot 09: 0x801E1F08 SB_Galleon_getExtraSize stub=const 180 ref=getExtraSize (stub)
 * - slot 10: 0x801E1E74 SB_Galleon_setScale ref=setScale
 * - slot 11: 0x801E1E64 SB_Galleon_func0B
 * - slot 12: 0x801E1E00 SB_Galleon_modelMtxFn ref=modelMtxFn
 * - slot 13: 0x801E1DF4 SB_Galleon_render2 ref=render2
 * - slot 14: 0x801E1DB0 SB_Galleon_func0E
 *
 * Reference-only hints:
 * - reference DLL name: SB_Galleon
 */

#if 0
/*
 * Reference-only slot names. Verify against EN before promoting any of these into live code.
 */
enum dll_01E8_SB_Galleon_slot {
    SB_GALLEON_INITIALISE = 0,
    SB_GALLEON_RELEASE = 1,
    SB_GALLEON_INIT = 3,
    SB_GALLEON_UPDATE = 4,
    SB_GALLEON_HITDETECT = 5,
    SB_GALLEON_RENDER = 6,
    SB_GALLEON_FREE = 7,
    SB_GALLEON_SLOT_08 = 8,
    SB_GALLEON_GETEXTRASIZE = 9,
    SB_GALLEON_SETSCALE = 10,
    SB_GALLEON_SLOT_11 = 11,
    SB_GALLEON_MODELMTXFN = 12,
    SB_GALLEON_RENDER2 = 13,
    SB_GALLEON_SLOT_14 = 14,
};
#endif
