/*
 * Auto-generated by tools/orig/object_family_packets.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists as a makeshift source-file boundary for object/DLL recovery work.
 *
 * DLL ID: 0x0239
 * Suggested family name: TextBlock
 * Output path: src/main/unknown/dll_0239_textblock.c
 * Retail placements: 0
 * Retail object defs: 5
 * Retail object record sizes: 0x100
 * Retail root placement widths: -
 * EN descriptor: 0x80329CB8 gTextBlockObjDescriptor
 * EN descriptor shape: slots=10 mask=1101111111
 *
 * Retail object defs:
 * - 0x02C8 KP_textbloc: class=0x0030, placements=0, romlists=0, objsize=0x100, widths=none, aliases=0x0593
 * - 0x02C9 KP_textbloc: class=0x0030, placements=0, romlists=0, objsize=0x100, widths=none, aliases=0x0594
 * - 0x02CA KP_textbloc: class=0x0030, placements=0, romlists=0, objsize=0x100, widths=none, aliases=0x0595
 * - 0x02CB KP_textbloc: class=0x0030, placements=0, romlists=0, objsize=0x100, widths=none, aliases=0x0596
 * - 0x0371 DFP_Textblo: class=0x0030, placements=0, romlists=0, objsize=0x100, widths=none, aliases=0x04E6
 *
 * EN slot map with reference-only names by slot index:
 * - slot 00: 0x802098B0 textblockObj_initialise stub=blr ref=initialise (stub)
 * - slot 01: 0x802098AC textblockObj_release stub=blr ref=release (stub)
 * - slot 03: 0x80209880 textblockObj_initUnsupported ref=init
 * - slot 04: 0x80209854 textblockObj_updateUnsupported ref=update
 * - slot 05: 0x80209850 textblockObj_hitDetect stub=blr ref=hitDetect (stub)
 * - slot 06: 0x8020984C textblockObj_render stub=blr ref=render (stub)
 * - slot 07: 0x80209820 textblockObj_freeUnsupported ref=free
 * - slot 08: 0x80209818 textblockObj_func08 stub=const 0
 * - slot 09: 0x80209810 textblockObj_getExtraSize stub=const 0 ref=getExtraSize (stub)
 *
 * Reference-only hints:
 * - reference DLL name: TextBlock
 */

#if 0
/*
 * Reference-only slot names. Verify against EN before promoting any of these into live code.
 */
enum dll_0239_TextBlock_slot {
    TEXTBLOCK_INITIALISE = 0,
    TEXTBLOCK_RELEASE = 1,
    TEXTBLOCK_INIT = 3,
    TEXTBLOCK_UPDATE = 4,
    TEXTBLOCK_HITDETECT = 5,
    TEXTBLOCK_RENDER = 6,
    TEXTBLOCK_FREE = 7,
    TEXTBLOCK_SLOT_08 = 8,
    TEXTBLOCK_GETEXTRASIZE = 9,
};
#endif
