/*
 * Auto-generated by tools/orig/object_family_packets.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists as a makeshift source-file boundary for object/DLL recovery work.
 *
 * DLL ID: 0x0243
 * Suggested family name: DBHoleControl1
 * Output path: src/main/unknown/dll_0243_dbholecontrol1.c
 * Retail placements: 4
 * Retail object defs: 1
 * Retail object record sizes: 0xC0
 * Retail root placement widths: 9w
 * EN descriptor: 0x80329810 gDBHoleControl1ObjDescriptor
 * EN descriptor shape: slots=10 mask=1101111111
 *
 * Retail object defs:
 * - 0x0424 DBHoleContr: class=0x0030, placements=4, romlists=1, objsize=0xC0, widths=9w x4, aliases=0x05BC
 *
 * EN slot map with reference-only names by slot index:
 * - slot 00: 0x80204094 dbholecontrol1_initialise stub=blr ref=initialise (stub)
 * - slot 01: 0x80204090 dbholecontrol1_release stub=blr ref=release (stub)
 * - slot 03: 0x80204018 dbholecontrol1_init ref=init
 * - slot 04: 0x80203F84 dbholecontrol1_update ref=update
 * - slot 05: 0x80203F80 dbholecontrol1_hitDetect stub=blr ref=hitDetect (stub)
 * - slot 06: 0x80203F50 dbholecontrol1_render ref=render
 * - slot 07: 0x80203F2C dbholecontrol1_free ref=free
 * - slot 08: 0x80203F24 dbholecontrol1_func08 stub=const 0
 * - slot 09: 0x80203F1C dbholecontrol1_getExtraSize stub=const 12 ref=getExtraSize (stub)
 *
 * Reference-only hints:
 * - reference DLL name: DBHoleControl1
 * - reference description: holes for egg thieves
 */

#if 0
/*
 * Reference-only slot names. Verify against EN before promoting any of these into live code.
 */
enum dll_0243_DBHoleControl1_slot {
    DBHOLECONTROL1_INITIALISE = 0,
    DBHOLECONTROL1_RELEASE = 1,
    DBHOLECONTROL1_INIT = 3,
    DBHOLECONTROL1_UPDATE = 4,
    DBHOLECONTROL1_HITDETECT = 5,
    DBHOLECONTROL1_RENDER = 6,
    DBHOLECONTROL1_FREE = 7,
    DBHOLECONTROL1_SLOT_08 = 8,
    DBHOLECONTROL1_GETEXTRASIZE = 9,
};
#endif
