/*
 * Auto-generated by tools/orig/object_family_packets.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists as a makeshift source-file boundary for object/DLL recovery work.
 *
 * DLL ID: 0x00E9
 * Suggested family name: setuppoint
 * Output path: src/main/unknown/dll_00E9_setuppoint.c
 * Retail placements: 278
 * Retail object defs: 1
 * Retail object record sizes: 0xA0
 * Retail root placement widths: 8w
 * EN descriptor: 0x80320C20 lbl_80320C20
 * EN descriptor shape: slots=10 mask=0001000000
 *
 * Retail object defs:
 * - 0x0493 setuppoint: class=0x0004, placements=278, romlists=123, objsize=0xA0, widths=8w x278, aliases=0x000D
 *
 * EN slot map with reference-only names by slot index:
 * - slot 03: 0x80171D10 DummyE9_init stub=blr ref=init (stub)
 *
 * Reference-only hints:
 * - reference DLL name: setuppoint
 * - reference description: All functions stubbed
 * - reference objparams size: 0x8
 * - field 0x18: actNo (u8) - Which act to set the map to when loading at this point
 * - field 0x19: idx (u8) - Which setuppoint this is
 * - field 0x1A: unnamed (unk8)
 * - field 0x1B: rotX (s8) - Unsure; no code left in game that reads these
 * - field 0x1C: objGroups (u32) - Value to set objgroups to when loading at this point
 */

#if 0
/*
 * Reference-only slot names. Verify against EN before promoting any of these into live code.
 */
enum dll_00E9_setuppoint_slot {
    SETUPPOINT_INIT = 3,
};
#endif
