/*
 * Auto-generated by tools/orig/object_family_packets.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists as a makeshift source-file boundary for object/DLL recovery work.
 *
 * DLL ID: 0x021C
 * Suggested family name: VFP_Ladders
 * Output path: src/main/unknown/dll_021C_vfp_ladders.c
 * Retail placements: 0
 * Retail object defs: 2
 * Retail object record sizes: 0xA0, 0xC0
 * Retail root placement widths: -
 * EN descriptor: 0x80328FE0 gVFP_LaddersObjDescriptor
 * EN descriptor shape: slots=10 mask=1101111111
 *
 * Retail object defs:
 * - 0x031D VFP_Ladders: class=0x0030, placements=0, romlists=0, objsize=0xC0, widths=none, aliases=0x0548
 * - 0x0335 VFP_Ladders: class=0x0030, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x03B0
 *
 * EN slot map with reference-only names by slot index:
 * - slot 00: 0x801FB21C vfpladders_initialise stub=blr ref=initialise (stub)
 * - slot 01: 0x801FB218 vfpladders_release stub=blr ref=release (stub)
 * - slot 03: 0x801FB1D0 vfpladders_init ref=init
 * - slot 04: 0x801FB03C vfpladders_update ref=update
 * - slot 05: 0x801FB038 vfpladders_hitDetect stub=blr ref=hitDetect (stub)
 * - slot 06: 0x801FB034 vfpladders_render stub=blr ref=render (stub)
 * - slot 07: 0x801FB004 vfpladders_free ref=free
 * - slot 08: 0x801FAFFC vfpladders_func08 stub=const 0
 * - slot 09: 0x801FAFF4 vfpladders_getExtraSize stub=const 8 ref=getExtraSize (stub)
 *
 * Reference-only hints:
 * - reference DLL name: VFP_Ladders
 */

#if 0
/*
 * Reference-only slot names. Verify against EN before promoting any of these into live code.
 */
enum dll_021C_VFP_Ladders_slot {
    VFP_LADDERS_INITIALISE = 0,
    VFP_LADDERS_RELEASE = 1,
    VFP_LADDERS_INIT = 3,
    VFP_LADDERS_UPDATE = 4,
    VFP_LADDERS_HITDETECT = 5,
    VFP_LADDERS_RENDER = 6,
    VFP_LADDERS_FREE = 7,
    VFP_LADDERS_SLOT_08 = 8,
    VFP_LADDERS_GETEXTRASIZE = 9,
};
#endif
