/*
 * Auto-generated by tools/orig/constructor_packets.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists as a retail-backed constructor/class packet for exploratory split work.
 *
 * Constructor: fn_80136CE4
 * Packet path: src/main/unknown/constructors/ctor_80136CE4_vtable.c
 * Score: 1200
 * Kind: vtable-like
 * Retail table: 0x8031ABF4 (loaded as 0x8031ABF8)
 * Primary store: fn_80136CE4 stores to r30+0x0
 *
 * Constructor-like functions:
 * - 0x80136CE4 fn_80136CE4
 *
 * Method slots:
 * - slot 00: 0x8011175C fn_8011175C
 * - slot 01: 0x80111160 fn_80111160
 * - slot 02: 0x8011115C fn_8011115C
 * - slot 03: 0x801110CC fn_801110CC
 */

#if 0
/*
 * Packet constants only. Promote names and boundaries after EN inspection.
 */
enum constructor_packet_info {
    PACKET_TABLE_ADDR = 0x8031ABF4,
    PACKET_TABLE_LOADED_ADDR = 0x8031ABF8,
    PACKET_CONSTRUCTOR_ADDR = 0x80136CE4,
    PACKET_SLOT_COUNT = 4,
    PACKET_STORE_DISP = 0x00000000,
};
#endif
