/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/unknown/autos/placeholder_8027A940.c
 * Text span: 0x8027A940-0x8027AC80
 * Imported Ghidra functions: 5
 * Verbatim-safe functions: 5
 * Auto-stubbed functions: 0
 */

#include "ghidra_import.h"
#include "main/unknown/autos/placeholder_8027A940.h"

/* Raw global references kept as loose externs for later cleanup. */
extern undefined1 DAT_803cb730;
extern undefined4 DAT_803cb7b0;
extern undefined4 DAT_803cb7b1;
extern undefined4 DAT_803cb7b2;
extern undefined4 DAT_803cb7b3;
extern undefined4 DAT_803cb7b4;
extern undefined4 DAT_803cb7b5;
extern undefined4 DAT_803cb7b6;
extern undefined4 DAT_803cb7b7;
extern undefined4 DAT_803cb7b8;
extern undefined4 DAT_803cb7b9;
extern undefined4 DAT_803cb7ba;
extern undefined4 DAT_803cb7bb;
extern undefined4 DAT_803cb7bc;
extern undefined4 DAT_803cb7bd;
extern undefined4 DAT_803cb7be;
extern undefined4 DAT_803cb7bf;
extern undefined4 DAT_803cb7c0;
extern undefined4 DAT_803cb7c1;
extern undefined4 DAT_803cb7c2;
extern undefined4 DAT_803cb7c3;
extern undefined4 DAT_803cb7c4;
extern undefined4 DAT_803cb7c5;
extern undefined4 DAT_803cb7c6;
extern undefined4 DAT_803cb7c7;
extern undefined4 DAT_803cb7c8;
extern undefined4 DAT_803cb7c9;
extern undefined4 DAT_803cb7ca;
extern undefined4 DAT_803cb7cb;
extern undefined4 DAT_803cb7cc;
extern undefined4 DAT_803cb7cd;
extern undefined4 DAT_803cb7ce;
extern undefined4 DAT_803cb7cf;
extern undefined4 DAT_803cb7d0;
extern undefined4 DAT_803cb7d1;
extern undefined4 DAT_803cb7d2;
extern undefined4 DAT_803cb7d3;
extern undefined4 DAT_803cb7d4;
extern undefined4 DAT_803cb7d5;
extern undefined4 DAT_803cb7d6;
extern undefined4 DAT_803cb7d7;
extern undefined4 DAT_803cb7d8;
extern undefined4 DAT_803cb7d9;
extern undefined4 DAT_803cb7da;
extern undefined4 DAT_803cb7db;
extern undefined4 DAT_803cb7dc;
extern undefined4 DAT_803cb7dd;
extern undefined4 DAT_803cb7de;
extern undefined4 DAT_803cb7df;
extern undefined4 DAT_803cb7e0;
extern undefined4 DAT_803cb7e1;
extern undefined4 DAT_803cb7e2;
extern undefined4 DAT_803cb7e3;
extern undefined4 DAT_803cb7e4;
extern undefined4 DAT_803cb7e5;
extern undefined4 DAT_803cb7e6;
extern undefined4 DAT_803cb7e7;
extern undefined4 DAT_803cb7e8;
extern undefined4 DAT_803cb7e9;
extern undefined4 DAT_803cb7ea;
extern undefined4 DAT_803cb7eb;
extern undefined4 DAT_803cb7ec;
extern undefined4 DAT_803cb7ed;
extern undefined4 DAT_803cb7ee;
extern undefined4 DAT_803cb7ef;
extern f64 DOUBLE_803e84b8;
extern f32 FLOAT_803e84b0;

/* Local declarations keep imported functions visible within the TU. */
undefined4 FUN_8027a940(int param_1);
void FUN_8027a9bc(int param_1);
void FUN_8027aa18(int param_1);
void FUN_8027aa94(void);
int FUN_8027ac44(uint param_1);

// Function: FUN_8027a940
// Entry: 8027a940
// Size: 124 bytes

undefined4 FUN_8027a940(int param_1)

{
  uint uVar1;
  
  if ((*(uint *)(param_1 + 0xf4) != 0xffffffff) && (*(byte *)(param_1 + 0x121) != 0xff)) {
    uVar1 = *(uint *)(param_1 + 0xf4) & 0xff;
    if (*(byte *)(param_1 + 0x122) == 0xff) {
      if ((byte)(&DAT_803cb7b0)[uVar1] == uVar1) {
        return 1;
      }
    }
    else if (uVar1 == (byte)(&DAT_803cb730)
                            [(uint)*(byte *)(param_1 + 0x121) +
                             (uint)*(byte *)(param_1 + 0x122) * 0x10]) {
      return 1;
    }
  }
  return 0;
}

// Function: FUN_8027a9bc
// Entry: 8027a9bc
// Size: 92 bytes

void FUN_8027a9bc(int param_1)

{
  uint uVar1;
  
  uVar1 = *(uint *)(param_1 + 0xf4);
  if (uVar1 == 0xffffffff) {
    return;
  }
  if (*(byte *)(param_1 + 0x121) == 0xff) {
    return;
  }
  if (*(byte *)(param_1 + 0x122) == 0xff) {
    (&DAT_803cb7b0)[uVar1 & 0xff] = (char)uVar1;
    return;
  }
  (&DAT_803cb730)[(uint)*(byte *)(param_1 + 0x121) + (uint)*(byte *)(param_1 + 0x122) * 0x10] =
       (char)uVar1;
  return;
}

// Function: FUN_8027aa18
// Entry: 8027aa18
// Size: 124 bytes

void FUN_8027aa18(int param_1)

{
  uint uVar1;
  
  if (*(uint *)(param_1 + 0xf4) == 0xffffffff) {
    return;
  }
  if (*(byte *)(param_1 + 0x121) == 0xff) {
    return;
  }
  uVar1 = *(uint *)(param_1 + 0xf4) & 0xff;
  if (*(byte *)(param_1 + 0x122) != 0xff) {
    if (uVar1 != (byte)(&DAT_803cb730)
                       [(uint)*(byte *)(param_1 + 0x121) + (uint)*(byte *)(param_1 + 0x122) * 0x10])
    {
      return;
    }
    (&DAT_803cb730)[(uint)*(byte *)(param_1 + 0x121) + (uint)*(byte *)(param_1 + 0x122) * 0x10] =
         0xff;
    return;
  }
  if ((byte)(&DAT_803cb7b0)[uVar1] != uVar1) {
    return;
  }
  (&DAT_803cb7b0)[uVar1] = 0xff;
  return;
}

// Function: FUN_8027aa94
// Entry: 8027aa94
// Size: 432 bytes

void FUN_8027aa94(void)

{
  undefined1 *puVar1;
  int iVar2;
  
  iVar2 = 4;
  puVar1 = &DAT_803cb730;
  do {
    *puVar1 = 0xff;
    puVar1[1] = 0xff;
    puVar1[2] = 0xff;
    puVar1[3] = 0xff;
    puVar1[4] = 0xff;
    puVar1[5] = 0xff;
    puVar1[6] = 0xff;
    puVar1[7] = 0xff;
    puVar1[8] = 0xff;
    puVar1[9] = 0xff;
    puVar1[10] = 0xff;
    puVar1[0xb] = 0xff;
    puVar1[0xc] = 0xff;
    puVar1[0xd] = 0xff;
    puVar1[0xe] = 0xff;
    puVar1[0xf] = 0xff;
    puVar1[0x10] = 0xff;
    puVar1[0x11] = 0xff;
    puVar1[0x12] = 0xff;
    puVar1[0x13] = 0xff;
    puVar1[0x14] = 0xff;
    puVar1[0x15] = 0xff;
    puVar1[0x16] = 0xff;
    puVar1[0x17] = 0xff;
    puVar1[0x18] = 0xff;
    puVar1[0x19] = 0xff;
    puVar1[0x1a] = 0xff;
    puVar1[0x1b] = 0xff;
    puVar1[0x1c] = 0xff;
    puVar1[0x1d] = 0xff;
    puVar1[0x1e] = 0xff;
    puVar1[0x1f] = 0xff;
    puVar1 = puVar1 + 0x20;
    iVar2 = iVar2 + -1;
  } while (iVar2 != 0);
  DAT_803cb7b0 = 0xff;
  DAT_803cb7b1 = 0xff;
  DAT_803cb7b2 = 0xff;
  DAT_803cb7b3 = 0xff;
  DAT_803cb7b4 = 0xff;
  DAT_803cb7b5 = 0xff;
  DAT_803cb7b6 = 0xff;
  DAT_803cb7b7 = 0xff;
  DAT_803cb7b8 = 0xff;
  DAT_803cb7b9 = 0xff;
  DAT_803cb7ba = 0xff;
  DAT_803cb7bb = 0xff;
  DAT_803cb7bc = 0xff;
  DAT_803cb7bd = 0xff;
  DAT_803cb7be = 0xff;
  DAT_803cb7bf = 0xff;
  DAT_803cb7c0 = 0xff;
  DAT_803cb7c1 = 0xff;
  DAT_803cb7c2 = 0xff;
  DAT_803cb7c3 = 0xff;
  DAT_803cb7c4 = 0xff;
  DAT_803cb7c5 = 0xff;
  DAT_803cb7c6 = 0xff;
  DAT_803cb7c7 = 0xff;
  DAT_803cb7c8 = 0xff;
  DAT_803cb7c9 = 0xff;
  DAT_803cb7ca = 0xff;
  DAT_803cb7cb = 0xff;
  DAT_803cb7cc = 0xff;
  DAT_803cb7cd = 0xff;
  DAT_803cb7ce = 0xff;
  DAT_803cb7cf = 0xff;
  DAT_803cb7d0 = 0xff;
  DAT_803cb7d1 = 0xff;
  DAT_803cb7d2 = 0xff;
  DAT_803cb7d3 = 0xff;
  DAT_803cb7d4 = 0xff;
  DAT_803cb7d5 = 0xff;
  DAT_803cb7d6 = 0xff;
  DAT_803cb7d7 = 0xff;
  DAT_803cb7d8 = 0xff;
  DAT_803cb7d9 = 0xff;
  DAT_803cb7da = 0xff;
  DAT_803cb7db = 0xff;
  DAT_803cb7dc = 0xff;
  DAT_803cb7dd = 0xff;
  DAT_803cb7de = 0xff;
  DAT_803cb7df = 0xff;
  DAT_803cb7e0 = 0xff;
  DAT_803cb7e1 = 0xff;
  DAT_803cb7e2 = 0xff;
  DAT_803cb7e3 = 0xff;
  DAT_803cb7e4 = 0xff;
  DAT_803cb7e5 = 0xff;
  DAT_803cb7e6 = 0xff;
  DAT_803cb7e7 = 0xff;
  DAT_803cb7e8 = 0xff;
  DAT_803cb7e9 = 0xff;
  DAT_803cb7ea = 0xff;
  DAT_803cb7eb = 0xff;
  DAT_803cb7ec = 0xff;
  DAT_803cb7ed = 0xff;
  DAT_803cb7ee = 0xff;
  DAT_803cb7ef = 0xff;
  return;
}

// Function: FUN_8027ac44
// Entry: 8027ac44
// Size: 60 bytes

int FUN_8027ac44(uint param_1)

{
  return (int)(FLOAT_803e84b0 *
              (float)((double)CONCAT44(0x43300000,param_1 & 0xffff) - DOUBLE_803e84b8));
}
