/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/unknown/autos/placeholder_80292C14.c
 * Text span: 0x80292C14-0x80292F04
 * Imported Ghidra functions: 2
 * Verbatim-safe functions: 2
 * Auto-stubbed functions: 0
 */

#include "ghidra_import.h"
#include "main/unknown/autos/placeholder_80292C14.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_802867a8();
extern undefined4 FUN_802867f4();

/* Local declarations keep imported functions visible within the TU. */
void FUN_80292c14(void);
void FUN_80292d24(void);

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80292C14
 * EN v1.0 Size: 272b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80292c14(void)

{
  FUN_802867a8();
  FUN_802867f4();
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80292D24
 * EN v1.0 Size: 480b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80292d24(void)

{
  FUN_802867a8();
  FUN_802867f4();
  return;
}
