/*
 * Auto-generated by tools/claim_auto_game_splits.py.
 *
 * This file claims a previously auto-generated game-code text window so it has a stable home
 * in `splits.txt` and can be subdivided into real sources later.
 *
 * Current EN split: 0x80283DA0-0x80283E10
 * Previous named split: main/dolphin/TRK_MINNOW_DOLPHIN/CircleBuffer
 * Next named split: main/dolphin/OdemuExi2/DebuggerDriver
 * Raw auto unit name: main/auto_03_80283DA0_text
 * Function count: 5
 *
 * Suggested follow-up:
 * - Subdivide this window into real source files once stronger corridor/object evidence exists.
 * - Use the listed function addresses to pull Ghidra bodies selectively when promoting a subrange.
 */

#include "main/unknown/autos/placeholder_80283DA0.h"

/*
 * Function inventory:
 * - fn_80283DA0 @ 0x80283DA0 size 0x20
 * - fn_80283DC0 @ 0x80283DC0 size 0x14
 * - fn_80283DD4 @ 0x80283DD4 size 0x14
 * - fn_80283DE8 @ 0x80283DE8 size 0x14
 * - fn_80283DFC @ 0x80283DFC size 0x14
 */
