/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/unknown/autos/placeholder_80294A4C.c
 * Text span: 0x80294A4C-0x80294F2C
 * Imported Ghidra functions: 9
 * Verbatim-safe functions: 8
 * Auto-stubbed functions: 1
 */

#include "ghidra_import.h"
#include "main/unknown/autos/placeholder_80294A4C.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern double ABS();
extern undefined4 FUN_802867ac();
extern undefined4 FUN_802867b4();
extern undefined4 FUN_802867f8();
extern undefined4 FUN_80286800();
extern double FUN_80292568();
extern undefined4 FUN_80293424();
extern undefined4 FUN_8029349c();
extern undefined4 sync();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4 DAT_80333348;
extern f64 DOUBLE_803e8ac8;

/* Local declarations keep imported functions visible within the TU. */
void FUN_80294a4c(void);
void FUN_80294b54(void);
void FUN_80294cac(void);
double FUN_80294d40(double param_1);
void FUN_80294da0(void);
void FUN_80294da8(void);
uint FUN_80294dbc(uint param_1);
double FUN_80294e7c(double param_1);
double FUN_80294e84(double param_1);

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80294A4C
 * EN v1.0 Size: 264b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80294a4c(void)

{
  FUN_802867b4();
  FUN_80293424();
  FUN_80286800();
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80294B54
 * EN v1.0 Size: 344b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80294b54(void)

{
  FUN_802867b4();
  FUN_8029349c();
  FUN_80286800();
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80294CAC
 * EN v1.0 Size: 148b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80294cac(void)

{
  FUN_802867ac();
  FUN_80293424();
  FUN_802867f8();
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80294D40
 * EN v1.0 Size: 96b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
double FUN_80294d40(double param_1)

{
  double dVar1;
  short local_1c [2];
  float local_18;
  
  local_1c[0] = ((ushort)((uint)(float)param_1 >> 0x17) & 0xff) - 0x80;
  local_18 = (float)((uint)(float)param_1 & 0x7fffff | 0x3f800000);
  dVar1 = FUN_80292568((float *)local_1c);
  return (double)(float)((double)local_18 + dVar1);
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80294DA0
 * EN v1.0 Size: 8b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80294da0(void)

{
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80294DA8
 * EN v1.0 Size: 20b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80294da8(void)

{
  sync(0);
  do {
                    /* WARNING: Do nothing block with infinite loop */
  } while( true );
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80294DBC
 * EN v1.0 Size: 192b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
uint FUN_80294dbc(uint param_1)
{
    return 0;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80294E7C
 * EN v1.0 Size: 8b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
double FUN_80294e7c(double param_1)

{
  return ABS(param_1);
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80294E84
 * EN v1.0 Size: 168b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
double FUN_80294e84(double param_1)

{
  uint uVar1;
  float fVar2;
  double dVar3;
  
  fVar2 = (float)param_1;
  dVar3 = (double)fVar2;
  uVar1 = (uint)param_1;
  if (((float)((double)(float)((double)CONCAT44(0x43300000,uVar1 ^ 0x80000000) - DOUBLE_803e8ac8) -
              dVar3) != 0.0) && (((uint)fVar2 & 0x7f800000) < 0x4b800000)) {
    if (((uint)fVar2 & 0x80000000) == 0) {
      dVar3 = (double)(float)((double)CONCAT44(0x43300000,uVar1 ^ 0x80000000) - DOUBLE_803e8ac8);
    }
    else {
      dVar3 = (double)(float)((double)CONCAT44(0x43300000,uVar1 - 1 ^ 0x80000000) - DOUBLE_803e8ac8)
      ;
    }
  }
  return dVar3;
}
