/*
 * Auto-generated by tools/claim_auto_game_splits.py.
 *
 * This file claims a previously auto-generated game-code text window so it has a stable home
 * in `splits.txt` and can be subdivided into real sources later.
 *
 * Current EN split: 0x80279EC0-0x8027A2FC
 * Previous named split: main/main/audio/synth_control
 * Next named split: main/dolphin/TRK_MINNOW_DOLPHIN/CircleBuffer
 * Raw auto unit name: main/auto_03_80279EC0_text
 * Function count: 1
 *
 * Suggested follow-up:
 * - Subdivide this window into real source files once stronger corridor/object evidence exists.
 * - Use the listed function addresses to pull Ghidra bodies selectively when promoting a subrange.
 */

#include "main/unknown/autos/placeholder_80279EC0.h"

/*
 * Function inventory:
 * - fn_80279EC0 @ 0x80279EC0 size 0x43C
 */
