/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/unknown/autos/placeholder_8027590C.c
 * Text span: 0x8027590C-0x8027591C
 * Imported Ghidra functions: 0
 * Inventory-derived stub functions: 1
 */

#include "ghidra_import.h"
#include "main/unknown/autos/placeholder_8027590C.h"

/* No raw Ghidra dump was available for this owner yet. */
/* Split inventory stubs keep the file compiled and routable in the meantime. */

undefined4 fn_8027590C(void);

/* Function: fn_8027590C */
/* Entry: 0x8027590C */
/* Size: 0x10 */
undefined4
fn_8027590C(void)
{
    return 0;
}
