/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/FRONT/dll_39.c
 * Text span: 0x80115FF0-0x80116858
 * Imported Ghidra functions: 7
 * Verbatim-safe functions: 4
 * Auto-stubbed functions: 3
 */

#include "ghidra_import.h"
#include "main/dll/FRONT/dll_39.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_8001406c();
extern undefined4 FUN_80014974();
extern undefined4 FUN_800201ac();
extern undefined4 FUN_80022e1c();
extern undefined4 FUN_800238c4();
extern undefined4 FUN_800238f8();
extern undefined4 FUN_80023d8c();
extern undefined8 FUN_80041f1c();
extern undefined8 FUN_80041f28();
extern undefined4 FUN_80041f34();
extern undefined4 FUN_80043070();
extern undefined4 FUN_80043938();
extern undefined4 FUN_80055464();
extern undefined4 FUN_8007d858();
extern undefined8 FUN_80088e98();
extern undefined8 FUN_8010123c();
extern undefined4 FUN_80117e10();
extern undefined4 FUN_801184a0();
extern undefined4 FUN_80118ac4();
extern undefined4 FUN_80118ba8();
extern bool FUN_80118c08();
extern undefined8 FUN_80118f30();
extern undefined4 FUN_80119154();
extern undefined4 FUN_80119254();
extern int FUN_801192a8();
extern undefined4 FUN_80119594();
extern int FUN_801195e0();
extern undefined8 FUN_8011dc94();
extern int FUN_80241de8();
extern undefined4 FUN_802420b0();
extern undefined4 FUN_80242fc0();
extern undefined4 FUN_8024d054();
extern int FUN_8025a850();
extern undefined4 FUN_8025aa74();
extern undefined4 FUN_8025ace8();
extern undefined4 FUN_8025ae7c();
extern uint FUN_8025ae84();
extern uint FUN_8025ae94();
extern int FUN_8025aea4();
extern undefined4 FUN_80286838();
extern undefined4 FUN_80286884();

/* Raw global references kept as loose externs for later cleanup. */
extern int DAT_803a5098;
extern undefined4 DAT_803dc070;
extern undefined4* DAT_803dd6cc;
extern undefined4 DAT_803dd970;
extern undefined4 DAT_803de260;
extern undefined4 DAT_803de264;
extern undefined4 DAT_803de268;
extern undefined4 DAT_803de270;
extern undefined4 DAT_803de274;
extern undefined4 DAT_803de280;
extern undefined4 DAT_803de281;
extern undefined4 DAT_803de282;
extern undefined4 DAT_803de288;
extern undefined4 DAT_803de28c;
extern undefined4 DAT_803de291;
extern undefined4 DAT_803de29c;
extern undefined4 DAT_803de2a0;
extern undefined4 DAT_803de2a4;
extern undefined4 DAT_803de2a8;
extern undefined4 DAT_803de2ac;
extern undefined4 DAT_803de2b0;
extern undefined4 DAT_803de2b4;
extern undefined4 DAT_803de2b8;
extern undefined4 DAT_803de2c0;
extern undefined4 DAT_803de2c4;
extern undefined4 DAT_803de2cd;
extern undefined4 DAT_803de318;
extern f32 FLOAT_803dc074;
extern f32 FLOAT_803de26c;
extern f32 FLOAT_803de278;
extern f32 FLOAT_803de27c;
extern f32 FLOAT_803e2970;
extern f32 FLOAT_803e2980;
extern int iRam803de2bc;
extern char s_Fail_to_prepare_8031afec[];
extern char s_n_attractmode_c_8031afdc[];

/* Local declarations keep imported functions visible within the TU. */
void FUN_80115ff0(void);
undefined4 FUN_80116110(void);
void FUN_8011615c(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 undefined4 param_9,undefined4 param_10,undefined4 param_11,undefined4 param_12,
                 undefined4 param_13,undefined4 param_14,undefined4 param_15,undefined4 param_16);
undefined4 FUN_80116258(void);
void FUN_8011637c(void);
void FUN_801163b8(void);
void FUN_801164c0(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8);

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80115FF0
 * EN v1.0 Size: 288b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80115ff0(void)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80116110
 * EN v1.0 Size: 76b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
undefined4 FUN_80116110(void)

{
  if (DAT_803de268 != '\0') {
    DAT_803de268 = '\0';
    FLOAT_803de26c = FLOAT_803e2980;
    FUN_80014974(4);
  }
  return 0;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8011615C
 * EN v1.0 Size: 252b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8011615c(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 undefined4 param_9,undefined4 param_10,undefined4 param_11,undefined4 param_12,
                 undefined4 param_13,undefined4 param_14,undefined4 param_15,undefined4 param_16)

{
  undefined8 uVar1;
  
  DAT_803de268 = 1;
  FLOAT_803de26c = FLOAT_803e2980;
  FUN_80043938(param_1,param_2,param_3,param_4,param_5,param_6,param_7,param_8);
  uVar1 = FUN_80041f28();
  FUN_80043070(uVar1,param_2,param_3,param_4,param_5,param_6,param_7,param_8,0x3f);
  uVar1 = FUN_80041f1c();
  uVar1 = FUN_80088e98(uVar1,param_2,param_3,param_4,param_5,param_6,param_7,param_8);
  uVar1 = FUN_8011dc94(uVar1,param_2,param_3,param_4,param_5,param_6,param_7,param_8);
  uVar1 = FUN_8010123c(uVar1,param_2,param_3,param_4,param_5,param_6,param_7,param_8);
  FUN_80055464(uVar1,param_2,param_3,param_4,param_5,param_6,param_7,param_8,0x12,'\0',param_11,
               param_12,param_13,param_14,param_15,param_16);
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80116258
 * EN v1.0 Size: 292b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
undefined4 FUN_80116258(void)
{
    return 0;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8011637C
 * EN v1.0 Size: 60b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8011637c(void)

{
  FUN_8001406c(0);
  DAT_803de270 = 0;
  DAT_803de274 = 0;
  DAT_803de282 = 0;
  DAT_803de281 = 0;
  DAT_803de280 = 0;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801163B8
 * EN v1.0 Size: 264b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_801163b8(void)

{
  undefined4 uVar1;
  
  if (DAT_803de288 == 2) {
    FUN_80118ac4();
    FUN_80119254();
    FUN_80119594();
    uVar1 = FUN_800238f8(0);
    if (DAT_803de2b4 != 0) {
      FUN_800238c4(DAT_803de2b4);
      DAT_803de2b4 = 0;
    }
    if (DAT_803de2b0 != 0) {
      FUN_800238c4(DAT_803de2b0);
      DAT_803de2b0 = 0;
    }
    if (DAT_803de2ac != 0) {
      FUN_800238c4(DAT_803de2ac);
      DAT_803de2ac = 0;
    }
    if (DAT_803de2a8 != 0) {
      FUN_800238c4(DAT_803de2a8);
      DAT_803de2a8 = 0;
    }
    if (DAT_803de2a4 != 0) {
      FUN_800238c4(DAT_803de2a4);
      DAT_803de2a4 = 0;
    }
    if (DAT_803de2a0 != 0) {
      FUN_800238c4(DAT_803de2a0);
      DAT_803de2a0 = 0;
    }
    if (DAT_803de29c != 0) {
      FUN_800238c4(DAT_803de29c);
      DAT_803de29c = 0;
    }
    FUN_800238f8(uVar1);
    DAT_803de288 = 4;
    DAT_803de291 = 1;
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801164C0
 * EN v1.0 Size: 920b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_801164c0(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8)
{
}
