/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/FRONT/n_options.c
 * Text span: 0x8011784C-0x801184E8
 * Imported Ghidra functions: 7
 * Verbatim-safe functions: 2
 * Auto-stubbed functions: 5
 */

#include "ghidra_import.h"
#include "main/dll/FRONT/n_options.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_800033a8();
extern undefined4 FUN_80003494();
extern undefined4 FUN_80070434();
extern undefined4 FUN_8007048c();
extern undefined4 FUN_801175b4();
extern undefined4 FUN_801175f8();
extern undefined4 FUN_80117708();
extern undefined4 FUN_801177b4();
extern undefined4 FUN_80119a10();
extern undefined4 FUN_802420b0();
extern undefined4 FUN_802420e0();
extern undefined4 FUN_80243e74();
extern undefined4 FUN_80243e88();
extern undefined4 FUN_80243e9c();
extern undefined4 FUN_802446f8();
extern int FUN_80244820();
extern int FUN_80246a0c();
extern undefined4 FUN_8024fe60();
extern uint FUN_8024ff18();
extern undefined4 FUN_80258674();
extern undefined4 FUN_80258944();
extern undefined4 FUN_80259288();
extern undefined4 FUN_8025aa74();
extern undefined4 FUN_8025ace8();
extern undefined4 FUN_8025b054();
extern undefined4 FUN_8025be54();
extern undefined4 FUN_8025be80();
extern undefined4 FUN_8025c1a4();
extern undefined4 FUN_8025c224();
extern undefined4 FUN_8025c2a8();
extern undefined4 FUN_8025c368();
extern undefined4 FUN_8025c49c();
extern undefined4 FUN_8025c510();
extern undefined4 FUN_8025c584();
extern undefined4 FUN_8025c5f0();
extern undefined4 FUN_8025c65c();
extern undefined4 FUN_8025c6b4();
extern undefined4 FUN_8025c754();
extern undefined4 FUN_8025c828();
extern undefined4 FUN_8025ca04();
extern undefined4 FUN_8025cce8();
extern undefined4 FUN_8025cdec();
extern undefined4 FUN_8025ce2c();
extern undefined8 FUN_80286840();
extern undefined4 FUN_8028688c();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4 DAT_8031b000;
extern undefined4 DAT_803a50a8;
extern undefined4 DAT_803a50b4;
extern undefined4 DAT_803a50c0;
extern undefined4 DAT_803a50e0;
extern undefined4 DAT_803a6420;
extern undefined4 DAT_803a692c;
extern undefined4 DAT_803a6a58;
extern undefined4 DAT_803a6a5d;
extern undefined4 DAT_803a6a5f;
extern undefined4 DAT_803a6a94;
extern undefined4 DAT_803a6a98;
extern undefined4 DAT_803a6a9c;
extern undefined4 DAT_803a6aa0;
extern undefined4 DAT_803a6aa8;
extern undefined4 DAT_803a6ab0;
extern undefined4 DAT_803de2d8;
extern undefined4 DAT_803de2e0;
extern undefined4* DAT_803de2e8;
extern undefined4 DAT_803de2ec;
extern undefined4 DAT_803de2f0;
extern undefined4 DAT_803de2f4;
extern undefined4 DAT_803de2f8;
extern undefined4 DAT_803e29b0;
extern undefined4 DAT_803e29b4;
extern undefined4 DAT_803e29b8;
extern undefined4 DAT_803e29bc;
extern undefined4 DAT_803e29c0;
extern f64 DOUBLE_803e29c8;
extern f32 FLOAT_803e29c4;

/* Local declarations keep imported functions visible within the TU. */
undefined4 FUN_8011784c(int param_1,int param_2);
void FUN_80117910(undefined4 param_1,undefined4 param_2,uint param_3,uint param_4,uint param_5);
undefined4 FUN_80117e10(uint param_1,int param_2);
void FUN_80117f1c(undefined2 *param_1,short *param_2,uint param_3);
void FUN_801182c0(void);
void FUN_80118434(void);
bool FUN_801184a0(uint param_1);

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8011784C
 * EN v1.0 Size: 196b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
undefined4 FUN_8011784c(int param_1,int param_2)
{
    return 0;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80117910
 * EN v1.0 Size: 1280b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80117910(undefined4 param_1,undefined4 param_2,uint param_3,uint param_4,uint param_5)

{
  uint uVar1;
  uint uVar2;
  double dVar3;
  undefined8 uVar4;
  undefined4 local_98;
  undefined4 local_94;
  undefined4 local_90;
  undefined4 local_8c;
  undefined4 local_88;
  uint auStack_84 [8];
  uint auStack_64 [8];
  uint auStack_44 [17];
  
  uVar4 = FUN_80286840();
  FUN_8007048c(1,3,1);
  FUN_8025cce8(0,1,0,0);
  FUN_8025cdec(1);
  FUN_8025ce2c(0);
  FUN_80259288(2);
  FUN_80070434(1);
  FUN_8025c754(7,0,0,7,0);
  FUN_80258944(2);
  FUN_80258674(0,1,4,0x3c,0,0x7d);
  FUN_80258674(1,1,4,0x3c,0,0x7d);
  FUN_8025ca04(4);
  FUN_8025be54(0);
  FUN_8025c828(0,1,1,0xff);
  FUN_8025be80(0);
  FUN_8025c1a4(0,0xf,8,0xe,2);
  FUN_8025c2a8(0,0,0,0,0,0);
  FUN_8025c224(0,7,4,6,1);
  FUN_8025c368(0,1,0,0,0,0);
  FUN_8025c584(0,0xc);
  FUN_8025c5f0(0,0x1c);
  FUN_8025c65c(0,0,0);
  FUN_8025c828(1,1,2,0xff);
  FUN_8025be80(1);
  FUN_8025c1a4(1,0xf,8,0xe,0);
  FUN_8025c2a8(1,0,0,1,0,0);
  FUN_8025c224(1,7,4,6,0);
  FUN_8025c368(1,1,0,0,0,0);
  FUN_8025c584(1,0xd);
  FUN_8025c5f0(1,0x1d);
  FUN_8025c65c(1,0,0);
  FUN_8025c828(2,0,0,0xff);
  FUN_8025be80(2);
  FUN_8025c1a4(2,0xf,8,0xc,0);
  FUN_8025c2a8(2,0,0,0,1,0);
  FUN_8025c224(2,4,7,7,0);
  FUN_8025c368(2,0,0,0,1,0);
  FUN_8025c65c(2,0,0);
  FUN_8025c828(3,0xff,0xff,0xff);
  FUN_8025be80(3);
  FUN_8025c1a4(3,1,0,0xe,0xf);
  FUN_8025c2a8(3,0,0,0,1,0);
  FUN_8025c224(3,7,7,7,7);
  FUN_8025c368(3,0,0,0,1,0);
  FUN_8025c65c(3,0,0);
  FUN_8025c584(3,0xe);
  local_8c = DAT_803e29b0;
  local_88 = DAT_803e29b4;
  FUN_8025c49c(1,(short *)&local_8c);
  local_90 = DAT_803e29b8;
  FUN_8025c510(0,(byte *)&local_90);
  local_94 = DAT_803e29bc;
  FUN_8025c510(1,(byte *)&local_94);
  local_98 = DAT_803e29c0;
  FUN_8025c510(2,(byte *)&local_98);
  FUN_8025c6b4(0,0,1,2,3);
  FUN_8025aa74(auStack_44,(uint)((ulonglong)uVar4 >> 0x20),param_4 & 0xffff,param_5 & 0xffff,1,0,0,
               '\0');
  dVar3 = (double)FLOAT_803e29c4;
  FUN_8025ace8(dVar3,dVar3,dVar3,auStack_44,0,0,0,'\0',0);
  FUN_8025b054(auStack_44,0);
  uVar1 = (int)(short)param_4 >> 1;
  uVar2 = (int)(short)param_5 >> 1;
  FUN_8025aa74(auStack_64,(uint)uVar4,uVar1 & 0xffff,uVar2 & 0xffff,1,0,0,'\0');
  dVar3 = (double)FLOAT_803e29c4;
  FUN_8025ace8(dVar3,dVar3,dVar3,auStack_64,0,0,0,'\0',0);
  FUN_8025b054(auStack_64,1);
  FUN_8025aa74(auStack_84,param_3,uVar1 & 0xffff,uVar2 & 0xffff,1,0,0,'\0');
  dVar3 = (double)FLOAT_803e29c4;
  FUN_8025ace8(dVar3,dVar3,dVar3,auStack_84,0,0,0,'\0',0);
  FUN_8025b054(auStack_84,2);
  FUN_8028688c();
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80117E10
 * EN v1.0 Size: 268b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
undefined4 FUN_80117e10(uint param_1,int param_2)
{
    return 0;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80117F1C
 * EN v1.0 Size: 932b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80117f1c(undefined2 *param_1,short *param_2,uint param_3)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801182C0
 * EN v1.0 Size: 372b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_801182c0(void)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80118434
 * EN v1.0 Size: 108b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80118434(void)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801184A0
 * EN v1.0 Size: 72b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
bool FUN_801184a0(uint param_1)

{
  bool bVar1;
  
  bVar1 = DAT_803a6a58 != 0;
  if (bVar1) {
    FUN_80003494(param_1,0x803a6a40,8);
  }
  return bVar1;
}
