/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/DB/DBstealerworm.c
 * Text span: 0x801E18DC-0x801E383C
 * Imported Ghidra functions: 17
 * Verbatim-safe functions: 0
 * Auto-stubbed functions: 17
 */

#include "ghidra_import.h"
#include "main/dll/DB/DBstealerworm.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_800066e0();
extern undefined4 FUN_8000a538();
extern undefined4 FUN_8000b7dc();
extern undefined4 FUN_8000b844();
extern undefined4 FUN_8000bb38();
extern undefined4 FUN_8000da78();
extern undefined4 FUN_8000e12c();
extern undefined4 FUN_800168a8();
extern undefined8 FUN_80019940();
extern uint FUN_80020078();
extern undefined4 FUN_800201ac();
extern undefined4 FUN_800217c8();
extern uint FUN_80022264();
extern int FUN_800284e8();
extern undefined4 FUN_8002ad08();
extern undefined4 FUN_8002b660();
extern undefined8 FUN_8002b9a0();
extern int FUN_8002bac4();
extern undefined2* FUN_8002becc();
extern int FUN_8002e088();
extern uint FUN_8002e144();
extern int FUN_8002e1f4();
extern int FUN_8002fb40();
extern undefined4 FUN_8003042c();
extern undefined4 FUN_80035ff8();
extern int FUN_80036974();
extern undefined4 FUN_8003709c();
extern undefined4 FUN_800372f8();
extern int FUN_800375e4();
extern undefined4 FUN_80038524();
extern undefined4 FUN_8003b9ec();
extern undefined4 FUN_80043658();
extern undefined4 FUN_8004832c();
extern undefined4 FUN_80054484();
extern undefined4 FUN_80054ed0();
extern undefined4 FUN_8005cf74();
extern undefined4 FUN_80089468();
extern undefined4 FUN_8008947c();
extern undefined4 FUN_80089484();
extern undefined4 FUN_800894c0();
extern undefined4 FUN_80089734();
extern undefined4 FUN_8008979c();
extern undefined4 FUN_80089804();
extern undefined4 FUN_8008986c();
extern undefined4 FUN_8008999c();
extern double FUN_8008f014();
extern undefined4 FUN_8009adfc();
extern undefined4 FUN_801d84c4();
extern undefined4 FUN_801e0018();
extern undefined4 FUN_801e167c();
extern int FUN_801e18cc();
extern int FUN_8028683c();
extern undefined4 FUN_80286888();
extern double FUN_80293900();
extern undefined4 FUN_802945e0();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4 DAT_802c2b78;
extern undefined4 DAT_802c2b7c;
extern undefined4 DAT_802c2b80;
extern undefined4 DAT_802c2b84;
extern undefined4 DAT_802c2b88;
extern undefined4 DAT_802c2b8c;
extern undefined4 DAT_802c2b90;
extern undefined4 DAT_802c2b94;
extern undefined4 DAT_802c2b98;
extern undefined4 DAT_802c2b9c;
extern undefined4 DAT_802c2ba0;
extern undefined4 DAT_802c2ba4;
extern undefined4 DAT_803dc070;
extern undefined4 DAT_803dcce0;
extern undefined4 DAT_803dcce4;
extern undefined4 DAT_803dcce8;
extern undefined4 DAT_803dccec;
extern undefined4 DAT_803dccf0;
extern undefined4 DAT_803dccf4;
extern undefined4 DAT_803dccf8;
extern undefined4* DAT_803dd6cc;
extern undefined4* DAT_803dd6d4;
extern undefined4* DAT_803dd6e4;
extern undefined4* DAT_803dd708;
extern undefined4* DAT_803dd72c;
extern undefined4 DAT_803de898;
extern undefined4 DAT_803de89c;
extern undefined4 DAT_803de8a0;
extern undefined4 DAT_803de8ac;
extern undefined4 DAT_803de8ad;
extern undefined4 DAT_803de8b0;
extern undefined4 DAT_803de8b4;
extern undefined4 DAT_803de8b8;
extern undefined4 DAT_803de8c0;
extern undefined4 DAT_803de8c8;
extern f64 DOUBLE_803e6458;
extern f64 DOUBLE_803e6480;
extern f64 DOUBLE_803e64c0;
extern f64 DOUBLE_803e64f8;
extern f32 FLOAT_803dc074;
extern f32 FLOAT_803de8a4;
extern f32 FLOAT_803de8a8;
extern f32 FLOAT_803e6360;
extern f32 FLOAT_803e6364;
extern f32 FLOAT_803e6388;
extern f32 FLOAT_803e63bc;
extern f32 FLOAT_803e63d0;
extern f32 FLOAT_803e6428;
extern f32 FLOAT_803e643c;
extern f32 FLOAT_803e644c;
extern f32 FLOAT_803e6460;
extern f32 FLOAT_803e6464;
extern f32 FLOAT_803e6468;
extern f32 FLOAT_803e646c;
extern f32 FLOAT_803e6470;
extern f32 FLOAT_803e6474;
extern f32 FLOAT_803e6478;
extern f32 FLOAT_803e6488;
extern f32 FLOAT_803e648c;
extern f32 FLOAT_803e6490;
extern f32 FLOAT_803e6494;
extern f32 FLOAT_803e6498;
extern f32 FLOAT_803e649c;
extern f32 FLOAT_803e64a0;
extern f32 FLOAT_803e64a4;
extern f32 FLOAT_803e64a8;
extern f32 FLOAT_803e64ac;
extern f32 FLOAT_803e64b0;
extern f32 FLOAT_803e64b4;
extern f32 FLOAT_803e64b8;
extern f32 FLOAT_803e64bc;
extern f32 FLOAT_803e64c8;
extern f32 FLOAT_803e64cc;
extern f32 FLOAT_803e64d0;
extern f32 FLOAT_803e64d4;
extern f32 FLOAT_803e64d8;
extern f32 FLOAT_803e64dc;
extern f32 FLOAT_803e64e0;
extern f32 FLOAT_803e64e4;
extern f32 FLOAT_803e64e8;
extern f32 FLOAT_803e64ec;
extern f32 FLOAT_803e64f0;
extern f32 FLOAT_803e64f4;
extern undefined bRam803dcce1;
extern undefined2 bRam803dcce2;
extern undefined bRam803dcce5;
extern undefined2 bRam803dcce6;
extern undefined bRam803dcce9;
extern undefined2 bRam803dccea;
extern undefined bRam803dcced;
extern undefined2 bRam803dccee;
extern undefined bRam803dccf1;
extern undefined2 bRam803dccf2;
extern undefined bRam803dccf5;
extern undefined2 bRam803dccf6;
extern undefined bRam803de8b9;
extern undefined2 bRam803de8ba;
extern undefined uRam803de8b1;
extern undefined2 uRam803de8b2;
extern undefined uRam803de8b5;
extern undefined2 uRam803de8b6;

/* Local declarations keep imported functions visible within the TU. */
void FUN_801e18dc(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 uint param_9);
void FUN_801e1b78(int param_1,int param_2);
undefined4
FUN_801e209c(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
            undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,uint param_9
            ,undefined4 param_10,int param_11);
undefined4 FUN_801e2398(void);
undefined4 FUN_801e2464(uint param_1);
void FUN_801e2508(int param_1,int param_2);
void FUN_801e25cc(void);
void FUN_801e26e4(int param_1);
void FUN_801e279c(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 uint param_9);
void FUN_801e29d4(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 undefined2 *param_9,undefined4 param_10,undefined4 param_11,undefined4 param_12,
                 undefined4 param_13,undefined4 param_14,undefined4 param_15,undefined4 param_16);
undefined4 FUN_801e2b60(void);
void FUN_801e2b70(int param_1);
void FUN_801e2bbc(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8);
void FUN_801e3078(int param_1,int param_2);
void FUN_801e3128(int param_1);
void FUN_801e314c(int param_1);
void FUN_801e32d4(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8);

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801E18DC
 * EN v1.0 Size: 668b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801e18dc(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 uint param_9)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801E1B78
 * EN v1.0 Size: 1316b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801e1b78(int param_1,int param_2)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801E209C
 * EN v1.0 Size: 764b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: address-label references need manual cleanup, forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

undefined4
FUN_801e209c(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
            undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,uint param_9
            ,undefined4 param_10,int param_11)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
    return 0;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801E2398
 * EN v1.0 Size: 204b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

undefined4 FUN_801e2398(void)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
    return 0;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801E2464
 * EN v1.0 Size: 164b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

undefined4 FUN_801e2464(uint param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
    return 0;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801E2508
 * EN v1.0 Size: 196b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801e2508(int param_1,int param_2)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801E25CC
 * EN v1.0 Size: 280b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801e25cc(void)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801E26E4
 * EN v1.0 Size: 184b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801e26e4(int param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801E279C
 * EN v1.0 Size: 568b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801e279c(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 uint param_9)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801E29D4
 * EN v1.0 Size: 396b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: function-pointer assignments need manual cleanup, forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801e29d4(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 undefined2 *param_9,undefined4 param_10,undefined4 param_11,undefined4 param_12,
                 undefined4 param_13,undefined4 param_14,undefined4 param_15,undefined4 param_16)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801E2B60
 * EN v1.0 Size: 16b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

undefined4 FUN_801e2b60(void)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
    return 0;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801E2B70
 * EN v1.0 Size: 76b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801e2b70(int param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801E2BBC
 * EN v1.0 Size: 1212b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801e2bbc(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801E3078
 * EN v1.0 Size: 176b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801e3078(int param_1,int param_2)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801E3128
 * EN v1.0 Size: 36b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801e3128(int param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801E314C
 * EN v1.0 Size: 392b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801e314c(int param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801E32D4
 * EN v1.0 Size: 1384b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801e32d4(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}
