#ifndef MAIN_UNKNOWN_AUTOS_PLACEHOLDER_802835C0_H_
#define MAIN_UNKNOWN_AUTOS_PLACEHOLDER_802835C0_H_

/*
 * Auto-generated by tools/claim_auto_game_splits.py.
 *
 * Placeholder owner for the former auto-generated game text window 0x802835C0-0x8028364C.
 * Previous named split: main/main/audio/synth_control
 * Next named split: main/dolphin/TRK_MINNOW_DOLPHIN/CircleBuffer
 * Function count: 2
 *
 * Function inventory:
 * - fn_802835C0 @ 0x802835C0 size 0x20
 * - fn_802835E0 @ 0x802835E0 size 0x6C
 */

#endif /* MAIN_UNKNOWN_AUTOS_PLACEHOLDER_802835C0_H_ */
