#ifndef MAIN_UNKNOWN_AUTOS_PLACEHOLDER_8026FD1C_H_
#define MAIN_UNKNOWN_AUTOS_PLACEHOLDER_8026FD1C_H_

#include "ghidra_import.h"

void FUN_8026fc8c(int param_1);

#endif /* MAIN_UNKNOWN_AUTOS_PLACEHOLDER_8026FD1C_H_ */
