#ifndef MAIN_UNKNOWN_AUTOS_PLACEHOLDER_802791FC_H_
#define MAIN_UNKNOWN_AUTOS_PLACEHOLDER_802791FC_H_

/*
 * Auto-generated by tools/claim_auto_game_splits.py.
 *
 * Placeholder owner for the former auto-generated game text window 0x802791FC-0x802792F8.
 * Previous named split: main/main/audio/synth_control
 * Next named split: main/dolphin/TRK_MINNOW_DOLPHIN/CircleBuffer
 * Function count: 1
 *
 * Function inventory:
 * - fn_802791FC @ 0x802791FC size 0xFC
 */

#endif /* MAIN_UNKNOWN_AUTOS_PLACEHOLDER_802791FC_H_ */
