#ifndef MAIN_UNKNOWN_AUTOS_PLACEHOLDER_8027ADC4_H_
#define MAIN_UNKNOWN_AUTOS_PLACEHOLDER_8027ADC4_H_

#include "ghidra_import.h"

undefined4 FUN_8027adc4(char *param_1);

#endif /* MAIN_UNKNOWN_AUTOS_PLACEHOLDER_8027ADC4_H_ */
