/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/creator1C4.c
 * Text span: 0x801C7CD8-0x801C8524
 * Imported Ghidra functions: 1
 * Verbatim-safe functions: 0
 * Auto-stubbed functions: 1
 */

#include "ghidra_import.h"
#include "main/dll/creator1C4.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined8 FUN_80008cbc();
extern undefined4 FUN_80009a94();
extern undefined4 FUN_8000a538();
extern undefined4 FUN_8000bb38();
extern byte FUN_8001469c();
extern undefined4 FUN_800146a8();
extern undefined4 FUN_800146c8();
extern undefined4 FUN_800146e8();
extern uint FUN_80020078();
extern undefined4 FUN_800201ac();
extern uint FUN_80022264();
extern int FUN_8002bac4();
extern undefined4 FUN_8002cc9c();
extern undefined4* FUN_80037048();
extern undefined4 FUN_80043604();
extern int FUN_8004832c();
extern undefined8 FUN_80088f20();
extern undefined4 FUN_801c76a4();
extern undefined4 FUN_801d84c4();
extern undefined4 FUN_801d8650();
extern undefined4 FUN_80286834();
extern undefined4 FUN_80286880();
extern uint FUN_80296cb4();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4* DAT_803dd6cc;
extern undefined4* DAT_803dd6d4;
extern undefined4* DAT_803dd72c;
extern f64 DOUBLE_803e5cc8;
extern f32 FLOAT_803dc074;
extern f32 FLOAT_803e5cd4;
extern f32 FLOAT_803e5cd8;

/* Local declarations keep imported functions visible within the TU. */
void FUN_801c7cd8(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8);

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801C7CD8
 * EN v1.0 Size: 2124b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_801c7cd8(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8)
{
}
