/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/dll_D1.c
 * Text span: 0x8013E010-0x8013E458
 * Imported Ghidra functions: 1
 * Verbatim-safe functions: 0
 * Auto-stubbed functions: 1
 */

#include "ghidra_import.h"
#include "main/dll/dll_D1.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern bool FUN_8000b598();
extern undefined4 FUN_8000bb38();
extern undefined4 FUN_8000dbb0();
extern undefined4 FUN_8000dcdc();
extern int FUN_80021884();
extern uint FUN_80022264();
extern undefined2* FUN_8002becc();
extern undefined4 FUN_8002e088();
extern uint FUN_8002e144();
extern undefined4 FUN_800394f0();
extern undefined4 FUN_80139cb8();
extern undefined4 FUN_8013a778();
extern int FUN_8013b6f0();
extern undefined4 FUN_80148ff0();
extern undefined4 FUN_801784f8();
extern undefined8 FUN_8028683c();
extern undefined4 FUN_80286888();

/* Raw global references kept as loose externs for later cleanup. */
extern f32 FLOAT_803e306c;
extern f32 FLOAT_803e30d4;
extern f32 FLOAT_803e3158;
extern f32 FLOAT_803e315c;
extern f32 FLOAT_803e3160;

/* Local declarations keep imported functions visible within the TU. */
void FUN_8013e010(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 undefined4 param_9,undefined4 param_10,int param_11,undefined4 param_12,
                 byte param_13,uint param_14,undefined4 param_15,undefined4 param_16);

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8013E010
 * EN v1.0 Size: 1096b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8013e010(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 undefined4 param_9,undefined4 param_10,int param_11,undefined4 param_12,
                 byte param_13,uint param_14,undefined4 param_15,undefined4 param_16)
{
}
