/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/genprops.c
 * Text span: 0x8016B550-0x801725F0
 * Imported Ghidra functions: 74
 * Verbatim-safe functions: 53
 * Auto-stubbed functions: 21
 */

#include "ghidra_import.h"
#include "main/dll/genprops.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_80003494();
extern undefined4 FUN_8000b4f0();
extern undefined8 FUN_8000b7dc();
extern undefined4 FUN_8000b844();
extern undefined4 FUN_8000b9bc();
extern undefined4 FUN_8000bb00();
extern undefined8 FUN_8000bb38();
extern undefined4 FUN_8000da9c();
extern undefined8 FUN_8000e670();
extern undefined* FUN_8000f56c();
extern double FUN_80010f00();
extern undefined4 FUN_80013e4c();
extern int FUN_80013ee8();
extern undefined4 FUN_8001d6e4();
extern undefined4 FUN_8001d7d8();
extern undefined4 FUN_8001d7f4();
extern undefined4 FUN_8001dadc();
extern undefined4 FUN_8001dbb4();
extern undefined4 FUN_8001dbd8();
extern undefined4 FUN_8001dbf0();
extern undefined4 FUN_8001dc18();
extern undefined4 FUN_8001dc30();
extern undefined4 FUN_8001dcfc();
extern undefined4 FUN_8001de04();
extern undefined4 FUN_8001de4c();
extern undefined4 FUN_8001f448();
extern int* FUN_8001f58c();
extern undefined4 FUN_80020000();
extern uint FUN_80020078();
extern undefined8 FUN_800201ac();
extern int FUN_80020800();
extern double FUN_80021794();
extern undefined4 FUN_80021884();
extern undefined4 FUN_80021b8c();
extern undefined4 FUN_80021fac();
extern uint FUN_80022264();
extern undefined4 FUN_80022790();
extern undefined4 FUN_800229cc();
extern undefined4 FUN_800238c4();
extern int FUN_80023d8c();
extern undefined4 FUN_80028590();
extern undefined4 FUN_800285f0();
extern undefined4 FUN_8002a84c();
extern undefined4 FUN_8002b554();
extern int FUN_8002b660();
extern int FUN_8002b678();
extern undefined4 FUN_8002b95c();
extern undefined4 FUN_8002b9a0();
extern undefined4 FUN_8002ba34();
extern int FUN_8002ba84();
extern int FUN_8002bac4();
extern undefined2* FUN_8002becc();
extern undefined4 FUN_8002cc9c();
extern int FUN_8002e088();
extern uint FUN_8002e144();
extern undefined4 FUN_8002e1f4();
extern undefined8 FUN_8002fb40();
extern undefined4 FUN_8003042c();
extern undefined4 FUN_80035a58();
extern undefined4 FUN_80035a6c();
extern undefined4 FUN_80035ea4();
extern undefined4 FUN_80035eec();
extern undefined8 FUN_80035ff8();
extern undefined4 FUN_80036018();
extern int FUN_80036868();
extern undefined4 FUN_80036f50();
extern undefined4* FUN_80037048();
extern undefined4 FUN_8003709c();
extern undefined4 FUN_800372f8();
extern undefined8 FUN_80037da8();
extern undefined4 FUN_80037e24();
extern uint FUN_800387b4();
extern undefined4 FUN_8003b6d8();
extern undefined4 FUN_8003b9ec();
extern undefined4 FUN_800413cc();
extern undefined4 FUN_80041bbc();
extern undefined4 FUN_8004c460();
extern undefined4 FUN_80054484();
extern undefined4 FUN_80054620();
extern undefined4 FUN_800551ec();
extern undefined4 FUN_800551f8();
extern undefined4 FUN_80060630();
extern undefined4 FUN_80062614();
extern undefined4 FUN_80065800();
extern int FUN_80065a20();
extern undefined4 FUN_80070434();
extern undefined4 FUN_8007048c();
extern undefined4 FUN_800737e8();
extern undefined4 FUN_8007986c();
extern undefined4 FUN_80079980();
extern undefined4 FUN_80079b3c();
extern undefined4 FUN_800803f8();
extern undefined4 FUN_80080404();
extern int FUN_80080434();
extern undefined4 FUN_80080484();
extern undefined4 FUN_8009742c();
extern undefined4 FUN_80097568();
extern undefined4 FUN_800979c0();
extern undefined4 FUN_80098608();
extern undefined4 FUN_800998ec();
extern undefined4 FUN_80099c40();
extern undefined8 FUN_800e83ec();
extern undefined4 FUN_800e85f4();
extern undefined4 FUN_80150950();
extern undefined4 FUN_80220088();
extern int FUN_802371d4();
extern undefined4 FUN_80247618();
extern undefined4 FUN_8024782c();
extern undefined4 FUN_80247a48();
extern undefined4 FUN_80247a7c();
extern undefined4 FUN_802570dc();
extern undefined4 FUN_80257b5c();
extern undefined4 FUN_80259000();
extern undefined4 FUN_80259288();
extern undefined4 FUN_8025c754();
extern undefined4 FUN_8025cce8();
extern undefined4 FUN_8025d180();
extern undefined4 FUN_8025d80c();
extern undefined4 FUN_8025d888();
extern undefined4 FUN_8025d8c4();
extern undefined4 FUN_80286814();
extern int FUN_8028682c();
extern int FUN_80286830();
extern int FUN_80286838();
extern int FUN_80286840();
extern undefined4 FUN_80286860();
extern undefined4 FUN_80286878();
extern undefined4 FUN_8028687c();
extern undefined4 FUN_80286884();
extern undefined4 FUN_8028688c();
extern undefined4 FUN_802925a0();
extern double FUN_80293900();
extern undefined4 FUN_80293a9c();
extern undefined4 FUN_802945e0();
extern undefined4 FUN_80294964();
extern undefined4 FUN_80296854();
extern undefined4 FUN_80296904();
extern int FUN_80296e2c();
extern int FUN_80296e60();
extern undefined4 FUN_8029725c();
extern undefined4 FUN_80297300();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4 DAT_802c29a0;
extern undefined4 DAT_802c29a4;
extern undefined4 DAT_802c29a8;
extern undefined4 DAT_802c29ac;
extern undefined4 DAT_802c29b0;
extern undefined4 DAT_802c29b4;
extern undefined4 DAT_802c29b8;
extern undefined4 DAT_802c29bc;
extern undefined4 DAT_802c29c0;
extern undefined4 DAT_802c29c4;
extern undefined4 DAT_802c29c8;
extern undefined4 DAT_802c29cc;
extern undefined4 DAT_802c29d0;
extern undefined4 DAT_802c29d4;
extern undefined4 DAT_802c29d8;
extern undefined4 DAT_802c29dc;
extern undefined4 DAT_802c29e0;
extern undefined4 DAT_802c29e4;
extern undefined4 DAT_802c29e8;
extern undefined4 DAT_802c29ec;
extern undefined4 DAT_803213b8;
extern undefined4 DAT_803213bc;
extern undefined4 DAT_803213c0;
extern undefined4 DAT_803213c4;
extern undefined4 DAT_803213c8;
extern undefined4 DAT_803213c9;
extern short DAT_803214f0;
extern undefined4 DAT_80321538;
extern undefined4 DAT_803215c8;
extern undefined4 DAT_803215c9;
extern undefined4 DAT_803215ca;
extern undefined4 DAT_80321618;
extern undefined4 DAT_80321678;
extern int DAT_80321688;
extern undefined4 DAT_80321698;
extern int DAT_803216a8;
extern undefined4 DAT_803ad318;
extern undefined4 DAT_803ad31c;
extern undefined4 DAT_803ad320;
extern undefined4 DAT_803ad324;
extern undefined4 DAT_803ad328;
extern undefined4 DAT_803ad32c;
extern undefined4 DAT_803ad330;
extern undefined4 DAT_803ad334;
extern undefined4 DAT_803ad338;
extern undefined4 DAT_803dc070;
extern undefined4 DAT_803dc9b8;
extern undefined4 DAT_803dc9c0;
extern undefined4 DAT_803dc9cc;
extern undefined4 DAT_803dc9d8;
extern undefined4 DAT_803dc9e0;
extern undefined4 DAT_803dc9e8;
extern undefined4 DAT_803dc9f0;
extern undefined4* DAT_803dd6d0;
extern undefined4* DAT_803dd6d4;
extern undefined4* DAT_803dd6d8;
extern undefined4* DAT_803dd6f4;
extern undefined4* DAT_803dd6f8;
extern undefined4* DAT_803dd6fc;
extern undefined4* DAT_803dd708;
extern undefined4* DAT_803dd718;
extern undefined4* DAT_803dd72c;
extern undefined4* DAT_803de720;
extern undefined4* DAT_803de724;
extern undefined4 DAT_803de728;
extern undefined4* DAT_803de730;
extern undefined4* DAT_803de734;
extern undefined4 DAT_803e3e38;
extern undefined4 DAT_cc008000;
extern f64 DOUBLE_803e3e28;
extern f64 DOUBLE_803e3e50;
extern f64 DOUBLE_803e3e88;
extern f64 DOUBLE_803e3eb0;
extern f64 DOUBLE_803e3ed0;
extern f64 DOUBLE_803e3f18;
extern f64 DOUBLE_803e3fb0;
extern f64 DOUBLE_803e4030;
extern f64 DOUBLE_803e4068;
extern f64 DOUBLE_803e4078;
extern f64 DOUBLE_803e40d0;
extern f32 FLOAT_803dc074;
extern f32 FLOAT_803dc9c8;
extern f32 FLOAT_803dc9d0;
extern f32 FLOAT_803dc9d4;
extern f32 FLOAT_803dda58;
extern f32 FLOAT_803dda5c;
extern f32 FLOAT_803e3e30;
extern f32 FLOAT_803e3e34;
extern f32 FLOAT_803e3e3c;
extern f32 FLOAT_803e3e40;
extern f32 FLOAT_803e3e44;
extern f32 FLOAT_803e3e48;
extern f32 FLOAT_803e3e5c;
extern f32 FLOAT_803e3e60;
extern f32 FLOAT_803e3e64;
extern f32 FLOAT_803e3e68;
extern f32 FLOAT_803e3e6c;
extern f32 FLOAT_803e3e70;
extern f32 FLOAT_803e3e74;
extern f32 FLOAT_803e3e78;
extern f32 FLOAT_803e3e7c;
extern f32 FLOAT_803e3e94;
extern f32 FLOAT_803e3e98;
extern f32 FLOAT_803e3e9c;
extern f32 FLOAT_803e3ea0;
extern f32 FLOAT_803e3ea4;
extern f32 FLOAT_803e3ea8;
extern f32 FLOAT_803e3ebc;
extern f32 FLOAT_803e3ec0;
extern f32 FLOAT_803e3ec4;
extern f32 FLOAT_803e3ec8;
extern f32 FLOAT_803e3ed8;
extern f32 FLOAT_803e3edc;
extern f32 FLOAT_803e3ee0;
extern f32 FLOAT_803e3ee4;
extern f32 FLOAT_803e3ee8;
extern f32 FLOAT_803e3eec;
extern f32 FLOAT_803e3ef0;
extern f32 FLOAT_803e3ef4;
extern f32 FLOAT_803e3ef8;
extern f32 FLOAT_803e3efc;
extern f32 FLOAT_803e3f00;
extern f32 FLOAT_803e3f04;
extern f32 FLOAT_803e3f08;
extern f32 FLOAT_803e3f0c;
extern f32 FLOAT_803e3f10;
extern f32 FLOAT_803e3f14;
extern f32 FLOAT_803e3f20;
extern f32 FLOAT_803e3f24;
extern f32 FLOAT_803e3f28;
extern f32 FLOAT_803e3f2c;
extern f32 FLOAT_803e3f30;
extern f32 FLOAT_803e3f34;
extern f32 FLOAT_803e3f38;
extern f32 FLOAT_803e3f3c;
extern f32 FLOAT_803e3f40;
extern f32 FLOAT_803e3f44;
extern f32 FLOAT_803e3f48;
extern f32 FLOAT_803e3f4c;
extern f32 FLOAT_803e3f50;
extern f32 FLOAT_803e3f54;
extern f32 FLOAT_803e3f58;
extern f32 FLOAT_803e3f5c;
extern f32 FLOAT_803e3f60;
extern f32 FLOAT_803e3f64;
extern f32 FLOAT_803e3f68;
extern f32 FLOAT_803e3f6c;
extern f32 FLOAT_803e3f70;
extern f32 FLOAT_803e3f74;
extern f32 FLOAT_803e3f78;
extern f32 FLOAT_803e3f7c;
extern f32 FLOAT_803e3f80;
extern f32 FLOAT_803e3f84;
extern f32 FLOAT_803e3f88;
extern f32 FLOAT_803e3f8c;
extern f32 FLOAT_803e3f90;
extern f32 FLOAT_803e3f94;
extern f32 FLOAT_803e3f98;
extern f32 FLOAT_803e3fa4;
extern f32 FLOAT_803e3fa8;
extern f32 FLOAT_803e3fb8;
extern f32 FLOAT_803e3fbc;
extern f32 FLOAT_803e3fc0;
extern f32 FLOAT_803e3fc4;
extern f32 FLOAT_803e3fc8;
extern f32 FLOAT_803e3fcc;
extern f32 FLOAT_803e3fd8;
extern f32 FLOAT_803e3fe8;
extern f32 FLOAT_803e3ff0;
extern f32 FLOAT_803e3ff4;
extern f32 FLOAT_803e3ff8;
extern f32 FLOAT_803e3ffc;
extern f32 FLOAT_803e4000;
extern f32 FLOAT_803e4004;
extern f32 FLOAT_803e4010;
extern f32 FLOAT_803e4014;
extern f32 FLOAT_803e4018;
extern f32 FLOAT_803e4024;
extern f32 FLOAT_803e4028;
extern f32 FLOAT_803e402c;
extern f32 FLOAT_803e4038;
extern f32 FLOAT_803e4040;
extern f32 FLOAT_803e4044;
extern f32 FLOAT_803e4048;
extern f32 FLOAT_803e404c;
extern f32 FLOAT_803e4050;
extern f32 FLOAT_803e4054;
extern f32 FLOAT_803e4058;
extern f32 FLOAT_803e405c;
extern f32 FLOAT_803e4060;
extern f32 FLOAT_803e4064;
extern f32 FLOAT_803e4070;
extern f32 FLOAT_803e4074;
extern f32 FLOAT_803e4080;
extern f32 FLOAT_803e4084;
extern f32 FLOAT_803e4098;
extern f32 FLOAT_803e409c;
extern f32 FLOAT_803e40a0;
extern f32 FLOAT_803e40a4;
extern f32 FLOAT_803e40a8;
extern f32 FLOAT_803e40ac;
extern f32 FLOAT_803e40b0;
extern f32 FLOAT_803e40b8;
extern f32 FLOAT_803e40bc;
extern f32 FLOAT_803e40c0;
extern f32 FLOAT_803e40c4;
extern f32 FLOAT_803e40c8;
extern f32 FLOAT_803e40e8;
extern f32 FLOAT_803e40ec;
extern void* PTR_DAT_803211ec;

/* Local declarations keep imported functions visible within the TU. */
void FUN_8016b550(uint param_1,int param_2);
void FUN_8016b6ec(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 int param_9,int param_10);
void FUN_8016b758(int param_1);
void FUN_8016b78c(uint param_1);
void FUN_8016ba98(undefined2 *param_1);
void FUN_8016bbd0(int param_1);
void FUN_8016bc1c(int param_1);
void FUN_8016bc8c(undefined2 *param_1);
void FUN_8016bd54(int param_1);
void FUN_8016bd78(int param_1);
void FUN_8016bdb0(short *param_1,int param_2,int param_3);
void FUN_8016be5c(int param_1);
void FUN_8016bea0(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 short *param_9);
void FUN_8016bf80(int param_1,int param_2);
void FUN_8016bfd0(int param_1);
void FUN_8016c004(void);
void FUN_8016c324(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 int param_9,int param_10);
void FUN_8016c3e8(ushort *param_1);
void FUN_8016c590(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 int param_9);
void FUN_8016c7e4(int param_1,int param_2);
void FUN_8016c958(int param_1);
void FUN_8016cc04(int param_1);
void FUN_8016cc7c(void);
void FUN_8016ce50(int param_1);
void FUN_8016d08c(int param_1,int param_2);
undefined4 FUN_8016d1f4(int param_1,undefined4 param_2,int param_3);
void FUN_8016d31c(int param_1);
void FUN_8016d394(int param_1,int param_2);
void FUN_8016de98(int param_1,undefined param_2,undefined param_3);
void FUN_8016dea8(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 undefined4 *param_9);
void FUN_8016e0a0(void);
void FUN_8016e1d8(void);
void FUN_8016e48c(void);
void FUN_8016eb80(uint param_1,char param_2,char param_3);
void FUN_8016ecc8(int param_1);
void FUN_8016ed7c(uint param_1);
void FUN_8016efa0(int param_1);
void FUN_8016effc(int param_1);
void FUN_8016f030(int param_1);
void FUN_8016f0a8(undefined8 param_1,undefined8 param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 int param_9);
void FUN_8016f39c(int param_1);
void FUN_8016f454(void);
void FUN_8016f4d4(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8);
undefined FUN_8016f618(int param_1);
undefined4 FUN_8016f624(int param_1,undefined4 param_2,int param_3);
void FUN_8016f70c(int param_1,int param_2,int param_3);
void FUN_8016fa08(int param_1);
void FUN_8016fa68(void);
void FUN_8016fca0(int param_1);
void FUN_8016fde0(undefined8 param_1,double param_2,double param_3,double param_4,undefined8 param_5
                 ,undefined8 param_6,undefined8 param_7,undefined8 param_8,short *param_9);
void FUN_8017028c(void);
void FUN_801704f0(int param_1);
void FUN_80170518(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 ushort *param_9);
void FUN_801706d4(int param_1,int param_2);
int FUN_80170780(double param_1,double param_2,double param_3,undefined8 param_4,undefined8 param_5,
                undefined8 param_6,undefined8 param_7,undefined8 param_8,int param_9);
void FUN_8017082c(void);
void FUN_80170f38(int param_1);
void FUN_80170f9c(void);
void FUN_8017141c(void);
void FUN_80171744(int param_1);
void FUN_801717cc(int param_1);
void FUN_801718b8(int param_1);
void FUN_8017191c(void);
void FUN_801719c8(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 undefined2 *param_9);
void FUN_80171d7c(undefined2 *param_1,int param_2);
void FUN_80171ea4(int param_1);
void FUN_80171ed0(ushort *param_1,int param_2);
void FUN_80172058(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 int param_9);
void FUN_8017212c(int param_1);
void FUN_80172150(int param_1,int param_2);
void FUN_801721c0(double param_1,double param_2,double param_3,int param_4);
undefined4 FUN_80172254(int param_1);
void FUN_801722a4(int param_1,int param_2);
void FUN_80172308(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 uint param_9);

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016B550
 * EN v1.0 Size: 412b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016b550(uint param_1,int param_2)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016B6EC
 * EN v1.0 Size: 108b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016b6ec(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 int param_9,int param_10)

{
  int iVar1;
  int *piVar2;
  
  piVar2 = *(int **)(param_9 + 0xb8);
  iVar1 = *piVar2;
  if ((iVar1 != 0) && (param_10 == 0)) {
    FUN_8002cc9c(param_1,param_2,param_3,param_4,param_5,param_6,param_7,param_8,iVar1);
    *piVar2 = 0;
  }
  (**(code **)(*DAT_803dd6fc + 0x18))(param_9);
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016B758
 * EN v1.0 Size: 52b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016b758(int param_1)

{
  char in_r8;
  
  if (in_r8 != '\0') {
    FUN_8003b9ec(param_1);
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016B78C
 * EN v1.0 Size: 780b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016b78c(uint param_1)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016BA98
 * EN v1.0 Size: 312b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016ba98(undefined2 *param_1)

{
  float fVar1;
  uint uVar2;
  undefined2 *puVar3;
  int iVar4;
  int *piVar5;
  double dVar6;
  double dVar7;
  double dVar8;
  undefined8 in_f4;
  undefined8 in_f5;
  undefined8 in_f6;
  undefined8 in_f7;
  undefined8 in_f8;
  float local_18 [4];
  
  piVar5 = *(int **)(param_1 + 0x5c);
  FUN_80035ff8((int)param_1);
  *(undefined *)(param_1 + 0x1b) = 0xff;
  fVar1 = FLOAT_803e3e60;
  *(float *)(param_1 + 0x12) = FLOAT_803e3e60;
  *(float *)(param_1 + 0x14) = FLOAT_803e3e6c;
  *(float *)(param_1 + 0x16) = fVar1;
  param_1[1] = 0xc000;
  *param_1 = 0;
  param_1[2] = 0;
  dVar7 = (double)*(float *)(param_1 + 8);
  dVar8 = (double)*(float *)(param_1 + 10);
  FUN_80065800((double)*(float *)(param_1 + 6),dVar7,dVar8,param_1,local_18,0);
  dVar6 = (double)*(float *)(param_1 + 8);
  piVar5[1] = (int)(float)(dVar6 - (double)local_18[0]);
  uVar2 = FUN_8002e144();
  if ((uVar2 & 0xff) == 0) {
    *piVar5 = 0;
  }
  else {
    puVar3 = FUN_8002becc(0x20,0xc);
    *(undefined4 *)(puVar3 + 4) = *(undefined4 *)(param_1 + 6);
    *(undefined4 *)(puVar3 + 6) = *(undefined4 *)(param_1 + 8);
    *(undefined4 *)(puVar3 + 8) = *(undefined4 *)(param_1 + 10);
    *(undefined *)(puVar3 + 2) = 1;
    *(undefined *)((int)puVar3 + 5) = 1;
    *(undefined *)(puVar3 + 3) = 0xff;
    *(undefined *)((int)puVar3 + 7) = 0xff;
    iVar4 = FUN_8002b678(dVar6,dVar7,dVar8,in_f4,in_f5,in_f6,in_f7,in_f8,(int)param_1,puVar3);
    *piVar5 = iVar4;
    *(undefined2 **)(*piVar5 + 0xc4) = param_1;
  }
  iVar4 = FUN_80013ee8(0x5b);
  piVar5[2] = iVar4;
  *(undefined *)(piVar5 + 3) = 0;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016BBD0
 * EN v1.0 Size: 76b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016bbd0(int param_1)

{
  char in_r8;
  
  if ((in_r8 != '\0') && (*(int *)(*(int *)(param_1 + 100) + 0xc) != 0)) {
    FUN_80062614();
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016BC1C
 * EN v1.0 Size: 112b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016bc1c(int param_1)

{
  float fVar1;
  float fVar2;
  
  fVar2 = FLOAT_803e3e70;
  fVar1 = FLOAT_803e3e70 -
          (*(float *)(*(int *)(param_1 + 0xc4) + 0x10) - *(float *)(param_1 + 0x10)) /
          **(float **)(param_1 + 0xb8);
  **(float **)(param_1 + 100) = FLOAT_803e3e74 * fVar1 + FLOAT_803e3e70;
  fVar1 = fVar1 * FLOAT_803e3e78;
  if (fVar2 < fVar1) {
    fVar1 = fVar2;
  }
  *(short *)(*(int *)(param_1 + 100) + 0x36) = (short)(int)(FLOAT_803e3e7c * fVar1);
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016BC8C
 * EN v1.0 Size: 200b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016bc8c(undefined2 *param_1)

{
  float *pfVar1;
  float local_18 [4];
  
  pfVar1 = *(float **)(param_1 + 0x5c);
  FUN_80065800((double)*(float *)(param_1 + 6),(double)*(float *)(param_1 + 8),
               (double)*(float *)(param_1 + 10),param_1,local_18,0);
  FUN_80035ff8((int)param_1);
  *(undefined *)(param_1 + 0x1b) = 0xff;
  param_1[1] = 0x4000;
  *param_1 = 0;
  param_1[2] = 0;
  *(uint *)(*(int *)(param_1 + 0x32) + 0x30) = *(uint *)(*(int *)(param_1 + 0x32) + 0x30) | 0x10000;
  *pfVar1 = local_18[0];
  *(float *)(param_1 + 8) = *(float *)(param_1 + 8) - local_18[0];
  *(undefined2 *)(*(int *)(param_1 + 0x32) + 0x36) = 0;
  **(float **)(param_1 + 0x32) = FLOAT_803e3e70;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016BD54
 * EN v1.0 Size: 36b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016bd54(int param_1)

{
  FUN_8003709c(param_1,7);
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016BD78
 * EN v1.0 Size: 56b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016bd78(int param_1)

{
  char in_r8;
  
  if (in_r8 != '\0') {
    FUN_8003b9ec(param_1);
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016BDB0
 * EN v1.0 Size: 172b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016bdb0(short *param_1,int param_2,int param_3)

{
  undefined *puVar1;
  
  *param_1 = -*(short *)(param_2 + 0x1c);
  param_1[1] = -*(short *)(param_2 + 0x1e);
  param_1[2] = -*(short *)(param_2 + 0x20);
  puVar1 = *(undefined **)(param_1 + 0x5c);
  *puVar1 = *(undefined *)(param_2 + 0x19);
  *(float *)(puVar1 + 4) =
       (float)((double)CONCAT44(0x43300000,(uint)*(byte *)(param_2 + 0x1a)) - DOUBLE_803e3e88);
  puVar1[1] = 0;
  if (param_3 == 0) {
    FUN_800372f8((int)param_1,7);
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016BE5C
 * EN v1.0 Size: 68b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016be5c(int param_1)

{
  char in_r8;
  
  if ((in_r8 != '\0') && (*(int *)(param_1 + 0xf4) == 0)) {
    FUN_8003b9ec(param_1);
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016BEA0
 * EN v1.0 Size: 224b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016bea0(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 short *param_9)

{
  float *pfVar1;
  
  pfVar1 = *(float **)(param_9 + 0x5c);
  *pfVar1 = *pfVar1 - FLOAT_803dc074;
  if ((double)FLOAT_803e3e94 < (double)*pfVar1) {
    *param_9 = *param_9 + (short)(int)(FLOAT_803e3e98 * FLOAT_803dc074);
    param_9[2] = param_9[2] + (short)(int)(FLOAT_803e3e9c * FLOAT_803dc074);
    if (FLOAT_803e3ea0 < *pfVar1) {
      *(undefined *)(param_9 + 0x1b) = 0xff;
    }
    else {
      *(char *)(param_9 + 0x1b) = (char)(int)(FLOAT_803e3ea4 * *pfVar1 * FLOAT_803e3ea8);
    }
  }
  else {
    FUN_8002cc9c((double)*pfVar1,param_2,param_3,param_4,param_5,param_6,param_7,param_8,
                 (int)param_9);
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016BF80
 * EN v1.0 Size: 80b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016bf80(int param_1,int param_2)

{
  **(float **)(param_1 + 0xb8) =
       (float)((double)CONCAT44(0x43300000,(int)*(short *)(param_2 + 0x1a) ^ 0x80000000) -
              DOUBLE_803e3eb0);
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016BFD0
 * EN v1.0 Size: 52b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016bfd0(int param_1)

{
  char in_r8;
  
  if (in_r8 != '\0') {
    FUN_8003b9ec(param_1);
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016C004
 * EN v1.0 Size: 800b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016c004(void)

{
  byte bVar1;
  short sVar2;
  uint uVar3;
  byte bVar4;
  int iVar5;
  uint uVar6;
  undefined4 *puVar7;
  int iVar8;
  char unaff_r27;
  int iVar9;
  int iVar10;
  double dVar11;
  undefined auStack_28 [4];
  uint local_24 [9];
  
  iVar5 = FUN_80286838();
  iVar10 = *(int *)(iVar5 + 0x4c);
  if (((((int)*(short *)(iVar10 + 0x20) == 0xffffffff) ||
       (uVar6 = FUN_80020078((int)*(short *)(iVar10 + 0x20)), uVar6 != 0)) &&
      (((int)*(short *)(iVar10 + 0x1e) == 0xffffffff ||
       (uVar6 = FUN_80020078((int)*(short *)(iVar10 + 0x1e)), uVar6 == 0)))) &&
     (puVar7 = FUN_80037048(3,(int *)local_24), 0 < (int)local_24[0])) {
    iVar9 = CONCAT22(*(undefined2 *)(iVar10 + 0x1c),*(undefined2 *)(iVar10 + 0x1a));
    for (uVar6 = 0; (int)(uVar6 & 0xffff) < (int)local_24[0]; uVar6 = uVar6 + 1) {
      uVar3 = uVar6 & 0xffff;
      iVar8 = *(int *)(puVar7[uVar3] + 0x4c);
      if (iVar8 == 0) {
        unaff_r27 = '\x01';
      }
      else {
        unaff_r27 = '\0';
        if ((iVar9 == *(int *)(iVar8 + 0x14)) || (iVar9 == 0)) {
          unaff_r27 = '\x01';
        }
      }
      if (unaff_r27 != '\0') {
        unaff_r27 = '\0';
        dVar11 = FUN_80021794((float *)(iVar5 + 0x18),(float *)(puVar7[uVar3] + 0x18));
        if (dVar11 < (double)FLOAT_803e3ebc) {
          if (*(int *)(iVar5 + 0xf4) == 0) {
            uVar6 = FUN_80022264(1,100);
            if ((int)uVar6 <= (int)*(char *)(iVar10 + 0x19)) {
              bVar1 = *(byte *)(iVar10 + 0x18);
              bVar4 = (char)(bVar1 & 0x30) >> 4;
              if (bVar4 == 1) {
                iVar8 = (**(code **)(*DAT_803dd6d8 + 0x24))(auStack_28);
                if (iVar8 == 0) {
                  bVar1 = *(byte *)(iVar10 + 0x18);
                  iVar8 = puVar7[uVar3];
                  if ((int)*(short *)(iVar10 + 0x1e) != 0xffffffff) {
                    FUN_800201ac((int)*(short *)(iVar10 + 0x1e),1);
                  }
                  sVar2 = *(short *)(iVar8 + 0x46);
                  if (sVar2 < 0x5b7) {
                    if ((sVar2 == 0x13a) || ((sVar2 < 0x13a && (sVar2 == 0x11)))) {
LAB_8016c228:
                      FUN_80150950(iVar8,bVar1 & 0xf);
                    }
                  }
                  else if ((sVar2 == 0x5e1) || ((sVar2 < 0x5e1 && (sVar2 < 0x5ba))))
                  goto LAB_8016c228;
                }
              }
              else if (bVar4 == 0) {
                iVar8 = puVar7[uVar3];
                if ((int)*(short *)(iVar10 + 0x1e) != 0xffffffff) {
                  FUN_800201ac((int)*(short *)(iVar10 + 0x1e),1);
                }
                sVar2 = *(short *)(iVar8 + 0x46);
                if (sVar2 < 0x5b7) {
                  if ((sVar2 == 0x13a) || ((sVar2 < 0x13a && (sVar2 == 0x11)))) {
LAB_8016c1a0:
                    FUN_80150950(iVar8,bVar1 & 0xf);
                  }
                }
                else if ((sVar2 == 0x5e1) || ((sVar2 < 0x5e1 && (sVar2 < 0x5ba))))
                goto LAB_8016c1a0;
              }
              else if ((bVar4 < 3) &&
                      (iVar8 = (**(code **)(*DAT_803dd6d8 + 0x24))(auStack_28), iVar8 != 0)) {
                bVar1 = *(byte *)(iVar10 + 0x18);
                iVar8 = puVar7[uVar3];
                if ((int)*(short *)(iVar10 + 0x1e) != 0xffffffff) {
                  FUN_800201ac((int)*(short *)(iVar10 + 0x1e),1);
                }
                sVar2 = *(short *)(iVar8 + 0x46);
                if (sVar2 < 0x5b7) {
                  if ((sVar2 == 0x13a) || ((sVar2 < 0x13a && (sVar2 == 0x11)))) {
LAB_8016c2b0:
                    FUN_80150950(iVar8,bVar1 & 0xf);
                  }
                }
                else if ((sVar2 == 0x5e1) || ((sVar2 < 0x5e1 && (sVar2 < 0x5ba))))
                goto LAB_8016c2b0;
              }
            }
            *(undefined4 *)(iVar5 + 0xf4) = 1;
          }
          unaff_r27 = '\x01';
        }
        uVar6 = local_24[0] & 0xffff;
      }
    }
    if (unaff_r27 == '\0') {
      *(undefined4 *)(iVar5 + 0xf4) = 0;
    }
  }
  FUN_80286884();
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016C324
 * EN v1.0 Size: 196b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016c324(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 int param_9,int param_10)

{
  undefined8 uVar1;
  
  (**(code **)(*DAT_803dd6d4 + 0x24))(*(undefined4 *)(param_9 + 0xb8));
  (**(code **)(*DAT_803dd6f4 + 8))(param_9,0xffff,0,0,0);
  FUN_8000da9c(param_9);
  uVar1 = FUN_8000b7dc(param_9,0x7f);
  if ((*(short *)(param_9 + 0x46) == 0x774) && (*(char *)(param_9 + 0xeb) != '\0')) {
    FUN_8002cc9c(uVar1,param_2,param_3,param_4,param_5,param_6,param_7,param_8,
                 *(int *)(param_9 + 200));
    FUN_80037da8(param_9,*(int *)(param_9 + 200));
  }
  if (param_10 != 0) {
    FUN_80080484();
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016C3E8
 * EN v1.0 Size: 424b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016c3e8(ushort *param_1)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016C590
 * EN v1.0 Size: 596b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016c590(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 int param_9)

{
  byte bVar1;
  int *piVar2;
  uint uVar3;
  undefined2 *puVar4;
  int iVar5;
  undefined4 uVar6;
  int iVar7;
  undefined4 uVar8;
  undefined4 in_r8;
  undefined4 in_r9;
  undefined4 in_r10;
  int iVar9;
  int iVar10;
  int iVar11;
  undefined8 extraout_f1;
  undefined8 uVar12;
  int local_18;
  int local_14;
  
  iVar10 = *(int *)(param_9 + 0xb8);
  if ((*(int *)(param_9 + 0x4c) != 0) && (*(short *)(*(int *)(param_9 + 0x4c) + 0x18) != -1)) {
    local_14 = (**(code **)(*DAT_803dd6d4 + 0x14))((double)FLOAT_803dc074);
    uVar12 = extraout_f1;
    if ((local_14 != 0) && (*(short *)(param_9 + 0xb4) == -2)) {
      iVar9 = (int)*(char *)(iVar10 + 0x57);
      iVar11 = 0;
      piVar2 = (int *)FUN_8002e1f4(&local_14,&local_18);
      iVar7 = 0;
      for (local_14 = 0; local_14 < local_18; local_14 = local_14 + 1) {
        iVar5 = *piVar2;
        if (*(short *)(iVar5 + 0xb4) == iVar9) {
          iVar11 = iVar5;
        }
        if (((*(short *)(iVar5 + 0xb4) == -2) && (*(short *)(iVar5 + 0x44) == 0x10)) &&
           (iVar10 = *(int *)(iVar5 + 0xb8), iVar9 == *(char *)(iVar10 + 0x57))) {
          iVar7 = iVar7 + 1;
        }
        piVar2 = piVar2 + 1;
      }
      if (((iVar7 < 2) && (iVar11 != 0)) && (*(short *)(iVar11 + 0xb4) != -1)) {
        *(undefined2 *)(iVar11 + 0xb4) = 0xffff;
        uVar12 = (**(code **)(*DAT_803dd6d4 + 0x4c))(iVar9);
      }
      *(undefined2 *)(param_9 + 0xb4) = 0xffff;
      *(ushort *)(param_9 + 0xb0) = *(ushort *)(param_9 + 0xb0) | 0x8000;
      *(ushort *)(param_9 + 6) = *(ushort *)(param_9 + 6) | 0x4000;
    }
    if (*(short *)(param_9 + 0x46) == 0x774) {
      for (iVar11 = 0; iVar11 < (int)(uint)*(byte *)(iVar10 + 0x8b); iVar11 = iVar11 + 1) {
        bVar1 = *(byte *)(iVar10 + iVar11 + 0x81);
        if (bVar1 == 0xb) {
          if (*(char *)(param_9 + 0xeb) != '\0') {
            FUN_8002cc9c(uVar12,param_2,param_3,param_4,param_5,param_6,param_7,param_8,
                         *(int *)(param_9 + 200));
            uVar12 = FUN_80037da8(param_9,*(int *)(param_9 + 200));
          }
        }
        else if (((bVar1 < 0xb) && (9 < bVar1)) && (uVar3 = FUN_8002e144(), (uVar3 & 0xff) != 0)) {
          puVar4 = FUN_8002becc(0x18,0x69);
          uVar6 = 0xffffffff;
          uVar8 = 0;
          iVar7 = FUN_8002e088(uVar12,param_2,param_3,param_4,param_5,param_6,param_7,param_8,puVar4
                               ,4,0xff,0xffffffff,(uint *)0x0,in_r8,in_r9,in_r10);
          FUN_80037e24(param_9,iVar7,0);
          FUN_8003042c((double)FLOAT_803e3ec4,param_2,param_3,param_4,param_5,param_6,param_7,
                       param_8,iVar7,0,0,uVar6,uVar8,in_r8,in_r9,in_r10);
          param_2 = (double)FLOAT_803dc074;
          uVar12 = FUN_8002fb40((double)FLOAT_803e3ec0,param_2);
        }
      }
    }
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016C7E4
 * EN v1.0 Size: 372b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016c7e4(int param_1,int param_2)

{
  int iVar1;
  int iVar2;
  
  FUN_8002b9a0(param_1,'d');
  iVar2 = *(int *)(param_1 + 0xb8);
  *(undefined2 *)(iVar2 + 0x6a) = *(undefined2 *)(param_2 + 0x1a);
  *(undefined2 *)(iVar2 + 0x6e) = 0xffff;
  *(float *)(iVar2 + 0x24) =
       FLOAT_803e3ec0 /
       (FLOAT_803e3ec0 +
       (float)((double)CONCAT44(0x43300000,(uint)*(byte *)(param_2 + 0x24)) - DOUBLE_803e3ed0));
  *(undefined4 *)(iVar2 + 0x28) = 0xffffffff;
  *(undefined4 *)(iVar2 + 0x98) = 0;
  *(undefined4 *)(iVar2 + 0x94) = 0;
  *(undefined2 *)(iVar2 + 0x116) = 0;
  *(undefined2 *)(iVar2 + 0x114) = 0;
  *(undefined4 *)(iVar2 + 0xe8) = 0;
  iVar1 = *(int *)(param_1 + 0xf4);
  if ((iVar1 == 0) && (*(short *)(param_2 + 0x18) != 1)) {
    (**(code **)(*DAT_803dd6d4 + 0x1c))(iVar2,param_2);
    *(int *)(param_1 + 0xf4) = *(short *)(param_2 + 0x18) + 1;
  }
  else if ((iVar1 != 0) && ((int)*(short *)(param_2 + 0x18) != iVar1 + -1)) {
    (**(code **)(*DAT_803dd6d4 + 0x24))(iVar2);
    if (*(short *)(param_2 + 0x18) != -1) {
      (**(code **)(*DAT_803dd6d4 + 0x1c))(iVar2,param_2);
    }
    *(int *)(param_1 + 0xf4) = *(short *)(param_2 + 0x18) + 1;
  }
  if (*(int *)(param_1 + 100) != 0) {
    *(undefined *)(*(int *)(param_1 + 100) + 0x3a) = 100;
    *(undefined *)(*(int *)(param_1 + 100) + 0x3b) = 0x96;
  }
  FUN_8002a84c(param_1,0xff);
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016C958
 * EN v1.0 Size: 684b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016c958(int param_1)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016CC04
 * EN v1.0 Size: 120b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016cc04(int param_1)

{
  (**(code **)(*DAT_803dd6d4 + 0x24))(*(undefined4 *)(param_1 + 0xb8));
  (**(code **)(*DAT_803dd6f4 + 8))(param_1,0xffff,0,0,0);
  FUN_8000b7dc(param_1,0x7f);
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016CC7C
 * EN v1.0 Size: 468b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016cc7c(void)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016CE50
 * EN v1.0 Size: 572b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016ce50(int param_1)

{
  byte bVar1;
  int *piVar2;
  int iVar3;
  int iVar4;
  int iVar5;
  int iVar6;
  int local_38;
  int local_34;
  undefined auStack_30 [12];
  undefined4 local_24;
  undefined4 local_20;
  undefined4 local_1c;
  
  iVar6 = *(int *)(param_1 + 0xb8);
  if ((*(int *)(param_1 + 0x4c) != 0) && (*(short *)(*(int *)(param_1 + 0x4c) + 0x18) != -1)) {
    for (local_38 = 0; local_38 < (int)(uint)*(byte *)(iVar6 + 0x8b); local_38 = local_38 + 1) {
      bVar1 = *(byte *)(iVar6 + local_38 + 0x81);
      if (bVar1 == 3) {
        *(uint *)(param_1 + 0xf8) = *(uint *)(param_1 + 0xf8) ^ 4;
      }
      else if (bVar1 < 3) {
        if (bVar1 == 1) {
          *(uint *)(param_1 + 0xf8) = *(uint *)(param_1 + 0xf8) ^ 1;
        }
        else if (bVar1 != 0) {
          *(uint *)(param_1 + 0xf8) = *(uint *)(param_1 + 0xf8) ^ 2;
        }
      }
      else if (bVar1 < 5) {
        local_24 = *(undefined4 *)(param_1 + 0xc);
        local_20 = *(undefined4 *)(param_1 + 0x10);
        local_1c = *(undefined4 *)(param_1 + 0x14);
        iVar4 = 3;
        do {
          (**(code **)(*DAT_803dd708 + 8))(param_1,0x7fe,auStack_30,0x200001,0xffffffff,0);
          iVar4 = iVar4 + -1;
        } while (iVar4 != 0);
      }
    }
    local_38 = (**(code **)(*DAT_803dd6d4 + 0x14))((double)FLOAT_803dc074,param_1);
    if ((local_38 != 0) && (*(short *)(param_1 + 0xb4) == -2)) {
      iVar5 = (int)*(char *)(iVar6 + 0x57);
      iVar6 = 0;
      piVar2 = (int *)FUN_8002e1f4(&local_38,&local_34);
      iVar4 = 0;
      for (local_38 = 0; local_38 < local_34; local_38 = local_38 + 1) {
        iVar3 = *piVar2;
        if (*(short *)(iVar3 + 0xb4) == iVar5) {
          iVar6 = iVar3;
        }
        if (((*(short *)(iVar3 + 0xb4) == -2) && (*(short *)(iVar3 + 0x44) == 0x10)) &&
           (iVar5 == *(char *)(*(int *)(iVar3 + 0xb8) + 0x57))) {
          iVar4 = iVar4 + 1;
        }
        piVar2 = piVar2 + 1;
      }
      if (((iVar4 < 2) && (iVar6 != 0)) && (*(short *)(iVar6 + 0xb4) != -1)) {
        *(undefined2 *)(iVar6 + 0xb4) = 0xffff;
        (**(code **)(*DAT_803dd6d4 + 0x4c))(iVar5);
      }
      *(undefined2 *)(param_1 + 0xb4) = 0xffff;
    }
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016D08C
 * EN v1.0 Size: 360b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016d08c(int param_1,int param_2)

{
  int iVar1;
  int iVar2;
  
  FUN_8002b9a0(param_1,'d');
  iVar2 = *(int *)(param_1 + 0xb8);
  *(undefined2 *)(iVar2 + 0x6a) = *(undefined2 *)(param_2 + 0x1a);
  *(undefined2 *)(iVar2 + 0x6e) = 0xffff;
  *(float *)(iVar2 + 0x24) =
       FLOAT_803e3f08 /
       (FLOAT_803e3f08 +
       (float)((double)CONCAT44(0x43300000,(uint)*(byte *)(param_2 + 0x24)) - DOUBLE_803e3f18));
  *(undefined4 *)(iVar2 + 0x28) = 0xffffffff;
  *(undefined4 *)(iVar2 + 0x98) = 0;
  *(undefined4 *)(iVar2 + 0x94) = 0;
  *(undefined2 *)(iVar2 + 0x116) = 0;
  *(undefined2 *)(iVar2 + 0x114) = 0;
  *(undefined4 *)(param_1 + 0xf8) = 0;
  iVar1 = *(int *)(param_1 + 0xf4);
  if ((iVar1 == 0) && (*(short *)(param_2 + 0x18) != 1)) {
    (**(code **)(*DAT_803dd6d4 + 0x1c))(iVar2,param_2);
    *(int *)(param_1 + 0xf4) = *(short *)(param_2 + 0x18) + 1;
  }
  else if ((iVar1 != 0) && ((int)*(short *)(param_2 + 0x18) != iVar1 + -1)) {
    (**(code **)(*DAT_803dd6d4 + 0x24))(iVar2);
    if (*(short *)(param_2 + 0x18) != -1) {
      (**(code **)(*DAT_803dd6d4 + 0x1c))(iVar2,param_2);
    }
    *(int *)(param_1 + 0xf4) = *(short *)(param_2 + 0x18) + 1;
  }
  if (*(int *)(param_1 + 100) != 0) {
    *(undefined *)(*(int *)(param_1 + 100) + 0x3a) = 100;
    *(undefined *)(*(int *)(param_1 + 100) + 0x3b) = 0x96;
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016D1F4
 * EN v1.0 Size: 296b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
undefined4 FUN_8016d1f4(int param_1,undefined4 param_2,int param_3)

{
  byte bVar1;
  int iVar2;
  byte *pbVar3;
  
  pbVar3 = *(byte **)(param_1 + 0xb8);
  if ((char)*pbVar3 < '\0') {
    FUN_800551f8((double)*(float *)(param_1 + 0x18),(double)*(float *)(param_1 + 0x1c),
                 (double)*(float *)(param_1 + 0x20),pbVar3[1],pbVar3[2]);
  }
  for (iVar2 = 0; iVar2 < (int)(uint)*(byte *)(param_3 + 0x8b); iVar2 = iVar2 + 1) {
    bVar1 = *(byte *)(param_3 + iVar2 + 0x81);
    if (bVar1 == 2) {
      *pbVar3 = *pbVar3 & 0x7f | 0x80;
      pbVar3[1] = 1;
      pbVar3[2] = 0;
    }
    else if (bVar1 < 2) {
      if (bVar1 == 0) {
        *pbVar3 = *pbVar3 & 0x7f;
        FUN_800551ec();
      }
      else {
        *pbVar3 = *pbVar3 & 0x7f | 0x80;
        pbVar3[1] = 0;
      }
    }
    else if (bVar1 < 4) {
      *pbVar3 = *pbVar3 & 0x7f | 0x80;
      pbVar3[2] = 1;
      pbVar3[1] = 0;
    }
  }
  return 0;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016D31C
 * EN v1.0 Size: 120b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016d31c(int param_1)

{
  byte bVar1;
  
  bVar1 = **(byte **)(param_1 + 0xb8);
  if ((char)bVar1 < '\0') {
    **(byte **)(param_1 + 0xb8) = bVar1 & 0x7f;
    FUN_800551ec();
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016D394
 * EN v1.0 Size: 2820b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016d394(int param_1,int param_2)

{
  float fVar1;
  int iVar2;
  uint uVar3;
  int iVar4;
  double dVar5;
  int local_58;
  float local_54;
  int local_50;
  undefined2 local_4c [3];
  short local_46;
  float local_44;
  undefined2 local_34;
  undefined2 local_32;
  undefined2 local_30;
  short local_2e;
  float local_2c;
  float local_28;
  float local_24;
  undefined4 local_20;
  longlong local_18;
  
  iVar4 = *(int *)(param_1 + 0xb8);
  if ((param_1 != 0) && (param_2 != 0)) {
    if (*(char *)(iVar4 + 0xba) != '\0') {
      iVar2 = FUN_80296e60(param_2);
      if (iVar2 == 0) {
        local_54 = FLOAT_803e3f24;
        fVar1 = FLOAT_803e3f28;
      }
      else {
        local_54 = FLOAT_803e3f20;
        fVar1 = FLOAT_803e3f20;
      }
      if (*(byte *)(iVar4 + 0xbb) == 7) {
        dVar5 = (double)FLOAT_803e3f2c;
        local_18 = (longlong)(int)(FLOAT_803e3f30 * fVar1);
        FUN_800979c0(dVar5,dVar5,dVar5,(double)(FLOAT_803e3f34 * local_54),param_1,7,
                     (uint)*(byte *)(iVar4 + 0xba),1,(int)(FLOAT_803e3f30 * fVar1),0,0);
      }
      else {
        dVar5 = (double)FLOAT_803e3f20;
        local_18 = (longlong)(int)(FLOAT_803e3f30 * fVar1);
        FUN_800979c0(dVar5,dVar5,dVar5,(double)(FLOAT_803e3f34 * local_54),param_1,
                     (uint)*(byte *)(iVar4 + 0xbb),(uint)*(byte *)(iVar4 + 0xba),1,
                     (int)(FLOAT_803e3f30 * fVar1),0,0);
      }
    }
    FUN_80296904(param_2,&local_50,&local_54);
    local_34 = 0;
    local_32 = 0;
    local_30 = 0;
    local_2c = FLOAT_803e3f20;
    if (local_50 == 0x87) {
      iVar4 = (int)(FLOAT_803e3f38 * (local_54 / FLOAT_803e3f30));
      local_18 = (longlong)iVar4;
      local_2e = 0x15 - (short)iVar4;
      local_28 = FLOAT_803e3f3c * (local_54 / FLOAT_803e3f40 - FLOAT_803e3f2c);
      local_34 = 0xc94;
      (**(code **)(*DAT_803dd708 + 8))(param_1,0x7b2,&local_34,2,0xffffffff,0);
      (**(code **)(*DAT_803dd708 + 8))(param_1,0x7b2,&local_34,2,0xffffffff,0);
      (**(code **)(*DAT_803dd708 + 8))(param_1,0x7b2,&local_34,2,0xffffffff,0);
      (**(code **)(*DAT_803dd708 + 8))(param_1,0x7b2,&local_34,2,0xffffffff,0);
      local_2e = 9;
      local_2c = FLOAT_803e3f48 * (local_54 / FLOAT_803e3f40) + FLOAT_803e3f44;
      local_24 = FLOAT_803e3f4c;
      local_34 = 0xc0e;
      (**(code **)(*DAT_803dd708 + 8))(param_1,0x7b3,&local_34,2,0xffffffff,0);
    }
    else if (local_50 < 0x87) {
      if (local_50 == 0x7f) {
        local_2c = FLOAT_803e3f58;
        local_2e = 10;
        local_24 = FLOAT_803e3f54;
        local_28 = FLOAT_803e3f50;
        local_34 = 0xc0e;
        (**(code **)(*DAT_803dd708 + 8))(param_1,0x7b3,&local_34,2,0xffffffff,0);
      }
      else if (local_50 < 0x7f) {
        if ((local_50 == 0x43) && (FLOAT_803e3f4c < local_54)) {
          iVar4 = (int)(FLOAT_803e3f38 * (local_54 / FLOAT_803e3f30));
          local_18 = (longlong)iVar4;
          local_2e = (short)iVar4 + 6;
          local_28 = FLOAT_803e3f3c * (local_54 / FLOAT_803e3f40 - FLOAT_803e3f2c);
          local_34 = 0xc94;
          (**(code **)(*DAT_803dd708 + 8))(param_1,0x7b4,&local_34,2,0xffffffff,0);
          (**(code **)(*DAT_803dd708 + 8))(param_1,0x7b4,&local_34,2,0xffffffff,0);
          local_2e = 9;
          local_2c = FLOAT_803e3f48 * (local_54 / FLOAT_803e3f40) + FLOAT_803e3f44;
          local_24 = FLOAT_803e3f4c;
          local_34 = 0xc0e;
          (**(code **)(*DAT_803dd708 + 8))(param_1,0x7b3,&local_34,2,0xffffffff,0);
        }
      }
      else if (local_50 == 0x85) {
        if (FLOAT_803e3f4c < local_54) {
          uVar3 = FUN_80020078(0xc55);
          if (uVar3 == 0) {
            fVar1 = local_54 / FLOAT_803e3f40;
            iVar4 = (int)(FLOAT_803e3f38 * fVar1);
            local_2e = (short)iVar4;
            local_34 = 0xc94;
          }
          else {
            fVar1 = local_54 / FLOAT_803e3f50;
            iVar4 = (int)(FLOAT_803e3f38 * fVar1);
            local_2e = (short)iVar4;
            local_34 = 0xc75;
          }
          local_18 = (longlong)iVar4;
          local_28 = FLOAT_803e3f5c * (FLOAT_803e3f28 - fVar1);
          local_2e = 0x15 - local_2e;
          (**(code **)(*DAT_803dd708 + 8))(param_1,0x7b2,&local_34,2,0xffffffff,0);
          (**(code **)(*DAT_803dd708 + 8))(param_1,0x7b2,&local_34,2,0xffffffff,0);
          (**(code **)(*DAT_803dd708 + 8))(param_1,0x7b2,&local_34,2,0xffffffff,0);
          (**(code **)(*DAT_803dd708 + 8))(param_1,0x7b2,&local_34,2,0xffffffff,0);
          local_2e = 9;
          uVar3 = FUN_80020078(0xc55);
          if (uVar3 == 0) {
            local_34 = 0xc0e;
            fVar1 = FLOAT_803e3f40;
          }
          else {
            local_34 = 0xc75;
            fVar1 = FLOAT_803e3f50;
          }
          local_2c = FLOAT_803e3f48 * (local_54 / fVar1) + FLOAT_803e3f44;
          local_24 = FLOAT_803e3f4c;
          (**(code **)(*DAT_803dd708 + 8))(param_1,0x7b3,&local_34,2,0xffffffff,0);
        }
      }
      else if (0x84 < local_50) {
        uVar3 = FUN_80020078(0xc55);
        if (uVar3 == 0) {
          local_34 = 0xc0e;
        }
        else {
          local_34 = 0xc75;
        }
        fVar1 = *(float *)(param_2 + 0x98);
        if (FLOAT_803e3f68 <= fVar1) {
          if (fVar1 < FLOAT_803e3f70) {
            local_28 = FLOAT_803e3f5c * (FLOAT_803e3f74 * (fVar1 - FLOAT_803e3f68) - FLOAT_803e3f2c)
            ;
            local_2e = 9;
            local_2c = FLOAT_803e3f20;
            local_24 = FLOAT_803e3f4c;
            (**(code **)(*DAT_803dd708 + 8))(param_1,0x7b3,&local_34,2,0xffffffff,0);
          }
        }
        else {
          local_28 = FLOAT_803e3f6c;
          local_2e = 9;
          local_2c = FLOAT_803e3f20;
          local_24 = FLOAT_803e3f4c;
          (**(code **)(*DAT_803dd708 + 8))(param_1,0x7b3,&local_34,2,0xffffffff,0);
        }
      }
    }
    else if (local_50 == 0x468) {
      if (FLOAT_803e3f4c < local_54) {
        iVar4 = (int)(FLOAT_803e3f38 * (local_54 / FLOAT_803e3f60));
        local_18 = (longlong)iVar4;
        local_46 = 0x15 - (short)iVar4;
        local_4c[0] = 0xc95;
        FUN_80296854(*(int *)(param_1 + 0xc4),&local_58);
        local_28 = *(float *)(local_58 + 0xc);
        local_24 = *(float *)(local_58 + 0x10);
        local_20 = *(undefined4 *)(local_58 + 0x14);
        (**(code **)(*DAT_803dd708 + 8))
                  (*(undefined4 *)(param_1 + 0xc4),0x7b9,&local_34,0x200001,0xffffffff,local_4c);
        (**(code **)(*DAT_803dd708 + 8))
                  (*(undefined4 *)(param_1 + 0xc4),0x7b9,&local_34,0x200001,0xffffffff,local_4c);
        (**(code **)(*DAT_803dd708 + 8))
                  (*(undefined4 *)(param_1 + 0xc4),0x7b9,&local_34,0x200001,0xffffffff,local_4c);
        (**(code **)(*DAT_803dd708 + 8))
                  (*(undefined4 *)(param_1 + 0xc4),0x7b9,&local_34,0x200001,0xffffffff,local_4c);
        local_46 = 9;
        local_4c[0] = 0xc95;
        local_44 = FLOAT_803e3f64 * (local_54 / FLOAT_803e3f60) + FLOAT_803e3f44;
        local_28 = *(float *)(local_58 + 0xc);
        local_24 = *(float *)(local_58 + 0x10);
        local_20 = *(undefined4 *)(local_58 + 0x14);
        (**(code **)(*DAT_803dd708 + 8))
                  (*(undefined4 *)(param_1 + 0xc4),0x7ba,&local_34,0x200001,0xffffffff,local_4c);
      }
    }
    else if (local_50 < 0x468) {
      if (local_50 < 0x89) {
        local_2e = 0x23;
        local_24 = FLOAT_803e3f4c;
        local_28 = FLOAT_803e3f50;
        local_34 = 0xc0e;
        (**(code **)(*DAT_803dd708 + 8))(param_1,0x7b3,&local_34,2,0xffffffff,0);
        local_2e = 0x12;
        local_24 = FLOAT_803e3f54;
        (**(code **)(*DAT_803dd708 + 8))(param_1,0x7b3,&local_34,2,0xffffffff,0);
      }
    }
    else if ((local_50 == 0x46f) && (FLOAT_803e3f4c < local_54)) {
      iVar4 = (int)(FLOAT_803e3f38 * (local_54 / FLOAT_803e3f60));
      local_18 = (longlong)iVar4;
      local_2e = 0x15 - (short)iVar4;
      local_28 = FLOAT_803e3f5c * (FLOAT_803e3f28 - local_54 / FLOAT_803e3f60);
      local_34 = 0xc94;
      (**(code **)(*DAT_803dd708 + 8))(param_1,0x7b2,&local_34,2,0xffffffff,0);
      (**(code **)(*DAT_803dd708 + 8))(param_1,0x7b2,&local_34,2,0xffffffff,0);
      (**(code **)(*DAT_803dd708 + 8))(param_1,0x7b2,&local_34,2,0xffffffff,0);
      (**(code **)(*DAT_803dd708 + 8))(param_1,0x7b2,&local_34,2,0xffffffff,0);
      local_2e = 9;
      local_2c = FLOAT_803e3f48 * (local_54 / FLOAT_803e3f60) + FLOAT_803e3f44;
      local_24 = FLOAT_803e3f4c;
      local_34 = 0xc0e;
      (**(code **)(*DAT_803dd708 + 8))(param_1,0x7b3,&local_34,2,0xffffffff,0);
    }
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016DE98
 * EN v1.0 Size: 16b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016de98(int param_1,undefined param_2,undefined param_3)

{
  int iVar1;
  
  iVar1 = *(int *)(param_1 + 0xb8);
  *(undefined *)(iVar1 + 0xbb) = param_2;
  *(undefined *)(iVar1 + 0xba) = param_3;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016DEA8
 * EN v1.0 Size: 504b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016dea8(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 undefined4 *param_9)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016E0A0
 * EN v1.0 Size: 312b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016e0a0(void)

{
  undefined *puVar1;
  double dVar2;
  float afStack_f8 [12];
  float afStack_c8 [12];
  float afStack_98 [12];
  float afStack_68 [12];
  float afStack_38 [3];
  float local_2c;
  float local_1c;
  float local_c;
  longlong local_8;
  
  if (DAT_803ad338 != '\0') {
    local_8 = (longlong)(int)DAT_803ad330;
    FUN_800737e8((char)(int)DAT_803ad330);
    puVar1 = FUN_8000f56c();
    FUN_80003494((uint)afStack_f8,(uint)puVar1,0x30);
    FUN_8024782c((double)FLOAT_803e3f98,afStack_98,0x78);
    dVar2 = (double)DAT_803ad324;
    FUN_80247a7c(dVar2,(double)(float)(dVar2 * (double)DAT_803ad32c),dVar2,afStack_68);
    FUN_80247618(afStack_68,afStack_98,afStack_68);
    FUN_80247a48((double)(DAT_803ad318 - FLOAT_803dda58),(double)DAT_803ad31c,
                 (double)(DAT_803ad320 - FLOAT_803dda5c),afStack_c8);
    FUN_80247618(afStack_f8,afStack_c8,afStack_f8);
    FUN_80247618(afStack_f8,afStack_68,afStack_38);
    FUN_8025d80c(afStack_38,0);
    FUN_80247618(afStack_f8,afStack_98,afStack_38);
    local_2c = FLOAT_803e3f4c;
    local_1c = FLOAT_803e3f4c;
    local_c = FLOAT_803e3f4c;
    FUN_8025d8c4(afStack_38,0x1e,0);
    FUN_8025d180((double)DAT_803ad328,10,0x14);
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016E1D8
 * EN v1.0 Size: 692b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016e1d8(void)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016E48C
 * EN v1.0 Size: 1780b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016e48c(void)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016EB80
 * EN v1.0 Size: 328b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016eb80(uint param_1,char param_2,char param_3)

{
  int iVar1;
  
  iVar1 = *(int *)(param_1 + 0xb8);
  if (param_2 == '\0') {
    if (FLOAT_803e3f4c < *(float *)(iVar1 + 0x50)) {
      FUN_8000bb38(param_1,0xc1);
    }
    if (param_3 == '\0') {
      *(float *)(iVar1 + 0x50) = FLOAT_803e3fbc;
    }
    else {
      *(float *)(iVar1 + 0x50) = FLOAT_803e3fc0;
    }
  }
  else {
    if (*(float *)(iVar1 + 0x50) < FLOAT_803e3f4c) {
      FUN_8000bb38(param_1,0xc0);
    }
    if (param_3 == '\0') {
      *(float *)(iVar1 + 0x50) = FLOAT_803e3fb8;
    }
    else {
      *(float *)(iVar1 + 0x50) = FLOAT_803e3f20;
    }
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016ECC8
 * EN v1.0 Size: 180b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016ecc8(int param_1)

{
  *(undefined4 *)(*(int *)(param_1 + 0xb8) + 0x48) = 0;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016ED7C
 * EN v1.0 Size: 548b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016ed7c(uint param_1)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016EFA0
 * EN v1.0 Size: 92b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016efa0(int param_1)

{
  int iVar1;
  int iVar2;
  
  iVar2 = *(int *)(param_1 + 0xb8);
  FUN_8016e48c();
  iVar1 = FUN_80020800();
  if (iVar1 == 0) {
    *(undefined *)(iVar2 + 0xbc) = 0;
  }
  else {
    *(undefined *)(iVar2 + 0xbc) = 1;
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016EFFC
 * EN v1.0 Size: 52b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016effc(int param_1)

{
  FUN_8016d394(param_1,*(int *)(param_1 + 0xc4));
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016F030
 * EN v1.0 Size: 120b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016f030(int param_1)

{
  int iVar1;
  uint *puVar2;
  
  iVar1 = 0;
  puVar2 = *(uint **)(param_1 + 0xb8);
  do {
    FUN_800238c4(*puVar2);
    puVar2 = puVar2 + 6;
    iVar1 = iVar1 + 1;
  } while (iVar1 < 3);
  (**(code **)(*DAT_803dd6f8 + 0x18))(param_1);
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016F0A8
 * EN v1.0 Size: 756b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016f0a8(undefined8 param_1,undefined8 param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 int param_9)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016F39C
 * EN v1.0 Size: 184b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016f39c(int param_1)

{
  int iVar1;
  int *piVar2;
  int iVar3;
  
  piVar2 = *(int **)(param_1 + 0xb8);
  *(undefined *)((int)piVar2 + 0xaa) = 1;
  *(undefined2 *)(piVar2 + 0x2c) = 2;
  piVar2[0x14] = (int)FLOAT_803e3fc0;
  if (*(int *)(param_1 + 0x54) != 0) {
    *(undefined2 *)(*(int *)(param_1 + 0x54) + 0xb2) = 0x109;
  }
  iVar3 = 0;
  do {
    iVar1 = FUN_80023d8c(60000,0x1a);
    *piVar2 = iVar1;
    *(undefined2 *)(piVar2 + 4) = 0xffff;
    piVar2 = piVar2 + 6;
    iVar3 = iVar3 + 1;
  } while (iVar3 < 3);
  DAT_803ad338 = 0;
  DAT_803ad334 = 0;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016F454
 * EN v1.0 Size: 128b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016f454(void)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016F4D4
 * EN v1.0 Size: 324b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016f4d4(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016F618
 * EN v1.0 Size: 12b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
undefined FUN_8016f618(int param_1)

{
  return *(undefined *)(*(int *)(param_1 + 0xb8) + 0x71);
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016F624
 * EN v1.0 Size: 232b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
undefined4 FUN_8016f624(int param_1,undefined4 param_2,int param_3)

{
  char cVar1;
  int *piVar2;
  int iVar3;
  
  piVar2 = *(int **)(param_1 + 0xb8);
  if ((*(byte *)(piVar2 + 0x1c) & 8) == 0) {
    for (iVar3 = 0; iVar3 < (int)(uint)*(byte *)(param_3 + 0x8b); iVar3 = iVar3 + 1) {
      cVar1 = *(char *)(param_3 + iVar3 + 0x81);
      if (cVar1 == '\x01') {
        if (*piVar2 != 0) {
          FUN_8001dc30((double)FLOAT_803e3fc8,*piVar2,'\x01');
        }
        *(ushort *)(param_1 + 6) = *(ushort *)(param_1 + 6) & 0xbfff;
      }
      else if (cVar1 == '\x02') {
        if (*piVar2 != 0) {
          FUN_8001dc30((double)FLOAT_803e3fc8,*piVar2,'\0');
        }
        *(ushort *)(param_1 + 6) = *(ushort *)(param_1 + 6) | 0x4000;
      }
    }
  }
  return 0;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016F70C
 * EN v1.0 Size: 764b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016f70c(int param_1,int param_2,int param_3)

{
  float fVar1;
  float *pfVar2;
  double dVar3;
  double dVar4;
  
  pfVar2 = (float *)(*(int *)(param_3 + 0x74) + (uint)*(byte *)(param_3 + 0xe4) * 0x18);
  if (pfVar2 != (float *)0x0) {
    dVar4 = (double)(*pfVar2 - *(float *)(param_2 + 0x24));
    dVar3 = (double)(pfVar2[2] - *(float *)(param_2 + 0x2c));
    FUN_80021884();
    FUN_80293900((double)(*(float *)(param_1 + 0x24) * *(float *)(param_1 + 0x24) +
                         *(float *)(param_1 + 0x2c) * *(float *)(param_1 + 0x2c)));
    FUN_80021884();
    FUN_80021884();
    FUN_80293900((double)(float)(dVar4 * dVar4 + (double)(float)(dVar3 * dVar3)));
    FUN_80021884();
    dVar3 = (double)FUN_802945e0();
    *(float *)(param_1 + 0x24) = (float)dVar3;
    dVar3 = (double)FUN_80294964();
    *(float *)(param_1 + 0x2c) = (float)dVar3;
    dVar3 = (double)FUN_802945e0();
    dVar4 = (double)FUN_80294964();
    if ((double)FLOAT_803e3fc8 != dVar4) {
      dVar3 = (double)(float)(dVar3 / dVar4);
    }
    *(float *)(param_1 + 0x28) = (float)dVar3;
    dVar3 = FUN_80293900((double)(*(float *)(param_1 + 0x2c) * *(float *)(param_1 + 0x2c) +
                                 *(float *)(param_1 + 0x24) * *(float *)(param_1 + 0x24) +
                                 *(float *)(param_1 + 0x28) * *(float *)(param_1 + 0x28)));
    fVar1 = (float)((double)FLOAT_803e3fd8 / dVar3);
    *(float *)(param_1 + 0x24) = *(float *)(param_1 + 0x24) * fVar1;
    *(float *)(param_1 + 0x28) = *(float *)(param_1 + 0x28) * fVar1;
    *(float *)(param_1 + 0x2c) = *(float *)(param_1 + 0x2c) * fVar1;
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016FA08
 * EN v1.0 Size: 96b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016fa08(int param_1)

{
  if (**(uint **)(param_1 + 0xb8) != 0) {
    FUN_8001f448(**(uint **)(param_1 + 0xb8));
  }
  (**(code **)(*DAT_803dd6f8 + 0x18))(param_1);
  FUN_8003709c(param_1,2);
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016FA68
 * EN v1.0 Size: 568b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016fa68(void)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016FCA0
 * EN v1.0 Size: 320b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016fca0(int param_1)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8016FDE0
 * EN v1.0 Size: 1196b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8016fde0(undefined8 param_1,double param_2,double param_3,double param_4,undefined8 param_5
                 ,undefined8 param_6,undefined8 param_7,undefined8 param_8,short *param_9)

{
  float fVar1;
  uint uVar2;
  undefined uVar3;
  int iVar4;
  int iVar5;
  uint *puVar6;
  double dVar7;
  double dVar8;
  float local_28 [2];
  undefined4 local_20;
  uint uStack_1c;
  undefined4 local_18;
  uint uStack_14;
  
  puVar6 = *(uint **)(param_9 + 0x5c);
  iVar5 = *(int *)(param_9 + 0x7c);
  iVar4 = *(int *)(param_9 + 0x26);
  if ((*(byte *)(puVar6 + 0x1c) & 8) == 0) {
    puVar6[0xf] = (uint)((float)puVar6[0xf] - FLOAT_803dc074);
    if ((float)puVar6[0xf] < FLOAT_803e3fc8) {
      puVar6[0xf] = (uint)FLOAT_803e3fc8;
    }
    if (param_9[0x23] == 0x83e) {
      if (*puVar6 != 0) {
        FUN_8001dc30((double)FLOAT_803e3fc8,*puVar6,'\0');
      }
      param_9[3] = param_9[3] | 0x4000;
    }
    else {
      if (FLOAT_803e3fc8 == (float)puVar6[0xd]) {
        dVar7 = (double)FUN_800229cc((float *)(param_9 + 0x12));
        puVar6[0xc] = (uint)(float)((double)FLOAT_803e3ff4 / dVar7);
      }
      puVar6[0xd] = (uint)((float)puVar6[0xd] + FLOAT_803dc074);
      if ((float)puVar6[0xc] < (float)puVar6[0xd]) {
        if (*(char *)(iVar4 + 0x19) == '\0') {
          uVar3 = 1;
        }
        else {
          uVar3 = 3;
        }
        FUN_80035eec((int)param_9,0xe,uVar3,0);
      }
      if ((*(byte *)(puVar6 + 0x1c) & 1) == 0) {
        puVar6[9] = *(uint *)(param_9 + 6);
        puVar6[10] = *(uint *)(param_9 + 8);
        puVar6[0xb] = *(uint *)(param_9 + 10);
        *(byte *)(puVar6 + 0x1c) = *(byte *)(puVar6 + 0x1c) | 1;
      }
      if (*(char *)(*(int *)(param_9 + 0x2a) + 0xad) != '\0') {
        if (*(char *)(*(int *)(param_9 + 0x2a) + 0xac) == '\x0e') {
          FUN_8000bb38((uint)param_9,0xba);
          (**(code **)(*DAT_803dd718 + 0x10))
                    ((double)*(float *)(param_9 + 6),(double)*(float *)(param_9 + 8),
                     (double)*(float *)(param_9 + 10),(double)FLOAT_803e3ff8,param_9);
          param_2 = (double)*(float *)(param_9 + 8);
          param_3 = (double)*(float *)(param_9 + 10);
          param_4 = (double)FLOAT_803e3fc8;
          (**(code **)(*DAT_803dd718 + 0x14))((double)*(float *)(param_9 + 6),(int)*param_9,2);
        }
        else {
          FUN_8000bb38((uint)param_9,0xb3);
        }
        if (*(char *)((int)puVar6 + 0x71) == '\0') {
          FUN_800998ec(param_9,3);
        }
        else if (*(char *)((int)puVar6 + 0x71) == '\x01') {
          FUN_800998ec(param_9,0);
        }
        else {
          FUN_800998ec(param_9,6);
        }
        puVar6[0xe] = (uint)FLOAT_803e3ff0;
        *(undefined *)(param_9 + 0x1b) = 0;
        if (*puVar6 != 0) {
          FUN_8001f448(*puVar6);
          *puVar6 = 0;
        }
        FUN_8003709c((int)param_9,2);
        FUN_80035ff8((int)param_9);
      }
      fVar1 = FLOAT_803e3fc8;
      if ((float)puVar6[0xe] == FLOAT_803e3fc8) {
        *(undefined4 *)(param_9 + 0x40) = *(undefined4 *)(param_9 + 6);
        *(undefined4 *)(param_9 + 0x42) = *(undefined4 *)(param_9 + 8);
        *(undefined4 *)(param_9 + 0x44) = *(undefined4 *)(param_9 + 10);
        if (iVar5 != 0) {
          if ((*(ushort *)(iVar5 + 0xb0) & 0x40) == 0) {
            FUN_8016f70c((int)param_9,(int)puVar6,iVar5);
          }
          else {
            param_9[0x7c] = 0;
            param_9[0x7d] = 0;
          }
        }
        puVar6[9] = (uint)(*(float *)(param_9 + 0x12) * FLOAT_803dc074 + (float)puVar6[9]);
        puVar6[10] = (uint)(*(float *)(param_9 + 0x14) * FLOAT_803dc074 + (float)puVar6[10]);
        dVar8 = (double)*(float *)(param_9 + 0x16);
        dVar7 = (double)FLOAT_803dc074;
        puVar6[0xb] = (uint)(float)(dVar8 * dVar7 + (double)(float)puVar6[0xb]);
        *(ushort *)((int)puVar6 + 0x46) =
             *(short *)((int)puVar6 + 0x46) + (ushort)DAT_803dc070 * 0x5dc;
        if ((*(byte *)(puVar6 + 0x1c) & 4) != 0) {
          puVar6[10] = (uint)-(FLOAT_803e3ffc * FLOAT_803dc074 - (float)puVar6[10]);
          dVar7 = (double)(float)puVar6[9];
          dVar8 = (double)(float)puVar6[10];
          param_3 = (double)(float)puVar6[0xb];
          iVar4 = FUN_80065a20(dVar7,dVar8,param_3,param_9,local_28,0);
          if (iVar4 == 0) {
            local_28[0] = local_28[0] - FLOAT_803e4000;
            dVar7 = (double)local_28[0];
            if ((dVar7 < (double)FLOAT_803e3fc8) && ((double)FLOAT_803e4004 < dVar7)) {
              puVar6[10] = (uint)(float)((double)(float)puVar6[10] - dVar7);
            }
          }
        }
        *(uint *)(param_9 + 6) = puVar6[9];
        *(uint *)(param_9 + 8) = puVar6[10];
        *(uint *)(param_9 + 10) = puVar6[0xb];
        if (iVar5 != 0) {
          uStack_1c = (uint)*(ushort *)((int)puVar6 + 0x46);
          local_20 = 0x43300000;
          dVar7 = (double)FUN_802945e0();
          *(float *)(param_9 + 6) =
               (float)((double)FLOAT_803e3fcc * dVar7 + (double)*(float *)(param_9 + 6));
          uStack_14 = (uint)*(ushort *)((int)puVar6 + 0x46);
          local_18 = 0x43300000;
          dVar7 = (double)FUN_80294964();
          dVar8 = (double)FLOAT_803e3fcc;
          *(float *)(param_9 + 10) = (float)(dVar8 * dVar7 + (double)*(float *)(param_9 + 10));
        }
        uVar2 = (uint)DAT_803dc070;
        iVar4 = *(int *)(param_9 + 0x7a);
        *(uint *)(param_9 + 0x7a) = iVar4 - uVar2;
        if ((int)(iVar4 - uVar2) < 0) {
          FUN_8002cc9c(dVar7,dVar8,param_3,param_4,param_5,param_6,param_7,param_8,(int)param_9);
        }
      }
      else {
        *(float *)(param_9 + 0x12) = FLOAT_803e3fc8;
        *(float *)(param_9 + 0x14) = fVar1;
        *(float *)(param_9 + 0x16) = fVar1;
        FUN_80035ea4((int)param_9);
        puVar6[0xe] = (uint)((float)puVar6[0xe] - FLOAT_803dc074);
        if ((double)(float)puVar6[0xe] <= (double)FLOAT_803e3fc8) {
          FUN_8002cc9c((double)(float)puVar6[0xe],param_2,param_3,param_4,param_5,param_6,param_7,
                       param_8,(int)param_9);
        }
      }
    }
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8017028C
 * EN v1.0 Size: 612b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8017028c(void)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801704F0
 * EN v1.0 Size: 40b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_801704f0(int param_1)

{
  FUN_8003b9ec(param_1);
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80170518
 * EN v1.0 Size: 444b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80170518(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 ushort *param_9)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801706D4
 * EN v1.0 Size: 172b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_801706d4(int param_1,int param_2)

{
  int iVar1;
  
  iVar1 = *(int *)(param_1 + 0xb8);
  FUN_800803f8((undefined4 *)(iVar1 + 4));
  *(float *)(iVar1 + 8) =
       ((float)((double)CONCAT44(0x43300000,(int)*(short *)(param_2 + 0x1a) ^ 0x80000000) -
               DOUBLE_803e4030) / FLOAT_803e4038) * FLOAT_803dc9c8;
  *(float *)(param_1 + 0x28) = FLOAT_803e4024;
  *(ushort *)(param_1 + 6) = *(ushort *)(param_1 + 6) | 0x4000;
  *(undefined4 *)(iVar1 + 0x10) = 1;
  FUN_80035ff8(param_1);
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80170780
 * EN v1.0 Size: 172b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
int FUN_80170780(double param_1,double param_2,double param_3,undefined8 param_4,undefined8 param_5,
                undefined8 param_6,undefined8 param_7,undefined8 param_8,int param_9)

{
  uint uVar1;
  int iVar2;
  undefined2 *puVar3;
  undefined4 in_r8;
  undefined4 in_r9;
  undefined4 in_r10;
  double dVar4;
  
  dVar4 = param_1;
  uVar1 = FUN_8002e144();
  if ((uVar1 & 0xff) == 0) {
    iVar2 = 0;
  }
  else {
    puVar3 = FUN_8002becc(0x24,0x836);
    *(undefined4 *)(puVar3 + 4) = *(undefined4 *)(param_9 + 0x18);
    *(undefined4 *)(puVar3 + 6) = *(undefined4 *)(param_9 + 0x1c);
    *(undefined4 *)(puVar3 + 8) = *(undefined4 *)(param_9 + 0x20);
    *(undefined *)(puVar3 + 2) = 1;
    *(undefined *)((int)puVar3 + 5) = 1;
    *(undefined *)((int)puVar3 + 7) = 0xff;
    iVar2 = FUN_8002e088(param_1,param_2,param_3,param_4,param_5,param_6,param_7,param_8,puVar3,5,
                         0xff,0xffffffff,(uint *)0x0,in_r8,in_r9,in_r10);
    if (iVar2 != 0) {
      *(float *)(iVar2 + 8) = (float)dVar4;
    }
  }
  return iVar2;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8017082C
 * EN v1.0 Size: 1804b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8017082c(void)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80170F38
 * EN v1.0 Size: 100b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80170f38(int param_1)

{
  uint uVar1;
  uint *puVar2;
  
  puVar2 = *(uint **)(param_1 + 0xb8);
  uVar1 = *puVar2;
  if (uVar1 != 0) {
    FUN_8001f448(uVar1);
    *puVar2 = 0;
  }
  FUN_8000b844(param_1,0x42c);
  FUN_8000b844(param_1,0x42d);
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80170F9C
 * EN v1.0 Size: 1152b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80170f9c(void)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8017141C
 * EN v1.0 Size: 808b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8017141c(void)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80171744
 * EN v1.0 Size: 136b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80171744(int param_1)

{
  int iVar1;
  
  iVar1 = FUN_8002b660(param_1);
  FUN_800285f0(iVar1,FUN_80028590);
  if (*(short *)(param_1 + 0x46) == 0x836) {
    FUN_8017082c();
  }
  else {
    FUN_8017082c();
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801717CC
 * EN v1.0 Size: 236b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_801717cc(int param_1)

{
  char in_r8;
  
  if (in_r8 != '\0') {
    FUN_8003b9ec(param_1);
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801718B8
 * EN v1.0 Size: 100b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_801718b8(int param_1)

{
  (**(code **)(*DAT_803dd6fc + 0x18))();
  FUN_80013e4c(DAT_803de730);
  FUN_80013e4c(DAT_803de734);
  DAT_803de730 = (undefined4*)0x0;
  DAT_803de734 = (undefined4*)0x0;
  FUN_8003709c(param_1,0x3e);
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8017191C
 * EN v1.0 Size: 172b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8017191c(void)

{
  float fVar1;
  int iVar2;
  char in_r8;
  
  iVar2 = FUN_80286840();
  if ((*(char *)((int)*(float **)(iVar2 + 0xb8) + 9) == '\0') && (in_r8 != '\0')) {
    fVar1 = **(float **)(iVar2 + 0xb8);
    if (fVar1 != FLOAT_803e4098) {
      FUN_8003b6d8(200,0,0,(char)(int)fVar1);
    }
    FUN_8003b9ec(iVar2);
  }
  FUN_8028688c();
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801719C8
 * EN v1.0 Size: 948b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_801719c8(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 undefined2 *param_9)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80171D7C
 * EN v1.0 Size: 296b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80171d7c(undefined2 *param_1,int param_2)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80171EA4
 * EN v1.0 Size: 44b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80171ea4(int param_1)

{
  FUN_8003b9ec(param_1);
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80171ED0
 * EN v1.0 Size: 392b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80171ed0(ushort *param_1,int param_2)

{
  float fVar1;
  uint uVar2;
  int iVar3;
  int iVar4;
  ushort local_78;
  ushort local_76;
  ushort local_74;
  float local_70;
  float local_6c;
  float local_68;
  float local_64;
  float afStack_60 [16];
  undefined4 local_20;
  uint uStack_1c;
  undefined4 local_18;
  uint uStack_14;
  
  iVar4 = *(int *)(param_1 + 0x5c);
  uStack_1c = *(byte *)(param_2 + 0x2a) ^ 0x80000000;
  local_20 = 0x43300000;
  local_18 = 0x43300000;
  fVar1 = (float)((double)CONCAT44(0x43300000,uStack_1c) - DOUBLE_803e40d0);
  if ((float)((double)CONCAT44(0x43300000,uStack_1c) - DOUBLE_803e40d0) < FLOAT_803e40bc) {
    fVar1 = FLOAT_803e40bc;
  }
  *(float *)(param_1 + 4) = fVar1 * FLOAT_803e40c0;
  *param_1 = (ushort)((int)(short)(ushort)*(byte *)(param_2 + 0x29) << 8);
  local_78 = *param_1;
  local_76 = param_1[1];
  local_74 = param_1[2];
  local_70 = FLOAT_803e40b8;
  local_6c = FLOAT_803e40c4;
  local_68 = FLOAT_803e40c4;
  local_64 = FLOAT_803e40c4;
  uStack_14 = uStack_1c;
  FUN_80021fac(afStack_60,&local_78);
  FUN_80022790((double)FLOAT_803e40c4,(double)FLOAT_803e40c4,(double)FLOAT_803e40b8,afStack_60,
               (float *)(iVar4 + 0x10),(float *)(iVar4 + 0x14),(float *)(iVar4 + 0x18));
  *(float *)(iVar4 + 0x1c) =
       -(*(float *)(param_1 + 10) * *(float *)(iVar4 + 0x18) +
        *(float *)(param_1 + 6) * *(float *)(iVar4 + 0x10) +
        *(float *)(param_1 + 8) * *(float *)(iVar4 + 0x14));
  *(float *)(iVar4 + 0x20) = FLOAT_803e40c8 * *(float *)(param_1 + 4);
  iVar3 = 0;
  do {
    uVar2 = FUN_80022264(0,0xf0);
    *(short *)(iVar4 + 0x34) = (short)uVar2;
    iVar4 = iVar4 + 2;
    iVar3 = iVar3 + 1;
  } while (iVar3 < 4);
  *(int *)(param_1 + 0x7a) = (int)*(char *)(param_2 + 0x28);
  param_1[0x58] = param_1[0x58] | 0xa000;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80172058
 * EN v1.0 Size: 212b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80172058(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 int param_9)

{
  uint uVar1;
  int iVar2;
  undefined2 *puVar3;
  short *psVar4;
  undefined4 in_r8;
  undefined4 in_r9;
  undefined4 in_r10;
  int iVar5;
  
  iVar5 = *(int *)(param_9 + 0x4c);
  uVar1 = FUN_8002e144();
  if (((((uVar1 & 0xff) != 0) && (iVar2 = FUN_8002bac4(), iVar2 != 0)) &&
      (iVar2 = FUN_8002ba84(), iVar2 == 0)) &&
     (uVar1 = FUN_80020078((int)*(short *)(iVar5 + 0x18)), uVar1 != 0)) {
    puVar3 = FUN_8002becc(0x18,0x24);
    *(undefined *)(puVar3 + 2) = 2;
    *(undefined *)((int)puVar3 + 5) = 4;
    *(undefined *)((int)puVar3 + 7) = 0xff;
    *(undefined4 *)(puVar3 + 4) = *(undefined4 *)(param_9 + 0xc);
    *(undefined4 *)(puVar3 + 6) = *(undefined4 *)(param_9 + 0x10);
    *(undefined4 *)(puVar3 + 8) = *(undefined4 *)(param_9 + 0x14);
    psVar4 = (short *)FUN_8002e088(param_1,param_2,param_3,param_4,param_5,param_6,param_7,param_8,
                                   puVar3,5,0xff,0xffffffff,(uint *)0x0,in_r8,in_r9,in_r10);
    *psVar4 = (ushort)*(byte *)(iVar5 + 0x1a) << 8;
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8017212C
 * EN v1.0 Size: 36b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8017212c(int param_1)

{
  FUN_8003709c(param_1,0x40);
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80172150
 * EN v1.0 Size: 112b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80172150(int param_1,int param_2)

{
  *(ushort *)(param_1 + 0xb0) = *(ushort *)(param_1 + 0xb0) | 0xe000;
  FUN_800372f8(param_1,0x40);
  if (*(int *)(param_1 + 0x54) != 0) {
    FUN_80035a6c(param_1,(short)((int)(uint)*(ushort *)(param_2 + 0x18) >> 3));
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801721C0
 * EN v1.0 Size: 148b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_801721c0(double param_1,double param_2,double param_3,int param_4)

{
  int iVar1;
  uint uVar2;
  
  iVar1 = *(int *)(param_4 + 0xb8);
  *(float *)(param_4 + 0xc) = (float)param_1;
  *(float *)(iVar1 + 0x24) = (float)param_1;
  *(float *)(param_4 + 0x10) = (float)param_2;
  *(float *)(iVar1 + 0x28) = (float)param_2;
  *(float *)(param_4 + 0x14) = (float)param_3;
  *(float *)(iVar1 + 0x2c) = (float)param_3;
  uVar2 = FUN_80020078((int)*(short *)(iVar1 + 0x10));
  if (uVar2 == 0) {
    FUN_800e85f4(param_4);
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80172254
 * EN v1.0 Size: 80b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
undefined4 FUN_80172254(int param_1)

{
  uint uVar1;
  int iVar2;
  
  iVar2 = *(int *)(param_1 + 0xb8);
  if (*(int *)(iVar2 + 0x18) == -2) {
    uVar1 = FUN_800387b4();
    *(uint *)(iVar2 + 0x18) = uVar1 & 0xffff;
  }
  return *(undefined4 *)(iVar2 + 0x18);
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801722A4
 * EN v1.0 Size: 100b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_801722a4(int param_1,int param_2)

{
  uint uVar1;
  int iVar2;
  
  iVar2 = *(int *)(param_1 + 0xb8);
  *(char *)(iVar2 + 0xf) = (char)param_2;
  if (param_2 == 0) {
    uVar1 = FUN_80020078((int)*(short *)(iVar2 + 0x10));
    if (uVar1 == 0) {
      FUN_80036018(param_1);
    }
  }
  else {
    FUN_80035ff8(param_1);
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80172308
 * EN v1.0 Size: 744b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80172308(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 uint param_9)

{
  short sVar1;
  char cVar2;
  uint uVar3;
  int iVar4;
  int iVar5;
  int iVar6;
  undefined8 uVar7;
  
  iVar6 = *(int *)(param_9 + 0xb8);
  iVar5 = *(int *)(param_9 + 0x4c);
  iVar4 = *(int *)(*(int *)(param_9 + 0x50) + 0x18);
  FUN_8002bac4();
  FUN_8002ba84();
  FUN_8002bac4();
  FUN_8002ba84();
  uVar7 = FUN_80035ff8(param_9);
  if ((*(ushort *)(param_9 + 6) & 0x2000) != 0) {
    *(float *)(iVar6 + 8) = FLOAT_803e40e8;
    if (*(int *)(param_9 + 100) != 0) {
      *(undefined4 *)(*(int *)(param_9 + 100) + 0x30) = 0x1000;
    }
  }
  if ((int)*(short *)(iVar6 + 0x10) != 0xffffffff) {
    FUN_800201ac((int)*(short *)(iVar6 + 0x10),1);
    uVar7 = FUN_800e83ec(param_9);
  }
  uVar3 = (uint)*(short *)(iVar5 + 0x1e);
  if (uVar3 != 0xffffffff) {
    uVar7 = FUN_800201ac(uVar3,1);
  }
  uVar3 = (uint)*(short *)(iVar5 + 0x2c);
  if (0 < (int)uVar3) {
    FUN_80020000(uVar3);
  }
  sVar1 = *(short *)(iVar4 + 2);
  if (sVar1 == 4) {
    sVar1 = *(short *)(param_9 + 0x46);
    if (sVar1 == 0x3cd) {
      iVar4 = FUN_8002bac4();
      FUN_8029725c(uVar7,param_2,param_3,param_4,param_5,param_6,param_7,param_8,iVar4,2);
      uVar3 = FUN_8002bac4();
      FUN_8000bb38(uVar3,0x49);
      FUN_80099c40((double)FLOAT_803e40ec,param_9,1,0x28);
    }
    else if ((sVar1 < 0x3cd) && (sVar1 == 0xb)) {
      uVar3 = FUN_8002bac4();
      uVar7 = FUN_8000bb38(uVar3,0x49);
      iVar4 = FUN_8002bac4();
      FUN_8029725c(uVar7,param_2,param_3,param_4,param_5,param_6,param_7,param_8,iVar4,4);
      FUN_80099c40((double)FLOAT_803e40ec,param_9,3,0x28);
    }
    else {
      uVar3 = FUN_8002bac4();
      FUN_8000bb38(uVar3,0x58);
      FUN_80099c40((double)FLOAT_803e40ec,param_9,0xff,0x28);
    }
  }
  else if ((sVar1 < 4) && (sVar1 == 1)) {
    sVar1 = *(short *)(param_9 + 0x46);
    if (sVar1 == 0x319) {
      FUN_8000bb38(param_9,0x16a);
      FUN_800201ac(0x3e9,1);
      *(undefined2 *)(iVar6 + 0x3c) = 0x4b0;
      FUN_80099c40((double)FLOAT_803e40ec,param_9,0xff,0x28);
    }
    else {
      if (sVar1 < 0x319) {
        if (sVar1 == 0x5a) {
          FUN_8000bb38(param_9,0x49);
          FUN_80099c40((double)FLOAT_803e40ec,param_9,2,0x28);
          goto LAB_801725bc;
        }
        if ((sVar1 < 0x5a) && (sVar1 == 0x22)) {
          FUN_8000bb38(param_9,0x49);
          FUN_80099c40((double)FLOAT_803e40ec,param_9,0xff,0x28);
          goto LAB_801725bc;
        }
      }
      else if (sVar1 == 0x6a6) {
        uVar3 = FUN_80020078(0x86a);
        cVar2 = (char)uVar3;
        if (cVar2 < '\a') {
          cVar2 = cVar2 + '\x01';
        }
        FUN_800201ac(0x86a,(int)cVar2);
        FUN_80099c40((double)FLOAT_803e40ec,param_9,6,0x28);
        FUN_8000bb38(param_9,0x49);
        goto LAB_801725bc;
      }
      FUN_8000bb38(param_9,0x58);
      FUN_80099c40((double)FLOAT_803e40ec,param_9,0xff,0x28);
    }
  }
  else {
    FUN_8000bb38(param_9,0x58);
    FUN_80099c40((double)FLOAT_803e40ec,param_9,0xff,0x28);
  }
LAB_801725bc:
  *(undefined4 *)(param_9 + 8) = *(undefined4 *)(*(int *)(param_9 + 0x50) + 4);
  *(undefined4 *)(param_9 + 0xf4) = 1;
  return;
}
