/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/laser19F.c
 * Text span: 0x801C4B54-0x801C532C
 * Imported Ghidra functions: 4
 * Verbatim-safe functions: 3
 * Auto-stubbed functions: 1
 */

#include "ghidra_import.h"
#include "main/dll/laser19F.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined8 FUN_80013ee8();
extern char FUN_80014cec();
extern undefined4 FUN_8001dc30();
extern undefined4 FUN_800201ac();
extern undefined4 FUN_80021754();
extern uint FUN_80021884();
extern uint FUN_80022264();
extern int FUN_8002bac4();
extern undefined4 FUN_8002fb40();
extern undefined4 FUN_80037a5c();
extern int FUN_80054ed0();
extern undefined4 FUN_8011f9b8();
extern undefined4 FUN_8011f9c4();
extern int FUN_8028683c();
extern undefined4 FUN_80286888();
extern undefined4 FUN_802945e0();
extern undefined4 FUN_80296c78();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4* DAT_803dd72c;
extern undefined4 DAT_803de838;
extern f64 DOUBLE_803e5bd0;
extern f32 FLOAT_803dc074;
extern f32 FLOAT_803e5b58;
extern f32 FLOAT_803e5ba0;
extern f32 FLOAT_803e5ba4;
extern f32 FLOAT_803e5ba8;
extern f32 FLOAT_803e5bac;
extern f32 FLOAT_803e5bb8;
extern f32 FLOAT_803e5bbc;
extern f32 FLOAT_803e5bc0;
extern f32 FLOAT_803e5bc4;
extern f32 FLOAT_803e5bc8;
extern f32 FLOAT_803e5bd8;
extern f32 FLOAT_803e5bdc;
extern f32 FLOAT_803e5be0;
extern f32 FLOAT_803e5be4;
extern f32 FLOAT_803e5be8;
extern f32 FLOAT_803e5bec;
extern f32 FLOAT_803e5bf0;
extern f32 FLOAT_803e5bf4;
extern f32 FLOAT_803e5bf8;

/* Local declarations keep imported functions visible within the TU. */
void FUN_801c4b54(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 undefined2 *param_9,int param_10,undefined4 param_11,undefined4 param_12,
                 undefined4 param_13,undefined4 param_14,undefined4 param_15,undefined4 param_16);
void FUN_801c4c18(ushort *param_1);
undefined4 FUN_801c4f6c(int param_1);
void FUN_801c50c4(undefined4 param_1,undefined4 param_2,int param_3);

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801C4B54
 * EN v1.0 Size: 196b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_801c4b54(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 undefined2 *param_9,int param_10,undefined4 param_11,undefined4 param_12,
                 undefined4 param_13,undefined4 param_14,undefined4 param_15,undefined4 param_16)

{
  uint uVar1;
  int iVar2;
  int *piVar3;
  undefined8 extraout_f1;
  undefined8 uVar4;
  
  piVar3 = *(int **)(param_9 + 0x5c);
  FUN_80037a5c((int)param_9,2);
  *param_9 = (short)((int)*(char *)(param_10 + 0x18) << 8);
  uVar1 = FUN_80022264(0xffffffb0,0x50);
  *(short *)(piVar3 + 0xb) = (short)uVar1 + 400;
  *(undefined *)((int)piVar3 + 0x49) = 0;
  uVar4 = FUN_80013ee8(0x81);
  DAT_803de838 = (undefined4)((ulonglong)uVar4 >> 0x20);
  piVar3[7] = (int)FLOAT_803e5b58;
  *(undefined *)((int)piVar3 + 0x4a) = *(undefined *)(param_10 + 0x19);
  *(undefined2 *)((int)piVar3 + 0x2e) = 0x118;
  if (*piVar3 == 0) {
    iVar2 = FUN_80054ed0(extraout_f1,param_2,param_3,param_4,param_5,param_6,param_7,param_8,0x2e,
                         (int)uVar4,param_11,param_12,param_13,param_14,param_15,param_16);
    *piVar3 = iVar2;
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801C4C18
 * EN v1.0 Size: 852b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_801c4c18(ushort *param_1)

{
  int iVar1;
  uint uVar2;
  int iVar3;
  int iVar4;
  double dVar5;
  double dVar6;
  undefined8 local_30;
  
  iVar4 = *(int *)(param_1 + 0x26);
  iVar3 = *(int *)(param_1 + 0x5c);
  iVar1 = FUN_8002bac4();
  if ((param_1[3] & 0x4000) == 0) {
    *(short *)(iVar3 + 0x1e) =
         *(short *)(iVar3 + 0x1e) + (short)(int)(FLOAT_803e5ba0 * FLOAT_803dc074);
    *(short *)(iVar3 + 0x20) =
         *(short *)(iVar3 + 0x20) + (short)(int)(FLOAT_803e5ba4 * FLOAT_803dc074);
    *(short *)(iVar3 + 0x22) =
         *(short *)(iVar3 + 0x22) + (short)(int)(FLOAT_803e5ba8 * FLOAT_803dc074);
    dVar5 = (double)FUN_802945e0();
    *(float *)(param_1 + 8) = FLOAT_803e5bac + (float)((double)*(float *)(iVar4 + 0xc) + dVar5);
    dVar5 = (double)FUN_802945e0();
    dVar6 = (double)FUN_802945e0();
    param_1[2] = (ushort)(int)(FLOAT_803e5bb8 * (float)(dVar6 + dVar5));
    dVar5 = (double)FUN_802945e0();
    dVar6 = (double)FUN_802945e0();
    param_1[1] = (ushort)(int)(FLOAT_803e5bb8 * (float)(dVar6 + dVar5));
    FUN_8002fb40((double)FLOAT_803e5bbc,(double)FLOAT_803dc074);
    if (iVar1 != 0) {
      uVar2 = FUN_80021884();
      uVar2 = (uVar2 & 0xffff) - (uint)*param_1;
      if (0x8000 < (int)uVar2) {
        uVar2 = uVar2 - 0xffff;
      }
      if ((int)uVar2 < -0x8000) {
        uVar2 = uVar2 + 0xffff;
      }
      local_30 = (double)CONCAT44(0x43300000,uVar2 ^ 0x80000000);
      *param_1 = *param_1 +
                 (short)(int)(((float)(local_30 - DOUBLE_803e5bd0) * FLOAT_803dc074) /
                             FLOAT_803e5bc0);
      dVar5 = (double)FUN_80021754((float *)(param_1 + 0xc),(float *)(iVar1 + 0x18));
      if ((double)FLOAT_803e5bc4 < dVar5) {
        *(undefined *)(param_1 + 0x1b) = 0xff;
      }
      else {
        *(char *)(param_1 + 0x1b) =
             (char)(int)(FLOAT_803e5bc8 * (float)(dVar5 / (double)FLOAT_803e5bc4));
      }
    }
  }
  else {
    *param_1 = 0;
    *(undefined4 *)(param_1 + 8) = *(undefined4 *)(iVar4 + 0xc);
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801C4F6C
 * EN v1.0 Size: 344b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
undefined4 FUN_801c4f6c(int param_1)

{
  float fVar1;
  float fVar2;
  char cVar4;
  undefined4 uVar3;
  int iVar5;
  undefined8 local_18;
  
  iVar5 = *(int *)(param_1 + 0xb8);
  if ((*(uint *)(iVar5 + 0x18) & 0x20) == 0) {
    FUN_8011f9b8(1);
    *(uint *)(iVar5 + 0x18) = *(uint *)(iVar5 + 0x18) | 0x20;
    fVar1 = FLOAT_803e5bd8;
    *(float *)(iVar5 + 4) = FLOAT_803e5bd8;
    *(float *)(iVar5 + 8) = fVar1;
    *(float *)(iVar5 + 0xc) = fVar1;
  }
  cVar4 = FUN_80014cec(0);
  fVar2 = FLOAT_803e5be0;
  local_18 = (double)CONCAT44(0x43300000,(int)cVar4 ^ 0x80000000);
  *(float *)(iVar5 + 8) =
       ((float)(local_18 - DOUBLE_803e5bd0) / FLOAT_803e5bdc) * FLOAT_803e5be0 * FLOAT_803dc074 +
       *(float *)(iVar5 + 8);
  fVar1 = *(float *)(iVar5 + 0x10);
  if ((FLOAT_803e5bd8 <= fVar1) || (*(float *)(iVar5 + 0xc) <= fVar1)) {
    if ((FLOAT_803e5bd8 < fVar1) && (*(float *)(iVar5 + 0xc) < fVar1)) {
      *(float *)(iVar5 + 0xc) = FLOAT_803e5be0 * FLOAT_803dc074 + *(float *)(iVar5 + 0xc);
    }
  }
  else {
    *(float *)(iVar5 + 0xc) = -(fVar2 * FLOAT_803dc074 - *(float *)(iVar5 + 0xc));
  }
  *(float *)(iVar5 + 4) =
       FLOAT_803dc074 * (*(float *)(iVar5 + 8) + *(float *)(iVar5 + 0xc)) + *(float *)(iVar5 + 4);
  iVar5 = (int)(FLOAT_803e5be4 * *(float *)(iVar5 + 4));
  FUN_8011f9c4(0x60,0x39,(short)iVar5);
  if ((iVar5 < 0x3a) && (-0x3a < iVar5)) {
    uVar3 = 0;
  }
  else {
    uVar3 = 1;
  }
  return uVar3;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801C50C4
 * EN v1.0 Size: 616b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_801c50c4(undefined4 param_1,undefined4 param_2,int param_3)
{
}
