/*
 * Auto-generated by tools/orig/object_class_packets.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists as a class-level recovery packet for early file-boundary work.
 *
 * Class ID: 0x007E
 * Reference class name: CmbSrc
 * Suggested packet name: CmbSrc
 * Output path: src/main/unknown/classes/class_007E_cmbsrc.c
 * Retail placements: 1089
 * Retail object defs: 7
 * DLL IDs: 0x02B1, 0x02B2
 * Descriptor-backed DLL IDs: 0x02B1, 0x02B2
 * Retail object record sizes: 0xA0
 * Retail root placement widths: 12w
 *
 * Retail object defs:
 * - 0x059C CmbSrc: dll=0x02B1, placements=417, romlists=27, objsize=0xA0, widths=12w x417, aliases=0x06E8
 * - 0x059D CmbSrcTPole: dll=0x02B1, placements=351, romlists=20, objsize=0xA0, widths=12w x351, aliases=0x07A8
 * - 0x05A0 DustMoteSou: dll=0x02B2, placements=153, romlists=24, objsize=0xA0, widths=12w x153, aliases=0x0802
 * - 0x059E CmbSrcTWall: dll=0x02B1, placements=147, romlists=6, objsize=0xA0, widths=12w x147, aliases=0x0853
 * - 0x05A1 TailLightSo: dll=0x02B2, placements=8, romlists=2, objsize=0xA0, widths=12w x8, aliases=0x0807
 * - 0x059F ThusterSour: dll=0x02B1, placements=7, romlists=1, objsize=0xA0, widths=12w x7, aliases=0x0758
 * - 0x05A2 FireWorkSou: dll=0x02B2, placements=6, romlists=1, objsize=0xA0, widths=12w x6, aliases=0x080E
 *
 * Descriptor slot maps:
 * - DLL 0x02B1: gCmbSrcObjDescriptor (slots=10, mask=1101111111)
 *   slot 00: 0x80237570 cmbsrc_initialise
 *   slot 01: 0x8023756C cmbsrc_release
 *   slot 03: 0x80236F90 cmbsrc_init
 *   slot 04: 0x80236D84 cmbsrc_update
 *   slot 05: 0x80236C9C cmbsrc_hitDetect
 *   slot 06: 0x80236BE4 cmbsrc_render
 *   slot 07: 0x80236B80 cmbsrc_free
 *   slot 08: 0x80236B78 cmbsrc_func08
 *   slot 09: 0x80236B70 cmbsrc_getExtraSize
 * - DLL 0x02B2: gDustMoteSouObjDescriptor (slots=10, mask=1101111111)
 *   slot 00: 0x80237804 dustmotesou_initialise
 *   slot 01: 0x80237800 dustmotesou_release
 *   slot 03: 0x802377BC dustmotesou_init
 *   slot 04: 0x802375C4 dustmotesou_update
 *   slot 05: 0x802375C0 dustmotesou_hitDetect
 *   slot 06: 0x802375B4 dustmotesou_render
 *   slot 07: 0x80237584 dustmotesou_free
 *   slot 08: 0x8023757C dustmotesou_func08
 *   slot 09: 0x80237574 dustmotesou_getExtraSize
 */

#if 0
/*
 * Reference-only class packet enums. Verify against EN before promoting names into live code.
 */
enum class_007E_CmbSrc_defs {
    CMBSRC_CMBSRC = 0x059C,
    CMBSRC_CMBSRCTPOLE = 0x059D,
    CMBSRC_DUSTMOTESOU = 0x05A0,
    CMBSRC_CMBSRCTWALL = 0x059E,
    CMBSRC_TAILLIGHTSO = 0x05A1,
    CMBSRC_THUSTERSOUR = 0x059F,
    CMBSRC_FIREWORKSOU = 0x05A2,
};
#endif
