/*
 * Auto-generated by tools/orig/object_class_packets.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists as a class-level recovery packet for early file-boundary work.
 *
 * Class ID: 0x006C
 * Reference class name: KT_RexFloorSwitch
 * Suggested packet name: KT_RexFloorSwitch
 * Output path: src/main/unknown/classes/class_006C_kt_rexfloorswitch.c
 * Retail placements: 8
 * Retail object defs: 1
 * DLL IDs: 0x0251
 * Descriptor-backed DLL IDs: 0x0251
 * Retail object record sizes: 0xC0
 * Retail root placement widths: 9w
 *
 * Retail object defs:
 * - 0x008E KT_RexFloor: dll=0x0251, placements=8, romlists=1, objsize=0xC0, widths=9w x8, aliases=0x03DD
 *
 * Descriptor slot maps:
 * - DLL 0x0251: gKtRexFloorSwitchObjDescriptor (slots=10, mask=1101111111)
 *   slot 00: 0x802164CC ktrexfloorswitch_initialise
 *   slot 01: 0x802164C8 ktrexfloorswitch_release
 *   slot 03: 0x802163FC ktrexfloorswitch_init
 *   slot 04: 0x80215A84 ktrexfloorswitch_update
 *   slot 05: 0x80215A80 ktrexfloorswitch_hitDetect
 *   slot 06: 0x80215A50 ktrexfloorswitch_render
 *   slot 07: 0x80215A4C ktrexfloorswitch_free
 *   slot 08: 0x80215A44 ktrexfloorswitch_func08
 *   slot 09: 0x80215A3C ktrexfloorswitch_getExtraSize
 */

#if 0
/*
 * Reference-only class packet enums. Verify against EN before promoting names into live code.
 */
enum class_006C_KT_RexFloorSwitch_defs {
    KT_REXFLOORSWITCH_KT_REXFLOOR = 0x008E,
};
#endif
