/*
 * Auto-generated by tools/orig/object_class_packets.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists as a class-level recovery packet for early file-boundary work.
 *
 * Class ID: 0x0053
 * Reference class name: Door53
 * Suggested packet name: Door53
 * Output path: src/main/unknown/classes/class_0053_door53.c
 * Retail placements: 164
 * Retail object defs: 77
 * DLL IDs: 0x0110, 0x015D, 0x0176, 0x0177, 0x017F
 * Descriptor-backed DLL IDs: 0x0110, 0x015D, 0x0176, 0x0177, 0x017F
 * Retail object record sizes: 0xA0, 0xC0, 0xE0, 0x120
 * Retail root placement widths: 9w
 * Fixed maps: dim2 ice block1, dim2 ice block2
 *
 * Retail object defs:
 * - 0x02DD SC_Shrine_d: dll=0x0110, placements=18, romlists=6, objsize=0xE0, widths=9w x18, aliases=0x044D
 * - 0x02DF SC_settelme: dll=0x0110, placements=11, romlists=7, objsize=0xE0, widths=9w x11, aliases=0x0289
 * - 0x0296 SH_Portcull: dll=0x0110, placements=10, romlists=5, objsize=0xE0, widths=9w x10, aliases=0x010C
 * - 0x01D4 LINK_Portcu: dll=0x0110, placements=9, romlists=3, objsize=0xE0, widths=9w x9, aliases=0x01C2
 * - 0x02E3 SC_stepping: dll=0x0110, placements=9, romlists=1, objsize=0xC0, widths=9w x9, aliases=0x0707
 * - 0x050E MSBush: dll=0x017F, placements=9, romlists=2, objsize=0xC0, widths=9w x9, aliases=0x0523
 * - 0x050F MSVine: dll=0x017F, placements=9, romlists=2, objsize=0xC0, widths=9w x9, aliases=0x0524
 * - 0x0167 DIMWoodDoor: dll=0x0110, placements=8, romlists=1, objsize=0xC0, widths=9w x8, aliases=0x024B
 * - 0x02E0 BossTRexPor: dll=0x0110, placements=8, romlists=1, objsize=0xE0, widths=9w x8, aliases=0x0821
 * - 0x0372 DFP_RoundDo: dll=0x0110, placements=6, romlists=1, objsize=0xC0, widths=9w x6, aliases=0x042E
 * - 0x0252 GF_DoorLeft: dll=0x0110, placements=4, romlists=2, objsize=0xC0, widths=9w x4, aliases=0x0770
 * - 0x0144 WCSunInside: dll=0x0110, placements=3, romlists=1, objsize=0xC0, widths=9w x3, aliases=0x00A5
 * - 0x0145 WCMoonInsid: dll=0x0110, placements=3, romlists=1, objsize=0xC0, widths=9w x3, aliases=0x0052
 * - 0x00B5 CFPrisonDoo: dll=0x0110, placements=2, romlists=1, objsize=0xC0, widths=9w x2, aliases=0x00C1
 * - 0x0136 WCGeneralDo: dll=0x0110, placements=2, romlists=1, objsize=0xC0, widths=9w x2, aliases=0x0527
 * - 0x018E DIM2IcePlat: dll=0x0110, placements=2, romlists=1, objsize=0xC0, widths=9w x2, map=dim2 ice block1, aliases=0x07C7
 * - 0x01E7 CCwaterShut: dll=0x0110, placements=2, romlists=1, objsize=0xC0, widths=9w x2, aliases=0x0100
 * - 0x01EF CCclawOnlyD: dll=0x0110, placements=2, romlists=2, objsize=0xC0, widths=9w x2, aliases=0x00DE
 * - 0x026C NW_Portcull: dll=0x0110, placements=2, romlists=1, objsize=0xE0, widths=9w x2, aliases=0x022E
 * - 0x0343 OFPclawOnly: dll=0x0110, placements=2, romlists=1, objsize=0xC0, widths=9w x2, aliases=0x0884
 * - 0x034D DFP_Bridge: dll=0x0110, placements=2, romlists=1, objsize=0xC0, widths=9w x2, aliases=0x06FB
 * - 0x03A5 WM_Door1: dll=0x0110, placements=2, romlists=1, objsize=0xC0, widths=9w x2, aliases=0x013E
 * - 0x008C KT_RexDoorP: dll=0x0110, placements=1, romlists=1, objsize=0xC0, widths=9w x1, aliases=0x03DB
 * - 0x008D KT_RexDoorT: dll=0x0110, placements=1, romlists=1, objsize=0xC0, widths=9w x1, aliases=0x03DC
 * - 0x00B6 CFWinPrison: dll=0x0110, placements=1, romlists=1, objsize=0xC0, widths=9w x1, aliases=0x05E9
 * - 0x00E6 CFTreasureD: dll=0x0110, placements=1, romlists=1, objsize=0xE0, widths=9w x1
 * - 0x00FB CFExplosive: dll=0x0110, placements=1, romlists=1, objsize=0xC0, widths=9w x1, aliases=0x05A0
 * - 0x0100 CFMainDoorA: dll=0x0110, placements=1, romlists=1, objsize=0xC0, widths=9w x1, aliases=0x009B
 * - 0x0102 CFBrokenPil: dll=0x0110, placements=1, romlists=1, objsize=0xC0, widths=9w x1, aliases=0x079A
 * - 0x011F WCTempleDoo: dll=0x0110, placements=1, romlists=1, objsize=0xC0, widths=9w x1, aliases=0x079F
 * - 0x0120 WCTempleDoo: dll=0x0110, placements=1, romlists=1, objsize=0xC0, widths=9w x1, aliases=0x07A4
 * - 0x0121 WCTempleDoo: dll=0x0110, placements=1, romlists=1, objsize=0xC0, widths=9w x1, aliases=0x0506
 * - 0x0127 WCSlabDoor: dll=0x0110, placements=1, romlists=1, objsize=0xE0, widths=9w x1, aliases=0x050C
 * - 0x0135 WCBossDoor: dll=0x0110, placements=1, romlists=1, objsize=0xC0, widths=9w x1, aliases=0x0511
 * - 0x0164 DIM_Portcul: dll=0x0110, placements=1, romlists=1, objsize=0xE0, widths=9w x1, aliases=0x030F
 * - 0x018F DIM2IcePlat: dll=0x0110, placements=1, romlists=1, objsize=0xC0, widths=9w x1, map=dim2 ice block2, aliases=0x07C9
 * - 0x0190 DIM2TrapDoo: dll=0x0110, placements=1, romlists=1, objsize=0xC0, widths=9w x1, aliases=0x0110
 * - 0x0192 DIM2TrapDoo: dll=0x0110, placements=1, romlists=1, objsize=0xC0, widths=9w x1, aliases=0x07C0
 * - 0x0198 DIM2CellDoo: dll=0x0110, placements=1, romlists=1, objsize=0xE0, widths=9w x1, aliases=0x0167
 * - 0x019A DIM2CellDoo: dll=0x0110, placements=1, romlists=1, objsize=0xE0, widths=9w x1, aliases=0x014C
 * - 0x01A1 DIM2PuzzleD: dll=0x0110, placements=1, romlists=1, objsize=0xC0, widths=9w x1, aliases=0x012B
 * - 0x01B1 DIM2IceGrat: dll=0x0110, placements=1, romlists=1, objsize=0xC0, widths=9w x1, aliases=0x00F3
 * - 0x01C2 IMPrisonGat: dll=0x0110, placements=1, romlists=1, objsize=0xE0, widths=9w x1, aliases=0x0166
 * - 0x01CA IMFence: dll=0x0110, placements=1, romlists=1, objsize=0xE0, widths=9w x1, aliases=0x00F1
 * - 0x01EB CCOceanDoor: dll=0x0110, placements=1, romlists=1, objsize=0xC0, widths=9w x1, aliases=0x00FD
 * - 0x01EE CCskullDoor: dll=0x0110, placements=1, romlists=1, objsize=0xC0, widths=9w x1, aliases=0x00ED
 * - 0x01F0 CCprisonDoo: dll=0x0110, placements=1, romlists=1, objsize=0xC0, widths=9w x1, aliases=0x00B6
 * - 0x01F9 CCclawdoor: dll=0x0110, placements=1, romlists=1, objsize=0xC0, widths=9w x1, aliases=0x02F5
 * - 0x0258 MMP_MagicCa: dll=0x0110, placements=1, romlists=1, objsize=0xC0, widths=9w x1, aliases=0x0825
 * - 0x0294 SH_MagicCav: dll=0x0110, placements=1, romlists=1, objsize=0x120, widths=9w x1, aliases=0x010F
 * - 0x0295 SH_QueensDo: dll=0x0110, placements=1, romlists=1, objsize=0xC0, widths=9w x1, aliases=0x010E
 * - 0x02DE SC_mounddoo: dll=0x0110, placements=1, romlists=1, objsize=0xC0, widths=9w x1, aliases=0x0288
 * - 0x02E1 SC_capeclaw: dll=0x0110, placements=1, romlists=1, objsize=0xC0, widths=9w x1, aliases=0x05C3
 * - 0x02E4 SC_hutdoor: dll=0x0110, placements=1, romlists=1, objsize=0xC0, widths=9w x1, aliases=0x07D7
 * - 0x0337 VFP_Doorloc: dll=0x0110, placements=1, romlists=1, objsize=0xC0, widths=9w x1, aliases=0x03AC
 * - 0x03B6 WMFinalDoor: dll=0x0110, placements=1, romlists=1, objsize=0xC0, widths=9w x1, aliases=0x0161
 * - 0x042E DR_EarthDoo: dll=0x0110, placements=1, romlists=1, objsize=0xC0, widths=9w x1, aliases=0x0864
 * - 0x045A DR_CloudDoo: dll=0x0110, placements=1, romlists=1, objsize=0xC0, widths=9w x1, aliases=0x0473
 * - 0x0460 DR_HighDoor: dll=0x0110, placements=1, romlists=1, objsize=0xC0, widths=9w x1, aliases=0x0489
 * - 0x0470 DR_DrakorDo: dll=0x0110, placements=1, romlists=1, objsize=0xC0, widths=9w x1, aliases=0x07E0
 * - 0x049E MCProjDoor: dll=0x0110, placements=1, romlists=1, objsize=0xE0, widths=9w x1, aliases=0x0106
 * - 0x00CF CFSlideDoor: dll=0x015D, placements=0, romlists=0, objsize=0xC0, widths=none, aliases=0x00D5
 * - 0x00D0 CFMainSlide: dll=0x015D, placements=0, romlists=0, objsize=0xC0, widths=none, aliases=0x00B7
 * - 0x00D5 CF_MovDeckD: dll=0x0110, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x0332
 * - 0x0123 WCSunTemple: dll=0x0110, placements=0, romlists=0, objsize=0xC0, widths=none, aliases=0x050A
 * - 0x0124 WCMoonTempl: dll=0x0110, placements=0, romlists=0, objsize=0xC0, widths=none, aliases=0x050B
 * - 0x0147 WCTempleTop: dll=0x0110, placements=0, romlists=0, objsize=0xC0, widths=none, aliases=0x077C
 * - 0x02CC KP_SectionD: dll=0x0110, placements=0, romlists=0, objsize=0xC0, widths=none, aliases=0x059C
 * - 0x02CD KP_FinDoor: dll=0x0110, placements=0, romlists=0, objsize=0xC0, widths=none, aliases=0x059E
 * - 0x03C1 SPDoor: dll=0x0110, placements=0, romlists=0, objsize=0xC0, widths=none, aliases=0x047E
 * - 0x0409 EC_Shrine_d: dll=0x0110, placements=0, romlists=0, objsize=0xE0, widths=none, aliases=0x0743
 * - 0x0439 DR_Shield: dll=0x0110, placements=0, romlists=0, objsize=0xE0, widths=none, aliases=0x06CC
 * - 0x0462 DR_James1Bo: dll=0x0110, placements=0, romlists=0, objsize=0xC0, widths=none, aliases=0x0737
 * - 0x05BD DFSH_Door1S: dll=0x0176, placements=0, romlists=0, objsize=0xE0, widths=none, aliases=0x008B
 * - 0x05BE DFSH_Door2S: dll=0x0177, placements=0, romlists=0, objsize=0xC0, widths=none, aliases=0x03A1
 * - 0x05C0 DFSH_Door3S: dll=0x0177, placements=0, romlists=0, objsize=0xC0, widths=none, aliases=0x03A2
 * - 0x05C1 DFSH_Door4S: dll=0x0177, placements=0, romlists=0, objsize=0xC0, widths=none, aliases=0x03A3
 *
 * Descriptor slot maps:
 * - DLL 0x0110: gDoorObjDescriptor (slots=10, mask=0001101001)
 *   slot 03: 0x8017B9CC Door_init
 *   slot 04: 0x8017B908 Door_update
 *   slot 06: 0x8017B8E4 Door_render
 *   slot 09: 0x8017B8DC Door_getExtraSize
 * - DLL 0x015D: gSlidingDoorObjDescriptor (slots=10, mask=1101111111)
 *   slot 00: 0x801A41D4 slidingdoor_initialise
 *   slot 01: 0x801A41D0 slidingdoor_release
 *   slot 03: 0x801A4154 slidingdoor_init
 *   slot 04: 0x801A40AC slidingdoor_update
 *   slot 05: 0x801A40A8 slidingdoor_hitDetect
 *   slot 06: 0x801A4078 slidingdoor_render
 *   slot 07: 0x801A4074 slidingdoor_free
 *   slot 08: 0x801A406C slidingdoor_func08
 *   slot 09: 0x801A4064 slidingdoor_getExtraSize
 * - DLL 0x0176: lbl_80325F20 (slots=1, mask=0)
 * - DLL 0x0177: gDFSH_Door2SpeciObjDescriptor (slots=10, mask=1101111111)
 *   slot 00: 0x801C2910 dfsh_door2speci_initialise
 *   slot 01: 0x801C290C dfsh_door2speci_release
 *   slot 03: 0x801C2868 dfsh_door2speci_init
 *   slot 04: 0x801C2864 dfsh_door2speci_update
 *   slot 05: 0x801C2860 dfsh_door2speci_hitDetect
 *   slot 06: 0x801C2830 dfsh_door2speci_render
 *   slot 07: 0x801C282C dfsh_door2speci_free
 *   slot 08: 0x801C2824 dfsh_door2speci_func08
 *   slot 09: 0x801C281C dfsh_door2speci_getExtraSize
 * - DLL 0x017F: gMoonSeedBushObjDescriptor (slots=10, mask=1101111111)
 *   slot 00: 0x801A6F48 MoonSeedBush_initialise
 *   slot 01: 0x801A6F44 MoonSeedBush_release
 *   slot 03: 0x801A6E70 MoonSeedBush_init
 *   slot 04: 0x801A6DA4 MoonSeedBush_update
 *   slot 05: 0x801A6DA0 MoonSeedBush_hitDetect
 *   slot 06: 0x801A6D70 MoonSeedBush_render
 *   slot 07: 0x801A6D6C MoonSeedBush_free
 *   slot 08: 0x801A6D64 MoonSeedBush_func08
 *   slot 09: 0x801A6D5C MoonSeedBush_getExtraSize
 */

#if 0
/*
 * Reference-only class packet enums. Verify against EN before promoting names into live code.
 */
enum class_0053_Door53_defs {
    DOOR53_SC_SHRINE_D = 0x02DD,
    DOOR53_SC_SETTELME = 0x02DF,
    DOOR53_SH_PORTCULL = 0x0296,
    DOOR53_LINK_PORTCU = 0x01D4,
    DOOR53_SC_STEPPING = 0x02E3,
    DOOR53_MSBUSH = 0x050E,
    DOOR53_MSVINE = 0x050F,
    DOOR53_DIMWOODDOOR = 0x0167,
    DOOR53_BOSSTREXPOR = 0x02E0,
    DOOR53_DFP_ROUNDDO = 0x0372,
    DOOR53_GF_DOORLEFT = 0x0252,
    DOOR53_WCSUNINSIDE = 0x0144,
    DOOR53_WCMOONINSID = 0x0145,
    DOOR53_CFPRISONDOO = 0x00B5,
    DOOR53_WCGENERALDO = 0x0136,
    DOOR53_DIM2ICEPLAT = 0x018E,
    DOOR53_CCWATERSHUT = 0x01E7,
    DOOR53_CCCLAWONLYD = 0x01EF,
    DOOR53_NW_PORTCULL = 0x026C,
    DOOR53_OFPCLAWONLY = 0x0343,
    DOOR53_DFP_BRIDGE = 0x034D,
    DOOR53_WM_DOOR1 = 0x03A5,
    DOOR53_KT_REXDOORP = 0x008C,
    DOOR53_KT_REXDOORT = 0x008D,
    DOOR53_CFWINPRISON = 0x00B6,
    DOOR53_CFTREASURED = 0x00E6,
    DOOR53_CFEXPLOSIVE = 0x00FB,
    DOOR53_CFMAINDOORA = 0x0100,
    DOOR53_CFBROKENPIL = 0x0102,
    DOOR53_WCTEMPLEDOO = 0x011F,
    DOOR53_WCTEMPLEDOO_0120 = 0x0120,
    DOOR53_WCTEMPLEDOO_0121 = 0x0121,
    DOOR53_WCSLABDOOR = 0x0127,
    DOOR53_WCBOSSDOOR = 0x0135,
    DOOR53_DIM_PORTCUL = 0x0164,
    DOOR53_DIM2ICEPLAT_018F = 0x018F,
    DOOR53_DIM2TRAPDOO = 0x0190,
    DOOR53_DIM2TRAPDOO_0192 = 0x0192,
    DOOR53_DIM2CELLDOO = 0x0198,
    DOOR53_DIM2CELLDOO_019A = 0x019A,
    DOOR53_DIM2PUZZLED = 0x01A1,
    DOOR53_DIM2ICEGRAT = 0x01B1,
    DOOR53_IMPRISONGAT = 0x01C2,
    DOOR53_IMFENCE = 0x01CA,
    DOOR53_CCOCEANDOOR = 0x01EB,
    DOOR53_CCSKULLDOOR = 0x01EE,
    DOOR53_CCPRISONDOO = 0x01F0,
    DOOR53_CCCLAWDOOR = 0x01F9,
    DOOR53_MMP_MAGICCA = 0x0258,
    DOOR53_SH_MAGICCAV = 0x0294,
    DOOR53_SH_QUEENSDO = 0x0295,
    DOOR53_SC_MOUNDDOO = 0x02DE,
    DOOR53_SC_CAPECLAW = 0x02E1,
    DOOR53_SC_HUTDOOR = 0x02E4,
    DOOR53_VFP_DOORLOC = 0x0337,
    DOOR53_WMFINALDOOR = 0x03B6,
    DOOR53_DR_EARTHDOO = 0x042E,
    DOOR53_DR_CLOUDDOO = 0x045A,
    DOOR53_DR_HIGHDOOR = 0x0460,
    DOOR53_DR_DRAKORDO = 0x0470,
    DOOR53_MCPROJDOOR = 0x049E,
    DOOR53_CFSLIDEDOOR = 0x00CF,
    DOOR53_CFMAINSLIDE = 0x00D0,
    DOOR53_CF_MOVDECKD = 0x00D5,
    DOOR53_WCSUNTEMPLE = 0x0123,
    DOOR53_WCMOONTEMPL = 0x0124,
    DOOR53_WCTEMPLETOP = 0x0147,
    DOOR53_KP_SECTIOND = 0x02CC,
    DOOR53_KP_FINDOOR = 0x02CD,
    DOOR53_SPDOOR = 0x03C1,
    DOOR53_EC_SHRINE_D = 0x0409,
    DOOR53_DR_SHIELD = 0x0439,
    DOOR53_DR_JAMES1BO = 0x0462,
    DOOR53_DFSH_DOOR1S = 0x05BD,
    DOOR53_DFSH_DOOR2S = 0x05BE,
    DOOR53_DFSH_DOOR3S = 0x05C0,
    DOOR53_DFSH_DOOR4S = 0x05C1,
};
#endif
