/*
 * Auto-generated by tools/orig/object_class_packets.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists as a class-level recovery packet for early file-boundary work.
 *
 * Class ID: 0x0061
 * Reference class name: various0061
 * Suggested packet name: various0061
 * Output path: src/main/unknown/classes/class_0061_various0061.c
 * Retail placements: 2907
 * Retail object defs: 213
 * DLL IDs: 0x00D2, 0x00D6, 0x0100, 0x010E, 0x0119, 0x011A, 0x011E, 0x012E, 0x012F, 0x015C, 0x0161, 0x0172, 0x0173, 0x0185, 0x0186, 0x0187, 0x0188, 0x018A, 0x018B, 0x01A2, 0x01A3, 0x01A4, 0x01A5, 0x01A6, 0x01B0, 0x01B1, 0x01B2, 0x01B8, 0x01BA, 0x01D0, 0x01D2, 0x01D3, 0x01F4, 0x01F6, 0x0215, 0x0262, 0x0274, 0x0275, 0x029B, 0x029C, 0x029D, 0x02A2, 0x02B0, 0x02B9, 0x02BA, 0x02BC, 0x02BD, 0x02BE, 0x02BF, 0xFFFF
 * Descriptor-backed DLL IDs: 0x00D2, 0x00D6, 0x0100, 0x010E, 0x0119, 0x011A, 0x011E, 0x012E, 0x012F, 0x0172, 0x0173, 0x0185, 0x0186, 0x0187, 0x0188, 0x018A, 0x018B, 0x01A2, 0x01A3, 0x01A4, 0x01A5, 0x01A6, 0x01B0, 0x01B1, 0x01B2, 0x01B8, 0x01BA, 0x01D0, 0x01D2, 0x01D3, 0x01F4, 0x01F6, 0x0215, 0x0262, 0x029B, 0x029C, 0x029D, 0x02A2, 0x02B0, 0x02B9, 0x02BA, 0x02BC, 0x02BD, 0x02BE, 0x02BF
 * Retail object record sizes: 0xA0, 0xC0, 0xE0, 0x100, 0x120, 0x140, 0x160, 0x2E0
 * Retail root placement widths: 8w
 * Fixed maps: dfcradle, dim2icefloe, dim2icefloe1, dim2icefloe2
 *
 * Retail object defs:
 * - 0x04C4 TrickyWarp: dll=0x0100, placements=2139, romlists=19, objsize=0xA0, widths=8w x2139, aliases=0x031C
 * - 0x007F DRDebrisGir: dll=0x011A, placements=65, romlists=1, objsize=0xA0, widths=8w x65, aliases=0x07A1
 * - 0x058D SnowLog: dll=0x011A, placements=65, romlists=3, objsize=0xA0, widths=8w x65, aliases=0x070E
 * - 0x0082 DRDebrisPip: dll=0x011A, placements=63, romlists=2, objsize=0xA0, widths=8w x63, aliases=0x07A3
 * - 0x0592 CobwebCeili: dll=0x011A, placements=54, romlists=4, objsize=0xA0, widths=8w x54, aliases=0x06C6
 * - 0x0587 SnowBoulder: dll=0x02B0, placements=40, romlists=3, objsize=0xA0, widths=8w x40, aliases=0x0038
 * - 0x0593 CobwebEdge: dll=0x011A, placements=32, romlists=6, objsize=0xA0, widths=8w x32, aliases=0x06C7
 * - 0x056B AlienTreePa: dll=0x011A, placements=26, romlists=3, objsize=0xA0, widths=8w x26, aliases=0x06B2
 * - 0x00A1 CFLightWall: dll=0x012E, placements=25, romlists=1, objsize=0xA0, widths=8w x25, aliases=0x00C0
 * - 0x0081 DRDebrisPip: dll=0x011A, placements=24, romlists=1, objsize=0xA0, widths=8w x24, aliases=0x07A2
 * - 0x057D BoulderOne: dll=0x02B0, placements=24, romlists=4, objsize=0xA0, widths=8w x24, aliases=0x0649
 * - 0x0591 CobwebCorne: dll=0x011A, placements=24, romlists=7, objsize=0xA0, widths=8w x24, aliases=0x06C5
 * - 0x04A2 MCLightning: dll=0x02BA, placements=20, romlists=7, objsize=0xA0, widths=8w x20, aliases=0x011C
 * - 0x00A5 CFGCrubble2: dll=0x012E, placements=17, romlists=1, objsize=0xA0, widths=8w x17, aliases=0x063F
 * - 0x058F SulphurCrys: dll=0x011A, placements=16, romlists=2, objsize=0xA0, widths=8w x16, aliases=0x0062
 * - 0x00A0 CFLightPill: dll=0x012E, placements=15, romlists=1, objsize=0xA0, widths=8w x15, aliases=0x0653
 * - 0x00A6 CFGCrubble3: dll=0x012E, placements=14, romlists=1, objsize=0xA0, widths=8w x14, aliases=0x0640
 * - 0x0027 KaldachomMe: dll=0x00D6, placements=13, romlists=1, objsize=0xA0, widths=8w x13, aliases=0x0824
 * - 0x00A7 CFGCrubble4: dll=0x012E, placements=13, romlists=1, objsize=0xA0, widths=8w x13, aliases=0x0641
 * - 0x0107 CF_Lamp: dll=0x01F4, placements=12, romlists=1, objsize=0xC0, widths=8w x12, aliases=0x03E4
 * - 0x0566 DirectionSi: dll=0x012E, placements=10, romlists=5, objsize=0xC0, widths=8w x10, aliases=0x081A
 * - 0x04A1 MCStaffEffe: dll=0x02B9, placements=9, romlists=1, objsize=0xA0, widths=8w x9, aliases=0x011B
 * - 0x01F6 CCdarkness: dll=0x012E, placements=8, romlists=1, objsize=0xA0, widths=8w x8, aliases=0x0092
 * - 0x057E RedBoulder: dll=0x02B0, placements=8, romlists=1, objsize=0xA0, widths=8w x8, aliases=0x0700
 * - 0x059B WaterLillyF: dll=0x011A, placements=7, romlists=1, objsize=0xA0, widths=8w x7, aliases=0x06F7
 * - 0x02EA SC_totempuz: dll=0x01BA, placements=6, romlists=1, objsize=0xC0, widths=8w x6, aliases=0x03C1
 * - 0x0538 ARWArwingGu: dll=0x029D, placements=6, romlists=6, objsize=0xC0, widths=8w x6, aliases=0x0610
 * - 0x0539 ARWArwingGu: dll=0x029D, placements=6, romlists=6, objsize=0xC0, widths=8w x6, aliases=0x0615
 * - 0x053A ARWArwingRo: dll=0x029D, placements=6, romlists=6, objsize=0xC0, widths=8w x6, aliases=0x0611
 * - 0x00A8 CFGCpillbre: dll=0x012E, placements=5, romlists=1, objsize=0xA0, widths=8w x5, aliases=0x0643
 * - 0x01CB LINK_levcon: dll=0x0173, placements=5, romlists=5, objsize=0xA0, widths=8w x5, aliases=0x0812
 * - 0x0504 BarrelPad: dll=0x012F, placements=5, romlists=4, objsize=0xA0, widths=8w x5, aliases=0x0748
 * - 0x009E CFrunnersta: dll=0x012E, placements=4, romlists=1, objsize=0xA0, widths=8w x4, aliases=0x063D
 * - 0x01FA CCgasvent: dll=0x0185, placements=4, romlists=1, objsize=0xA0, widths=8w x4, aliases=0x05AC
 * - 0x021A WORLDshield: dll=0x012E, placements=4, romlists=1, objsize=0xA0, widths=8w x4, aliases=0x0811
 * - 0x02E9 SC_totempol: dll=0x01B8, placements=4, romlists=1, objsize=0xA0, widths=8w x4, aliases=0x038F
 * - 0x0580 Cactus: dll=0x02B0, placements=4, romlists=1, objsize=0xA0, widths=8w x4, aliases=0x0749
 * - 0x0080 InfoTablet: dll=0x012E, placements=3, romlists=2, objsize=0xA0, widths=8w x3, aliases=0x0816
 * - 0x01D8 LINKSnowLog: dll=0x011A, placements=3, romlists=1, objsize=0xA0, widths=8w x3, aliases=0x0211
 * - 0x01ED CCpedstal: dll=0x018A, placements=3, romlists=1, objsize=0x100, widths=8w x3, aliases=0x00F0
 * - 0x0212 WORLDsun: dll=0x01D3, placements=3, romlists=1, objsize=0xC0, widths=8w x3, aliases=0x05E2
 * - 0x0218 WORLDastGen: dll=0x01D3, placements=3, romlists=1, objsize=0xA0, widths=8w x3, aliases=0x061E
 * - 0x036C VFPSplstne: dll=0x012E, placements=3, romlists=2, objsize=0xA0, widths=8w x3, aliases=0x087C
 * - 0x04DC coldWaterCo: dll=0x0119, placements=3, romlists=3, objsize=0xC0, widths=8w x3, aliases=0x0572
 * - 0x00A9 CFGCsmallbl: dll=0x012E, placements=2, romlists=1, objsize=0xA0, widths=8w x2, aliases=0x0644
 * - 0x0251 GF_JukeBox: dll=0x012E, placements=2, romlists=2, objsize=0xA0, widths=8w x2, aliases=0x075F
 * - 0x0271 NWCallOFEld: dll=0x012F, placements=2, romlists=1, objsize=0xE0, widths=8w x2, aliases=0x0079
 * - 0x02EE SC_DummyTri: dll=0x011A, placements=2, romlists=1, objsize=0xA0, widths=8w x2, aliases=0x07D0
 * - 0x02EF SC_DummySqu: dll=0x011A, placements=2, romlists=1, objsize=0xA0, widths=8w x2, aliases=0x07D1
 * - 0x02F0 SC_DummyCir: dll=0x011A, placements=2, romlists=1, objsize=0xA0, widths=8w x2, aliases=0x07D2
 * - 0x0314 VFP_Warding: dll=0x012E, placements=2, romlists=1, objsize=0xA0, widths=8w x2, aliases=0x0729
 * - 0x036A DFPSplstne: dll=0x012E, placements=2, romlists=2, objsize=0xA0, widths=8w x2, aliases=0x087B
 * - 0x049D MagicCaveBo: dll=0x011E, placements=2, romlists=1, objsize=0xE0, widths=8w x2, aliases=0x0029
 * - 0x0075 DIMSpellsto: dll=0x012E, placements=1, romlists=1, objsize=0xA0, widths=8w x1, aliases=0x0867
 * - 0x0125 WCSunDoor: dll=0x012E, placements=1, romlists=1, objsize=0xC0, widths=8w x1, aliases=0x051F
 * - 0x0126 WCMoonDoor: dll=0x012E, placements=1, romlists=1, objsize=0xC0, widths=8w x1, aliases=0x0520
 * - 0x0180 DIM_tricky: dll=0x01D0, placements=1, romlists=1, objsize=0xA0, widths=8w x1, aliases=0x0711
 * - 0x01DD LINKB_levco: dll=0x0172, placements=1, romlists=1, objsize=0xC0, widths=8w x1, aliases=0x018C
 * - 0x01E4 CClevcontro: dll=0x018B, placements=1, romlists=1, objsize=0xA0, widths=8w x1, aliases=0x0105
 * - 0x01F4 CClightfoot: dll=0x0188, placements=1, romlists=1, objsize=0x100, widths=8w x1, aliases=0x00A6
 * - 0x01F8 CCqueen: dll=0x0187, placements=1, romlists=1, objsize=0xC0, widths=8w x1, aliases=0x0086
 * - 0x01FB CCgasventCo: dll=0x0186, placements=1, romlists=1, objsize=0xC0, widths=8w x1, aliases=0x05AD
 * - 0x0202 WORLDplanet: dll=0x01D2, placements=1, romlists=1, objsize=0xA0, widths=8w x1, aliases=0x05D4
 * - 0x0203 WORLDcloudr: dll=0x01D3, placements=1, romlists=1, objsize=0xC0, widths=8w x1, aliases=0x05D5
 * - 0x0204 WORLDdragro: dll=0x01D3, placements=1, romlists=1, objsize=0xC0, widths=8w x1, aliases=0x05D6
 * - 0x0205 WORLDwalled: dll=0x01D3, placements=1, romlists=1, objsize=0xC0, widths=8w x1, aliases=0x05D7
 * - 0x0206 WORLDdarkic: dll=0x01D3, placements=1, romlists=1, objsize=0xC0, widths=8w x1, aliases=0x05D8
 * - 0x0207 WORLDcloudl: dll=0x01D3, placements=1, romlists=1, objsize=0xE0, widths=8w x1, aliases=0x05DC
 * - 0x0208 WORLDpath1: dll=0x01D3, placements=1, romlists=1, objsize=0x2E0, widths=8w x1, aliases=0x05DD
 * - 0x0209 WORLDpath2: dll=0x01D3, placements=1, romlists=1, objsize=0x2E0, widths=8w x1, aliases=0x05ED
 * - 0x020A WORLDpath3: dll=0x01D3, placements=1, romlists=1, objsize=0x2E0, widths=8w x1, aliases=0x05EE
 * - 0x020B WORLDpath4: dll=0x01D3, placements=1, romlists=1, objsize=0x2E0, widths=8w x1, aliases=0x05EF
 * - 0x020C WORLDpath5: dll=0x01D3, placements=1, romlists=1, objsize=0x2E0, widths=8w x1, aliases=0x05F0
 * - 0x020D WORLDpath6: dll=0x01D3, placements=1, romlists=1, objsize=0x2E0, widths=8w x1, aliases=0x05F1
 * - 0x020E WORLDpath7: dll=0x01D3, placements=1, romlists=1, objsize=0x2E0, widths=8w x1, aliases=0x05F2
 * - 0x020F WORLDpath8: dll=0x01D3, placements=1, romlists=1, objsize=0x2E0, widths=8w x1, aliases=0x05F3
 * - 0x0210 WORLDarwing: dll=0x01D3, placements=1, romlists=1, objsize=0xA0, widths=8w x1, aliases=0x05DE
 * - 0x0211 WORLDgreatf: dll=0x01D3, placements=1, romlists=1, objsize=0xA0, widths=8w x1, aliases=0x05DF
 * - 0x0214 WORLDpepper: dll=0x01D3, placements=1, romlists=1, objsize=0xC0, widths=8w x1, aliases=0x05E3
 * - 0x0215 WORLDsunfla: dll=0x01D3, placements=1, romlists=1, objsize=0xA0, widths=8w x1, aliases=0x05DB
 * - 0x0219 WORLDhalo: dll=0x01D3, placements=1, romlists=1, objsize=0xA0, widths=8w x1, aliases=0x0621
 * - 0x021B WORLDhalobr: dll=0x01D3, placements=1, romlists=1, objsize=0xA0, widths=8w x1, aliases=0x0626
 * - 0x021C WORLDarrow: dll=0x01D3, placements=1, romlists=1, objsize=0xC0, widths=8w x1, aliases=0x0740
 * - 0x0228 LINKH_Asset: dll=0x012E, placements=1, romlists=1, objsize=0xA0, widths=8w x1, aliases=0x0847
 * - 0x0229 LINKC_Asset: dll=0x012E, placements=1, romlists=1, objsize=0xA0, widths=8w x1, aliases=0x0848
 * - 0x022A LINKE_Asset: dll=0x012E, placements=1, romlists=1, objsize=0xA0, widths=8w x1, aliases=0x084D
 * - 0x022B LINKJ_Asset: dll=0x012E, placements=1, romlists=1, objsize=0xA0, widths=8w x1, aliases=0x084F
 * - 0x022C LINKF_Asset: dll=0x012E, placements=1, romlists=1, objsize=0xA0, widths=8w x1, aliases=0x084E
 * - 0x0230 Andross: dll=0x02BC, placements=1, romlists=1, objsize=0x120, widths=8w x1, aliases=0x076A
 *   ref param 0x3A: size (s8)
 *   ref param 0x3B: height (s8)
 * - 0x0231 Androssleft: dll=0x02BD, placements=1, romlists=1, objsize=0xE0, widths=8w x1, aliases=0x076B
 * - 0x0232 Androssrigh: dll=0x02BD, placements=1, romlists=1, objsize=0xE0, widths=8w x1, aliases=0x076C
 * - 0x0233 AndrossBrai: dll=0x02BE, placements=1, romlists=1, objsize=0xC0, widths=8w x1, aliases=0x0772
 * - 0x024D GF_Pilotsea: dll=0x012E, placements=1, romlists=1, objsize=0xA0, widths=8w x1, aliases=0x0746
 * - 0x025F MMP_defenDo: dll=0x012E, placements=1, romlists=1, objsize=0xA0, widths=8w x1, aliases=0x02D3
 * - 0x0260 MMP_defenDo: dll=0x012E, placements=1, romlists=1, objsize=0xA0, widths=8w x1, aliases=0x02D4
 * - 0x026A NWCellLock: dll=0x012E, placements=1, romlists=1, objsize=0xA0, widths=8w x1, aliases=0x026D
 * - 0x0272 NW_levcontr: dll=0x01A5, placements=1, romlists=1, objsize=0xC0, widths=8w x1, aliases=0x006B
 * - 0x0284 NW_tricky: dll=0x01A2, placements=1, romlists=1, objsize=0xA0, widths=8w x1, aliases=0x031F
 * - 0x0285 NW_animice1: dll=0x01A3, placements=1, romlists=1, objsize=0xA0, widths=8w x1, aliases=0x0562
 * - 0x0286 NW_animice2: dll=0x01A3, placements=1, romlists=1, objsize=0xA0, widths=8w x1, aliases=0x0563
 * - 0x0287 NW_animice3: dll=0x01A3, placements=1, romlists=1, objsize=0xA0, widths=8w x1, aliases=0x0564
 * - 0x0288 NW_ice1: dll=0x01A4, placements=1, romlists=1, objsize=0xA0, widths=8w x1, map=dim2icefloe1, aliases=0x0565
 * - 0x0289 NW_ice2: dll=0x01A4, placements=1, romlists=1, objsize=0xA0, widths=8w x1, map=dim2icefloe2, aliases=0x0566
 * - 0x028A NW_ice3: dll=0x01A4, placements=1, romlists=1, objsize=0xA0, widths=8w x1, map=dim2icefloe, aliases=0x0567
 * - 0x02A9 SH_staff: dll=0x01B1, placements=1, romlists=1, objsize=0x100, widths=8w x1, aliases=0x0646
 * - 0x02AB SH_tricky: dll=0x01A6, placements=1, romlists=1, objsize=0xA0, widths=8w x1, aliases=0x02EE
 * - 0x02B4 SH_swapston: dll=0x01B0, placements=1, romlists=1, objsize=0x160, widths=8w x1, aliases=0x01CC
 * - 0x02F2 SC_throne: dll=0x011A, placements=1, romlists=1, objsize=0xA0, widths=8w x1, aliases=0x06FA
 * - 0x02F7 SB_Wheel: dll=0x01F6, placements=1, romlists=1, objsize=0xA0, widths=8w x1, aliases=0x0803
 * - 0x0336 VFP_Maindoo: dll=0x012E, placements=1, romlists=1, objsize=0xA0, widths=8w x1, aliases=0x03A7
 * - 0x0338 VFP_Maindoo: dll=0x012E, placements=1, romlists=1, objsize=0xA0, widths=8w x1, aliases=0x03AA
 * - 0x037A WM_newcryst: dll=0x0215, placements=1, romlists=1, objsize=0xA0, widths=8w x1, aliases=0x0783
 * - 0x037B WM_newcryst: dll=0x0215, placements=1, romlists=1, objsize=0xE0, widths=8w x1, aliases=0x0784
 * - 0x037C WM_newcryst: dll=0x0215, placements=1, romlists=1, objsize=0xA0, widths=8w x1, aliases=0x0785
 * - 0x037E WM_Explosiv: dll=0x012E, placements=1, romlists=1, objsize=0xA0, widths=8w x1, aliases=0x0761
 * - 0x046F DR_TrackDoo: dll=0x012E, placements=1, romlists=1, objsize=0xA0, widths=8w x1, aliases=0x04A3
 * - 0x0537 ARWSpeedStr: dll=0x02A2, placements=1, romlists=1, objsize=0xA0, widths=8w x1, aliases=0x060F
 * - 0x057B BrokenPipe: dll=0x02B0, placements=1, romlists=1, objsize=0xA0, widths=8w x1, aliases=0x0719
 * - 0x0596 GrassWeedCl: dll=0x011A, placements=1, romlists=1, objsize=0xA0, widths=8w x1, aliases=0x06E5
 * - 0x0005 TrickyBadge: dll=0xFFFF, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x0244
 * - 0x0006 TrickyBadge: dll=0xFFFF, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x0254
 * - 0x0008 ModelsWithT: dll=0xFFFF, placements=0, romlists=0, objsize=0xE0, widths=none, aliases=0x0025
 * - 0x000B TrickyExcla: dll=0xFFFF, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x0175
 * - 0x000C TrickyQuest: dll=0xFFFF, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x017C
 * - 0x000D TrickyFood: dll=0xFFFF, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x017B
 * - 0x0011 BackPack: dll=0xFFFF, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x066A
 * - 0x0015 staffEnd: dll=0xFFFF, placements=0, romlists=0, objsize=0xC0, widths=none, aliases=0x064E
 * - 0x0017 SCweaponT1: dll=0xFFFF, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x0033
 * - 0x0019 SCweaponT2: dll=0xFFFF, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x05F9
 * - 0x001A SCweaponT3: dll=0xFFFF, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x05FA
 * - 0x001B SCweaponT4: dll=0xFFFF, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x05FE
 * - 0x001C LFweaponT1: dll=0xFFFF, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x06F1
 * - 0x001D LFweaponT2: dll=0xFFFF, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x06F2
 * - 0x001E BGSweapon: dll=0xFFFF, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x07A5
 * - 0x0021 rapidFireLa: dll=0x029B, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x0655
 * - 0x0049 LaserTurret: dll=0x012E, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x0742
 * - 0x0054 Tumbleweed1: dll=0x00D2, placements=0, romlists=0, objsize=0xE0, widths=none, aliases=0x039D
 *   ref param 0x48: bit0 (GameBit16)
 *   ref param 0x4A: bit1 (GameBit16)
 *   ref param 0x4C: bit2 (GameBit16)
 *   ref param 0x4E: bit3 (GameBit16)
 * - 0x0055 Tumbleweed2: dll=0x00D2, placements=0, romlists=0, objsize=0xC0, widths=none, aliases=0x03FB
 * - 0x0056 Tumbleweed3: dll=0x00D2, placements=0, romlists=0, objsize=0xE0, widths=none, aliases=0x04BA
 * - 0x0057 Tumbleweed4: dll=0x00D2, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x04C1
 * - 0x0058 Tumbleweed1: dll=0x00D2, placements=0, romlists=0, objsize=0xE0, widths=none, aliases=0x040A
 * - 0x0059 Tumbleweed2: dll=0x00D2, placements=0, romlists=0, objsize=0xE0, widths=none, aliases=0x040B
 * - 0x005A Tumbleweed3: dll=0x00D2, placements=0, romlists=0, objsize=0xE0, widths=none, aliases=0x04BB
 * - 0x007A DrakorMissi: dll=0x0262, placements=0, romlists=0, objsize=0xC0, widths=none, aliases=0x070F
 * - 0x009F CFrunnersta: dll=0x012E, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x0645
 * - 0x00A3 CFDungeonLi: dll=0x012E, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x0654
 * - 0x00A4 CFGCrubble1: dll=0x012E, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x063E
 * - 0x00AA SkyDome: dll=0x012E, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x061F
 * - 0x00F7 CFTreasRobo: dll=0x0161, placements=0, romlists=0, objsize=0xE0, widths=none, aliases=0x02A2
 * - 0x00FF CFForceFiel: dll=0x015C, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x0088
 * - 0x0184 DIM2Torch: dll=0x012E, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x02AC
 * - 0x01D6 LINKSnowTre: dll=0x011A, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x020A
 * - 0x01D9 LINKSnowTre: dll=0x011A, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x0212
 * - 0x0213 WORLDsunray: dll=0x01D3, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x05DA
 * - 0x0217 WORLDComet: dll=0x01D3, placements=0, romlists=0, objsize=0xC0, widths=none, aliases=0x080F
 * - 0x0227 GFRONT_Asse: dll=0x012E, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x074F
 * - 0x022E robotscorpi: dll=0xFFFF, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x0826
 * - 0x022F firebaddie: dll=0xFFFF, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x083A
 * - 0x0234 AndrossLigh: dll=0x02BF, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x0855
 * - 0x0235 ANDAsteroid: dll=0x029B, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x080D
 * - 0x0236 ANDSuckAste: dll=0x029B, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x0859
 * - 0x0237 AndrossRing: dll=0x029B, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x07E4
 * - 0x0239 AndrossSpir: dll=0x012E, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x0888
 * - 0x025E MMP_telesco: dll=0xFFFF, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x030B
 * - 0x028B nw_testobj: dll=0x011A, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x0638
 * - 0x02A3 SH_BeaconTw: dll=0x012E, placements=0, romlists=0, objsize=0x140, widths=none, aliases=0x0055
 * - 0x02AA SH_staffHaz: dll=0x01B2, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x0659
 * - 0x02C4 KP_console_: dll=0x012E, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x058F
 * - 0x02C5 KP_console_: dll=0x012E, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x0590
 * - 0x02C6 KP_console_: dll=0x012E, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x0591
 * - 0x02C7 KP_console_: dll=0x012E, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x0592
 * - 0x042B KillerSpike: dll=0x012E, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x0751
 * - 0x042D DR_EarthSad: dll=0xFFFF, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x06F5
 * - 0x043C DR_Tower: dll=0x012E, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x06D0
 * - 0x0443 DR_IonCanno: dll=0x012E, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x0428
 * - 0x0444 DRbullet: dll=0x0262, placements=0, romlists=0, objsize=0xC0, widths=none, aliases=0x0429
 * - 0x045C DRPerch: dll=0xFFFF, placements=0, romlists=0, objsize=0xC0, widths=none, aliases=0x0477
 * - 0x046C DR_pulley: dll=0x0274, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x04A1
 * - 0x046D DR_cradle: dll=0x0275, placements=0, romlists=0, objsize=0xA0, widths=none, map=dfcradle, aliases=0x04A7
 * - 0x0482 DR_CloudCal: dll=0x012E, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x04E5
 * - 0x0483 DieSeqObjec: dll=0x012E, placements=0, romlists=0, objsize=0xC0, widths=none, aliases=0x0881
 * - 0x0484 DieDuster: dll=0x010E, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x04F3
 * - 0x0485 DieFox: dll=0x010E, placements=0, romlists=0, objsize=0xC0, widths=none, aliases=0x0882
 * - 0x0486 DieKrystal: dll=0x010E, placements=0, romlists=0, objsize=0xC0, widths=none, aliases=0x0887
 * - 0x0524 ARWArwingTa: dll=0x012E, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x06DE
 * - 0x0525 ARWArwingLa: dll=0x029B, placements=0, romlists=0, objsize=0xC0, widths=none, aliases=0x0604
 * - 0x0526 ARWArwingLa: dll=0x029B, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x06AE
 * - 0x0527 ARWArwingBo: dll=0x029C, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x0605
 * - 0x054A ARWStarFiel: dll=0x012E, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x06DD
 * - 0x0555 SKYScapeDef: dll=0xFFFF, placements=0, romlists=0, objsize=0xC0, widths=none, aliases=0x0627
 * - 0x0556 SKYScapeSto: dll=0xFFFF, placements=0, romlists=0, objsize=0xC0, widths=none, aliases=0x0629
 * - 0x0557 SKYScapeSto: dll=0xFFFF, placements=0, romlists=0, objsize=0xC0, widths=none, aliases=0x075E
 * - 0x0558 SKYScapeSpa: dll=0xFFFF, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x05F5
 * - 0x0559 SKYRingDefa: dll=0xFFFF, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x0628
 * - 0x055A SKYRingStor: dll=0xFFFF, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x0762
 * - 0x055B SKYMountain: dll=0xFFFF, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x062A
 * - 0x055C SKYmountain: dll=0xFFFF, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x085C
 * - 0x055D SKYmountain: dll=0xFFFF, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x0861
 * - 0x055E SKYmountain: dll=0xFFFF, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x0863
 * - 0x055F SKYSun: dll=0xFFFF, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x062B
 * - 0x0560 SKYMoon: dll=0xFFFF, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x062C
 * - 0x057C MetalRafter: dll=0x02B0, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x071A
 * - 0x0581 DragonFly: dll=0x012E, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x064A
 * - 0x0589 SnowBush: dll=0x011A, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x003B
 * - 0x0597 GrassSupaCh: dll=0x011A, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x06E6
 * - 0x0598 FernBush: dll=0x011A, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x06EE
 * - 0x0599 FernCurly: dll=0x011A, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x06EF
 * - 0x05B3 CommandMenu: dll=0xFFFF, placements=0, romlists=0, objsize=0xC0, widths=none, aliases=0x065E
 * - 0x05B4 CommandMenu: dll=0xFFFF, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x065F
 * - 0x05B5 CommandMenu: dll=0xFFFF, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x07DA
 * - 0x05B6 CommandMenu: dll=0xFFFF, placements=0, romlists=0, objsize=0xC0, widths=none, aliases=0x07DB
 * - 0x05B7 FrontEndLog: dll=0xFFFF, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x0665
 * - 0x05C2 Footstep: dll=0xFFFF, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x078E
 *
 * Descriptor slot maps:
 * - DLL 0x00D2: gTumbleweedObjDescriptor (slots=16, mask=0001101101111111)
 *   slot 03: 0x80164F2C tumbleweed_init
 *   slot 04: 0x80164EE4 tumbleweed_update
 *   slot 06: 0x80164180 tumbleweed_render
 *   slot 07: 0x80164084 tumbleweed_free
 *   slot 09: 0x8016407C tumbleweed_getExtraSize
 * - DLL 0x00D6: gKaldaChompMeObjDescriptor (slots=10, mask=1101111111)
 *   slot 00: 0x801696D0 kaldachompme_initialise
 *   slot 01: 0x801696CC kaldachompme_release
 *   slot 03: 0x80169660 kaldachompme_init
 *   slot 04: 0x801695D4 kaldachompme_update
 *   slot 05: 0x801695D0 kaldachompme_hitDetect
 *   slot 06: 0x801695A0 kaldachompme_render
 *   slot 07: 0x8016959C kaldachompme_free
 *   slot 08: 0x80169594 kaldachompme_func08
 *   slot 09: 0x8016958C kaldachompme_getExtraSize
 * - DLL 0x0100: gTrickyWarpObjDescriptor (slots=10, mask=0001100101)
 *   slot 03: 0x80180218 trickywarp_init
 *   slot 04: 0x8017FF48 trickywarp_update
 *   slot 07: 0x8017FF0C trickywarp_free
 *   slot 09: 0x8017FF40 trickywarp_getExtraSize
 * - DLL 0x010E: gDeathSeqObjDescriptor (slots=10, mask=1101111111)
 *   slot 00: 0x8018CD60 deathseq_initialise
 *   slot 01: 0x8018CD5C deathseq_release
 *   slot 03: 0x8018CC8C deathseq_init
 *   slot 04: 0x8018C830 deathseq_update
 *   slot 05: 0x8018C82C deathseq_hitDetect
 *   slot 06: 0x8018C828 deathseq_render
 *   slot 07: 0x8018C7E8 deathseq_free
 *   slot 08: 0x8018C7E0 deathseq_func08
 *   slot 09: 0x8018C7D8 deathseq_getExtraSize
 * - DLL 0x0119: gColdWaterControlObjDescriptor (slots=10, mask=0001100001)
 *   slot 03: 0x80188378 coldwatercontrol_init
 *   slot 04: 0x80188254 coldwatercontrol_update
 *   slot 09: 0x8018824C coldwatercontrol_getExtraSize
 * - DLL 0x011A: gDecoration11AObjDescriptor (slots=10, mask=0001111101)
 *   slot 03: 0x80188814 decoration11a_init
 *   slot 04: 0x80188794 decoration11a_update
 *   slot 05: 0x801885C0 decoration11a_hitDetect
 *   slot 06: 0x80188590 decoration11a_render
 *   slot 07: 0x8018858C decoration11a_free
 *   slot 09: 0x80188584 decoration11a_getExtraSize
 * - DLL 0x011E: gMagicCaveBottomObjDescriptor (slots=10, mask=0000100101)
 *   slot 04: 0x8018ADF0 magiccavebottom_update
 *   slot 07: 0x8018ADBC magiccavebottom_free
 *   slot 09: 0x8018ADB4 magiccavebottom_getExtraSize
 * - DLL 0x012E: gCflightwallObjDescriptor (slots=10, mask=1101111111)
 *   slot 00: 0x80191B5C cflightwall_initialise
 *   slot 01: 0x80191B58 cflightwall_release
 *   slot 03: 0x80191AB0 cflightwall_init
 *   slot 04: 0x80191AAC cflightwall_update
 *   slot 05: 0x80191AA8 cflightwall_hitDetect
 *   slot 06: 0x80191A84 cflightwall_render
 *   slot 07: 0x80191A80 cflightwall_free
 *   slot 08: 0x80191A78 cflightwall_func08
 *   slot 09: 0x80191A70 cflightwall_getExtraSize
 * - DLL 0x012F: gBarrelPadObjDescriptor (slots=10, mask=1101111111)
 *   slot 00: 0x80191CFC barrelpad_initialise
 *   slot 01: 0x80191CF8 barrelpad_release
 *   slot 03: 0x80191C50 barrelpad_init
 *   slot 04: 0x80191B9C barrelpad_update
 *   slot 05: 0x80191B98 barrelpad_hitDetect
 *   slot 06: 0x80191B74 barrelpad_render
 *   slot 07: 0x80191B70 barrelpad_free
 *   slot 08: 0x80191B68 barrelpad_func08
 *   slot 09: 0x80191B60 barrelpad_getExtraSize
 * - DLL 0x0172: gLINKBLevControlObjDescriptor (slots=10, mask=0001100001)
 *   slot 03: 0x801AF38C linkb_levcontrol_init
 *   slot 04: 0x801AEE34 linkb_levcontrol_update
 *   slot 09: 0x801AEE2C linkb_levcontrol_getExtraSize
 * - DLL 0x0173: gLINKLevControlObjDescriptor (slots=10, mask=0001100101)
 *   slot 03: 0x801AF978 link_levcontrol_init
 *   slot 04: 0x801AF8B0 link_levcontrol_update
 *   slot 07: 0x801AF850 link_levcontrol_free
 *   slot 09: 0x801AF848 link_levcontrol_getExtraSize
 * - DLL 0x0185: gCCgasventObjDescriptor (slots=10, mask=0001101101)
 *   slot 03: 0x801A9F84 ccgasvent_init
 *   slot 04: 0x801A9EA4 ccgasvent_update
 *   slot 06: 0x801A9EA0 ccgasvent_render
 *   slot 07: 0x801A9E7C ccgasvent_free
 *   slot 09: 0x801A9E74 ccgasvent_getExtraSize
 * - DLL 0x0186: gCCgasventControlObjDescriptor (slots=10, mask=0001101101)
 *   slot 03: 0x801AA4FC ccgasventcontrol_init
 *   slot 04: 0x801AA188 ccgasventcontrol_update
 *   slot 06: 0x801AA158 ccgasventcontrol_render
 *   slot 07: 0x801AA10C ccgasventcontrol_free
 *   slot 09: 0x801AA104 ccgasventcontrol_getExtraSize
 * - DLL 0x0187: gCCqueenObjDescriptor (slots=10, mask=0001101001)
 *   slot 03: 0x801AA694 ccqueen_init
 *   slot 04: 0x801AA5AC ccqueen_update
 *   slot 06: 0x801AA560 ccqueen_render
 *   slot 09: 0x801AA558 ccqueen_getExtraSize
 * - DLL 0x0188: gCClightfootObjDescriptor (slots=10, mask=0001100101)
 *   slot 03: 0x801AB438 cclightfoot_init
 *   slot 04: 0x801AA90C cclightfoot_update
 *   slot 07: 0x801AA818 cclightfoot_free
 *   slot 09: 0x801AA810 cclightfoot_getExtraSize
 * - DLL 0x018A: gCCpedstalObjDescriptor (slots=10, mask=0001100001)
 *   slot 03: 0x801AB9B0 ccpedstal_init
 *   slot 04: 0x801AB900 ccpedstal_update
 *   slot 09: 0x801AB6F8 ccpedstal_getExtraSize
 * - DLL 0x018B: gCClevcontrolObjDescriptor (slots=10, mask=0001101101)
 *   slot 03: 0x801ABF48 cclevcontrol_init
 *   slot 04: 0x801ABB30 cclevcontrol_update
 *   slot 06: 0x801ABB0C cclevcontrol_render
 *   slot 07: 0x801ABADC cclevcontrol_free
 *   slot 09: 0x801ABAD4 cclevcontrol_getExtraSize
 * - DLL 0x01A2: gNW_trickyObjDescriptor (slots=10, mask=0001100101)
 *   slot 03: 0x801CFB04 nw_tricky_init
 *   slot 04: 0x801CF7E8 nw_tricky_update
 *   slot 07: 0x801CF7C0 nw_tricky_free
 *   slot 09: 0x801CF7B8 nw_tricky_getExtraSize
 * - DLL 0x01A3: gNW_animiceObjDescriptor (slots=10, mask=1101111111)
 *   slot 00: 0x801CFBB0 nw_animice_initialise
 *   slot 01: 0x801CFBAC nw_animice_release
 *   slot 03: 0x801CFB6C nw_animice_init
 *   slot 04: 0x801CFB68 nw_animice_update
 *   slot 05: 0x801CFB64 nw_animice_hitDetect
 *   slot 06: 0x801CFB60 nw_animice_render
 *   slot 07: 0x801CFB3C nw_animice_free
 *   slot 08: 0x801CFB34 nw_animice_func08
 *   slot 09: 0x801CFB2C nw_animice_getExtraSize
 * - DLL 0x01A4: gNW_iceObjDescriptor (slots=10, mask=0001101101)
 *   slot 03: 0x801CFD44 nw_ice_init
 *   slot 04: 0x801CFBE4 nw_ice_update
 *   slot 06: 0x801CFBE0 nw_ice_render
 *   slot 07: 0x801CFBBC nw_ice_free
 *   slot 09: 0x801CFBB4 nw_ice_getExtraSize
 * - DLL 0x01A5: gNW_levcontrolObjDescriptor (slots=10, mask=0001100101)
 *   slot 03: 0x801D04E0 nw_levcontrol_init
 *   slot 04: 0x801CFF20 nw_levcontrol_update
 *   slot 07: 0x801CFECC nw_levcontrol_free
 *   slot 09: 0x801CFEC4 nw_levcontrol_getExtraSize
 * - DLL 0x01A6: gSH_trickyObjDescriptor (slots=10, mask=0001100001)
 *   slot 03: 0x801D07C0 sh_tricky_init
 *   slot 04: 0x801D06A4 sh_tricky_update
 *   slot 09: 0x801D069C sh_tricky_getExtraSize
 * - DLL 0x01B0: gWarpStoneObjDescriptor (slots=10, mask=1101111111)
 *   slot 00: 0x801D7BA4 warpstone_initialise
 *   slot 01: 0x801D7BA0 warpstone_release
 *   slot 03: 0x801D7B00 warpstone_init
 *   slot 04: 0x801D7674 warpstone_update
 *   slot 05: 0x801D759C warpstone_hitDetect
 *   slot 06: 0x801D74C4 warpstone_render
 *   slot 07: 0x801D7478 warpstone_free
 *   slot 08: 0x801D7470 warpstone_func08
 *   slot 09: 0x801D7468 warpstone_getExtraSize
 * - DLL 0x01B1: gSH_staffObjDescriptor (slots=10, mask=0000101101)
 *   slot 04: 0x801DA608 sh_staff_update
 *   slot 06: 0x801D9BDC sh_staff_render
 *   slot 07: 0x801D9B24 sh_staff_free
 *   slot 09: 0x801D9B1C sh_staff_getExtraSize
 * - DLL 0x01B2: gSH_staffHazeObjDescriptor (slots=10, mask=0000101000)
 *   slot 04: 0x801DA924 sh_staffhaze_update
 *   slot 06: 0x801DA8C4 sh_staffhaze_render
 * - DLL 0x01B8: gSC_totempoleObjDescriptor (slots=10, mask=1101111111)
 *   slot 00: 0x801DCC6C sc_totempole_initialise
 *   slot 01: 0x801DCC68 sc_totempole_release
 *   slot 03: 0x801DCBF8 sc_totempole_init
 *   slot 04: 0x801DCA2C sc_totempole_update
 *   slot 05: 0x801DCA28 sc_totempole_hitDetect
 *   slot 06: 0x801DC9F8 sc_totempole_render
 *   slot 07: 0x801DC9F4 sc_totempole_free
 *   slot 08: 0x801DC9EC sc_totempole_func08
 *   slot 09: 0x801DC9E4 sc_totempole_getExtraSize
 * - DLL 0x01BA: gSC_totempuzzleObjDescriptor (slots=10, mask=1101111111)
 *   slot 00: 0x801DDA24 sc_totempuzzle_initialise
 *   slot 01: 0x801DDA20 sc_totempuzzle_release
 *   slot 03: 0x801DD884 sc_totempuzzle_init
 *   slot 04: 0x801DD46C sc_totempuzzle_update
 *   slot 05: 0x801DD468 sc_totempuzzle_hitDetect
 *   slot 06: 0x801DD438 sc_totempuzzle_render
 *   slot 07: 0x801DD434 sc_totempuzzle_free
 *   slot 08: 0x801DD42C sc_totempuzzle_func08
 *   slot 09: 0x801DD424 sc_totempuzzle_getExtraSize
 * - DLL 0x01D0: gDIM_trickyObjDescriptor (slots=10, mask=0001111111)
 *   slot 03: 0x801B6D30 dim_tricky_init
 *   slot 04: 0x801B6C68 dim_tricky_update
 *   slot 05: 0x801B6C64 dim_tricky_hitDetect
 *   slot 06: 0x801B6C40 dim_tricky_render
 *   slot 07: 0x801B6C3C dim_tricky_free
 *   slot 08: 0x801B6C34 dim_tricky_func08
 *   slot 09: 0x801B6C2C dim_tricky_getExtraSize
 * - DLL 0x01D2: gWorldPlanetObjDescriptor (slots=10, mask=1101111111)
 *   slot 00: 0x8020D9E0 worldplanet_initialise
 *   slot 01: 0x8020D9DC worldplanet_release
 *   slot 03: 0x8020D7EC worldplanet_init
 *   slot 04: 0x8020C9CC worldplanet_update
 *   slot 05: 0x8020C9C8 worldplanet_hitDetect
 *   slot 06: 0x8020C998 worldplanet_render
 *   slot 07: 0x8020C974 worldplanet_free
 *   slot 08: 0x8020C96C worldplanet_func08
 *   slot 09: 0x8020C964 worldplanet_getExtraSize
 * - DLL 0x01D3: gWorldObjObjDescriptor (slots=10, mask=1101111111)
 *   slot 00: 0x8020F210 worldobj_initialise
 *   slot 01: 0x8020F20C worldobj_release
 *   slot 03: 0x8020ECE8 worldobj_init
 *   slot 04: 0x8020DFA8 worldobj_update
 *   slot 05: 0x8020DFA4 worldobj_hitDetect
 *   slot 06: 0x8020DD9C worldobj_render
 *   slot 07: 0x8020DD38 worldobj_free
 *   slot 08: 0x8020DD18 worldobj_func08
 *   slot 09: 0x8020DD10 worldobj_getExtraSize
 * - DLL 0x01F4: gLampObjDescriptor (slots=10, mask=0001101101)
 *   slot 03: 0x801E5D64 Lamp_init
 *   slot 04: 0x801E5B54 Lamp_update
 *   slot 06: 0x801E59FC Lamp_render
 *   slot 07: 0x801E59B4 Lamp_free
 *   slot 09: 0x801E59AC Lamp_getExtraSize
 * - DLL 0x01F6: gFlagObjDescriptor (slots=10, mask=1101111111)
 *   slot 00: 0x801E5F70 Flag_initialise
 *   slot 01: 0x801E5F6C Flag_release
 *   slot 03: 0x801E5F20 Flag_init
 *   slot 04: 0x801E5E0C Flag_update
 *   slot 05: 0x801E5E08 Flag_hitDetect
 *   slot 06: 0x801E5DD8 Flag_render
 *   slot 07: 0x801E5DD4 Flag_free
 *   slot 08: 0x801E5DCC Flag_func08
 *   slot 09: 0x801E5DC4 Flag_getExtraSize
 * - DLL 0x0215: gWM_newcrystalObjDescriptor (slots=10, mask=1101111111)
 *   slot 00: 0x801F9800 wmnewcrystal_initialise
 *   slot 01: 0x801F97FC wmnewcrystal_release
 *   slot 03: 0x801F978C wmnewcrystal_init
 *   slot 04: 0x801F9788 wmnewcrystal_update
 *   slot 05: 0x801F9784 wmnewcrystal_hitDetect
 *   slot 06: 0x801F9760 wmnewcrystal_render
 *   slot 07: 0x801F975C wmnewcrystal_free
 *   slot 08: 0x801F9754 wmnewcrystal_func08
 *   slot 09: 0x801F974C wmnewcrystal_getExtraSize
 * - DLL 0x0262: gDrakorMissileObjDescriptor (slots=14, mask=11011111111111)
 *   slot 00: 0x80218B20 drakormissile_initialise
 *   slot 01: 0x80218B1C drakormissile_release
 *   slot 03: 0x802189C0 drakormissile_init
 *   slot 04: 0x802185CC drakormissile_update
 *   slot 05: 0x802185C8 drakormissile_hitDetect
 *   slot 06: 0x80218474 drakormissile_render
 *   slot 07: 0x8021841C drakormissile_free
 *   slot 08: 0x80218414 drakormissile_func08
 *   slot 09: 0x8021840C drakormissile_getExtraSize
 * - DLL 0x029B: gArwingAndrossStuffObjDescriptor (slots=10, mask=1101111111)
 *   slot 00: 0x8022ECDC arwingandrossstuff_initialise
 *   slot 01: 0x8022ECD8 arwingandrossstuff_release
 *   slot 03: 0x8022EB68 arwingandrossstuff_init
 *   slot 04: 0x8022E94C arwingandrossstuff_update
 *   slot 05: 0x8022E6B0 arwingandrossstuff_hitDetect
 *   slot 06: 0x8022E680 arwingandrossstuff_render
 *   slot 07: 0x8022E640 arwingandrossstuff_free
 *   slot 08: 0x8022E638 arwingandrossstuff_func08
 *   slot 09: 0x8022E630 arwingandrossstuff_getExtraSize
 * - DLL 0x029C: gARWArwingBoObjDescriptor (slots=10, mask=1101111111)
 *   slot 00: 0x8022F144 arwarwingbo_initialise
 *   slot 01: 0x8022F140 arwarwingbo_release
 *   slot 03: 0x8022F0EC arwarwingbo_init
 *   slot 04: 0x8022EE30 arwarwingbo_update
 *   slot 05: 0x8022EE2C arwarwingbo_hitDetect
 *   slot 06: 0x8022EDFC arwarwingbo_render
 *   slot 07: 0x8022EDB4 arwarwingbo_free
 *   slot 08: 0x8022EDAC arwarwingbo_func08
 *   slot 09: 0x8022EDA4 arwarwingbo_getExtraSize
 * - DLL 0x029D: gARWArwingGuObjDescriptor (slots=10, mask=1101111111)
 *   slot 00: 0x8022F528 arwarwinggu_initialise
 *   slot 01: 0x8022F524 arwarwinggu_release
 *   slot 03: 0x8022F4FC arwarwinggu_init
 *   slot 04: 0x8022F368 arwarwinggu_update
 *   slot 05: 0x8022F364 arwarwinggu_hitDetect
 *   slot 06: 0x8022F360 arwarwinggu_render
 *   slot 07: 0x8022F35C arwarwinggu_free
 *   slot 08: 0x8022F354 arwarwinggu_func08
 *   slot 09: 0x8022F300 arwarwinggu_getExtraSize
 * - DLL 0x02A2: gARWSpeedStrObjDescriptor (slots=10, mask=1101111111)
 *   slot 00: 0x80231024 arwspeedstr_initialise
 *   slot 01: 0x80231020 arwspeedstr_release
 *   slot 03: 0x80231014 arwspeedstr_init
 *   slot 04: 0x80230E68 arwspeedstr_update
 *   slot 05: 0x80230E64 arwspeedstr_hitDetect
 *   slot 06: 0x80230E40 arwspeedstr_render
 *   slot 07: 0x80230E3C arwspeedstr_free
 *   slot 08: 0x80230E34 arwspeedstr_func08
 *   slot 09: 0x80230E2C arwspeedstr_getExtraSize
 * - DLL 0x02B0: gBrokenPipeObjDescriptor (slots=10, mask=0001100001)
 *   slot 03: 0x80236194 brokenpipe_init
 *   slot 04: 0x8023615C brokenpipe_update
 *   slot 09: 0x80236154 brokenpipe_getExtraSize
 * - DLL 0x02B9: gMCStaffEffeObjDescriptor (slots=10, mask=0001101000)
 *   slot 03: 0x802392F4 mcstaffeffe_init
 *   slot 04: 0x802392F0 mcstaffeffe_update
 *   slot 06: 0x802392B8 mcstaffeffe_render
 * - DLL 0x02BA: gMCLightningObjDescriptor (slots=10, mask=0001101101)
 *   slot 03: 0x802397E4 mclightning_init
 *   slot 04: 0x80239778 mclightning_update
 *   slot 06: 0x80239520 mclightning_render
 *   slot 07: 0x802394E0 mclightning_free
 *   slot 09: 0x802394D8 mclightning_getExtraSize
 * - DLL 0x02BC: gAndrossObjDescriptor (slots=10, mask=0001111111)
 *   slot 03: 0x8023EF3C andross_init
 *   slot 04: 0x8023AA64 andross_update
 *   slot 05: 0x8023AA60 andross_hitDetect
 *   slot 06: 0x8023AA3C andross_render
 *   slot 07: 0x8023AA18 andross_free
 *   slot 08: 0x8023AA10 andross_func08
 *   slot 09: 0x8023AA08 andross_getExtraSize
 * - DLL 0x02BD: gAndrossHandObjDescriptor (slots=10, mask=0001111111)
 *   slot 03: 0x8023FBF4 androsshand_init
 *   slot 04: 0x8023F468 androsshand_update
 *   slot 05: 0x8023F464 androsshand_hitDetect
 *   slot 06: 0x8023F440 androsshand_render
 *   slot 07: 0x8023F43C androsshand_free
 *   slot 08: 0x8023F434 androsshand_func08
 *   slot 09: 0x8023F42C androsshand_getExtraSize
 * - DLL 0x02BE: gAndrossBrainObjDescriptor (slots=10, mask=0001111111)
 *   slot 03: 0x8023FFE0 androssbrain_init
 *   slot 04: 0x8023FD38 androssbrain_update
 *   slot 05: 0x8023FD34 androssbrain_hitDetect
 *   slot 06: 0x8023FD10 androssbrain_render
 *   slot 07: 0x8023FD0C androssbrain_free
 *   slot 08: 0x8023FD04 androssbrain_func08
 *   slot 09: 0x8023FCFC androssbrain_getExtraSize
 * - DLL 0x02BF: gAndrossLighObjDescriptor (slots=10, mask=0001111111)
 *   slot 03: 0x80240348 androssligh_init
 *   slot 04: 0x80240294 androssligh_update
 *   slot 05: 0x80240290 androssligh_hitDetect
 *   slot 06: 0x80240260 androssligh_render
 *   slot 07: 0x8024025C androssligh_free
 *   slot 08: 0x80240254 androssligh_func08
 *   slot 09: 0x8024024C androssligh_getExtraSize
 */

#if 0
/*
 * Reference-only class packet enums. Verify against EN before promoting names into live code.
 */
enum class_0061_various0061_defs {
    VARIOUS0061_TRICKYWARP = 0x04C4,
    VARIOUS0061_DRDEBRISGIR = 0x007F,
    VARIOUS0061_SNOWLOG = 0x058D,
    VARIOUS0061_DRDEBRISPIP = 0x0082,
    VARIOUS0061_COBWEBCEILI = 0x0592,
    VARIOUS0061_SNOWBOULDER = 0x0587,
    VARIOUS0061_COBWEBEDGE = 0x0593,
    VARIOUS0061_ALIENTREEPA = 0x056B,
    VARIOUS0061_CFLIGHTWALL = 0x00A1,
    VARIOUS0061_DRDEBRISPIP_0081 = 0x0081,
    VARIOUS0061_BOULDERONE = 0x057D,
    VARIOUS0061_COBWEBCORNE = 0x0591,
    VARIOUS0061_MCLIGHTNING = 0x04A2,
    VARIOUS0061_CFGCRUBBLE2 = 0x00A5,
    VARIOUS0061_SULPHURCRYS = 0x058F,
    VARIOUS0061_CFLIGHTPILL = 0x00A0,
    VARIOUS0061_CFGCRUBBLE3 = 0x00A6,
    VARIOUS0061_KALDACHOMME = 0x0027,
    VARIOUS0061_CFGCRUBBLE4 = 0x00A7,
    VARIOUS0061_CF_LAMP = 0x0107,
    VARIOUS0061_DIRECTIONSI = 0x0566,
    VARIOUS0061_MCSTAFFEFFE = 0x04A1,
    VARIOUS0061_CCDARKNESS = 0x01F6,
    VARIOUS0061_REDBOULDER = 0x057E,
    VARIOUS0061_WATERLILLYF = 0x059B,
    VARIOUS0061_SC_TOTEMPUZ = 0x02EA,
    VARIOUS0061_ARWARWINGGU = 0x0538,
    VARIOUS0061_ARWARWINGGU_0539 = 0x0539,
    VARIOUS0061_ARWARWINGRO = 0x053A,
    VARIOUS0061_CFGCPILLBRE = 0x00A8,
    VARIOUS0061_LINK_LEVCON = 0x01CB,
    VARIOUS0061_BARRELPAD = 0x0504,
    VARIOUS0061_CFRUNNERSTA = 0x009E,
    VARIOUS0061_CCGASVENT = 0x01FA,
    VARIOUS0061_WORLDSHIELD = 0x021A,
    VARIOUS0061_SC_TOTEMPOL = 0x02E9,
    VARIOUS0061_CACTUS = 0x0580,
    VARIOUS0061_INFOTABLET = 0x0080,
    VARIOUS0061_LINKSNOWLOG = 0x01D8,
    VARIOUS0061_CCPEDSTAL = 0x01ED,
    VARIOUS0061_WORLDSUN = 0x0212,
    VARIOUS0061_WORLDASTGEN = 0x0218,
    VARIOUS0061_VFPSPLSTNE = 0x036C,
    VARIOUS0061_COLDWATERCO = 0x04DC,
    VARIOUS0061_CFGCSMALLBL = 0x00A9,
    VARIOUS0061_GF_JUKEBOX = 0x0251,
    VARIOUS0061_NWCALLOFELD = 0x0271,
    VARIOUS0061_SC_DUMMYTRI = 0x02EE,
    VARIOUS0061_SC_DUMMYSQU = 0x02EF,
    VARIOUS0061_SC_DUMMYCIR = 0x02F0,
    VARIOUS0061_VFP_WARDING = 0x0314,
    VARIOUS0061_DFPSPLSTNE = 0x036A,
    VARIOUS0061_MAGICCAVEBO = 0x049D,
    VARIOUS0061_DIMSPELLSTO = 0x0075,
    VARIOUS0061_WCSUNDOOR = 0x0125,
    VARIOUS0061_WCMOONDOOR = 0x0126,
    VARIOUS0061_DIM_TRICKY = 0x0180,
    VARIOUS0061_LINKB_LEVCO = 0x01DD,
    VARIOUS0061_CCLEVCONTRO = 0x01E4,
    VARIOUS0061_CCLIGHTFOOT = 0x01F4,
    VARIOUS0061_CCQUEEN = 0x01F8,
    VARIOUS0061_CCGASVENTCO = 0x01FB,
    VARIOUS0061_WORLDPLANET = 0x0202,
    VARIOUS0061_WORLDCLOUDR = 0x0203,
    VARIOUS0061_WORLDDRAGRO = 0x0204,
    VARIOUS0061_WORLDWALLED = 0x0205,
    VARIOUS0061_WORLDDARKIC = 0x0206,
    VARIOUS0061_WORLDCLOUDL = 0x0207,
    VARIOUS0061_WORLDPATH1 = 0x0208,
    VARIOUS0061_WORLDPATH2 = 0x0209,
    VARIOUS0061_WORLDPATH3 = 0x020A,
    VARIOUS0061_WORLDPATH4 = 0x020B,
    VARIOUS0061_WORLDPATH5 = 0x020C,
    VARIOUS0061_WORLDPATH6 = 0x020D,
    VARIOUS0061_WORLDPATH7 = 0x020E,
    VARIOUS0061_WORLDPATH8 = 0x020F,
    VARIOUS0061_WORLDARWING = 0x0210,
    VARIOUS0061_WORLDGREATF = 0x0211,
    VARIOUS0061_WORLDPEPPER = 0x0214,
    VARIOUS0061_WORLDSUNFLA = 0x0215,
    VARIOUS0061_WORLDHALO = 0x0219,
    VARIOUS0061_WORLDHALOBR = 0x021B,
    VARIOUS0061_WORLDARROW = 0x021C,
    VARIOUS0061_LINKH_ASSET = 0x0228,
    VARIOUS0061_LINKC_ASSET = 0x0229,
    VARIOUS0061_LINKE_ASSET = 0x022A,
    VARIOUS0061_LINKJ_ASSET = 0x022B,
    VARIOUS0061_LINKF_ASSET = 0x022C,
    VARIOUS0061_ANDROSS = 0x0230,
    VARIOUS0061_ANDROSSLEFT = 0x0231,
    VARIOUS0061_ANDROSSRIGH = 0x0232,
    VARIOUS0061_ANDROSSBRAI = 0x0233,
    VARIOUS0061_GF_PILOTSEA = 0x024D,
    VARIOUS0061_MMP_DEFENDO = 0x025F,
    VARIOUS0061_MMP_DEFENDO_0260 = 0x0260,
    VARIOUS0061_NWCELLLOCK = 0x026A,
    VARIOUS0061_NW_LEVCONTR = 0x0272,
    VARIOUS0061_NW_TRICKY = 0x0284,
    VARIOUS0061_NW_ANIMICE1 = 0x0285,
    VARIOUS0061_NW_ANIMICE2 = 0x0286,
    VARIOUS0061_NW_ANIMICE3 = 0x0287,
    VARIOUS0061_NW_ICE1 = 0x0288,
    VARIOUS0061_NW_ICE2 = 0x0289,
    VARIOUS0061_NW_ICE3 = 0x028A,
    VARIOUS0061_SH_STAFF = 0x02A9,
    VARIOUS0061_SH_TRICKY = 0x02AB,
    VARIOUS0061_SH_SWAPSTON = 0x02B4,
    VARIOUS0061_SC_THRONE = 0x02F2,
    VARIOUS0061_SB_WHEEL = 0x02F7,
    VARIOUS0061_VFP_MAINDOO = 0x0336,
    VARIOUS0061_VFP_MAINDOO_0338 = 0x0338,
    VARIOUS0061_WM_NEWCRYST = 0x037A,
    VARIOUS0061_WM_NEWCRYST_037B = 0x037B,
    VARIOUS0061_WM_NEWCRYST_037C = 0x037C,
    VARIOUS0061_WM_EXPLOSIV = 0x037E,
    VARIOUS0061_DR_TRACKDOO = 0x046F,
    VARIOUS0061_ARWSPEEDSTR = 0x0537,
    VARIOUS0061_BROKENPIPE = 0x057B,
    VARIOUS0061_GRASSWEEDCL = 0x0596,
    VARIOUS0061_TRICKYBADGE = 0x0005,
    VARIOUS0061_TRICKYBADGE_0006 = 0x0006,
    VARIOUS0061_MODELSWITHT = 0x0008,
    VARIOUS0061_TRICKYEXCLA = 0x000B,
    VARIOUS0061_TRICKYQUEST = 0x000C,
    VARIOUS0061_TRICKYFOOD = 0x000D,
    VARIOUS0061_BACKPACK = 0x0011,
    VARIOUS0061_STAFFEND = 0x0015,
    VARIOUS0061_SCWEAPONT1 = 0x0017,
    VARIOUS0061_SCWEAPONT2 = 0x0019,
    VARIOUS0061_SCWEAPONT3 = 0x001A,
    VARIOUS0061_SCWEAPONT4 = 0x001B,
    VARIOUS0061_LFWEAPONT1 = 0x001C,
    VARIOUS0061_LFWEAPONT2 = 0x001D,
    VARIOUS0061_BGSWEAPON = 0x001E,
    VARIOUS0061_RAPIDFIRELA = 0x0021,
    VARIOUS0061_LASERTURRET = 0x0049,
    VARIOUS0061_TUMBLEWEED1 = 0x0054,
    VARIOUS0061_TUMBLEWEED2 = 0x0055,
    VARIOUS0061_TUMBLEWEED3 = 0x0056,
    VARIOUS0061_TUMBLEWEED4 = 0x0057,
    VARIOUS0061_TUMBLEWEED1_0058 = 0x0058,
    VARIOUS0061_TUMBLEWEED2_0059 = 0x0059,
    VARIOUS0061_TUMBLEWEED3_005A = 0x005A,
    VARIOUS0061_DRAKORMISSI = 0x007A,
    VARIOUS0061_CFRUNNERSTA_009F = 0x009F,
    VARIOUS0061_CFDUNGEONLI = 0x00A3,
    VARIOUS0061_CFGCRUBBLE1 = 0x00A4,
    VARIOUS0061_SKYDOME = 0x00AA,
    VARIOUS0061_CFTREASROBO = 0x00F7,
    VARIOUS0061_CFFORCEFIEL = 0x00FF,
    VARIOUS0061_DIM2TORCH = 0x0184,
    VARIOUS0061_LINKSNOWTRE = 0x01D6,
    VARIOUS0061_LINKSNOWTRE_01D9 = 0x01D9,
    VARIOUS0061_WORLDSUNRAY = 0x0213,
    VARIOUS0061_WORLDCOMET = 0x0217,
    VARIOUS0061_GFRONT_ASSE = 0x0227,
    VARIOUS0061_ROBOTSCORPI = 0x022E,
    VARIOUS0061_FIREBADDIE = 0x022F,
    VARIOUS0061_ANDROSSLIGH = 0x0234,
    VARIOUS0061_ANDASTEROID = 0x0235,
    VARIOUS0061_ANDSUCKASTE = 0x0236,
    VARIOUS0061_ANDROSSRING = 0x0237,
    VARIOUS0061_ANDROSSSPIR = 0x0239,
    VARIOUS0061_MMP_TELESCO = 0x025E,
    VARIOUS0061_NW_TESTOBJ = 0x028B,
    VARIOUS0061_SH_BEACONTW = 0x02A3,
    VARIOUS0061_SH_STAFFHAZ = 0x02AA,
    VARIOUS0061_KP_CONSOLE = 0x02C4,
    VARIOUS0061_KP_CONSOLE_02C5 = 0x02C5,
    VARIOUS0061_KP_CONSOLE_02C6 = 0x02C6,
    VARIOUS0061_KP_CONSOLE_02C7 = 0x02C7,
    VARIOUS0061_KILLERSPIKE = 0x042B,
    VARIOUS0061_DR_EARTHSAD = 0x042D,
    VARIOUS0061_DR_TOWER = 0x043C,
    VARIOUS0061_DR_IONCANNO = 0x0443,
    VARIOUS0061_DRBULLET = 0x0444,
    VARIOUS0061_DRPERCH = 0x045C,
    VARIOUS0061_DR_PULLEY = 0x046C,
    VARIOUS0061_DR_CRADLE = 0x046D,
    VARIOUS0061_DR_CLOUDCAL = 0x0482,
    VARIOUS0061_DIESEQOBJEC = 0x0483,
    VARIOUS0061_DIEDUSTER = 0x0484,
    VARIOUS0061_DIEFOX = 0x0485,
    VARIOUS0061_DIEKRYSTAL = 0x0486,
    VARIOUS0061_ARWARWINGTA = 0x0524,
    VARIOUS0061_ARWARWINGLA = 0x0525,
    VARIOUS0061_ARWARWINGLA_0526 = 0x0526,
    VARIOUS0061_ARWARWINGBO = 0x0527,
    VARIOUS0061_ARWSTARFIEL = 0x054A,
    VARIOUS0061_SKYSCAPEDEF = 0x0555,
    VARIOUS0061_SKYSCAPESTO = 0x0556,
    VARIOUS0061_SKYSCAPESTO_0557 = 0x0557,
    VARIOUS0061_SKYSCAPESPA = 0x0558,
    VARIOUS0061_SKYRINGDEFA = 0x0559,
    VARIOUS0061_SKYRINGSTOR = 0x055A,
    VARIOUS0061_SKYMOUNTAIN = 0x055B,
    VARIOUS0061_SKYMOUNTAIN_055C = 0x055C,
    VARIOUS0061_SKYMOUNTAIN_055D = 0x055D,
    VARIOUS0061_SKYMOUNTAIN_055E = 0x055E,
    VARIOUS0061_SKYSUN = 0x055F,
    VARIOUS0061_SKYMOON = 0x0560,
    VARIOUS0061_METALRAFTER = 0x057C,
    VARIOUS0061_DRAGONFLY = 0x0581,
    VARIOUS0061_SNOWBUSH = 0x0589,
    VARIOUS0061_GRASSSUPACH = 0x0597,
    VARIOUS0061_FERNBUSH = 0x0598,
    VARIOUS0061_FERNCURLY = 0x0599,
    VARIOUS0061_COMMANDMENU = 0x05B3,
    VARIOUS0061_COMMANDMENU_05B4 = 0x05B4,
    VARIOUS0061_COMMANDMENU_05B5 = 0x05B5,
    VARIOUS0061_COMMANDMENU_05B6 = 0x05B6,
    VARIOUS0061_FRONTENDLOG = 0x05B7,
    VARIOUS0061_FOOTSTEP = 0x05C2,
};
#endif
