/*
 * Auto-generated by tools/orig/object_class_packets.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists as a class-level recovery packet for early file-boundary work.
 *
 * Class ID: 0x0072
 * Reference class name: SkeetlaWall
 * Suggested packet name: SkeetlaWall
 * Output path: src/main/unknown/classes/class_0072_skeetlawall.c
 * Retail placements: 0
 * Retail object defs: 1
 * DLL IDs: 0x00D4
 * Descriptor-backed DLL IDs: 0x00D4
 * Retail object record sizes: 0xA0
 * Retail root placement widths: -
 *
 * Retail object defs:
 * - 0x0024 SkeetlaWall: dll=0x00D4, placements=0, romlists=0, objsize=0xA0, widths=none, aliases=0x04AD
 *
 * Descriptor slot maps:
 * - DLL 0x00D4: gSkeetlaWallObjDescriptor (slots=11, mask=11011111111)
 *   slot 00: 0x80167760 skeetlawall_initialise
 *   slot 01: 0x8016775C skeetlawall_release
 *   slot 03: 0x8016771C skeetlawall_init
 *   slot 04: 0x80167718 skeetlawall_update
 *   slot 05: 0x80167714 skeetlawall_hitDetect
 *   slot 06: 0x801676D4 skeetlawall_render
 *   slot 07: 0x801676D0 skeetlawall_free
 *   slot 08: 0x801676C8 skeetlawall_func08
 *   slot 09: 0x801676C0 skeetlawall_getExtraSize
 */

#if 0
/*
 * Reference-only class packet enums. Verify against EN before promoting names into live code.
 */
enum class_0072_SkeetlaWall_defs {
    SKEETLAWALL_SKEETLAWALL = 0x0024,
};
#endif
