/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/baddie/Tumbleweed.c
 * Text span: 0x80132368-0x80139724
 * Imported Ghidra functions: 68
 * Verbatim-safe functions: 33
 * Auto-stubbed functions: 35
 */

#include "ghidra_import.h"
#include "main/dll/baddie/Tumbleweed.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_80003494();
extern undefined4 FUN_80008cbc();
extern undefined4 FUN_8000a3a0();
extern undefined4 FUN_8000a538();
extern bool FUN_8000b598();
extern undefined4 FUN_8000b844();
extern undefined8 FUN_8000bb38();
extern void* FUN_8000facc();
extern int FUN_8000fb04();
extern undefined4 FUN_8000fb20();
extern byte FUN_80014074();
extern undefined4 FUN_800140dc();
extern int FUN_8001496c();
extern undefined4 FUN_80014974();
extern uint FUN_80014e9c();
extern uint FUN_80014f14();
extern undefined4 FUN_80016848();
extern undefined8 FUN_800168a8();
extern void* FUN_80017400();
extern void* FUN_800195a8();
extern undefined4 FUN_8001983c();
extern undefined4 FUN_80019884();
extern undefined8 FUN_80019940();
extern int FUN_80019b4c();
extern undefined8 FUN_80019b54();
extern uint FUN_80020078();
extern undefined4 FUN_800201ac();
extern double FUN_80021730();
extern double FUN_80021794();
extern int FUN_80021884();
extern uint FUN_80022264();
extern int FUN_800279a8();
extern undefined4 FUN_80027a44();
extern undefined4 FUN_80027a90();
extern undefined4 FUN_80028600();
extern undefined4 FUN_8002ae08();
extern int FUN_8002b660();
extern int FUN_8002bac4();
extern void* FUN_8002becc();
extern undefined8 FUN_8002cc9c();
extern undefined4 FUN_8002e088();
extern int FUN_8002fb40();
extern undefined4 FUN_8003042c();
extern uint FUN_80036d04();
extern int FUN_80036f50();
extern void* FUN_80037048();
extern undefined8 FUN_80037da8();
extern undefined4 FUN_80037e24();
extern undefined4 FUN_800394f0();
extern undefined4 FUN_8003b320();
extern undefined4 FUN_8003b408();
extern undefined4 FUN_8003b9ec();
extern undefined4 FUN_8003ba50();
extern undefined4 FUN_8004c460();
extern undefined8 FUN_80054484();
extern undefined4 FUN_80054ed0();
extern uint FUN_8005b128();
extern undefined4 FUN_8005d294();
extern uint FUN_80070050();
extern undefined4 FUN_80075534();
extern undefined4 FUN_80075b98();
extern undefined4 FUN_80076008();
extern undefined4 FUN_80076144();
extern undefined4 FUN_80076998();
extern undefined4 FUN_80077318();
extern undefined4 FUN_80078d98();
extern undefined4 FUN_80089734();
extern undefined4 FUN_8008986c();
extern undefined4 FUN_8008999c();
extern int FUN_80111fb0();
extern undefined4 FUN_801163b8();
extern undefined4 FUN_801171ec();
extern undefined4 FUN_8011853c();
extern undefined4 FUN_80129fb0();
extern undefined4 FUN_80129ff8();
extern undefined4 FUN_8012c9e8();
extern undefined4 FUN_80130124();
extern ushort FUN_8013047c();
extern undefined4 FUN_80132294();
extern double FUN_8014ca48();
extern undefined4 FUN_80242114();
extern undefined4 FUN_802430ec();
extern undefined4 FUN_80243e74();
extern undefined4 FUN_80243e9c();
extern undefined4 FUN_80246a0c();
extern undefined4 FUN_80246dcc();
extern undefined8 FUN_802475b8();
extern undefined4 FUN_80247a48();
extern undefined4 FUN_8024c8cc();
extern undefined4 FUN_8024c910();
extern undefined8 FUN_8024d054();
extern undefined4 FUN_8024dcb8();
extern undefined4 FUN_8024ddd4();
extern undefined4 FUN_80256bc4();
extern undefined4 FUN_802570dc();
extern undefined4 FUN_80257b5c();
extern undefined8 FUN_80258a94();
extern undefined4 FUN_80259000();
extern undefined4 FUN_80259288();
extern undefined4 FUN_8025c428();
extern undefined4 FUN_8025d6ac();
extern undefined4 FUN_8025d80c();
extern undefined4 FUN_8025d888();
extern undefined4 FUN_8025da88();
extern int FUN_80286718();
extern undefined2 FUN_802867ac();
extern undefined4 FUN_802867f8();
extern ulonglong FUN_8028682c();
extern undefined8 FUN_80286830();
extern undefined8 FUN_80286834();
extern undefined8 FUN_80286838();
extern undefined8 FUN_8028683c();
extern short FUN_80286840();
extern undefined4 FUN_80286878();
extern undefined4 FUN_8028687c();
extern undefined4 FUN_80286880();
extern undefined4 FUN_80286884();
extern undefined4 FUN_80286888();
extern undefined4 FUN_8028688c();
extern undefined4 FUN_8028fde8();
extern undefined4 FUN_8028fec8();
extern undefined4 FUN_8029312c();
extern undefined4 FUN_802945e0();
extern undefined4 FUN_80294964();
extern uint FUN_80296328();
extern uint countLeadingZeros();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4 DAT_8030eac0;
extern undefined4 DAT_8030eac4;
extern undefined4 DAT_8031d15c;
extern undefined4 DAT_8031d15e;
extern undefined4 DAT_8031d15f;
extern undefined4 DAT_8031d270;
extern undefined4 DAT_8031d300;
extern undefined4 DAT_8031d302;
extern undefined4 DAT_8031d304;
extern undefined4 DAT_8031d888;
extern undefined4 DAT_8031d88a;
extern undefined4 DAT_8031d8a0;
extern short DAT_8031da38;
extern undefined4 DAT_8031dae0;
extern undefined4 DAT_8031dae2;
extern undefined4 DAT_803974e0;
extern undefined4 DAT_803aaa30;
extern undefined4 DAT_803aab98;
extern int DAT_803aabf8;
extern undefined4 DAT_803aabfc;
extern undefined4 DAT_803aac00;
extern undefined4 DAT_803aac04;
extern undefined4 DAT_803aac08;
extern undefined4 DAT_803aac0c;
extern undefined4 DAT_803aac10;
extern undefined4 DAT_803aac14;
extern undefined4 DAT_803aac18;
extern undefined4 DAT_803aac38;
extern undefined4 DAT_803aac3c;
extern undefined4 DAT_803aac40;
extern undefined4 DAT_803aac44;
extern undefined4 DAT_803aac50;
extern undefined4 DAT_803aac60;
extern undefined DAT_803aac78;
extern undefined4 DAT_803dc070;
extern undefined4 DAT_803dc071;
extern undefined4 DAT_803dc6d6;
extern undefined4 DAT_803dc818;
extern undefined4 DAT_803dc819;
extern undefined4 DAT_803dc828;
extern undefined4 DAT_803dc82c;
extern undefined4 DAT_803dc830;
extern undefined4 DAT_803dc838;
extern undefined4 DAT_803dc83a;
extern undefined4 DAT_803dc850;
extern undefined4 DAT_803dc858;
extern undefined4 DAT_803dc860;
extern undefined4 DAT_803dc864;
extern undefined4 DAT_803dc868;
extern undefined4 DAT_803dc86c;
extern undefined4 DAT_803dc870;
extern undefined4 DAT_803dc871;
extern undefined4 DAT_803dc872;
extern undefined4 DAT_803dc878;
extern undefined* DAT_803dc87c;
extern undefined4 DAT_803dc880;
extern undefined4 DAT_803dc884;
extern undefined4 DAT_803dc888;
extern undefined4 DAT_803dc890;
extern undefined4 DAT_803dc898;
extern undefined4 DAT_803dd5e8;
extern undefined4* DAT_803dd6d0;
extern undefined4* DAT_803dd6d4;
extern undefined4* DAT_803dd6e8;
extern undefined4* DAT_803dd708;
extern undefined4* DAT_803dd720;
extern undefined4* DAT_803dd72c;
extern undefined4* DAT_803dd738;
extern undefined4 DAT_803dd968;
extern undefined4 DAT_803dd96c;
extern undefined4 DAT_803de3db;
extern undefined4 DAT_803de400;
extern undefined4 DAT_803de422;
extern undefined4 DAT_803de43a;
extern undefined4 DAT_803de5a8;
extern undefined4 DAT_803de5a9;
extern undefined4 DAT_803de5aa;
extern undefined4 DAT_803de5ac;
extern undefined4 DAT_803de5b0;
extern undefined4 DAT_803de5b2;
extern undefined4 DAT_803de5b4;
extern undefined4 DAT_803de5b8;
extern undefined4 DAT_803de5bc;
extern undefined4 DAT_803de5c0;
extern undefined4 DAT_803de5c4;
extern undefined4 DAT_803de5c5;
extern undefined4 DAT_803de5c6;
extern undefined4 DAT_803de5c7;
extern undefined4 DAT_803de5c8;
extern undefined4 DAT_803de5ca;
extern undefined4 DAT_803de5dc;
extern undefined4 DAT_803de5e0;
extern undefined4 DAT_803de5ec;
extern undefined4 DAT_803de5f0;
extern undefined4 DAT_803de5f4;
extern undefined4 DAT_803de5f8;
extern undefined4 DAT_803de600;
extern undefined4 DAT_803de604;
extern undefined4 DAT_803de608;
extern undefined4 DAT_803de610;
extern undefined4 DAT_803de611;
extern undefined4 DAT_803de612;
extern undefined4 DAT_803de613;
extern undefined4 DAT_803de614;
extern undefined4 DAT_803de616;
extern undefined4 DAT_803de618;
extern undefined4 DAT_803de620;
extern undefined4 DAT_803de624;
extern undefined4 DAT_803de628;
extern undefined4 DAT_803de62a;
extern undefined4 DAT_803de62b;
extern undefined4 DAT_803de62c;
extern undefined4 DAT_803de638;
extern undefined4 DAT_803de63c;
extern undefined4 DAT_803de640;
extern undefined4 DAT_803de654;
extern undefined4 DAT_803de660;
extern undefined4 DAT_803de661;
extern undefined4 DAT_803de664;
extern undefined4 DAT_803de670;
extern undefined4 DAT_803de671;
extern undefined4 DAT_803de672;
extern undefined4 DAT_803de673;
extern undefined4 DAT_803de674;
extern undefined4 DAT_803de676;
extern undefined4 DAT_803de678;
extern undefined4 DAT_803de67c;
extern undefined4 DAT_803de680;
extern undefined4 DAT_803de684;
extern undefined4 DAT_803de688;
extern undefined4 DAT_803de68c;
extern undefined4 DAT_803de690;
extern undefined4 DAT_803de694;
extern undefined4 DAT_803de696;
extern undefined4 DAT_803de698;
extern undefined4 DAT_803de69a;
extern undefined4 DAT_803de69c;
extern undefined4 DAT_803de6a0;
extern undefined4 DAT_803de6a4;
extern undefined4 DAT_803de6a8;
extern undefined4 DAT_803de6ac;
extern undefined4 DAT_803de6b0;
extern undefined4 DAT_803de6b4;
extern undefined4 DAT_803de6b8;
extern undefined4 DAT_803de6bc;
extern undefined4 DAT_803de6c0;
extern undefined4 DAT_803e2e90;
extern undefined4 DAT_803e2e94;
extern undefined4 DAT_cc008000;
extern f64 DOUBLE_803e2ee0;
extern f64 DOUBLE_803e2ee8;
extern f64 DOUBLE_803e2f50;
extern f64 DOUBLE_803e2f58;
extern f64 DOUBLE_803e2f60;
extern f64 DOUBLE_803e2f78;
extern f64 DOUBLE_803e2f98;
extern f64 DOUBLE_803e2fa0;
extern f64 DOUBLE_803e3038;
extern f64 DOUBLE_803e3040;
extern f64 DOUBLE_803e3090;
extern f32 FLOAT_803dc074;
extern f32 FLOAT_803dc81c;
extern f32 FLOAT_803dc820;
extern f32 FLOAT_803dc824;
extern f32 FLOAT_803dc83c;
extern f32 FLOAT_803dc840;
extern f32 FLOAT_803dc844;
extern f32 FLOAT_803dc848;
extern f32 FLOAT_803dc84c;
extern f32 FLOAT_803dc854;
extern f32 FLOAT_803dc874;
extern f32 FLOAT_803de5cc;
extern f32 FLOAT_803de5d0;
extern f32 FLOAT_803de5d4;
extern f32 FLOAT_803de5d8;
extern f32 FLOAT_803de5e8;
extern f32 FLOAT_803de5fc;
extern f32 FLOAT_803de61c;
extern f32 FLOAT_803de630;
extern f32 FLOAT_803de634;
extern f32 FLOAT_803de644;
extern f32 FLOAT_803de648;
extern f32 FLOAT_803de64c;
extern f32 FLOAT_803de650;
extern f32 FLOAT_803de658;
extern f32 FLOAT_803de65c;
extern f32 FLOAT_803de668;
extern f32 FLOAT_803de66c;
extern f32 FLOAT_803e2e98;
extern f32 FLOAT_803e2e9c;
extern f32 FLOAT_803e2ea0;
extern f32 FLOAT_803e2ea4;
extern f32 FLOAT_803e2ea8;
extern f32 FLOAT_803e2eac;
extern f32 FLOAT_803e2eb4;
extern f32 FLOAT_803e2eb8;
extern f32 FLOAT_803e2ebc;
extern f32 FLOAT_803e2ec0;
extern f32 FLOAT_803e2ec4;
extern f32 FLOAT_803e2ec8;
extern f32 FLOAT_803e2ecc;
extern f32 FLOAT_803e2ed0;
extern f32 FLOAT_803e2ed4;
extern f32 FLOAT_803e2ed8;
extern f32 FLOAT_803e2edc;
extern f32 FLOAT_803e2ef0;
extern f32 FLOAT_803e2ef4;
extern f32 FLOAT_803e2ef8;
extern f32 FLOAT_803e2efc;
extern f32 FLOAT_803e2f08;
extern f32 FLOAT_803e2f0c;
extern f32 FLOAT_803e2f10;
extern f32 FLOAT_803e2f14;
extern f32 FLOAT_803e2f18;
extern f32 FLOAT_803e2f1c;
extern f32 FLOAT_803e2f20;
extern f32 FLOAT_803e2f24;
extern f32 FLOAT_803e2f28;
extern f32 FLOAT_803e2f2c;
extern f32 FLOAT_803e2f30;
extern f32 FLOAT_803e2f38;
extern f32 FLOAT_803e2f3c;
extern f32 FLOAT_803e2f40;
extern f32 FLOAT_803e2f44;
extern f32 FLOAT_803e2f48;
extern f32 FLOAT_803e2f70;
extern f32 FLOAT_803e2f80;
extern f32 FLOAT_803e2f84;
extern f32 FLOAT_803e2f88;
extern f32 FLOAT_803e2f8c;
extern f32 FLOAT_803e2f90;
extern f32 FLOAT_803e2f94;
extern f32 FLOAT_803e2fa8;
extern f32 FLOAT_803e2fac;
extern f32 FLOAT_803e2fb0;
extern f32 FLOAT_803e2fb4;
extern f32 FLOAT_803e2fb8;
extern f32 FLOAT_803e2fbc;
extern f32 FLOAT_803e2fc8;
extern f32 FLOAT_803e2fcc;
extern f32 FLOAT_803e2fd0;
extern f32 FLOAT_803e2fd4;
extern f32 FLOAT_803e2fd8;
extern f32 FLOAT_803e2fdc;
extern f32 FLOAT_803e2fe0;
extern f32 FLOAT_803e2fe4;
extern f32 FLOAT_803e2fe8;
extern f32 FLOAT_803e2fec;
extern f32 FLOAT_803e2ff0;
extern f32 FLOAT_803e2ff4;
extern f32 FLOAT_803e2ff8;
extern f32 FLOAT_803e2ffc;
extern f32 FLOAT_803e3000;
extern f32 FLOAT_803e3004;
extern f32 FLOAT_803e3008;
extern f32 FLOAT_803e300c;
extern f32 FLOAT_803e3010;
extern f32 FLOAT_803e3014;
extern f32 FLOAT_803e3018;
extern f32 FLOAT_803e3020;
extern f32 FLOAT_803e3024;
extern f32 FLOAT_803e3028;
extern f32 FLOAT_803e302c;
extern f32 FLOAT_803e3030;
extern f32 FLOAT_803e3034;
extern f32 FLOAT_803e3048;
extern f32 FLOAT_803e306c;
extern f32 FLOAT_803e3070;
extern f32 FLOAT_803e3074;
extern f32 FLOAT_803e3078;
extern f32 FLOAT_803e307c;
extern f32 FLOAT_803e3080;
extern f32 FLOAT_803e3084;
extern f32 FLOAT_803e3088;
extern f32 FLOAT_803e3098;
extern f32 FLOAT_803e309c;
extern f32 FLOAT_803e30a8;
extern void* PTR_DAT_8030eac8;
extern void* PTR_DAT_8030eacc;
extern void* PTR_DAT_8031d158;
extern int iRam803dc834;
extern char s_Alignment_8031de30[];
extern char s_Exception__8031de04[];
extern char s_General_Purpose_Registers_8031dec0[];
extern char s_Machine_check_8031de20[];
extern char s_Memory_Protection_Error_8031de6c[];
extern char s_Performance_monitor_8031de3c[];
extern char s_Stack__x__depth__d_8031dea0[];
extern char s_Stack_trace_8031de94[];
extern char s_System_management_interrupt_8031de50[];
extern char s_System_reset_8031de10[];
extern char s_Unknown_error_8031de84[];
extern char s__08x__08x_8031deb4[];
extern char s__08x__08x__08x__08x_8031dedc[];
extern char s__d____d_803dc89c[];
extern char s_errorThreadFunc__x_8031ddf0[];

/* Local declarations keep imported functions visible within the TU. */
void FUN_801323ac();
uint FUN_8013385c(void);
void FUN_80133868(void);
void FUN_801338a4();
void FUN_80133aa0();
void FUN_80133ba0();
void FUN_80133cbc(void);
void FUN_80133cf4();
void FUN_8013422c();
void FUN_801342c8();
void FUN_801342f8();
void FUN_801343d4(void);
void FUN_801343f8();
undefined4 FUN_80134428();
void FUN_801346ec(void);
void FUN_80134710();
void FUN_80134754();
void FUN_80134884();
void FUN_80134b90(void);
void FUN_80134bbc();
void FUN_80134bf8(uint param_1,int param_2);
void FUN_80134d50();
undefined FUN_80134f44(void);
void FUN_80134f4c(void);
undefined4 FUN_80134f70(void);
void FUN_80134fb0(double param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 char param_9);
void FUN_801350c8();
void FUN_80135b9c();
void FUN_80135ba8();
void FUN_80135c30();
void FUN_80135e18();
void FUN_80135f78(int param_1);
void FUN_80135fb4(int param_1);
void FUN_80136050();
void FUN_80136b30();
void FUN_80136c2c();
void FUN_80136c4c();
void FUN_80136c5c(void);
void FUN_80136c68();
void FUN_80136ce4();
uint FUN_80136dc8(undefined4 param_1,int param_2);
void FUN_80137188();
void FUN_801378a8();
void FUN_80137928();
void FUN_80137950();
void FUN_80137c30();
void FUN_80137cd0(void);
void FUN_80137d20();
void FUN_80137d88(undefined4 param_1,undefined4 param_2,byte *param_3);
void FUN_80137f08();
void FUN_801380b0(void);
void FUN_8013817c(void);
void FUN_80138180();
void FUN_80138c58();
void FUN_80138c90(int param_1,uint param_2);
undefined4 FUN_80138ca8(int param_1,ushort param_2,short param_3);
void FUN_80138d68(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 int param_9,int param_10,int *param_11);
void FUN_80138ee8(int param_1,undefined4 *param_2);
void FUN_80139104(int param_1,int *param_2);
void FUN_80139280(int param_1);
undefined4 FUN_8013929c(int param_1);
double FUN_80139300(int param_1);
undefined4 FUN_8013930c(int param_1);
int FUN_80139318(int param_1);
int FUN_80139324(int param_1);
void FUN_80139330(void);
void FUN_801394ec(undefined2 *param_1,int param_2);
void FUN_801395e8(void);

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801323AC
 * EN v1.0 Size: 5296b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_801323ac()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8013385C
 * EN v1.0 Size: 12b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
uint FUN_8013385c(void)
{
  return DAT_803de5b8 & 0xffff;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80133868
 * EN v1.0 Size: 60b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80133868(void)
{
  bool bVar1;
  
  bVar1 = false;
  if ((DAT_803de5c4 == '\x02') && (DAT_803dc818 != '\0')) {
    bVar1 = true;
  }
  if (!bVar1) {
    return;
  }
  DAT_803de5a8 = 5;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801338A4
 * EN v1.0 Size: 508b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_801338a4()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80133AA0
 * EN v1.0 Size: 256b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80133aa0()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80133BA0
 * EN v1.0 Size: 284b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80133ba0()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80133CBC
 * EN v1.0 Size: 56b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80133cbc(void)
{
  if (DAT_803de5bc != 0) {
    FUN_80054484();
    DAT_803de5bc = 0;
    DAT_803de5ac = 0;
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80133CF4
 * EN v1.0 Size: 1336b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80133cf4()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8013422C
 * EN v1.0 Size: 156b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8013422c()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801342C8
 * EN v1.0 Size: 48b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_801342c8()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801342F8
 * EN v1.0 Size: 220b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_801342f8()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801343D4
 * EN v1.0 Size: 36b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_801343d4(void)
{
  FUN_80054484();
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801343F8
 * EN v1.0 Size: 48b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_801343f8()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80134428
 * EN v1.0 Size: 708b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
undefined4 FUN_80134428()
{
    return 0;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801346EC
 * EN v1.0 Size: 36b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_801346ec(void)
{
  FUN_80054484();
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80134710
 * EN v1.0 Size: 68b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80134710()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80134754
 * EN v1.0 Size: 304b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80134754()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80134884
 * EN v1.0 Size: 780b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80134884()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80134B90
 * EN v1.0 Size: 44b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80134b90(void)
{
  FUN_80054484();
  FUN_80054484();
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80134BBC
 * EN v1.0 Size: 60b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80134bbc()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80134BF8
 * EN v1.0 Size: 344b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80134bf8(uint param_1,int param_2)
{
  char cVar1;
  short sVar2;
  int iVar3;
  
  for (iVar3 = 0; iVar3 < *(char *)(param_2 + 0x1b); iVar3 = iVar3 + 1) {
    sVar2 = *(short *)(param_1 + 0x46);
    if (sVar2 == 0x77f) {
      cVar1 = *(char *)(param_2 + iVar3 + 0x13);
      if (cVar1 == '\0') {
        FUN_8000bb38(param_1,0x36b);
      }
      else if (cVar1 == '\a') {
        FUN_8000bb38(param_1,0x421);
      }
    }
    else if (sVar2 < 0x77f) {
      if (sVar2 == 0x77d) {
        if (*(char *)(param_2 + iVar3 + 0x13) == '\0') {
          FUN_8000bb38(param_1,0x368);
        }
      }
      else if (0x77c < sVar2) {
        cVar1 = *(char *)(param_2 + iVar3 + 0x13);
        if (cVar1 == '\0') {
          FUN_8000bb38(param_1,0x370);
        }
        else if (cVar1 == '\a') {
          FUN_8000bb38(param_1,0x36c);
        }
      }
    }
    else if (sVar2 < 0x781) {
      cVar1 = *(char *)(param_2 + iVar3 + 0x13);
      if (cVar1 == '\0') {
        FUN_8000bb38(param_1,0x36a);
      }
      else if (cVar1 == '\a') {
        FUN_8000bb38(param_1,0x369);
      }
    }
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80134D50
 * EN v1.0 Size: 500b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80134d50()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80134F44
 * EN v1.0 Size: 8b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
undefined FUN_80134f44(void)
{
  return DAT_803de613;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80134F4C
 * EN v1.0 Size: 36b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80134f4c(void)
{
  DAT_803de613 = 1;
  DAT_803de614 = 0;
  DAT_803de616 = 0;
  DAT_803de628 = 0;
  DAT_803de618 = 0;
  DAT_803de62a = 0;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80134F70
 * EN v1.0 Size: 64b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
undefined4 FUN_80134f70(void)
{
  int iVar1;
  undefined4 uVar2;
  
  iVar1 = FUN_8001496c();
  if ((iVar1 - 2U < 5) || (iVar1 == 7)) {
    uVar2 = 1;
  }
  else {
    uVar2 = 0;
  }
  return uVar2;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80134FB0
 * EN v1.0 Size: 280b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80134fb0(double param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 char param_9)
{
  ushort *puVar1;
  undefined *puVar2;
  undefined8 uVar3;
  double dVar4;
  double dVar5;
  
  if (param_9 == '\0') {
    if (DAT_803de620 == '\0') {
      FLOAT_803de61c = FLOAT_803e2fa8;
      param_1 = (double)FLOAT_803de634;
      if ((double)FLOAT_803e2fac < param_1) {
        DAT_803de620 = '\x01';
      }
    }
    else {
      FLOAT_803de61c = FLOAT_803de634;
    }
  }
  else {
    FLOAT_803de61c = FLOAT_803e2fa8;
    DAT_803de620 = '\0';
  }
  puVar1 = FUN_800195a8(param_1,param_2,param_3,param_4,param_5,param_6,param_7,param_8,0x3d9);
  if (*puVar1 != 0xffff) {
    puVar2 = FUN_80017400((uint)*(byte *)(puVar1 + 2));
    if (DAT_803de62c == 0) {
      DAT_803de62c = (uint)*(short *)(puVar2 + 0x16);
    }
    dVar5 = (double)FLOAT_803e2fb0;
    dVar4 = (double)(FLOAT_803e2fa8 - FLOAT_803de61c);
    *(short *)(puVar2 + 0x16) =
         (short)(int)(dVar5 * dVar4 +
                     (double)(float)((double)CONCAT44(0x43300000,DAT_803de62c ^ 0x80000000) -
                                    DOUBLE_803e2f78));
    uVar3 = FUN_80019940(0xff,0xff,0xff,(byte)(int)(FLOAT_803e2fb4 * FLOAT_803de630));
    FUN_800168a8(uVar3,dVar4,dVar5,param_4,param_5,param_6,param_7,param_8,0x3d9);
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801350C8
 * EN v1.0 Size: 2772b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_801350c8()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80135B9C
 * EN v1.0 Size: 12b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80135b9c()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80135BA8
 * EN v1.0 Size: 136b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80135ba8()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80135C30
 * EN v1.0 Size: 488b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80135c30()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80135E18
 * EN v1.0 Size: 352b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80135e18()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80135F78
 * EN v1.0 Size: 60b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80135f78(int param_1)
{
  if (*(short *)(param_1 + 0x46) == 0x77d) {
    FUN_8000a538((int *)0x3a,0);
    DAT_803de613 = 0;
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80135FB4
 * EN v1.0 Size: 156b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80135fb4(int param_1)
{
  char in_r8;
  
  if ((in_r8 != '\0') && (DAT_803de62b != '\0')) {
    FUN_8003b9ec(param_1);
    if ((DAT_803de613 != '\0') && (DAT_803de62a == '\0')) {
      FUN_800201ac(0xdf6,1);
      DAT_803de62a = '\x01';
      (**(code **)(*DAT_803dd6d4 + 0x50))(0x57,0,0,0);
      FUN_801163b8();
      DAT_803de624 = 0;
    }
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80136050
 * EN v1.0 Size: 2784b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80136050()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80136B30
 * EN v1.0 Size: 252b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80136b30()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80136C2C
 * EN v1.0 Size: 32b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80136c2c()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80136C4C
 * EN v1.0 Size: 16b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80136c4c()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80136C5C
 * EN v1.0 Size: 12b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80136c5c(void)
{
  DAT_803de62b = 0;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80136C68
 * EN v1.0 Size: 124b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80136c68()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80136CE4
 * EN v1.0 Size: 228b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80136ce4()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80136DC8
 * EN v1.0 Size: 960b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
uint FUN_80136dc8(undefined4 param_1,int param_2)
{
  uint uVar1;
  uint uVar2;
  int iVar3;
  uint uVar4;
  uint uVar5;
  
  if (param_2 < 0x40) {
    if (DAT_803de678 != 0) {
      if (DAT_803de68c != 0) {
        FUN_8004c460(DAT_803de6a4,0);
        FLOAT_803de66c =
             FLOAT_803e3020 /
             (FLOAT_803e3024 *
             (float)((double)CONCAT44(0x43300000,(uint)*(ushort *)(DAT_803de6a4 + 10)) -
                    DOUBLE_803e3038));
        FLOAT_803de668 =
             FLOAT_803e3020 /
             (FLOAT_803e3024 *
             (float)((double)CONCAT44(0x43300000,(uint)*(ushort *)(DAT_803de6a4 + 0xc)) -
                    DOUBLE_803e3038));
      }
      DAT_803de678 = 0;
    }
    param_2 = param_2 + -0x21;
  }
  else if (param_2 < 0x60) {
    if (DAT_803de678 != 1) {
      if (DAT_803de68c != 0) {
        FUN_8004c460(DAT_803de6a0,0);
        FLOAT_803de66c =
             FLOAT_803e3020 /
             (FLOAT_803e3024 *
             (float)((double)CONCAT44(0x43300000,(uint)*(ushort *)(DAT_803de6a0 + 10)) -
                    DOUBLE_803e3038));
        FLOAT_803de668 =
             FLOAT_803e3020 /
             (FLOAT_803e3024 *
             (float)((double)CONCAT44(0x43300000,(uint)*(ushort *)(DAT_803de6a0 + 0xc)) -
                    DOUBLE_803e3038));
      }
      DAT_803de678 = 1;
    }
    param_2 = param_2 + -0x40;
  }
  else if (param_2 < 0x80) {
    if (DAT_803de678 != 2) {
      if (DAT_803de68c != 0) {
        FUN_8004c460(DAT_803de69c,0);
        FLOAT_803de66c =
             FLOAT_803e3020 /
             (FLOAT_803e3024 *
             (float)((double)CONCAT44(0x43300000,(uint)*(ushort *)(DAT_803de69c + 10)) -
                    DOUBLE_803e3038));
        FLOAT_803de668 =
             FLOAT_803e3020 /
             (FLOAT_803e3024 *
             (float)((double)CONCAT44(0x43300000,(uint)*(ushort *)(DAT_803de69c + 0xc)) -
                    DOUBLE_803e3038));
      }
      DAT_803de678 = 2;
    }
    param_2 = param_2 + -0x60;
  }
  iVar3 = DAT_803de678 * 0x40 + -0x7fce2410;
  uVar5 = (uint)*(byte *)(iVar3 + param_2 * 2);
  uVar4 = (*(byte *)(iVar3 + param_2 * 2 + 1) - uVar5) + 1;
  if (DAT_803de68c != 0) {
    uVar1 = (uint)((float)((double)CONCAT44(0x43300000,(uint)DAT_803de69a) - DOUBLE_803e3038) *
                  (FLOAT_803de658 +
                  (float)((double)CONCAT44(0x43300000,(uint)DAT_803de660) - DOUBLE_803e3038)));
    uVar2 = (uint)((float)((double)CONCAT44(0x43300000,(uint)DAT_803de698) - DOUBLE_803e3038) *
                  (FLOAT_803de65c +
                  (float)((double)CONCAT44(0x43300000,(uint)DAT_803de661) - DOUBLE_803e3038)));
    FUN_80078d98();
    FUN_80076008((double)((float)((double)CONCAT44(0x43300000,uVar5 << 5 ^ 0x80000000) -
                                 DOUBLE_803e3040) * FLOAT_803de66c),(double)FLOAT_803e3030,
                 (double)(FLOAT_803de66c *
                         (float)((double)CONCAT44(0x43300000,(uVar5 + uVar4) * 0x20 ^ 0x80000000) -
                                DOUBLE_803e3040)),(double)(FLOAT_803e3034 * FLOAT_803de668),
                 uVar1 << 2,uVar2 << 2,
                 (short)(int)(FLOAT_803e3028 *
                             ((float)((double)CONCAT44(0x43300000,uVar4 ^ 0x80000000) -
                                     DOUBLE_803e3040) *
                              (FLOAT_803de658 +
                              (float)((double)CONCAT44(0x43300000,(uint)DAT_803de660) -
                                     DOUBLE_803e3038)) +
                             (float)((double)CONCAT44(0x43300000,uVar1 ^ 0x80000000) -
                                    DOUBLE_803e3040))),
                 (short)(int)(FLOAT_803e3028 *
                             (FLOAT_803e302c *
                              (FLOAT_803de65c +
                              (float)((double)CONCAT44(0x43300000,(uint)DAT_803de661) -
                                     DOUBLE_803e3038)) +
                             (float)((double)CONCAT44(0x43300000,uVar2 ^ 0x80000000) -
                                    DOUBLE_803e3040))));
  }
  return uVar4;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80137188
 * EN v1.0 Size: 1824b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80137188()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801378A8
 * EN v1.0 Size: 128b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_801378a8()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80137928
 * EN v1.0 Size: 40b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80137928()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80137950
 * EN v1.0 Size: 736b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80137950()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80137C30
 * EN v1.0 Size: 160b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80137c30()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80137CD0
 * EN v1.0 Size: 80b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80137cd0(void)
{
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80137D20
 * EN v1.0 Size: 104b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80137d20()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80137D88
 * EN v1.0 Size: 384b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80137d88(undefined4 param_1,undefined4 param_2,byte *param_3)
{
  int iVar1;
  int iVar2;
  int iVar3;
  int iVar4;
  int iVar5;
  int iVar6;
  int iVar7;
  int iVar8;
  int iVar9;
  int iVar10;
  int iVar11;
  int iVar12;
  undefined8 uVar13;
  
  uVar13 = FUN_80286838();
  iVar1 = (int)((ulonglong)uVar13 >> 0x20);
  if (DAT_803de6a8 != '\0') {
    iVar10 = 0;
    iVar8 = ((int)uVar13 + 1) * 0x280;
    iVar9 = (int)uVar13 * 0x280;
    do {
      iVar7 = 0;
      iVar6 = iVar1 + iVar9;
      iVar11 = iVar1 + iVar8;
      iVar5 = (iVar11 + 1) * 2;
      iVar4 = iVar11 * 2;
      iVar3 = (iVar6 + 1) * 2;
      iVar2 = iVar6 * 2;
      iVar12 = 4;
      do {
        if ((1 << iVar7 & (uint)*param_3) != 0) {
          *(undefined2 *)(DAT_803de6b0 + iVar2) = 0xc080;
          *(undefined2 *)(DAT_803de6b0 + iVar3) = 0xc080;
          *(undefined2 *)(DAT_803de6b0 + iVar4) = 0xc080;
          *(undefined2 *)(DAT_803de6b0 + iVar5) = 0xc080;
        }
        if ((1 << iVar7 + 1 & (uint)*param_3) != 0) {
          *(undefined2 *)(DAT_803de6b0 + iVar2 + 2) = 0xc080;
          *(undefined2 *)(DAT_803de6b0 + iVar3 + 2) = 0xc080;
          *(undefined2 *)(DAT_803de6b0 + iVar4 + 2) = 0xc080;
          *(undefined2 *)(DAT_803de6b0 + iVar5 + 2) = 0xc080;
        }
        iVar2 = iVar2 + 4;
        iVar3 = iVar3 + 4;
        iVar4 = iVar4 + 4;
        iVar5 = iVar5 + 4;
        iVar7 = iVar7 + 2;
        iVar12 = iVar12 + -1;
      } while (iVar12 != 0);
      FUN_80242114(DAT_803de6b0 + iVar6 * 2,0x10);
      FUN_80242114(DAT_803de6b0 + iVar11 * 2,0x10);
      iVar9 = iVar9 + 0x500;
      iVar8 = iVar8 + 0x500;
      iVar10 = iVar10 + 1;
      param_3 = param_3 + 1;
    } while (iVar10 < 5);
  }
  FUN_80286884();
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80137F08
 * EN v1.0 Size: 424b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80137f08()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801380B0
 * EN v1.0 Size: 204b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_801380b0(void)
{
  FUN_802430ec(0,FUN_80138c58);
  FUN_802430ec(1,FUN_80138c58);
  FUN_802430ec(2,FUN_80138c58);
  FUN_802430ec(0xb,FUN_80138c58);
  FUN_802430ec(0xd,FUN_80138c58);
  FUN_802430ec(0xf,FUN_80138c58);
  FUN_802430ec(3,FUN_80138c58);
  FUN_802430ec(5,FUN_80138c58);
  FUN_80246a0c(-0x7fc54288,FUN_80138180,0,0x803ad088,0x1000,0,1);
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8013817C
 * EN v1.0 Size: 4b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8013817c(void)
{
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80138180
 * EN v1.0 Size: 2776b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80138180()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80138C58
 * EN v1.0 Size: 56b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80138c58()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80138C90
 * EN v1.0 Size: 24b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80138c90(int param_1,uint param_2)
{
  *(byte *)(*(int *)(param_1 + 0xb8) + 0x58) =
       (byte)((param_2 & 0xff) << 6) & 0x40 | *(byte *)(*(int *)(param_1 + 0xb8) + 0x58) & 0xbf;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80138CA8
 * EN v1.0 Size: 192b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
undefined4 FUN_80138ca8(int param_1,ushort param_2,short param_3)
{
  undefined4 uVar1;
  bool bVar2;
  int iVar3;
  
  iVar3 = *(int *)(param_1 + 0xb8);
  if ((*(byte *)(iVar3 + 0x58) >> 6 & 1) == 0) {
    if ((*(short *)(param_1 + 0xa0) < 0x30) && (0x28 < *(short *)(param_1 + 0xa0))) {
      uVar1 = 0;
    }
    else {
      bVar2 = FUN_8000b598(param_1,0x10);
      if (bVar2) {
        uVar1 = 0;
      }
      else {
        FUN_800394f0(param_1,iVar3 + 0x3a8,param_2,param_3,0xffffffff,0);
        uVar1 = 1;
      }
    }
  }
  else {
    uVar1 = 0;
  }
  return uVar1;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80138D68
 * EN v1.0 Size: 384b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80138d68(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 int param_9,int param_10,int *param_11)
{
  int iVar1;
  int iVar2;
  int iVar3;
  undefined8 uVar4;
  char local_18 [12];
  
  if (*param_11 != 0) {
    uVar4 = FUN_80037da8(param_9,*param_11);
    FUN_8002cc9c(uVar4,param_2,param_3,param_4,param_5,param_6,param_7,param_8,*param_11);
    *param_11 = 0;
    local_18[0] = -1;
    local_18[1] = 0xff;
    local_18[2] = 0xff;
    iVar1 = *(int *)(param_10 + 0x7a8);
    if (iVar1 != 0) {
      local_18[*(byte *)(param_10 + 0x7bc) >> 6] = '\x01';
    }
    iVar2 = *(int *)(param_10 + 0x7b0);
    if (iVar2 != 0) {
      local_18[*(byte *)(param_10 + 0x7bc) >> 4 & 3] = '\x01';
    }
    iVar3 = *(int *)(param_10 + 0x7b8);
    if (iVar3 != 0) {
      local_18[*(byte *)(param_10 + 0x7bc) >> 2 & 3] = '\x01';
    }
    if (local_18[0] == -1) {
      if (iVar1 == 0) {
        if (iVar2 == 0) {
          if (iVar3 != 0) {
            FUN_80037da8(param_9,iVar3);
            FUN_80037e24(param_9,*(int *)(param_10 + 0x7b8),0);
            *(byte *)(param_10 + 0x7bc) = *(byte *)(param_10 + 0x7bc) & 0xf3;
          }
        }
        else {
          FUN_80037da8(param_9,iVar2);
          FUN_80037e24(param_9,*(int *)(param_10 + 0x7b0),0);
          *(byte *)(param_10 + 0x7bc) = *(byte *)(param_10 + 0x7bc) & 0xcf;
        }
      }
      else {
        FUN_80037da8(param_9,iVar1);
        FUN_80037e24(param_9,*(int *)(param_10 + 0x7a8),0);
        *(byte *)(param_10 + 0x7bc) = *(byte *)(param_10 + 0x7bc) & 0x3f;
      }
    }
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80138EE8
 * EN v1.0 Size: 540b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80138ee8(int param_1,undefined4 *param_2)
{
  float fVar1;
  float fVar2;
  int *piVar3;
  
  FUN_8002b660(param_1);
  if (*(char *)((int)param_2 + 0x82e) < '\0') {
    piVar3 = (int *)FUN_8002b660(param_1);
    FUN_80027a90((double)FLOAT_803e306c,piVar3,1,-1,0x1a,0x21);
    param_2[0x20c] = FLOAT_803e3070;
    FUN_80027a44((double)FLOAT_803e306c,piVar3,0);
    *(byte *)((int)param_2 + 0x82e) = *(byte *)((int)param_2 + 0x82e) & 0x7f;
    *(byte *)((int)param_2 + 0x82e) = *(byte *)((int)param_2 + 0x82e) & 0xbf | 0x40;
  }
  if ((*(byte *)((int)param_2 + 0x82e) >> 6 & 1) != 0) {
    fVar1 = (float)((double)CONCAT44(0x43300000,(uint)*(byte *)*param_2) - DOUBLE_803e3090) /
            (float)((double)CONCAT44(0x43300000,(uint)((byte *)*param_2)[1]) - DOUBLE_803e3090);
    if (fVar1 <= (float)param_2[0x20c]) {
      if (fVar1 < (float)param_2[0x20c]) {
        param_2[0x20d] = -(FLOAT_803e3074 * FLOAT_803dc074 - (float)param_2[0x20d]);
        param_2[0x20c] = (float)param_2[0x20d] * FLOAT_803dc074 + (float)param_2[0x20c];
        fVar2 = FLOAT_803e306c;
        if ((float)param_2[0x20c] < FLOAT_803e306c) {
          param_2[0x20d] = FLOAT_803e306c;
          param_2[0x20c] = fVar2;
        }
        if ((float)param_2[0x20c] < fVar1) {
          if ((float)param_2[0x20d] <= FLOAT_803e3084) {
            param_2[0x20d] = (float)param_2[0x20d] * FLOAT_803e3080;
          }
          else {
            param_2[0x20d] = FLOAT_803e306c;
            param_2[0x20c] = fVar1;
          }
        }
      }
    }
    else {
      param_2[0x20d] = FLOAT_803e3074 * FLOAT_803dc074 + (float)param_2[0x20d];
      param_2[0x20c] = (float)param_2[0x20d] * FLOAT_803dc074 + (float)param_2[0x20c];
      fVar2 = FLOAT_803e3078;
      if ((float)param_2[0x20c] <= FLOAT_803e3078) {
        if (fVar1 < (float)param_2[0x20c]) {
          if (FLOAT_803e307c <= (float)param_2[0x20d]) {
            param_2[0x20d] = (float)param_2[0x20d] * FLOAT_803e3080;
          }
          else {
            param_2[0x20d] = FLOAT_803e306c;
            param_2[0x20c] = fVar1;
          }
        }
      }
      else {
        param_2[0x20d] = FLOAT_803e306c;
        param_2[0x20c] = fVar2;
      }
    }
    piVar3 = (int *)FUN_8002b660(param_1);
    FUN_80027a44((double)(FLOAT_803e3088 * (float)param_2[0x20c] - FLOAT_803e3078),piVar3,1);
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80139104
 * EN v1.0 Size: 380b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80139104(int param_1,int *param_2)
{
  float fVar1;
  uint uVar2;
  uint uVar3;
  int iVar4;
  undefined uVar5;
  
  uVar2 = *(byte *)(*param_2 + 2) / 10;
  if (*(byte *)(param_2 + 0x20b) != uVar2) {
    uVar3 = FUN_80020078(0x3ed);
    if (uVar3 == 0) {
      FUN_800201ac(0x3ed,1);
      (**(code **)(*DAT_803dd6d4 + 0x48))(5,param_1,0xffffffff);
      param_2[0x15] = param_2[0x15] | 0x4000;
      param_2[0x20a] = (int)((float)param_2[0x20a] + FLOAT_803e3098);
    }
    param_2[0x20a] = (int)((float)param_2[0x20a] - FLOAT_803dc074);
    fVar1 = (float)param_2[0x20a];
    if (fVar1 <= FLOAT_803e3098) {
      uVar5 = (undefined)uVar2;
      if (fVar1 <= FLOAT_803e306c) {
        *(undefined *)(param_2 + 0x20b) = uVar5;
        FUN_8002ae08(param_1,0,0,0,0,0);
      }
      else {
        if (fVar1 <= FLOAT_803e3070) {
          iVar4 = FUN_8002b660(param_1);
          *(undefined *)(*(int *)(iVar4 + 0x34) + 8) = uVar5;
          fVar1 = (float)param_2[0x20a] / FLOAT_803e3070;
        }
        else {
          fVar1 = FLOAT_803e3078 - (fVar1 - FLOAT_803e3070) / FLOAT_803e3070;
        }
        FUN_8002ae08(param_1,0xff,0xff,0xff,(int)(FLOAT_803e309c * fVar1),1);
      }
    }
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80139280
 * EN v1.0 Size: 28b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80139280(int param_1)
{
  int iVar1;
  
  iVar1 = *(int *)(param_1 + 0xb8);
  *(uint *)(iVar1 + 0x54) = *(uint *)(iVar1 + 0x54) | 0x80000000;
  *(float *)(iVar1 + 0x808) = FLOAT_803e3098;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8013929C
 * EN v1.0 Size: 100b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
undefined4 FUN_8013929c(int param_1)
{
  uint uVar1;
  undefined4 uVar2;
  int iVar3;
  
  iVar3 = *(int *)(param_1 + 0xb8);
  uVar1 = FUN_80020078(0x4e4);
  if ((uVar1 == 0) ||
     (*(uint *)(iVar3 + 0x54) = *(uint *)(iVar3 + 0x54) | 0x10000,
     (*(uint *)(iVar3 + 0x54) & 0x10) == 0)) {
    uVar2 = 0;
  }
  else {
    uVar2 = 1;
  }
  return uVar2;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80139300
 * EN v1.0 Size: 12b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
double FUN_80139300(int param_1)
{
  return (double)*(float *)(*(int *)(param_1 + 0xb8) + 0x14);
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8013930C
 * EN v1.0 Size: 12b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
undefined4 FUN_8013930c(int param_1)
{
  return *(undefined4 *)(*(int *)(param_1 + 0xb8) + 0x24);
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80139318
 * EN v1.0 Size: 12b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
int FUN_80139318(int param_1)
{
  return (int)*(short *)(*(int *)(param_1 + 0xb8) + 0x414);
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80139324
 * EN v1.0 Size: 12b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
int FUN_80139324(int param_1)
{
  return *(int *)(param_1 + 0xb8) + 0x408;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80139330
 * EN v1.0 Size: 444b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80139330(void)
{
  short sVar1;
  int *piVar2;
  int iVar3;
  uint uVar4;
  uint uVar5;
  uint uVar6;
  int iVar7;
  double extraout_f1;
  double dVar8;
  double in_f30;
  double dVar9;
  double in_f31;
  double in_ps30_1;
  double in_ps31_1;
  undefined8 uVar10;
  int local_48 [12];
  float local_18;
  float fStack_14;
  float local_8;
  float fStack_4;
  
  local_8 = (float)in_f31;
  fStack_4 = (float)in_ps31_1;
  local_18 = (float)in_f30;
  fStack_14 = (float)in_ps30_1;
  uVar10 = FUN_80286834();
  dVar9 = extraout_f1;
  piVar2 = FUN_80037048(3,local_48);
  dVar9 = (double)(float)(dVar9 * dVar9);
  for (iVar7 = 0; iVar7 < local_48[0]; iVar7 = iVar7 + 1) {
    iVar3 = FUN_80111fb0(*piVar2);
    if (iVar3 == 0) {
      dVar8 = FUN_8014ca48(*piVar2);
    }
    else {
      dVar8 = (double)(**(code **)(*DAT_803dd738 + 0x60))(*piVar2);
    }
    iVar3 = *(int *)(*piVar2 + 0x4c);
    if ((int)*(short *)(iVar3 + 0x18) == 0xffffffff) {
      uVar5 = 0;
    }
    else {
      uVar5 = FUN_80020078((int)*(short *)(iVar3 + 0x18));
    }
    if ((int)*(short *)(iVar3 + 0x1a) == 0xffffffff) {
      uVar6 = 1;
    }
    else {
      uVar6 = FUN_80020078((int)*(short *)(iVar3 + 0x1a));
    }
    uVar4 = FUN_80036d04(*piVar2,0x31);
    if ((((((uVar4 == 0) && ((double)FLOAT_803e306c < dVar8)) && (uVar5 == 0)) &&
         ((uVar6 != 0 && (*(short *)(*piVar2 + 0x46) != 0x851)))) &&
        (iVar3 = (**(code **)(*DAT_803dd72c + 0x68))(*(undefined4 *)(iVar3 + 0x14)), iVar3 != 0)) &&
       ((((int)uVar10 != 0 ||
         (((sVar1 = *(short *)(*piVar2 + 0x46), sVar1 != 0x3fe && (sVar1 != 0x4d7)) &&
          ((sVar1 != 0x27c && (sVar1 != 0x251)))))) &&
        (dVar8 = FUN_80021794((float *)((int)((ulonglong)uVar10 >> 0x20) + 0x18),
                              (float *)(*piVar2 + 0x18)), dVar8 < dVar9)))) {
      dVar9 = dVar8;
    }
    piVar2 = piVar2 + 1;
  }
  FUN_80286880();
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801394EC
 * EN v1.0 Size: 252b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_801394ec(undefined2 *param_1,int param_2)
{
  bool bVar1;
  char cVar2;
  undefined2 local_28;
  undefined2 local_26;
  undefined2 local_24;
  float local_20;
  float local_1c;
  float local_18;
  float local_14;
  
  cVar2 = '\x14';
  if ((*(uint *)(param_2 + 0x54) & 0x1800) != 0) {
    local_1c = *(float *)(param_2 + 0x408) - *(float *)(param_1 + 0xc);
    local_18 = *(float *)(param_2 + 0x40c) - *(float *)(param_1 + 0xe);
    local_14 = *(float *)(param_2 + 0x410) - *(float *)(param_1 + 0x10);
    local_20 = FLOAT_803e3078;
    local_28 = *param_1;
    local_26 = param_1[1];
    local_24 = param_1[2];
    if ((*(uint *)(param_2 + 0x54) & 0x800) == 0) {
      while (bVar1 = cVar2 != '\0', cVar2 = cVar2 + -1, bVar1) {
        (**(code **)(*DAT_803dd708 + 8))(param_1,0x533,&local_28,2,0xffffffff,0);
      }
      *(uint *)(param_2 + 0x54) = *(uint *)(param_2 + 0x54) & 0xffffefff;
    }
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801395E8
 * EN v1.0 Size: 316b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_801395e8(void)
{
  int iVar1;
  int iVar2;
  int iVar3;
  int iVar4;
  int iVar5;
  double dVar6;
  double dVar7;
  double dVar8;
  undefined8 uVar9;
  
  uVar9 = FUN_8028683c();
  iVar1 = (int)((ulonglong)uVar9 >> 0x20);
  dVar7 = (double)FLOAT_803e30a8;
  iVar4 = 0;
  iVar3 = 0;
  iVar2 = iVar1;
  dVar8 = dVar7;
  for (iVar5 = 0; iVar5 < (int)(uint)*(byte *)(iVar1 + 0x798); iVar5 = iVar5 + 1) {
    if ((int)*(char *)(iVar2 + 0x74d) == (int)uVar9) {
      dVar6 = FUN_80021730((float *)(*(int *)(iVar1 + 4) + 0x18),
                           (float *)(*(int *)(iVar2 + 0x748) + 0x18));
      if (*(char *)(iVar2 + 0x74c) == '\x01') {
        if (dVar6 < dVar8) {
          iVar4 = *(int *)(iVar2 + 0x748);
          dVar8 = dVar6;
        }
      }
      else if (dVar6 < dVar7) {
        iVar3 = *(int *)(iVar2 + 0x748);
        dVar7 = dVar6;
      }
    }
    iVar2 = iVar2 + 8;
  }
  if (iVar4 == 0) {
    if (iVar3 == 0) goto LAB_801396fc;
    *(int *)(iVar1 + 0x24) = iVar3;
  }
  else {
    *(int *)(iVar1 + 0x24) = iVar4;
  }
  iVar2 = *(int *)(iVar1 + 0x24) + 0x18;
  if (*(int *)(iVar1 + 0x28) != iVar2) {
    *(int *)(iVar1 + 0x28) = iVar2;
    *(uint *)(iVar1 + 0x54) = *(uint *)(iVar1 + 0x54) & 0xfffffbff;
    *(undefined2 *)(iVar1 + 0xd2) = 0;
  }
  *(undefined *)(iVar1 + 10) = 0;
LAB_801396fc:
  FUN_80286888();
  return;
}
