/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/DIM/DIMbosstonsil.c
 * Text span: 0x801BDA04-0x801BDD60
 * Imported Ghidra functions: 1
 * Verbatim-safe functions: 0
 * Auto-stubbed functions: 1
 */

#include "ghidra_import.h"
#include "main/dll/DIM/DIMbosstonsil.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined8 FUN_80008cbc();
extern undefined4 FUN_800168a8();
extern uint FUN_80020078();
extern undefined8 FUN_800201ac();
extern undefined8 FUN_8002854c();
extern undefined4 FUN_8002b554();
extern int FUN_8002b660();
extern undefined4 FUN_8002ba84();
extern undefined4 FUN_8002bac4();
extern undefined8 FUN_80033a34();
extern undefined4 FUN_80089734();
extern undefined4 FUN_8008986c();
extern undefined4 FUN_8008999c();
extern undefined4 FUN_80115328();
extern undefined8 FUN_80115330();
extern undefined4 FUN_801bc0f8();
extern undefined4 FUN_801bcd98();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4 DAT_803ad60c;
extern undefined4* DAT_803dd6d4;
extern undefined4* DAT_803dd738;
extern f32 FLOAT_803dc074;
extern f32 FLOAT_803e5870;
extern f32 FLOAT_803e58dc;
extern f32 FLOAT_803e58e4;
extern f32 FLOAT_803e58e8;
extern f32 FLOAT_803e58ec;

/* Local declarations keep imported functions visible within the TU. */
void FUN_801bda04(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 ushort *param_9);

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801BDA04
 * EN v1.0 Size: 860b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_801bda04(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 ushort *param_9)
{
}
