/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/DIM/DIMboss.c
 * Text span: 0x801BD0E8-0x801BDA04
 * Imported Ghidra functions: 4
 * Verbatim-safe functions: 1
 * Auto-stubbed functions: 3
 */

#include "ghidra_import.h"
#include "main/dll/DIM/DIMboss.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_8000a538();
extern undefined4 FUN_8000faec();
extern undefined4 FUN_80013e4c();
extern undefined8 FUN_80014f6c();
extern undefined4 FUN_80015650();
extern undefined4 FUN_80019c5c();
extern undefined4 FUN_8001f448();
extern uint FUN_80020078();
extern undefined8 FUN_800201ac();
extern undefined4 FUN_80020390();
extern undefined8 FUN_800235b0();
extern undefined8 FUN_80028500();
extern int FUN_8002b660();
extern undefined4 FUN_8002bac4();
extern undefined4 FUN_8002cc9c();
extern undefined8 FUN_8003709c();
extern undefined4 FUN_8003b9ec();
extern undefined8 FUN_80041f34();
extern undefined8 FUN_8004312c();
extern undefined8 FUN_8004316c();
extern uint FUN_800431a4();
extern undefined4 FUN_80043604();
extern undefined4 FUN_80043658();
extern undefined8 FUN_80043938();
extern undefined8 FUN_80044548();
extern undefined4 FUN_8004832c();
extern undefined8 FUN_80048350();
extern undefined4 FUN_8004a5b8();
extern undefined8 FUN_8004a9e4();
extern undefined4 FUN_8005517c();
extern undefined4 FUN_80060630();
extern undefined8 FUN_8007d858();
extern undefined8 FUN_80114e4c();
extern undefined4 FUN_80115088();
extern undefined4 FUN_801bbb4c();
extern undefined4 FUN_801bc0f8();
extern undefined8 FUN_801bcd98();
extern undefined4 FUN_80286834();
extern undefined4 FUN_80286880();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4 DAT_803ad63c;
extern undefined4 DAT_803adc60;
extern undefined4 DAT_803adc78;
extern undefined4 DAT_803dd5d0;
extern undefined4* DAT_803dd6d4;
extern undefined4* DAT_803dd70c;
extern undefined4* DAT_803dd72c;
extern undefined4* DAT_803dd734;
extern undefined4* DAT_803dd738;
extern undefined4 DAT_803de800;
extern undefined4 DAT_803de808;
extern f32 FLOAT_803e58dc;
extern f32 FLOAT_803e5908;

/* Local declarations keep imported functions visible within the TU. */
void FUN_801bd0e8(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 undefined4 param_9,undefined4 param_10,int param_11,undefined4 param_12,
                 undefined4 param_13,int param_14,int param_15,undefined4 param_16);
void FUN_801bd814(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 int param_9);
void FUN_801bd918(short *param_1);
void FUN_801bd9c8(int param_1);

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801BD0E8
 * EN v1.0 Size: 1836b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_801bd0e8(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 undefined4 param_9,undefined4 param_10,int param_11,undefined4 param_12,
                 undefined4 param_13,int param_14,int param_15,undefined4 param_16)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801BD814
 * EN v1.0 Size: 260b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_801bd814(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 int param_9)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801BD918
 * EN v1.0 Size: 176b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_801bd918(short *param_1)

{
  char in_r8;
  int iVar1;
  
  iVar1 = *(int *)(param_1 + 0x5c);
  if (((in_r8 != '\0') && (*(int *)(param_1 + 0x7a) == 0)) && (*(short *)(iVar1 + 0x402) != 3)) {
    FUN_8003b9ec((int)param_1);
    FUN_801bbb4c();
    FUN_80115088(param_1,-0x7fc529c4,0);
    iVar1 = **(int **)(iVar1 + 0x40c);
    if (((iVar1 != 0) && (*(char *)(iVar1 + 0x2f8) != '\0')) && (*(char *)(iVar1 + 0x4c) != '\0')) {
      FUN_80060630(iVar1);
    }
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801BD9C8
 * EN v1.0 Size: 60b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_801bd9c8(int param_1)
{
}
