#ifndef MAIN_DLL_TREX_TREX_LEVELCONTROL_H_
#define MAIN_DLL_TREX_TREX_LEVELCONTROL_H_

#include "ghidra_import.h"

#define SB_SHIPGUN_EXTRA_SIZE 0x10

#define SB_SHIPGUN_CLOUDRUNNER_ALIAS_OBJECT_TYPE 0x008C
#define SB_SHIPGUN_GALLEON_ALIAS_OBJECT_TYPE 0x008E
#define SB_SHIPGUN_WM_GALLEON_ALIAS_OBJECT_TYPE 0x0139

#define SB_SHIPGUN_START_HEALTH 2
#define SB_SHIPGUN_WAKE_DELAY 60
#define SB_SHIPGUN_FIRST_DAMAGE_HIT_COUNT 4
#define SB_SHIPGUN_SECOND_DAMAGE_HIT_COUNT 8
#define SB_SHIPGUN_FAST_FIRE_GALLEON_STAGE 3
#define SB_SHIPGUN_VOLLEY_SIZE 3
#define SB_SHIPGUN_FIRE_DELAY_VARIANCE 40
#define SB_SHIPGUN_SLOW_FIRE_DELAY 120
#define SB_SHIPGUN_FAST_FIRE_DELAY 80
#define SB_SHIPGUN_CANNONBALL_LIFETIME 120

#define SB_SHIPGUN_CANNONBALL_ALLOC_SIZE 0x18
#define SB_SHIPGUN_CANNONBALL_MODEL_FIELD 2
#define SB_SHIPGUN_CANNONBALL_FLAGS_FIELD 1
#define SB_SHIPGUN_CANNONBALL_BYTE_FF 0xFF

#define SB_SHIPGUN_HIT_REACT_TYPE 0x0F
#define SB_SHIPGUN_HIT_REACT_POWER 200
#define SB_SHIPGUN_HIT_ANIM_A 0x36
#define SB_SHIPGUN_HIT_ANIM_B 0x3A
#define SB_SHIPGUN_FIRE_ANIM 0x3C
#define SB_SHIPGUN_RANGE_FAR_ANIM 0x40
#define SB_SHIPGUN_RANGE_NEAR_ANIM 0x312

#define SB_SHIPGUN_SMOKE_PARTICLE_ID 0x7AA
#define SB_SHIPGUN_SMOKE_PARTICLE_FLAGS 0x0C0A
#define SB_SHIPGUN_SMOKE_PARTICLE_PARAM 2

#define SB_CANNONBALL_EXTRA_SIZE 0x24
#define SB_FIREBALL_EXTRA_SIZE 0x18

#define SB_CANNONBALL_ALIAS_OBJECT_TYPE 0x0113
#define SB_CLOUDBALL_ALIAS_OBJECT_TYPE 0x0119

#define SB_CANNONBALL_TRAJECTORY_INITIALIZED_FLAG 0x01
#define SB_CANNONBALL_INITIAL_BURST_FLAG 0x02
#define SB_CANNONBALL_SOLID_HITBOX_FLAG 0x0001

#define SB_CANNONBALL_BURST_PARTICLE_ID 170
#define SB_CANNONBALL_TRAIL_PARTICLE_ID 169
#define SB_CANNONBALL_IMPACT_SMOKE_PARTICLE_ID 167
#define SB_CANNONBALL_IMPACT_SPARK_PARTICLE_ID 171
#define SB_CANNONBALL_SMOKE_PARTICLE_COUNT 50
#define SB_CANNONBALL_SPARK_PARTICLE_COUNT 10

#define SB_CANNONBALL_SETUP_SIZE 4
#define SB_CANNONBALL_SETUP_MODEL_ID 389
#define SB_CANNONBALL_SETUP_PARAM 5
#define SB_CANNONBALL_ROTATION_STEP 4000

#define SB_CANNONBALL_HITBOX_ENABLE_DELAY 15
#define SB_CANNONBALL_HITBOX_TYPE 5
#define SB_CANNONBALL_HITBOX_PRIORITY 1
#define SB_CANNONBALL_HITBOX_SIZE 16

#define SB_CANNONBALL_IMPACT_SFX 0x31D
#define SB_CANNONBALL_IMPACT_VISUAL_TIMER 25

#define SB_CANNONBALL_LIGHT_KIND 1
#define SB_CANNONBALL_LIGHT_FIELD50 2
#define SB_CANNONBALL_LIGHT_RED 200
#define SB_CANNONBALL_LIGHT_GREEN 60
#define SB_CANNONBALL_LIGHT_BLUE 0
#define SB_CANNONBALL_LIGHT_ALPHA 0
#define SB_CANNONBALL_LIGHT_FIELD_BC 1

#define SB_CANNONBALL_LAUNCH_SFX 53
#define SB_CANNONBALL_LOOP_SFX 714

void SB_ShipGun_update(int obj);

#endif /* MAIN_DLL_TREX_TREX_LEVELCONTROL_H_ */
