#ifndef MAIN_DLL_TREX_TREX_LEVELCONTROL_H_
#define MAIN_DLL_TREX_TREX_LEVELCONTROL_H_

#include "ghidra_import.h"

#define SB_CANNONBALL_EXTRA_SIZE 0x24
#define SB_FIREBALL_EXTRA_SIZE 0x18

#define SB_CANNONBALL_TRAJECTORY_INITIALIZED_FLAG 0x01
#define SB_CANNONBALL_INITIAL_BURST_FLAG 0x02
#define SB_CANNONBALL_SOLID_HITBOX_FLAG 0x0001

#define SB_CANNONBALL_BURST_PARTICLE_ID 170
#define SB_CANNONBALL_TRAIL_PARTICLE_ID 169
#define SB_CANNONBALL_IMPACT_SMOKE_PARTICLE_ID 167
#define SB_CANNONBALL_IMPACT_SPARK_PARTICLE_ID 171
#define SB_CANNONBALL_SMOKE_PARTICLE_COUNT 50
#define SB_CANNONBALL_SPARK_PARTICLE_COUNT 10

#define SB_CANNONBALL_SETUP_SIZE 4
#define SB_CANNONBALL_SETUP_MODEL_ID 389
#define SB_CANNONBALL_SETUP_PARAM 5
#define SB_CANNONBALL_ROTATION_STEP 4000

#define SB_CANNONBALL_HITBOX_ENABLE_DELAY 15
#define SB_CANNONBALL_HITBOX_TYPE 5
#define SB_CANNONBALL_HITBOX_PRIORITY 1
#define SB_CANNONBALL_HITBOX_SIZE 16

#define SB_CANNONBALL_IGNORE_OBJECT_TYPE_119 0x119
#define SB_CANNONBALL_IGNORE_OBJECT_TYPE_113 0x113
#define SB_CANNONBALL_IMPACT_SFX 0x31D
#define SB_CANNONBALL_IMPACT_VISUAL_TIMER 25

#define SB_CANNONBALL_LIGHT_KIND 1
#define SB_CANNONBALL_LIGHT_FIELD50 2
#define SB_CANNONBALL_LIGHT_RED 200
#define SB_CANNONBALL_LIGHT_GREEN 60
#define SB_CANNONBALL_LIGHT_BLUE 0
#define SB_CANNONBALL_LIGHT_ALPHA 0
#define SB_CANNONBALL_LIGHT_FIELD_BC 1

#define SB_CANNONBALL_LAUNCH_SFX 53
#define SB_CANNONBALL_LOOP_SFX 714

void SB_ShipGun_update(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8);

#endif /* MAIN_DLL_TREX_TREX_LEVELCONTROL_H_ */
