/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/CAM/camdrakor.c
 * Text span: 0x8010C374-0x8010D608
 * Imported Ghidra functions: 6
 * Verbatim-safe functions: 3
 * Auto-stubbed functions: 3
 */

#include "ghidra_import.h"
#include "main/dll/CAM/camdrakor.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_8000e054();
extern undefined2* FUN_8000facc();
extern uint FUN_80014e9c();
extern double FUN_80021434();
extern uint FUN_80021884();
extern undefined4 FUN_800238c4();
extern undefined4 FUN_80023d8c();
extern undefined4 FUN_800551f8();
extern undefined4 FUN_801037c0();
extern undefined4 FUN_8010c1a4();
extern uint FUN_801ef35c();
extern undefined4 FUN_80247e94();
extern undefined4 FUN_80247eb8();
extern undefined4 FUN_80247edc();
extern undefined4 FUN_80247ef8();
extern double FUN_80247f54();
extern undefined4 FUN_80286840();
extern undefined4 FUN_8028688c();
extern undefined4 FUN_802932a4();
extern double FUN_80293900();
extern undefined4 FUN_802945e0();
extern undefined4 FUN_80294964();
extern uint FUN_80296a6c();
extern int FUN_80296a88();
extern undefined4 FUN_80297334();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4* DAT_803dd6d0;
extern undefined4* DAT_803de1e0;
extern undefined4 DAT_803de1e4;
extern undefined4* DAT_803de1e8;
extern undefined4 DAT_803de1f0;
extern f64 DOUBLE_803e2598;
extern f64 DOUBLE_803e25b8;
extern f64 DOUBLE_803e2608;
extern f32 FLOAT_803dc074;
extern f32 FLOAT_803e2540;
extern f32 FLOAT_803e2544;
extern f32 FLOAT_803e254c;
extern f32 FLOAT_803e2550;
extern f32 FLOAT_803e2554;
extern f32 FLOAT_803e2558;
extern f32 FLOAT_803e255c;
extern f32 FLOAT_803e2560;
extern f32 FLOAT_803e2564;
extern f32 FLOAT_803e2568;
extern f32 FLOAT_803e256c;
extern f32 FLOAT_803e2570;
extern f32 FLOAT_803e2574;
extern f32 FLOAT_803e2578;
extern f32 FLOAT_803e2584;
extern f32 FLOAT_803e2588;
extern f32 FLOAT_803e258c;
extern f32 FLOAT_803e2590;
extern f32 FLOAT_803e25a0;
extern f32 FLOAT_803e25a4;
extern f32 FLOAT_803e25a8;
extern f32 FLOAT_803e25ac;
extern f32 FLOAT_803e25b0;
extern f32 FLOAT_803e25c0;
extern f32 FLOAT_803e25c8;
extern f32 FLOAT_803e25cc;
extern f32 FLOAT_803e25d0;
extern f32 FLOAT_803e25d4;
extern f32 FLOAT_803e25d8;
extern f32 FLOAT_803e25dc;
extern f32 FLOAT_803e25e0;
extern f32 FLOAT_803e25e4;
extern f32 FLOAT_803e25e8;
extern f32 FLOAT_803e25ec;
extern f32 FLOAT_803e25f0;
extern f32 FLOAT_803e25f4;
extern f32 FLOAT_803e25f8;
extern f32 FLOAT_803e25fc;
extern f32 FLOAT_803e2600;

/* Local declarations keep imported functions visible within the TU. */
void FUN_8010c374(void);
void FUN_8010cff8(int param_1,undefined4 param_2,undefined4 *param_3);
void FUN_8010d160(void);
void FUN_8010d18c(undefined2 *param_1);
void FUN_8010d534(void);
void FUN_8010d5dc(void);

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8010C374
 * EN v1.0 Size: 3204b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8010c374(void)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8010CFF8
 * EN v1.0 Size: 360b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8010cff8(int param_1,undefined4 param_2,undefined4 *param_3)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8010D160
 * EN v1.0 Size: 44b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8010d160(void)

{
  FUN_800238c4(DAT_803de1e8);
  DAT_803de1e8 = 0;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8010D18C
 * EN v1.0 Size: 936b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8010d18c(undefined2 *param_1)

{
  float fVar1;
  float fVar2;
  float fVar3;
  double dVar4;
  uint uVar5;
  int iVar6;
  
  uVar5 = 0;
  iVar6 = *(int *)(param_1 + 0x52);
  if (iVar6 != 0) {
    uVar5 = FUN_801ef35c(iVar6);
  }
  if (uVar5 != *(byte *)(DAT_803de1e8 + 10)) {
    fVar3 = FLOAT_803e25c8;
    if ((uVar5 == 2) ||
       (fVar1 = FLOAT_803e25d0, fVar2 = FLOAT_803e25d4, fVar3 = FLOAT_803e25cc, uVar5 == 5)) {
      fVar1 = FLOAT_803e25d8;
      fVar2 = DAT_803de1e8[1];
    }
    *(char *)(DAT_803de1e8 + 10) = (char)uVar5;
    DAT_803de1e8[6] = fVar3 - DAT_803de1e8[3];
    DAT_803de1e8[4] = DAT_803de1e8[3];
    DAT_803de1e8[9] = fVar1 - (DAT_803de1e8[7] + fVar2);
    DAT_803de1e8[8] = DAT_803de1e8[7];
    DAT_803de1e8[5] = FLOAT_803e25d4;
  }
  fVar3 = FLOAT_803e25dc;
  if (DAT_803de1e8[5] < FLOAT_803e25dc) {
    DAT_803de1e8[5] = FLOAT_803e25e0 * FLOAT_803dc074 + DAT_803de1e8[5];
    if (fVar3 < DAT_803de1e8[5]) {
      DAT_803de1e8[5] = fVar3;
    }
    DAT_803de1e8[3] = DAT_803de1e8[5] * DAT_803de1e8[6] + DAT_803de1e8[4];
    DAT_803de1e8[7] = DAT_803de1e8[5] * DAT_803de1e8[9] + DAT_803de1e8[8];
  }
  dVar4 = DOUBLE_803e2608;
  if ((uVar5 == 2) || (uVar5 == 5)) {
    *DAT_803de1e8 =
         -(((float)((double)CONCAT44(0x43300000,(int)*(short *)(iVar6 + 4) ^ 0x80000000) -
                   DOUBLE_803e2608) / FLOAT_803e25e4) * FLOAT_803dc074 - *DAT_803de1e8);
    DAT_803de1e8[1] =
         -(((float)((double)CONCAT44(0x43300000,(int)*(short *)(iVar6 + 2) ^ 0x80000000) - dVar4) /
           FLOAT_803e25e8) * FLOAT_803dc074 - DAT_803de1e8[1]);
    fVar3 = FLOAT_803e25ec;
    *DAT_803de1e8 = -(FLOAT_803e25ec * *DAT_803de1e8 * FLOAT_803dc074 - *DAT_803de1e8);
    DAT_803de1e8[1] = -(fVar3 * DAT_803de1e8[1] * FLOAT_803dc074 - DAT_803de1e8[1]);
    *(float *)(param_1 + 0xe) = DAT_803de1e8[1] + *(float *)(iVar6 + 0x1c) + DAT_803de1e8[7];
  }
  else {
    *DAT_803de1e8 =
         -(((float)((double)CONCAT44(0x43300000,(int)*(short *)(iVar6 + 4) ^ 0x80000000) -
                   DOUBLE_803e2608) / FLOAT_803e25e4) * FLOAT_803dc074 - *DAT_803de1e8);
    DAT_803de1e8[1] =
         -(((float)((double)CONCAT44(0x43300000,(int)*(short *)(iVar6 + 2) ^ 0x80000000) - dVar4) /
           FLOAT_803e25e8) * FLOAT_803dc074 - DAT_803de1e8[1]);
    fVar3 = FLOAT_803e25ec;
    *DAT_803de1e8 = -(FLOAT_803e25ec * *DAT_803de1e8 * FLOAT_803dc074 - *DAT_803de1e8);
    DAT_803de1e8[1] = -(fVar3 * DAT_803de1e8[1] * FLOAT_803dc074 - DAT_803de1e8[1]);
    *(float *)(param_1 + 0xe) = DAT_803de1e8[1] + *(float *)(iVar6 + 0x1c) + DAT_803de1e8[7];
  }
  *(float *)(param_1 + 0xc) = FLOAT_803e25f0 + *(float *)(iVar6 + 0x18) + DAT_803de1e8[2];
  *(float *)(param_1 + 0x10) = *(float *)(iVar6 + 0x20) + *DAT_803de1e8;
  param_1[1] = 0x708;
  *param_1 = 0x4000;
  param_1[2] = (short)(-(int)*(short *)(iVar6 + 4) >> 3);
  *(float *)(param_1 + 0x5a) = FLOAT_803e25f4;
  fVar3 = (DAT_803de1e8[3] - DAT_803de1e8[2]) / FLOAT_803e25f8;
  fVar1 = FLOAT_803e25fc;
  if ((fVar3 <= FLOAT_803e25fc) && (fVar1 = fVar3, fVar3 < FLOAT_803e2600)) {
    fVar1 = FLOAT_803e2600;
  }
  DAT_803de1e8[2] = DAT_803de1e8[2] + fVar1 * FLOAT_803dc074;
  FUN_8000e054((double)*(float *)(param_1 + 0xc),(double)*(float *)(param_1 + 0xe),
               (double)*(float *)(param_1 + 0x10),(float *)(param_1 + 6),(float *)(param_1 + 8),
               (float *)(param_1 + 10),*(int *)(param_1 + 0x18));
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8010D534
 * EN v1.0 Size: 168b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8010d534(void)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8010D5DC
 * EN v1.0 Size: 44b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8010d5dc(void)

{
  FUN_800238c4(DAT_803de1f0);
  DAT_803de1f0 = 0;
  return;
}
