#ifndef MAIN_DLL_DLL_7A_H_
#define MAIN_DLL_DLL_7A_H_

/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/dll_7A.c
 * Text span: 0x8010096C-0x80100970
 * No raw Ghidra functions mapped into this owner yet.
 */

#include "ghidra_import.h"

#endif /* MAIN_DLL_DLL_7A_H_ */
