#ifndef MAIN_DLL_MODANIMEFLASH1_H_
#define MAIN_DLL_MODANIMEFLASH1_H_

/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/modanimeflash1.c
 * Text span: 0x80100558-0x8010055C
 * No raw Ghidra functions mapped into this owner yet.
 */

#include "ghidra_import.h"

#endif /* MAIN_DLL_MODANIMEFLASH1_H_ */
